// Code generated by TestStylesheetBlobMatchesBuilder (go test ./internal/experience/journeycss/ -run TestStylesheetBlobMatchesBuilder -update-blob); DO NOT EDIT.

package journeycss

const stylesheetBlob = ":root{--jn-accent:#2b3a8f;--jn-accent-ink:#ffffff;--jn-accent-soft:#e4ecfb;--jn-accent-strong:#1f2c73;--jn-canvas:#f6f7fb;--jn-control-border:#7d859c;--jn-danger:#9b1130;--jn-danger-ink:#ffffff;--jn-danger-soft:#fde6ea;--jn-ease:cubic-bezier(.22,.61,.36,1);--jn-font:system-ui,-apple-system,\"Segoe UI\",Roboto,sans-serif;--jn-hairline:#dfe3ee;--jn-info:#14448f;--jn-info-soft:#e4ecfb;--jn-ink:#16192a;--jn-ink-muted:#545a70;--jn-masthead:#10142b;--jn-masthead-chip:#232a4a;--jn-masthead-chip-ink:#ccd3e8;--jn-masthead-ink:#ffffff;--jn-masthead-muted:#b9c0d8;--jn-mono:ui-monospace,\"Cascadia Mono\",Consolas,monospace;--jn-neutral:#3f465e;--jn-neutral-soft:#eceef5;--jn-r1:0.375rem;--jn-r2:0.625rem;--jn-r3:0.75rem;--jn-r4:1rem;--jn-ring:0 0 0 3px rgba(43,58,143,.28);--jn-rpill:999px;--jn-s1:0.5rem;--jn-s2:1rem;--jn-s3:1.5rem;--jn-s4:2rem;--jn-s5:3rem;--jn-shadow-lift:0 2px 6px rgba(16,20,43,.10),0 14px 32px rgba(16,20,43,.09);--jn-success:#0f6136;--jn-success-soft:#dff3e6;--jn-surface:#ffffff;--jn-surface-muted:#eceef5;--jn-surface-sunk:#eef0f7;--jn-warning:#7a4a00;--jn-warning-soft:#fdeed3;}" +
	":where(.jn-page,.jn-embedded),:where(.jn-page,.jn-embedded) *,:where(.jn-page,.jn-embedded) *::before,:where(.jn-page,.jn-embedded) *::after{box-sizing:border-box;}" +
	":where(.jn-page,.jn-embedded){-webkit-text-size-adjust:100%;}" +
	"body:has(>.jn-page){margin:0;}" +
	":where(.jn-page,.jn-embedded){background-color:var(--jn-canvas);color:var(--jn-ink);font-family:var(--jn-font);font-feature-settings:\"cv05\" 1,\"ss01\" 1;font-size:1rem;line-height:1.55;overflow-wrap:break-word;text-rendering:optimizeLegibility;}" +
	":where(.jn-page,.jn-embedded) :is(h1,h2,h3,h4,p,ul,ol,dl,dd,figure,table){margin:0;}" +
	":where(.jn-page,.jn-embedded) :is(ul,ol){list-style:none;padding:0;}" +
	":where(.jn-page,.jn-embedded) svg{display:block;}" +
	":where(.jn-page,.jn-embedded) a{color:var(--jn-accent);text-decoration-thickness:1px;text-underline-offset:0.15em;transition:color 0.15s var(--jn-ease);}" +
	":where(.jn-page,.jn-embedded) a:hover{color:var(--jn-accent-strong);}" +
	":where(.jn-page,.jn-embedded) :focus-visible{border-radius:var(--jn-r1);outline:3px solid var(--jn-accent);outline-offset:2px;}" +
	".jn-masthead :focus-visible{outline-color:var(--jn-masthead-ink);}" +
	".jn-visually-hidden{border:0;clip:rect(0,0,0,0);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;white-space:nowrap;width:1px;}" +
	".jn-skip{background-color:var(--jn-surface);border:1px solid var(--jn-control-border);border-radius:var(--jn-r1);box-shadow:var(--jn-shadow-lift);color:var(--jn-accent);font-weight:600;inset-inline-start:var(--jn-s1);padding-bottom:0.5rem;padding-left:0.875rem;padding-right:0.875rem;padding-top:0.5rem;position:absolute;text-decoration:none;top:var(--jn-s1);transform:translateY(-200%);z-index:20;}" +
	".jn-skip:focus{transform:translateY(0);}" +
	".jn-page{display:flex;flex-direction:column;min-height:100vh;min-width:0;}" +
	".jn-shell{margin-bottom:0;margin-left:auto;margin-right:auto;margin-top:0;max-width:80rem;padding-bottom:0;padding-left:var(--jn-s2);padding-right:var(--jn-s2);padding-top:0;width:100%;}" +
	".jn-masthead{background-color:var(--jn-masthead);border-bottom:1px solid var(--jn-masthead-chip);color:var(--jn-masthead-ink);}" +
	".jn-masthead a{color:var(--jn-masthead-ink);}" +
	".jn-masthead-inner{display:flex;flex-direction:column;gap:var(--jn-s2);padding-bottom:.875rem;padding-top:.875rem;}" +
	".jn-brandbar{align-items:center;display:flex;gap:0.75rem;min-width:0;}" +
	".jn-markwell{align-items:center;background:linear-gradient(140deg,var(--jn-masthead-chip),var(--jn-accent-strong));border:1px solid var(--jn-masthead-chip);border-radius:var(--jn-r2);box-shadow:inset 0 1px 0 rgba(255,255,255,.10);color:var(--jn-masthead-ink);display:flex;flex:none;height:2.5rem;justify-content:center;width:2.5rem;}" +
	".jn-brandtext{display:flex;flex-direction:column;line-height:1.25;min-width:0;}" +
	".jn-brand-name{font-size:1rem;font-weight:600;letter-spacing:-0.014em;}" +
	".jn-tenant{color:var(--jn-masthead-muted);font-size:0.75rem;letter-spacing:0.005em;}" +
	".jn-nav ul{display:flex;flex-wrap:wrap;gap:0.25rem;}" +
	".jn-nav a{border-radius:var(--jn-r1);color:var(--jn-masthead-muted);display:inline-block;font-size:0.875rem;font-weight:500;padding-bottom:0.375rem;padding-left:0.75rem;padding-right:0.75rem;padding-top:0.375rem;text-decoration:none;transition:background-color 0.15s var(--jn-ease),color 0.15s var(--jn-ease);}" +
	".jn-nav a:hover{background-color:var(--jn-masthead-chip);color:var(--jn-masthead-ink);}" +
	".jn-nav a[aria-current=\"page\"]{background-color:var(--jn-masthead-chip);box-shadow:inset 0 -2px 0 0 var(--jn-accent-soft);color:var(--jn-masthead-ink);}" +
	".jn-principal{align-items:center;color:var(--jn-masthead-muted);display:flex;flex-wrap:wrap;font-size:0.8125rem;gap:0.5rem;min-width:0;}" +
	".jn-principal-subject{color:var(--jn-masthead-ink);font-weight:600;}" +
	".jn-rolechip{background-color:var(--jn-masthead-chip);border-radius:var(--jn-rpill);color:var(--jn-masthead-chip-ink);display:inline-block;font-family:var(--jn-mono);font-size:0.75rem;letter-spacing:-0.01em;padding-bottom:0.0625rem;padding-left:0.5rem;padding-right:0.5rem;padding-top:0.0625rem;}" +
	".jn-logout{color:var(--jn-masthead-muted);font-size:0.8125rem;}" +
	"@media (min-width:64rem){.jn-masthead-inner{align-items:center;flex-direction:row;justify-content:space-between;}" +
	"}" +
	"@media (min-width:64rem){.jn-principal{justify-content:flex-end;max-width:34rem;}" +
	"}" +
	".jn-noticeband{padding-top:var(--jn-s2);}" +
	".jn-notice{align-items:flex-start;animation-duration:.32s;animation-fill-mode:both;animation-name:jn-slidein-2zqd52uojwort;animation-timing-function:var(--jn-ease);background-color:var(--jn-surface);border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);box-shadow:none;display:flex;gap:0.75rem;padding-bottom:0.875rem;padding-left:1rem;padding-right:1rem;padding-top:0.875rem;}" +
	"@keyframes jn-slidein-2zqd52uojwort{from{opacity:0;transform:translateY(6px);}" +
	"to{opacity:1;transform:none;}" +
	"}" +
	".jn-notice-icon{flex:none;margin-top:.125rem;}" +
	".jn-notice-body{min-width:0;}" +
	".jn-notice-title{font-weight:600;letter-spacing:-0.01em;}" +
	".jn-notice-detail{color:var(--jn-ink-muted);font-size:0.875rem;margin-top:.125rem;}" +
	".jn-notice-fields{margin-top:.625rem;}" +
	".jn-notice-support{font-size:0.8125rem;margin-top:.75rem;}" +
	".jn-notice-support summary{cursor:pointer;font-weight:600;text-decoration:underline;text-underline-offset:.18em;}" +
	".jn-notice-support-body{display:flex;flex-direction:column;gap:0.375rem;margin-top:.5rem;}" +
	".jn-notice-support-body label{font-weight:600;}" +
	".jn-support-reference{background-color:var(--jn-surface);border:1px solid var(--jn-hairline);border-radius:var(--jn-r1);box-sizing:border-box;color:var(--jn-ink);max-width:100%;padding-bottom:0.375rem;padding-left:0.5rem;padding-right:0.5rem;padding-top:0.375rem;width:22rem;}" +
	".jn-notice-support-body p{color:var(--jn-ink-muted);}" +
	".jn-notice-fields-title{font-size:0.8125rem;font-weight:600;}" +
	".jn-notice-fieldlist{display:flex;flex-wrap:wrap;gap:0.5rem;list-style:none;margin:.375rem 0 0;padding:0;}" +
	".jn-notice-fieldlist a{align-items:center;background-color:var(--jn-surface);border:1px solid var(--jn-hairline);border-radius:var(--jn-r1);color:var(--jn-ink);display:inline-flex;font-size:0.8125rem;font-weight:600;padding-bottom:0.25rem;padding-left:0.5rem;padding-right:0.5rem;padding-top:0.25rem;text-decoration:underline;text-underline-offset:.18em;}" +
	".jn-notice-fieldlist a:hover{background-color:var(--jn-surface-muted);}" +
	".jn-notice[data-tone=\"info\"]{background-color:var(--jn-info-soft);border-color:var(--jn-info);}" +
	".jn-notice[data-tone=\"info\"] .jn-notice-title,.jn-notice[data-tone=\"info\"] .jn-notice-icon{color:var(--jn-info);}" +
	".jn-notice[data-tone=\"success\"]{background-color:var(--jn-success-soft);border-color:var(--jn-success);}" +
	".jn-notice[data-tone=\"success\"] .jn-notice-title,.jn-notice[data-tone=\"success\"] .jn-notice-icon{color:var(--jn-success);}" +
	".jn-notice[data-tone=\"warning\"]{background-color:var(--jn-warning-soft);border-color:var(--jn-warning);}" +
	".jn-notice[data-tone=\"warning\"] .jn-notice-title,.jn-notice[data-tone=\"warning\"] .jn-notice-icon{color:var(--jn-warning);}" +
	".jn-notice[data-tone=\"danger\"]{background-color:var(--jn-danger-soft);border-color:var(--jn-danger);}" +
	".jn-notice[data-tone=\"danger\"] .jn-notice-title,.jn-notice[data-tone=\"danger\"] .jn-notice-icon{color:var(--jn-danger);}" +
	".jn-main{flex:1 1 auto;padding-bottom:var(--jn-s5);padding-top:var(--jn-s3);}" +
	".jn-stack{display:flex;flex-direction:column;gap:var(--jn-s3);min-width:0;}" +
	".jn-pagehead{max-width:46rem;}" +
	":where(.jn-page,.jn-embedded) h1{font-size:1.75rem;font-weight:700;letter-spacing:-0.024em;line-height:1.18;}" +
	".jn-embedded .jn-pagehead>h1{font-size:var(--hcm-font-size-heading,1.75rem);letter-spacing:-0.04em;line-height:1.1;}" +
	".jn-display{font-size:2rem;font-weight:700;letter-spacing:-0.03em;line-height:1.1;}" +
	".jn-lead{color:var(--jn-ink-muted);font-size:1rem;margin-top:.5rem;}" +
	":where(.jn-page,.jn-embedded) h2{align-items:center;display:flex;font-size:1.25rem;font-weight:600;gap:0.5rem;letter-spacing:-0.018em;line-height:1.3;}" +
	":where(.jn-page,.jn-embedded) h3{font-size:1rem;font-weight:600;letter-spacing:-0.012em;line-height:1.35;}" +
	".jn-headicon{color:var(--jn-ink-muted);}" +
	".jn-eyebrow{color:var(--jn-ink-muted);font-size:0.75rem;font-weight:600;letter-spacing:var(--hcm-tracking-caps,.05em);text-transform:uppercase;}" +
	".jn-sectionhead{align-items:baseline;display:flex;flex-wrap:wrap;gap:var(--jn-s1);justify-content:space-between;margin-bottom:var(--jn-s2);}" +
	".jn-count{color:var(--jn-ink-muted);font-size:0.8125rem;font-variant-numeric:tabular-nums;}" +
	".jn-card{background-color:var(--jn-surface);border:1px solid var(--jn-hairline);border-radius:var(--jn-r3);box-shadow:none;min-width:0;padding:var(--jn-s2);}" +
	".jn-panel{background-color:var(--jn-surface);border:1px solid var(--jn-hairline);border-radius:var(--jn-r4);box-shadow:none;min-width:0;padding:var(--jn-s3);}" +
	".jn-mono{font-family:var(--jn-mono);font-size:0.8125rem;letter-spacing:-0.01em;overflow-wrap:anywhere;}" +
	".jn-num{font-variant-numeric:tabular-nums;}" +
	".jn-muted{color:var(--jn-ink-muted);}" +
	".jn-proposal-view{max-width:64rem;}" +
	".jn-proposal-head{max-width:52rem;}" +
	".jn-context-actions{column-gap:1.25rem;display:flex;flex-wrap:wrap;margin-top:var(--jn-s2);max-width:100%;min-width:0;row-gap:0.5rem;}" +
	".jn-context-actions .jn-btn{max-width:100%;overflow-wrap:break-word;text-align:center;white-space:normal;}" +
	".jn-context-link{color:var(--jn-accent);font-size:0.875rem;font-weight:600;text-decoration:none;}" +
	".jn-context-link:hover{text-decoration:underline;}" +
	".jn-subject-card{overflow:hidden;position:relative;}" +
	".jn-subject-card::before{background-color:var(--jn-accent);content:\"\";inset-block:0;inset-inline-start:0;position:absolute;width:4px;}" +
	".jn-subject-identity{align-items:center;display:flex;flex-wrap:wrap;gap:var(--jn-s2);}" +
	".jn-subject-identity>div:nth-child(2){flex:1;min-width:12rem;}" +
	".jn-subject-avatar{align-items:center;background-color:var(--jn-accent-soft);border-radius:50%;color:var(--jn-accent-strong);display:flex;flex:none;font-weight:700;height:3rem;justify-content:center;letter-spacing:0.02em;width:3rem;}" +
	".jn-subject-title{color:var(--jn-ink-muted);font-size:0.875rem;margin-top:.125rem;}" +
	".jn-subject-facts{border-top:1px solid var(--jn-hairline);margin-top:var(--jn-s2);padding-top:var(--jn-s2);}" +
	".jn-chip{align-items:center;background-color:var(--jn-neutral-soft);border-radius:var(--jn-rpill);box-shadow:inset 0 0 0 1px rgba(22,25,42,.05);color:var(--jn-neutral);display:inline-flex;font-size:0.75rem;font-weight:600;gap:0.3125rem;letter-spacing:-0.005em;padding-bottom:0.1875rem;padding-left:0.5625rem;padding-right:0.5625rem;padding-top:0.1875rem;white-space:nowrap;}" +
	".jn-chip[data-tone=\"info\"]{background-color:var(--jn-info-soft);color:var(--jn-info);}" +
	".jn-chip[data-tone=\"success\"]{background-color:var(--jn-success-soft);color:var(--jn-success);}" +
	".jn-chip[data-tone=\"warning\"]{background-color:var(--jn-warning-soft);color:var(--jn-warning);}" +
	".jn-chip[data-tone=\"danger\"]{background-color:var(--jn-danger-soft);color:var(--jn-danger);}" +
	".jn-chip-dot{background:currentColor;border-radius:50%;flex:none;height:0.4375rem;width:0.4375rem;}" +
	".jn-chip-icon{flex:none;}" +
	".jn-grid{display:grid;gap:var(--jn-s2);grid-template-columns:repeat(auto-fill,minmax(min(19rem,100%),1fr));}" +
	".jn-grid:has(> .jn-griditem:only-child){grid-template-columns:1fr;}" +
	".jn-journey-groups{display:grid;gap:var(--jn-s4);}" +
	".jn-journey-group>.jn-sectionhead{margin-bottom:var(--jn-s2);}" +
	".jn-journey{display:flex;flex-direction:column;gap:0.625rem;position:relative;transition:border-color var(--hcm-motion-fast,.15s) var(--jn-ease),background-color var(--hcm-motion-fast,.15s) var(--jn-ease);}" +
	".jn-journey::before{background-color:var(--jn-hairline);border-radius:var(--jn-r3) var(--jn-r3) 0 0;content:\"\";height:3px;inset-inline-end:0;inset-inline-start:0;position:absolute;top:0;}" +
	".jn-journey[data-stage=\"AWAITING_APPROVAL\"]::before{background-color:var(--jn-warning);}" +
	".jn-journey[data-stage=\"COMPLETED\"]::before{background-color:var(--jn-success);}" +
	".jn-journey[data-stage=\"BLOCKED\"]::before,.jn-journey[data-stage=\"REJECTED\"]::before,\n.jn-journey[data-stage=\"FAILED\"]::before{background-color:var(--jn-danger);}" +
	".jn-journey[data-stage=\"PROPOSED\"]::before{background-color:var(--jn-info);}" +
	".jn-journey:hover{border-color:var(--jn-control-border);}" +
	".jn-journey:focus-within{box-shadow:var(--jn-ring);}" +
	".jn-journey-top{align-items:flex-start;display:flex;gap:0.75rem;justify-content:space-between;}" +
	".jn-journey h3{margin:0;}" +
	".jn-journey h3 a{color:var(--jn-ink);text-decoration:none;}" +
	".jn-journey h3 a::after{border-radius:inherit;content:\"\";inset:0;position:absolute;}" +
	".jn-journey h3 a:hover{color:var(--jn-accent);}" +
	".jn-journey-headline{color:var(--jn-ink-muted);font-size:0.875rem;}" +
	".jn-journey-codes{color:var(--jn-ink-muted);font-size:0.75rem;font-variant-numeric:tabular-nums;letter-spacing:.025em;margin-block-end:0;margin-block-start:-.375rem;}" +
	".jn-journey-pay{font-size:1.125rem;font-variant-numeric:tabular-nums;font-weight:600;letter-spacing:-0.016em;}" +
	".jn-meta{color:var(--jn-ink-muted);column-gap:1rem;display:flex;flex-wrap:wrap;font-size:0.8125rem;row-gap:0.25rem;}" +
	".jn-meta-key{color:var(--jn-ink-muted);font-weight:600;}" +
	".jn-journey-foot{align-items:center;border-top:1px solid var(--jn-hairline);color:var(--jn-accent);display:flex;font-size:0.8125rem;font-weight:600;gap:0.375rem;margin-top:auto;padding-top:.625rem;}" +
	".jn-journey-arrow{transition:transform 0.2s var(--jn-ease);}" +
	".jn-journey:hover .jn-journey-arrow{transform:translateX(3px);}" +
	".jn-people-note{align-items:flex-start;color:var(--jn-ink-muted);display:flex;font-size:0.8125rem;gap:0.375rem;margin-bottom:var(--jn-s2);margin-top:calc(var(--jn-s2) * -0.5);}" +
	".jn-people-note-icon{color:var(--jn-info);flex:none;margin-top:.0625rem;}" +
	".jn-peoplewrap{max-height:34rem;overflow-y:auto;overscroll-behavior:contain;}" +
	"table.jn-people{font-size:0.8125rem;}" +
	".jn-people thead th{z-index:2;}" +
	".jn-people tbody th,.jn-people tbody td{height:2.75rem;padding-bottom:.375rem;padding-top:.375rem;vertical-align:middle;white-space:nowrap;}" +
	".jn-people tbody th{font-weight:inherit;}" +
	".jn-people-idcell{position:relative;}" +
	".jn-people-idbox{align-items:flex-start;display:flex;flex-direction:column;gap:0.0625rem;line-height:1.3;min-width:0;text-align:start;}" +
	".jn-people-pick{background:none;border:0;border-radius:var(--jn-r1);color:inherit;cursor:pointer;font:inherit;padding:0;width:100%;}" +
	".jn-people-pick:hover .jn-people-name{color:var(--jn-accent);}" +
	".jn-people-name{color:var(--jn-ink);font-size:0.875rem;font-weight:600;letter-spacing:-0.014em;}" +
	".jn-people-title{color:var(--jn-ink-muted);font-size:0.75rem;}" +
	".jn-people-number{color:var(--jn-ink-muted);font-size:0.75rem;}" +
	".jn-people-selected{align-items:center;color:var(--jn-accent);display:inline-flex;font-size:0.75rem;font-weight:600;gap:0.25rem;letter-spacing:var(--hcm-tracking-caps,.05em);margin-top:.125rem;text-transform:uppercase;}" +
	".jn-people-selected-icon{flex:none;}" +
	".jn-people-job{font-variant-numeric:tabular-nums;font-weight:600;}" +
	".jn-people-pay{font-weight:600;}" +
	".jn-people-count{font-weight:600;}" +
	".jn-people-journeys{color:var(--jn-ink-muted);}" +
	".jn-people-action{text-align:end;}" +
	".jn-source{font-weight:600;}" +
	".jn-people tbody tr[data-tone=\"info\"] .jn-people-idcell{box-shadow:inset 3px 0 0 0 var(--jn-info);}" +
	".jn-people tbody tr[data-tone=\"success\"] .jn-people-idcell{box-shadow:inset 3px 0 0 0 var(--jn-success);}" +
	".jn-people tbody tr[data-tone=\"warning\"] .jn-people-idcell{box-shadow:inset 3px 0 0 0 var(--jn-warning);}" +
	".jn-people tbody tr[data-tone=\"danger\"] .jn-people-idcell{box-shadow:inset 3px 0 0 0 var(--jn-danger);}" +
	".jn-people tbody tr[data-selected=\"true\"]{background-color:var(--jn-accent-soft);}" +
	".jn-people tbody tr[data-selected=\"true\"] .jn-people-idcell{box-shadow:inset 3px 0 0 0 var(--jn-accent);}" +
	".jn-people tbody tr[data-tone=\"info\"] .jn-people-idcell:dir(rtl){box-shadow:inset -3px 0 0 0 var(--jn-info);}" +
	".jn-people tbody tr[data-tone=\"success\"] .jn-people-idcell:dir(rtl){box-shadow:inset -3px 0 0 0 var(--jn-success);}" +
	".jn-people tbody tr[data-tone=\"warning\"] .jn-people-idcell:dir(rtl){box-shadow:inset -3px 0 0 0 var(--jn-warning);}" +
	".jn-people tbody tr[data-tone=\"danger\"] .jn-people-idcell:dir(rtl){box-shadow:inset -3px 0 0 0 var(--jn-danger);}" +
	".jn-people tbody tr[data-selected=\"true\"] .jn-people-idcell:dir(rtl){box-shadow:inset -3px 0 0 0 var(--jn-accent);}" +
	".jn-people tbody tr[data-selected=\"true\"] .jn-people-name{color:var(--jn-accent-strong);}" +
	".jn-empty{color:var(--jn-ink-muted);padding-bottom:var(--jn-s4);padding-left:var(--jn-s2);padding-right:var(--jn-s2);padding-top:var(--jn-s4);text-align:center;}" +
	".jn-empty.jn-empty-inset{background-color:var(--jn-surface-sunk);border:1px dashed var(--jn-control-border);border-radius:var(--jn-r2);padding-bottom:var(--jn-s3);padding-left:var(--jn-s2);padding-right:var(--jn-s2);padding-top:var(--jn-s3);}" +
	".jn-empty-mark{color:var(--jn-control-border);margin:0 auto var(--jn-s1);}" +
	".jn-empty-title{color:var(--jn-ink);font-size:1rem;font-weight:600;}" +
	".jn-empty-title+p{font-size:0.875rem;line-height:1.5;margin:.375rem auto 0;max-width:48ch;text-wrap:pretty;}" +
	".jn-callout{align-items:flex-start;background-color:var(--jn-info-soft);border:1px solid var(--jn-info);border-radius:var(--jn-r2);display:flex;gap:0.75rem;padding-bottom:0.875rem;padding-left:1rem;padding-right:1rem;padding-top:0.875rem;}" +
	".jn-callout-icon{color:var(--jn-info);flex:none;margin-top:.125rem;}" +
	".jn-callout-title{color:var(--jn-info);font-weight:600;}" +
	".jn-callout-detail{font-size:0.875rem;margin-top:.125rem;}" +
	".jn-fieldgrid{display:grid;gap:var(--jn-s2);grid-template-columns:1fr;}" +
	"@media (min-width:44rem){.jn-fieldgrid{grid-template-columns:1fr 1fr;}" +
	"}" +
	"@media (min-width:44rem){.jn-field[data-span=\"full\"]{grid-column:1 / -1;}" +
	"}" +
	".jn-field{display:flex;flex-direction:column;gap:0.3125rem;min-width:0;}" +
	".jn-label{font-size:0.8125rem;font-weight:600;letter-spacing:-0.005em;}" +
	".jn-req{color:var(--jn-danger);margin-inline-start:.125rem;}" +
	".jn-inputwrap{align-items:stretch;background-color:var(--jn-surface);border:1px solid var(--jn-control-border);border-radius:var(--jn-r1);display:flex;min-width:0;transition:box-shadow 0.15s var(--jn-ease),border-color 0.15s var(--jn-ease);}" +
	".jn-inputwrap:hover{border-color:var(--jn-ink-muted);}" +
	".jn-inputwrap:focus-within{border-color:var(--jn-accent);box-shadow:var(--jn-ring);}" +
	".jn-field[data-invalid=\"true\"] .jn-inputwrap{border-color:var(--jn-danger);border-width:2px;}" +
	".jn-adorn{align-items:center;background-color:var(--jn-surface-sunk);color:var(--jn-ink-muted);display:flex;font-size:0.8125rem;font-weight:600;padding-bottom:0;padding-left:0.625rem;padding-right:0.625rem;padding-top:0;white-space:nowrap;}" +
	".jn-adorn[data-side=\"prefix\"]{border-inline-end:1px solid var(--jn-hairline);border-radius:var(--jn-r1) 0 0 var(--jn-r1);}" +
	".jn-adorn[data-side=\"suffix\"]{border-inline-start:1px solid var(--jn-hairline);border-radius:0 var(--jn-r1) var(--jn-r1) 0;}" +
	".jn-input{background-color:transparent;border:0;border-radius:var(--jn-r1);color:var(--jn-ink);font:inherit;font-size:0.875rem;min-width:0;padding-bottom:0.5rem;padding-left:0.625rem;padding-right:0.625rem;padding-top:0.5rem;width:100%;}" +
	".jn-input:focus{outline:none;}" +
	"textarea.jn-input{line-height:1.5;min-height:5rem;resize:vertical;}" +
	"select.jn-input{cursor:pointer;}" +
	".jn-help{color:var(--jn-ink-muted);font-size:0.75rem;}" +
	".jn-error{align-items:center;color:var(--jn-danger);display:flex;font-size:0.75rem;font-weight:600;gap:0.3125rem;}" +
	".jn-formfoot>.jn-btn,.jn-formfoot>.jn-confirm,.jn-formfoot>.jn-confirm>summary.jn-btn{width:100%;}" +
	"@media (min-width:30rem){.jn-formfoot>.jn-btn,.jn-formfoot>.jn-confirm,.jn-formfoot>.jn-confirm>summary.jn-btn{width:auto;}" +
	"}" +
	".jn-formfoot{align-items:center;border-top:1px solid var(--jn-hairline);display:flex;flex-wrap:wrap;gap:var(--jn-s2);margin-top:var(--jn-s3);padding-top:var(--jn-s2);}" +
	".jn-btn{align-items:center;background:linear-gradient(180deg,var(--jn-accent),var(--jn-accent-strong));border:1px solid transparent;border-radius:var(--jn-r1);box-shadow:none;color:var(--jn-accent-ink);cursor:pointer;display:inline-flex;font:inherit;font-size:0.875rem;font-weight:600;gap:0.375rem;justify-content:center;letter-spacing:-0.005em;padding-bottom:0.5625rem;padding-left:1.125rem;padding-right:1.125rem;padding-top:0.5625rem;text-decoration:none;transition:transform .12s var(--jn-ease),box-shadow .15s var(--jn-ease),filter .15s var(--jn-ease);white-space:nowrap;}" +
	".jn-btn:hover{filter:brightness(1.08);}" +
	".jn-btn:active{transform:translateY(1px);}" +
	".jn-btn[data-variant=\"secondary\"]{background:var(--jn-surface);border-color:var(--jn-control-border);box-shadow:none;color:var(--jn-accent);}" +
	".jn-btn[data-variant=\"secondary\"]:hover{background:var(--jn-surface-sunk);filter:none;}" +
	".jn-btn[data-variant=\"danger\"]{background:linear-gradient(180deg,var(--jn-danger),var(--jn-danger));color:var(--jn-danger-ink);}" +
	"a.jn-btn:hover{color:var(--jn-accent-ink);}" +
	".jn-btn[data-size=\"sm\"]{font-size:0.75rem;letter-spacing:0;padding-bottom:0.3125rem;padding-left:0.6875rem;padding-right:0.6875rem;padding-top:0.3125rem;}" +
	".jn-btn[disabled]{background-color:var(--jn-surface-muted);border-color:var(--jn-hairline);box-shadow:none;color:var(--jn-ink-muted);cursor:not-allowed;filter:none;transform:none;}" +
	".jn-hero{display:flex;flex-direction:column;gap:0.75rem;overflow:hidden;position:relative;}" +
	".jn-hero-top{align-items:flex-start;display:flex;flex-wrap:wrap;gap:var(--jn-s2);justify-content:space-between;}" +
	".jn-hero-pay{font-size:1.5rem;font-variant-numeric:tabular-nums;font-weight:600;letter-spacing:-0.024em;}" +
	".jn-hero-ids{border-top:1px solid var(--jn-hairline);color:var(--jn-ink-muted);padding-top:.75rem;}" +
	".jn-stepper{display:flex;flex-direction:column;gap:0;}" +
	".jn-step{display:flex;gap:0.75rem;padding-bottom:var(--jn-s2);position:relative;}" +
	".jn-step:last-child{padding-bottom:0;}" +
	".jn-step::before{background-color:var(--jn-hairline);bottom:0.25rem;content:\"\";inset-inline-start:.8125rem;position:absolute;top:1.875rem;width:2px;}" +
	".jn-step::after{background-color:var(--jn-accent);content:\"\";height:0;inset-inline-start:.8125rem;position:absolute;top:1.875rem;transform-origin:top;width:2px;}" +
	".jn-step:last-child::before,.jn-step:last-child::after{display:none;}" +
	".jn-step[data-state=\"done\"]::after{animation-duration:.5s;animation-fill-mode:both;animation-name:jn-grow-y-31etq5wrprejp;animation-timing-function:var(--jn-ease);height:calc(100% - 2rem);}" +
	"@keyframes jn-grow-y-31etq5wrprejp{from{height:0;}" +
	"to{height:calc(100% - 2rem);}" +
	"}" +
	".jn-step[data-state=\"done\"]:nth-child(2)::after{animation-delay:.12s;}" +
	".jn-step[data-state=\"done\"]:nth-child(3)::after{animation-delay:.24s;}" +
	".jn-step[data-state=\"done\"]:nth-child(4)::after{animation-delay:.36s;}" +
	".jn-step[data-state=\"done\"]:nth-child(5)::after{animation-delay:.48s;}" +
	".jn-stepmark{align-items:center;background-color:var(--jn-surface);border:2px solid var(--jn-control-border);border-radius:50%;color:var(--jn-ink-muted);display:flex;flex:none;font-size:0.75rem;font-variant-numeric:tabular-nums;font-weight:700;height:1.75rem;justify-content:center;position:relative;width:1.75rem;z-index:1;}" +
	".jn-step[data-state=\"done\"] .jn-stepmark{background-color:var(--jn-accent);border-color:var(--jn-accent);color:var(--jn-accent-ink);}" +
	".jn-step[data-state=\"done\"] .jn-stepcheck{animation-duration:.35s;animation-fill-mode:both;animation-name:jn-pop-3ridygbxw2ry0;animation-timing-function:var(--jn-ease);}" +
	"@keyframes jn-pop-3ridygbxw2ry0{from{opacity:0;transform:scale(.4);}" +
	"60%{opacity:1;transform:scale(1.15);}" +
	"to{transform:scale(1);}" +
	"}" +
	".jn-step[data-state=\"active\"] .jn-stepmark{animation-duration:2.4s;animation-iteration-count:infinite;animation-name:jn-halo-d2evgl2isjd5;animation-timing-function:var(--jn-ease);background-color:var(--jn-accent-soft);border-color:var(--jn-accent);border-width:3px;color:var(--jn-accent);}" +
	"@keyframes jn-halo-d2evgl2isjd5{0%,100%{box-shadow:0 0 0 0 rgba(43,58,143,.30);}" +
	"50%{box-shadow:0 0 0 6px rgba(43,58,143,0);}" +
	"}" +
	".jn-step[data-state=\"failed\"] .jn-stepmark{background-color:var(--jn-danger);border-color:var(--jn-danger);color:var(--jn-danger-ink);}" +
	".jn-stepbody{min-width:0;padding-top:.125rem;}" +
	".jn-steplabel{font-size:0.875rem;font-weight:600;}" +
	".jn-step[data-state=\"active\"] .jn-steplabel{color:var(--jn-accent);}" +
	".jn-step[data-state=\"upcoming\"] .jn-steplabel{color:var(--jn-ink-muted);}" +
	".jn-step[data-state=\"failed\"] .jn-steplabel{color:var(--jn-danger);}" +
	".jn-stepdetail{color:var(--jn-ink-muted);font-size:0.8125rem;}" +
	".jn-stepat{color:var(--jn-ink-muted);font-size:0.75rem;font-variant-numeric:tabular-nums;}" +
	"@media (min-width:60rem){.jn-stepper{flex-direction:row;}" +
	"}" +
	"@media (min-width:60rem){.jn-step{flex:1 1 0;flex-direction:column;gap:0.5rem;padding-bottom:0;padding-inline-end:var(--jn-s2);}" +
	"}" +
	"@media (min-width:60rem){.jn-step:last-child{padding-inline-end:0;}" +
	"}" +
	"@media (min-width:60rem){.jn-step::before{bottom:auto;height:2px;inset-inline-end:.5rem;inset-inline-start:2.25rem;top:0.8125rem;width:auto;}" +
	"}" +
	"@media (min-width:60rem){.jn-step::after{height:2px;inset-inline-start:2.25rem;top:0.8125rem;width:0;}" +
	"}" +
	"@media (min-width:60rem){.jn-step[data-state=\"done\"]::after{animation-duration:.5s;animation-fill-mode:both;animation-name:jn-grow-x-2ybesrv1y7m9d;animation-timing-function:var(--jn-ease);height:2px;width:calc(100% - 2.75rem);}" +
	"}" +
	"@keyframes jn-grow-x-2ybesrv1y7m9d{from{width:0;}" +
	"to{width:calc(100% - 2.75rem);}" +
	"}" +
	"@media (min-width:60rem){.jn-stepbody{padding-top:0;}" +
	"}" +
	".jn-columns{align-items:start;display:grid;gap:var(--jn-s3);grid-template-columns:minmax(0,1fr);}" +
	"@media (min-width:64rem){.jn-columns{grid-template-columns:minmax(0,1fr) 23rem;}" +
	"}" +
	"@media (min-width:64rem){.jn-rail{position:static;}" +
	"}" +
	".jn-col{display:flex;flex-direction:column;gap:var(--jn-s3);min-width:0;}" +
	".jn-context-nav{align-items:center;column-gap:1.25rem;display:flex;flex-wrap:wrap;row-gap:0.5rem;}" +
	".jn-context-nav a{color:var(--jn-accent);font-size:0.875rem;font-weight:600;}" +
	".jn-context-nav a:first-child::before{content:\"\\2190\\00a0\";}" +
	".jn-subsection{margin-top:var(--jn-s3);}" +
	".jn-subsection:first-of-type{margin-top:var(--jn-s2);}" +
	".jn-subhead{color:var(--jn-ink-muted);font-size:0.8125rem;font-weight:600;letter-spacing:var(--hcm-tracking-caps,.05em);margin-bottom:.75rem;text-transform:uppercase;}" +
	".jn-facts{column-gap:var(--jn-s2);display:grid;grid-template-columns:1fr;row-gap:0.75rem;}" +
	"@media (min-width:34rem){.jn-facts{grid-template-columns:1fr 1fr;}" +
	"}" +
	".jn-fact{min-width:0;}" +
	".jn-fact dt{color:var(--jn-ink-muted);font-size:0.75rem;font-weight:600;letter-spacing:0.02em;}" +
	".jn-fact dd{font-size:0.875rem;font-weight:600;margin:0;}" +
	".jn-fact[data-tone=\"success\"] dd{color:var(--jn-success);font-weight:600;}" +
	".jn-fact[data-tone=\"warning\"] dd{color:var(--jn-warning);font-weight:600;}" +
	".jn-fact[data-tone=\"danger\"] dd{color:var(--jn-danger);font-weight:600;}" +
	".jn-fact[data-tone=\"info\"] dd{color:var(--jn-info);font-weight:600;}" +
	".jn-tablewrap{border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);overflow-x:auto;}" +
	".jn-people-preview-foot{align-items:center;background-color:var(--jn-surface-muted);border-top:1px solid var(--jn-hairline);display:flex;gap:0.75rem;inset-inline-start:0;justify-content:space-between;padding:0.75rem;position:sticky;}" +
	".jn-people-preview-foot p{color:var(--jn-ink-muted);font-size:0.8125rem;margin:0;}" +
	"table.jn-table{border-collapse:collapse;font-size:0.875rem;width:100%;}" +
	".jn-table th,.jn-table td{border-bottom:1px solid var(--jn-hairline);padding-bottom:0.5625rem;padding-left:0.75rem;padding-right:0.75rem;padding-top:0.5625rem;text-align:start;vertical-align:top;}" +
	".jn-table thead th{background-color:var(--jn-surface-muted);color:var(--jn-ink-muted);font-size:0.75rem;font-weight:600;letter-spacing:var(--hcm-tracking-caps,.05em);position:sticky;text-transform:uppercase;top:0;white-space:nowrap;}" +
	".jn-table tbody tr:last-child th,.jn-table tbody tr:last-child td{border-bottom:0;}" +
	".jn-table td.jn-num,.jn-table th.jn-num{font-variant-numeric:tabular-nums;}" +
	".jn-table tbody th{font-weight:600;}" +
	".jn-table th.jn-mono{overflow-wrap:normal;white-space:nowrap;}" +
	".jn-zebra tbody tr:nth-child(even){background-color:var(--jn-surface-sunk);}" +
	".jn-table tbody tr{transition:background-color 0.15s var(--jn-ease);}" +
	".jn-table tbody tr:hover{background-color:var(--jn-accent-soft);}" +
	".jn-table tr[data-changed=\"true\"]{background-color:var(--jn-accent-soft);}" +
	".jn-table tr[data-changed=\"true\"] td.jn-proposed{color:var(--jn-accent);font-weight:600;}" +
	".jn-delta{display:block;font-variant-numeric:tabular-nums;font-weight:600;margin-top:.25rem;white-space:nowrap;}" +
	".jn-table td.jn-change{white-space:nowrap;}" +
	".jn-board{display:flex;flex-direction:column;gap:0.5rem;}" +
	".jn-check{align-items:flex-start;animation-duration:.4s;animation-fill-mode:both;animation-name:jn-slidein-2zqd52uojwort;animation-timing-function:var(--jn-ease);background-color:var(--jn-surface);border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);display:flex;gap:0.75rem;padding-bottom:0.625rem;padding-left:0.75rem;padding-right:0.75rem;padding-top:0.625rem;}" +
	"@keyframes jn-slidein-2zqd52uojwort{from{opacity:0;transform:translateY(6px);}" +
	"to{opacity:1;transform:none;}" +
	"}" +
	".jn-check[data-row=\"1\"]{animation-delay:.06s;}" +
	".jn-check[data-row=\"2\"]{animation-delay:.12s;}" +
	".jn-check[data-row=\"3\"]{animation-delay:.18s;}" +
	".jn-check[data-row=\"4\"]{animation-delay:.24s;}" +
	".jn-check[data-row=\"5\"]{animation-delay:.30s;}" +
	".jn-check[data-row=\"6\"]{animation-delay:.36s;}" +
	".jn-check[data-row=\"7\"]{animation-delay:.42s;}" +
	".jn-check[data-severity=\"blocking\"]{border-inline-start:3px solid var(--jn-danger);}" +
	".jn-check[data-severity=\"warning\"]{border-inline-start:3px solid var(--jn-warning);}" +
	".jn-check[data-severity=\"success\"]{border-inline-start:3px solid var(--jn-success);}" +
	".jn-check[data-severity=\"info\"]{border-inline-start:3px solid var(--jn-info);}" +
	".jn-checkpill{align-items:center;background-color:var(--jn-neutral-soft);border-radius:var(--jn-rpill);box-shadow:inset 0 0 0 1px rgba(22,25,42,.05);color:var(--jn-neutral);display:inline-flex;flex:none;font-size:0.75rem;font-weight:600;gap:0.3125rem;letter-spacing:var(--hcm-tracking-caps,.05em);min-width:6.5rem;overflow:hidden;padding-bottom:0.25rem;padding-left:0.625rem;padding-right:0.625rem;padding-top:0.25rem;position:relative;text-transform:uppercase;}" +
	".jn-checkpill[data-tone=\"info\"]{background-color:var(--jn-info-soft);color:var(--jn-info);}" +
	".jn-checkpill[data-tone=\"success\"]{background-color:var(--jn-success-soft);color:var(--jn-success);}" +
	".jn-checkpill[data-tone=\"warning\"]{background-color:var(--jn-warning-soft);color:var(--jn-warning);}" +
	".jn-checkpill[data-tone=\"danger\"]{background-color:var(--jn-danger-soft);color:var(--jn-danger);}" +
	".jn-checkpill::after{background:linear-gradient(100deg,transparent 20%,rgba(255,255,255,.55) 50%,transparent 80%);border-radius:inherit;content:\"\";inset:0;position:absolute;transform:translateX(-100%);}" +
	".jn-checkpill[data-tone=\"success\"]::after{animation-delay:.35s;animation-duration:.9s;animation-fill-mode:both;animation-name:jn-sweep-1lm4ikpk3kwah;animation-timing-function:var(--jn-ease);}" +
	"@keyframes jn-sweep-1lm4ikpk3kwah{from{transform:translateX(-100%);}" +
	"to{transform:translateX(140%);}" +
	"}" +
	".jn-notes-count{align-items:center;background-color:var(--jn-neutral-soft);border-radius:var(--jn-rpill);color:var(--jn-ink-muted);display:inline-flex;font-size:0.75rem;font-variant-numeric:tabular-nums;font-weight:600;justify-content:center;margin-inline-start:.5rem;min-width:1.5rem;padding:0 .5rem;vertical-align:middle;}" +
	".jn-notes-empty{color:var(--jn-ink-muted);font-size:0.875rem;margin-bottom:var(--jn-s2);}" +
	".jn-notes{display:flex;flex-direction:column;gap:var(--jn-s1);margin-bottom:var(--jn-s2);max-height:28rem;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:thin;}" +
	".jn-note-card{background-color:var(--jn-surface-muted);border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);display:flex;gap:0.625rem;padding:.625rem .75rem;}" +
	".jn-note[data-own=\"true\"] .jn-note-card{background-color:var(--jn-accent-soft);border-inline-start:3px solid var(--jn-accent);}" +
	".jn-note-avatar{align-items:center;background-color:var(--jn-neutral-soft);border-radius:50%;color:var(--jn-ink);display:inline-flex;flex:none;font-size:0.6875rem;font-weight:700;height:1.75rem;justify-content:center;letter-spacing:.02em;width:1.75rem;}" +
	".jn-note[data-own=\"true\"] .jn-note-avatar{background-color:var(--jn-accent);color:var(--jn-accent-ink);}" +
	".jn-note-main{display:flex;flex:1 1 auto;flex-direction:column;gap:0.125rem;min-width:0;}" +
	".jn-note-meta{align-items:baseline;column-gap:.5rem;display:flex;flex-wrap:wrap;font-size:0.8125rem;}" +
	".jn-note-author{color:var(--jn-ink);font-weight:600;overflow-wrap:anywhere;}" +
	".jn-note-own{background-color:var(--jn-accent);border-radius:var(--jn-rpill);color:var(--jn-accent-ink);font-size:0.6875rem;font-weight:600;padding:0 .375rem;}" +
	".jn-note-at{color:var(--jn-ink-muted);font-size:0.75rem;font-variant-numeric:tabular-nums;margin-inline-start:auto;}" +
	".jn-note-stage{color:var(--jn-ink-muted);font-size:0.75rem;}" +
	".jn-note-body{color:var(--jn-ink);font-size:0.875rem;line-height:1.5;margin-top:.25rem;overflow-wrap:anywhere;white-space:pre-wrap;}" +
	".jn-note-compose{border-top:1px solid var(--jn-hairline);display:flex;flex-direction:column;gap:0.5rem;padding-top:var(--jn-s2);}" +
	".jn-note-compose textarea{min-height:5.5rem;resize:vertical;}" +
	".jn-note-compose-foot{align-items:center;display:flex;flex-wrap:wrap;gap:0.75rem;}" +
	".jn-note-compose-foot .jn-btn{margin-inline-start:auto;}" +
	".jn-note-count{color:var(--jn-ink-muted);font-size:0.75rem;font-variant-numeric:tabular-nums;}" +
	".jn-note-count[data-state=\"near\"]{color:var(--jn-warning);font-weight:600;}" +
	".jn-note-count[data-state=\"over\"]{color:var(--jn-danger-ink);font-weight:600;}" +
	".jn-note-status{color:var(--jn-success);font-size:0.75rem;font-weight:600;min-height:1em;}" +
	".jn-note-status:empty{display:none;}" +
	".jn-wait-explanation{border-inline-start:3px solid var(--jn-warning);}" +
	".jn-wait-explanation .jn-facts{margin-top:var(--jn-s2);}" +
	".jn-checkpill[data-tone=\"warning\"]{animation-delay:.4s;animation-duration:2.8s;animation-iteration-count:infinite;animation-name:jn-amber-u5d68e6kyj7y;animation-timing-function:ease-in-out;}" +
	"@keyframes jn-amber-u5d68e6kyj7y{0%,100%{box-shadow:inset 0 0 0 1px rgba(122,74,0,.20);}" +
	"50%{box-shadow:inset 0 0 0 1px rgba(122,74,0,.20),0 0 0 4px rgba(122,74,0,.10);}" +
	"}" +
	".jn-checkpill[data-tone=\"danger\"]{animation-delay:.3s;animation-duration:2.2s;animation-iteration-count:infinite;animation-name:jn-alert-20wtq4njut0zx;animation-timing-function:ease-in-out;}" +
	"@keyframes jn-alert-20wtq4njut0zx{0%,100%{box-shadow:inset 0 0 0 1px rgba(155,17,48,.25);}" +
	"50%{box-shadow:inset 0 0 0 1px rgba(155,17,48,.25),0 0 0 4px rgba(155,17,48,.12);}" +
	"}" +
	".jn-checkpill[data-tone=\"info\"]{animation-delay:.5s;animation-duration:3.2s;animation-iteration-count:infinite;animation-name:jn-breathe-75v4lrd889a5;animation-timing-function:ease-in-out;}" +
	"@keyframes jn-breathe-75v4lrd889a5{0%,100%{opacity:1;}" +
	"50%{opacity:.82;}" +
	"}" +
	".jn-checkpill-icon{flex:none;}" +
	".jn-check-body{min-width:0;}" +
	".jn-check-msg{font-size:0.875rem;}" +
	".jn-check-code{color:var(--jn-ink-muted);margin-top:.125rem;}" +
	".jn-gauges{display:grid;gap:var(--jn-s2);grid-template-columns:1fr;margin-top:var(--jn-s3);}" +
	"@media (min-width:52rem){.jn-gauges{grid-template-columns:1fr 1fr;}" +
	"}" +
	".jn-gauge{background-color:var(--jn-surface-sunk);border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);min-width:0;padding-bottom:0.875rem;padding-left:1rem;padding-right:1rem;padding-top:0.875rem;}" +
	".jn-gauge .jn-subhead{margin-bottom:.625rem;}" +
	".jn-band,.jn-meter{height:auto;overflow:visible;width:100%;}" +
	".jn-band-track{fill:var(--jn-surface-muted);stroke:var(--jn-control-border);stroke-width:1;}" +
	".jn-band-fill{animation-delay:.15s;animation-duration:.6s;animation-fill-mode:both;animation-name:jn-grow-x-svg-12bsajj0jnz3p;animation-timing-function:var(--jn-ease);fill:var(--jn-accent);opacity:0.85;transform-box:fill-box;transform-origin:left center;}" +
	"@keyframes jn-grow-x-svg-12bsajj0jnz3p{from{transform:scaleX(0);}" +
	"to{transform:scaleX(1);}" +
	"}" +
	".jn-band-tick{stroke:var(--jn-control-border);stroke-dasharray:2 2;stroke-width:1;}" +
	".jn-band-marker{animation-delay:.5s;animation-duration:.45s;animation-fill-mode:both;animation-name:jn-drop-3rw36llel9w5q;animation-timing-function:var(--jn-ease);stroke-linecap:round;stroke-width:3;}" +
	"@keyframes jn-drop-3rw36llel9w5q{from{opacity:0;transform:translateY(-6px);}" +
	"to{opacity:1;transform:none;}" +
	"}" +
	".jn-band-marker[data-which=\"current\"]{stroke:var(--jn-neutral);}" +
	".jn-band-marker[data-which=\"proposed\"]{animation-delay:.65s;stroke:var(--jn-accent-strong);}" +
	".jn-meter-track{fill:var(--jn-surface-muted);stroke:var(--jn-control-border);stroke-width:1;}" +
	".jn-meter-fill{animation-delay:.2s;animation-duration:.7s;animation-fill-mode:both;animation-name:jn-grow-x-svg-12bsajj0jnz3p;animation-timing-function:var(--jn-ease);transform-box:fill-box;transform-origin:left center;}" +
	"@keyframes jn-grow-x-svg-12bsajj0jnz3p{from{transform:scaleX(0);}" +
	"to{transform:scaleX(1);}" +
	"}" +
	".jn-meter[data-tone=\"success\"] .jn-meter-fill{fill:var(--jn-success);}" +
	".jn-meter[data-tone=\"warning\"] .jn-meter-fill{fill:var(--jn-warning);}" +
	".jn-meter[data-tone=\"danger\"] .jn-meter-fill{animation:jn-grow-x-svg-12bsajj0jnz3p .7s var(--jn-ease) .2s both,jn-alert-20wtq4njut0zx 2.2s ease-in-out 1s infinite;fill:var(--jn-danger);}" +
	".jn-gauge-scale{color:var(--jn-ink-muted);display:flex;font-size:0.75rem;font-variant-numeric:tabular-nums;gap:0.5rem;justify-content:space-between;margin-top:.125rem;}" +
	".jn-gauge-legend{align-items:baseline;column-gap:0.625rem;display:grid;font-size:0.8125rem;grid-template-columns:auto 1fr;margin-top:.625rem;row-gap:0.125rem;}" +
	".jn-gauge-legend dt{align-items:center;color:var(--jn-ink-muted);display:flex;gap:0.375rem;}" +
	".jn-gauge-legend dt[data-which]::before{background-color:var(--jn-neutral);border-radius:var(--hcm-radius-xs,4px);content:\"\";height:0.5rem;width:0.5rem;}" +
	".jn-gauge-legend dt[data-which=\"proposed\"]::before{background-color:var(--jn-accent-strong);}" +
	".jn-gauge-legend dd{font-weight:600;margin:0;text-align:end;}" +
	".jn-gauge-note{color:var(--jn-ink-muted);font-size:0.75rem;margin-top:.625rem;}" +
	".jn-window{background-color:var(--jn-surface-sunk);border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);margin-top:var(--jn-s3);padding-bottom:0.875rem;padding-left:1rem;padding-right:1rem;padding-top:0.875rem;}" +
	".jn-strip{display:flex;flex-direction:column;gap:0.5rem;}" +
	"@media (min-width:44rem){.jn-strip{flex-direction:row;gap:0;}" +
	"}" +
	".jn-stop{display:flex;flex:1 1 0;flex-direction:column;gap:0.0625rem;padding-inline-start:1.125rem;position:relative;}" +
	"@media (min-width:44rem){.jn-stop{padding-inline-start:0;padding-top:1.125rem;}" +
	"}" +
	".jn-stop-dot{background-color:var(--jn-surface);border:2px solid var(--jn-control-border);border-radius:50%;height:0.625rem;inset-inline-start:0;position:absolute;top:0.375rem;width:0.625rem;}" +
	"@media (min-width:44rem){.jn-stop-dot{inset-inline-start:0;top:0;}" +
	"}" +
	"@media (min-width:44rem){.jn-stop::before{background-color:var(--jn-hairline);content:\"\";height:2px;inset-inline-end:0;inset-inline-start:.625rem;position:absolute;top:0.25rem;}" +
	"}" +
	"@media (min-width:44rem){.jn-stop:last-child::before{display:none;}" +
	"}" +
	".jn-stop[data-which=\"effective\"] .jn-stop-dot{background-color:var(--jn-accent);border-color:var(--jn-accent);}" +
	".jn-stop-label{color:var(--jn-ink-muted);font-size:0.75rem;font-weight:600;letter-spacing:var(--hcm-tracking-caps,.05em);text-transform:uppercase;}" +
	".jn-stop-value{font-size:0.875rem;font-variant-numeric:tabular-nums;font-weight:600;}" +
	".jn-stop[data-which=\"effective\"] .jn-stop-value{color:var(--jn-accent);}" +
	".jn-workitems{display:flex;flex-direction:column;gap:0.75rem;}" +
	".jn-workitem{background-color:var(--jn-surface-sunk);border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);padding-bottom:0.75rem;padding-left:0.875rem;padding-right:0.875rem;padding-top:0.75rem;}" +
	".jn-workitem-top{align-items:flex-start;display:flex;gap:0.75rem;justify-content:space-between;margin-bottom:.375rem;}" +
	".jn-workitem-kind{align-items:center;display:flex;font-size:0.875rem;font-weight:600;gap:0.375rem;}" +
	".jn-workitem-icon{color:var(--jn-ink-muted);}" +
	".jn-workitem-lines{color:var(--jn-ink-muted);display:flex;flex-direction:column;font-size:0.8125rem;gap:0.125rem;}" +
	".jn-evidence{display:flex;flex-wrap:wrap;gap:0.375rem;}" +
	".jn-evidence li{background-color:var(--jn-surface-sunk);border:1px solid var(--jn-hairline);border-radius:var(--jn-r1);font-family:var(--jn-mono);font-size:0.75rem;overflow-wrap:anywhere;padding-bottom:0.1875rem;padding-left:0.5rem;padding-right:0.5rem;padding-top:0.1875rem;}" +
	".jn-quiet{align-items:flex-start;background-color:var(--jn-surface-sunk);border:1px dashed var(--jn-control-border);border-radius:var(--jn-r2);color:var(--jn-ink-muted);display:flex;gap:0.625rem;padding-bottom:0.875rem;padding-left:1rem;padding-right:1rem;padding-top:0.875rem;}" +
	".jn-quiet-icon{flex:none;margin-top:.125rem;}" +
	".jn-actions{display:flex;flex-direction:column;gap:var(--jn-s2);}" +
	".jn-action{border-top:3px solid var(--jn-hairline);display:flex;flex-direction:column;gap:0.625rem;}" +
	".jn-action[data-variant=\"primary\"]{border-top-color:var(--jn-accent);}" +
	".jn-action[data-variant=\"danger\"]{border-top-color:var(--jn-danger);}" +
	".jn-action h3{letter-spacing:-0.014em;}" +
	".jn-action-desc{color:var(--jn-ink-muted);font-size:0.8125rem;}" +
	".jn-actsas{align-items:center;background-color:var(--jn-info-soft);border-radius:var(--jn-r1);color:var(--jn-info);display:flex;font-size:0.75rem;gap:0.375rem;padding-bottom:0.3125rem;padding-left:0.5rem;padding-right:0.5rem;padding-top:0.3125rem;}" +
	".jn-blocked{align-items:flex-start;background-color:var(--jn-warning-soft);border-radius:var(--jn-r1);color:var(--jn-warning);display:flex;font-size:0.75rem;gap:0.375rem;padding-bottom:0.3125rem;padding-left:0.5rem;padding-right:0.5rem;padding-top:0.3125rem;}" +
	".jn-confirm-trigger{width:100%;}" +
	".jn-confirm-close-label{display:none;}" +
	".jn-confirm[open] > summary.jn-btn{background:var(--jn-surface);border-color:var(--jn-control-border);box-shadow:none;color:var(--jn-accent);}" +
	".jn-confirm[open] > summary .jn-confirm-open-label{display:none;}" +
	".jn-confirm[open] > summary .jn-confirm-close-label{display:inline;}" +
	".jn-confirm-dialog{background-color:var(--jn-surface);border:1px solid var(--jn-control-border);border-radius:var(--jn-r3);box-shadow:0 1.5rem 4rem rgba(0,0,0,.35);color:var(--jn-ink);inset:0;margin:auto;max-height:calc(100dvh - 1.5rem);overflow:hidden;padding:0;position:fixed;width:min(38rem, calc(100vw - 1.25rem));}" +
	".jn-confirm-dialog[open]{display:flex;flex-direction:column;}" +
	".jn-confirm-dialog::backdrop{background:rgba(8,15,22,.72);}" +
	".jn-confirm-head{align-items:center;border-bottom:1px solid var(--jn-hairline);display:flex;gap:0.75rem;justify-content:space-between;padding:1rem;}" +
	".jn-confirm-title{font-size:1.125rem;font-weight:700;}" +
	".jn-confirm-cancel{flex:0 0 2.5rem;min-height:2.5rem;padding:0;white-space:nowrap;width:2.5rem;}" +
	"@media (min-width:22.5625rem){.jn-confirm-cancel{flex:0 1 auto;padding-bottom:0.625rem;padding-left:1rem;padding-right:1rem;padding-top:0.625rem;width:auto;}" +
	"}" +
	".jn-confirm-cancel-label{display:none;}" +
	"@media (min-width:22.5625rem){.jn-confirm-cancel-label{display:inline;}" +
	"}" +
	".jn-confirm-cancel-glyph{display:inline;font-size:1.25rem;}" +
	"@media (min-width:22.5625rem){.jn-confirm-cancel-glyph{display:none;}" +
	"}" +
	".jn-confirm-scroll{display:flex;flex-direction:column;gap:0.875rem;min-height:0;overflow-y:auto;overscroll-behavior:contain;padding:1rem;}" +
	".jn-confirm-facts{display:grid;gap:0.5rem;grid-template-columns:1fr;}" +
	"@media (min-width:30rem){.jn-confirm-facts{grid-template-columns:repeat(2,minmax(0,1fr));}" +
	"}" +
	".jn-confirm-facts .jn-fact dd{font-size:0.875rem;}" +
	".jn-confirm-note{align-items:flex-start;background-color:var(--jn-warning-soft);border-radius:var(--jn-r1);color:var(--jn-warning);display:flex;font-size:0.75rem;gap:0.375rem;padding:0.5rem;}" +
	".jn-confirm-icon{flex:none;margin-top:.0625rem;}" +
	".jn-confirm-surface{animation-duration:.18s;animation-fill-mode:both;animation-name:jn-slidein-2zqd52uojwort;animation-timing-function:var(--jn-ease);background-color:var(--jn-surface);border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);box-shadow:var(--jn-shadow-lift);display:flex;flex-direction:column;height:fit-content;inset:auto 0 0 0;margin:0;max-height:calc(100vh - 2rem);overflow-y:auto;overscroll-behavior:contain;padding:1rem;position:fixed;width:100%;}" +
	"@keyframes jn-slidein-2zqd52uojwort{from{opacity:0;transform:translateY(6px);}" +
	"to{opacity:1;transform:none;}" +
	"}" +
	":root .jn-confirm-surface{max-height:calc(100dvh - 2rem);}" +
	":root .jn-confirm-surface .jn-confirm-actionbar:where(*){bottom:-1rem;margin-bottom:-1rem;padding-bottom:1.625rem;}" +
	"@media (min-width:30.0625rem){:root .jn-confirm-surface{inset:0;margin:auto;width:min(34rem,calc(100vw - 2rem));}" +
	"}" +
	".jn-confirm-surface>.jn-confirm-body{display:flex;flex-direction:column;gap:0.875rem;}" +
	".jn-confirm-backdrop{background:color-mix(in srgb,var(--jn-ink) 45%,transparent);inset:0;position:fixed;}" +
	".jn-confirm-actionbar{background-color:var(--jn-surface);bottom:0;display:flex;flex-wrap:wrap;gap:0.625rem;justify-content:flex-end;margin-top:.125rem;padding-bottom:0.625rem;padding-top:0.625rem;position:sticky;}" +
	".jn-confirm[open]::details-content{content-visibility:visible;display:contents;}" +
	".jn-confirm-actionbar>.jn-btn{flex-shrink:0;max-width:100%;white-space:normal;}" +
	".jn-confirm-actionbar>.jn-confirm-cancel{flex:0 0 auto;padding-bottom:0.625rem;padding-left:1rem;padding-right:1rem;padding-top:0.625rem;width:auto;}" +
	".jn-confirm-cancel{order:0;}" +
	".jn-confirm-status{color:var(--jn-ink-muted);font-size:0.75rem;min-height:1em;}" +
	".jn-timeline{display:flex;flex-direction:column;}" +
	".jn-tl{display:flex;gap:0.75rem;padding-bottom:var(--jn-s2);position:relative;}" +
	".jn-tl:last-child{padding-bottom:0;}" +
	".jn-tl::before{background-color:var(--jn-hairline);bottom:0;content:\"\";inset-inline-start:.4375rem;position:absolute;top:1.125rem;width:2px;}" +
	".jn-tl:last-child::before{display:none;}" +
	".jn-tldot{background-color:var(--jn-surface);border:3px solid var(--jn-neutral);border-radius:50%;flex:none;height:1rem;margin-top:.1875rem;position:relative;width:1rem;z-index:1;}" +
	".jn-tl[data-tone=\"info\"] .jn-tldot{border-color:var(--jn-info);}" +
	".jn-tl[data-tone=\"success\"] .jn-tldot{border-color:var(--jn-success);}" +
	".jn-tl[data-tone=\"warning\"] .jn-tldot{border-color:var(--jn-warning);}" +
	".jn-tl[data-tone=\"danger\"] .jn-tldot{border-color:var(--jn-danger);}" +
	".jn-tl:first-child .jn-tldot{animation-duration:2.6s;animation-iteration-count:infinite;animation-name:jn-halo-d2evgl2isjd5;animation-timing-function:var(--jn-ease);}" +
	"@keyframes jn-halo-d2evgl2isjd5{0%,100%{box-shadow:0 0 0 0 rgba(43,58,143,.30);}" +
	"50%{box-shadow:0 0 0 6px rgba(43,58,143,0);}" +
	"}" +
	".jn-tlbody{display:flex;flex-direction:column;gap:0.125rem;min-width:0;}" +
	".jn-tlat{color:var(--jn-ink-muted);font-size:0.75rem;font-variant-numeric:tabular-nums;}" +
	".jn-tltitle{font-size:0.875rem;font-weight:600;}" +
	".jn-tldetail{color:var(--jn-ink-muted);font-size:0.8125rem;}" +
	".jn-footer{background-color:var(--jn-surface);border-top:1px solid var(--jn-hairline);}" +
	".jn-footer-inner{color:var(--jn-ink-muted);display:flex;flex-direction:column;font-size:0.75rem;gap:0.25rem;padding-bottom:var(--jn-s3);padding-top:var(--jn-s3);}" +
	".jn-provenance{column-gap:1rem;display:flex;flex-wrap:wrap;row-gap:0.25rem;}" +
	":where(.jn-page,.jn-embedded) :is(img,svg,video,canvas){max-width:100%;}" +
	":where(.jn-shell,.jn-page,.jn-pagehead,.jn-card,.jn-cardhead,.jn-grid,.jn-griditem,\n.jn-columns,.jn-maincol,.jn-rail,.jn-field,.jn-fieldgrid,.jn-fact,.jn-tlbody,\n.jn-network-stage,.jn-proxy-copy){min-width:0;}" +
	":where(.jn-page,.jn-embedded) :is(input,select,textarea,button){max-width:100%;}" +
	":where(.jn-pagehead,.jn-cardhead,.jn-toolbar,.jn-actions,.jn-provenance){flex-wrap:wrap;}" +
	":where(.jn-title,.jn-cardtitle,.jn-tltitle,.jn-tldetail,.jn-fact dd){overflow-wrap:anywhere;}" +
	".jn-tablewrap{max-width:100%;overscroll-behavior-inline:contain;scrollbar-width:thin;}" +
	".jn-journey-ref{font-size:0.75rem;font-variant-numeric:tabular-nums;font-weight:600;letter-spacing:.04em;margin-inline-start:.5rem;opacity:.7;unicode-bidi:isolate;}" +
	".jn-stepstate{color:inherit;display:inline-block;font-size:0.75rem;font-weight:600;letter-spacing:.02em;margin-inline-start:var(--jn-s2);}" +
	":is(.jn-page,.jn-embedded) .jn-journey-headline{font-size:0.875rem;}" +
	":is(.jn-page,.jn-embedded) .jn-journey-pay{font-size:1.125rem;}" +
	":is(.jn-page,.jn-embedded) .jn-meta{font-size:0.8125rem;}" +
	":is(.jn-page,.jn-embedded) .jn-journey-next{font-size:0.8125rem;}" +
	":is(.jn-page,.jn-embedded) .jn-journey-foot{font-size:0.8125rem;}" +
	":is(.jn-page,.jn-embedded) .jn-journey :is(p,li,dd,dt){max-inline-size:none;}" +
	".jn-journey-groups{align-items:start;gap:var(--jn-s3);grid-template-columns:repeat(auto-fill,minmax(min(21rem,100%),1fr));}" +
	".jn-journey-group:has(.jn-griditem+.jn-griditem){grid-column:1/-1;}" +
	".jn-journey-group-head{align-items:baseline;border-block-end:1px solid var(--jn-hairline);display:flex;flex-wrap:wrap;gap:0 var(--jn-s1);margin-block-end:.75rem;padding-block-end:.4375rem;}" +
	".jn-journey-group-subject{font-size:0.875rem;font-weight:600;letter-spacing:-.01em;margin:0;min-inline-size:0;overflow-wrap:anywhere;}" +
	".jn-journey-group-statuses{display:flex;flex-wrap:wrap;gap:.375rem;margin-inline-start:.25rem;}" +
	".jn-sectionhead-inline{gap:.625rem;justify-content:flex-start;}" +
	".jn-journey{gap:.5rem;padding:1.125rem;}" +
	".jn-journey h3{font-size:1rem;font-weight:600;letter-spacing:-.012em;line-height:1.25;}" +
	".jn-journey-headline{margin-block-start:-.25rem;overflow-wrap:anywhere;}" +
	".jn-journey>.jn-meta{column-gap:1rem;row-gap:.1875rem;}" +
	".jn-journey-next{border-inline-start:2px solid var(--jn-hairline);font-size:0.8125rem;padding-inline-start:.5625rem;}" +
	".jn-journey-next .jn-meta-value{color:var(--jn-ink);font-weight:600;}" +
	".jn-journey[data-stage=\"AWAITING_APPROVAL\"] .jn-journey-next{border-inline-start-color:var(--jn-warning);}" +
	".jn-journey[data-stage=\"BLOCKED\"] .jn-journey-next,\n.jn-journey[data-stage=\"FAILED\"] .jn-journey-next,\n.jn-journey[data-stage=\"REPAIR_REQUIRED\"] .jn-journey-next{border-inline-start-color:var(--jn-danger);}" +
	".jn-journey-technical,.jn-journey-technical summary,.jn-journey .jn-copy-btn{position:relative;z-index:1;}" +
	".jn-journey-technical>summary{border-radius:var(--jn-r1);color:var(--jn-ink-muted);cursor:pointer;font-size:0.75rem;font-weight:600;inline-size:fit-content;margin-inline-start:-.3125rem;padding:.125rem .3125rem;}" +
	".jn-journey-technical>summary:hover{color:var(--jn-ink);}" +
	".jn-journey-technical[open]>summary{color:var(--jn-ink);margin-block-end:.375rem;}" +
	".jn-tech-body{display:grid;gap:.25rem;}" +
	".jn-tech-row{align-items:center;display:flex;flex-wrap:wrap;font-size:0.75rem;gap:.375rem;}" +
	".jn-copy-btn{appearance:none;background:transparent;border:1px solid var(--jn-hairline);border-radius:var(--jn-r1);color:var(--jn-ink-muted);cursor:pointer;font:inherit;font-size:0.75rem;font-weight:600;min-block-size:1.5rem;padding:.0625rem .375rem;}" +
	".jn-copy-btn:hover{border-color:var(--jn-control-border);color:var(--jn-ink);}" +
	".jn-copy-btn:focus-visible{box-shadow:var(--jn-ring);outline:none;}" +
	".position-picker{border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);display:block;margin:0;min-inline-size:0;padding:var(--jn-s3);}" +
	".position-picker>legend{color:var(--jn-ink-muted);font-size:0.8125rem;font-weight:600;padding-inline:var(--jn-s2);}" +
	".position-picker-options{display:grid;gap:var(--jn-s2);list-style:none;margin:0;max-block-size:18rem;overflow-y:auto;padding:0;}" +
	".position-picker-option{align-items:baseline;border:1px solid var(--jn-hairline);border-radius:var(--jn-r1);display:flex;flex-wrap:wrap;gap:var(--jn-s2);justify-content:space-between;max-inline-size:none;padding:var(--jn-s2);}" +
	".position-picker-option:has(input:checked){background:var(--jn-accent-soft);border-color:var(--jn-accent);}" +
	".position-picker-option:hover{border-color:var(--jn-control-border);}" +
	".position-picker-option>label{align-items:baseline;cursor:pointer;display:flex;gap:var(--jn-s2);min-inline-size:0;}" +
	".position-picker-option-main{align-items:baseline;display:flex;flex-wrap:wrap;gap:0 var(--jn-s2);min-inline-size:0;}" +
	".position-picker-option-main>strong{font-size:0.875rem;font-weight:600;}" +
	".position-picker-option-main>small{color:var(--jn-ink-muted);font-size:0.8125rem;}" +
	".position-picker-option-main>small:empty{display:none;}" +
	".position-picker-option-meta{color:var(--jn-ink-muted);font-size:0.8125rem;white-space:nowrap;}" +
	".position-picker-empty{border-style:dashed;}" +
	".position-picker-empty-title{font-weight:600;margin:var(--jn-s2) 0 var(--jn-s1);}" +
	".position-picker-empty-detail{color:var(--jn-ink-muted);display:block;}" +
	".jn-compare{table-layout:fixed;width:100%;}" +
	".jn-compare :is(td,th){overflow-wrap:anywhere;white-space:normal;}" +
	".jn-compare.jn-table :is(td,th).jn-change{white-space:normal;}" +
	".jn-network-stage{min-height:24rem;position:relative;}" +
	".jn-network-stale{opacity:0.22;pointer-events:none;user-select:none;}" +
	".jn-network-proxy{inset:0;overflow:hidden;padding:var(--jn-s3);position:absolute;z-index:2;}" +
	".jn-proxy-toolbar,.jn-proxy-row{align-items:center;display:flex;gap:var(--jn-s2);}" +
	".jn-proxy-toolbar{border-bottom:1px solid var(--jn-hairline);justify-content:space-between;min-height:3rem;padding-bottom:var(--jn-s2);}" +
	".jn-proxy-rows{display:grid;}" +
	".jn-proxy-row{border-bottom:1px solid var(--jn-hairline);min-height:4.75rem;}" +
	".jn-proxy-block{background-color:var(--jn-surface-muted);border-radius:var(--jn-r1);display:block;overflow:hidden;position:relative;}" +
	".jn-proxy-heading{height:1rem;width:min(18rem,54%);}" +
	".jn-proxy-control{height:2.5rem;width:9rem;}" +
	".jn-proxy-avatar{border-radius:50%;flex:none;height:2.5rem;width:2.5rem;}" +
	".jn-proxy-copy{display:grid;flex:1;gap:0.625rem;min-width:0;}" +
	".jn-proxy-line{height:0.75rem;width:72%;}" +
	".jn-proxy-line-short{width:42%;}" +
	".jn-proxy-chip{border-radius:var(--jn-rpill);display:none;flex:none;height:1.625rem;width:5.5rem;}" +
	".jn-proxy-control{width:6rem;}" +
	"@media (prefers-reduced-motion:no-preference){:root:not([data-hcm-motion-preference=\"reduce\"]):not([data-hcm-motion-preference=\"limited\"]) .jn-proxy-block::after,\n:root:not([data-hcm-motion-preference=\"reduce\"]):not([data-hcm-motion-preference=\"limited\"]) .jn-loading::after{animation-duration:1.25s;animation-iteration-count:infinite;animation-name:jn-sweep-1lm4ikpk3kwah;animation-timing-function:linear;background:linear-gradient(100deg,transparent 18%,rgba(255,255,255,.58) 48%,transparent 78%);content:\"\";inset:0;pointer-events:none;position:absolute;}" +
	"}" +
	"@keyframes jn-sweep-1lm4ikpk3kwah{from{transform:translateX(-100%);}" +
	"to{transform:translateX(140%);}" +
	"}" +
	"@media (min-width:40rem){.jn-proxy-chip{display:block;}" +
	"}" +
	"@media (min-width:40rem){.jn-proxy-control{width:9rem;}" +
	"}" +
	"@media print{.jn-page{background-color:var(--jn-surface);}" +
	"}" +
	"@media print{.jn-masthead,.jn-skip,.jn-actions,.jn-btn{display:none;}" +
	"}" +
	"@media print{.jn-card,.jn-panel{box-shadow:none;break-inside:avoid;}" +
	"}" +
	"@media print{.jn-columns{grid-template-columns:minmax(0,1fr);}" +
	"}" +
	"@media print{.jn-rail{max-height:none;overflow:visible;position:static;}" +
	"}" +
	"@media (prefers-reduced-motion:reduce){:where(.jn-page,.jn-embedded),:where(.jn-page,.jn-embedded) *,:where(.jn-page,.jn-embedded) *::before,:where(.jn-page,.jn-embedded) *::after{animation-duration:.001ms !important;animation-iteration-count:1 !important;scroll-behavior:auto !important;transition-duration:.001ms !important;}" +
	"}" +
	"@media (prefers-reduced-motion:reduce){.jn-journey:hover{transform:none;}" +
	"}" +
	"@media (prefers-reduced-motion:reduce){.jn-checkpill::after{display:none;}" +
	"}" +
	".jn-journey-filter{margin-block:.75rem 1rem;}" +
	".jn-journey-filter-fields{align-items:end;display:grid;gap:0.75rem;grid-template-columns:minmax(0,1fr);}" +
	".jn-journey-filter-actions{align-items:center;display:flex;flex-wrap:wrap;gap:0.75rem;min-block-size:2.5rem;}" +
	".jn-journey-filter-toggle{align-items:center;display:inline-flex;gap:0.375rem;justify-self:start;}" +
	".jn-journey-filter-panel{display:grid;gap:0.75rem;grid-template-columns:minmax(0,1fr);}" +
	".jn-journey-filter-panel[data-open=\"false\"]{display:none;}" +
	"@media (min-width:40rem){.jn-journey-filter-toggle{display:none;}" +
	"}" +
	"@media (min-width:40rem){.jn-journey-filter-panel,.jn-journey-filter-panel[data-open=\"false\"]{display:contents;}" +
	"}" +
	".jn-journey-filter[data-collapsible=\"false\"] .jn-journey-filter-toggle{display:none;}" +
	".jn-journey-filter[data-collapsible=\"false\"] .jn-journey-filter-panel{display:contents;}" +
	".jn-journey-filter[data-collapsible=\"true\"] .jn-journey-filter-panel[data-open=\"false\"]{display:none;}" +
	"@media (min-width:40rem){.jn-journey-filter[data-collapsible=\"true\"] .jn-journey-filter-toggle{display:inline-flex;}" +
	"}" +
	"@media (min-width:40rem){.jn-journey-filter[data-collapsible=\"true\"] .jn-journey-filter-panel[data-open=\"false\"]{display:none;}" +
	"}" +
	"@media (min-width:40rem){.jn-journey-filter[data-collapsible=\"false\"] .jn-journey-filter-panel{display:contents;}" +
	"}" +
	"@media (min-width:40rem){.jn-journey-filter-fields{grid-template-columns:repeat(2,minmax(0,1fr));}" +
	"}" +
	"@media (min-width:40rem){.jn-journey-filter-fields>.jn-field:first-child{grid-column:1/-1;}" +
	"}" +
	"@media (min-width:68.75rem){.jn-journey-filter-fields{grid-template-columns:repeat(5,minmax(0,1fr));}" +
	"}" +
	"@media (min-width:68.75rem){.jn-journey-filter-fields>.jn-field:first-child{grid-column:span 2;}" +
	"}" +
	".jn-journey-filter .jn-field[data-field-id=\"journey-filter-sort\"]{min-inline-size:13rem;}" +
	"@media (min-width:68.75rem){.jn-journey-filter-actions{grid-column:span 3;}" +
	"}" +
	".jn-journey-filter-clear{color:var(--jn-accent);font-size:0.875rem;font-weight:600;}" +
	".jn-journey-top h3{min-inline-size:0;overflow-wrap:break-word;}" +
	".jn-journey-status{display:inline-flex;flex:none;}" +
	".jn-journey-refline{align-items:center;color:var(--jn-ink-muted);column-gap:.375rem;display:flex;flex-wrap:wrap;font-size:0.75rem;margin:0;row-gap:.25rem;}" +
	".jn-journey-refline .jn-journey-ref{color:var(--jn-ink);direction:ltr;margin-inline-start:0;opacity:1;white-space:nowrap;}" +
	".jn-review-cards{display:grid;gap:var(--jn-s3);grid-template-columns:1fr;min-width:0;}" +
	"@media (min-width:48rem){.jn-review-cards{grid-template-columns:1fr 1fr;}" +
	"}" +
	".jn-review-card{background-color:var(--jn-surface-muted);border:1px solid var(--jn-hairline);border-radius:var(--jn-r2);min-width:0;overflow-wrap:anywhere;padding:var(--jn-s3);}" +
	".jn-review-card .jn-subhead{margin:0 0 var(--jn-s2);}" +
	".promotion-review{display:grid;gap:var(--jn-s1);}" +
	".promotion-review p{font-size:0.875rem;margin:0;}" +
	".promotion-review-manager{font-weight:600;}" +
	".promotion-review-cycle-safe{color:var(--jn-success);font-weight:600;}" +
	".promotion-review-cycle-unsafe{color:var(--jn-warning);font-weight:600;}" +
	".compensation-guardrail>h3{font-size:0.9375rem;font-weight:600;margin:0 0 var(--jn-s2);}" +
	".compensation-guardrail-facts{column-gap:var(--jn-s2);display:grid;grid-template-columns:1fr;margin:0;row-gap:0.75rem;}" +
	"@media (min-width:34rem){.compensation-guardrail-facts{grid-template-columns:1fr 1fr;}" +
	"}" +
	".compensation-guardrail-facts>div{min-width:0;}" +
	".compensation-guardrail-facts dt{color:var(--jn-ink-muted);font-size:0.75rem;font-weight:600;}" +
	".compensation-guardrail-facts dd{font-size:0.875rem;font-variant-numeric:tabular-nums;font-weight:600;margin:0;}" +
	".compensation-guardrail-reason{color:var(--jn-ink-muted);font-size:0.875rem;margin:var(--jn-s2) 0 0;}" +
	".compensation-guardrail-action{max-inline-size:100%;}" +
	".jn-compare.jn-table{display:block;table-layout:auto;}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table{display:table;table-layout:fixed;}" +
	"}" +
	".jn-compare.jn-table>tbody{display:block;}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>tbody{display:table-row-group;}" +
	"}" +
	".jn-compare.jn-table>thead{clip:rect(0,0,0,0);height:1px;overflow:hidden;position:absolute;width:1px;}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>thead{clip:auto;height:auto;overflow:visible;position:static;width:auto;}" +
	"}" +
	".jn-compare.jn-table>tbody>tr{align-items:baseline;border-bottom:1px solid var(--jn-hairline);display:flex;flex-wrap:wrap;gap:.25rem .5rem;padding:.625rem .75rem;}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>tbody>tr{border-bottom:0;display:table-row;padding:0;}" +
	"}" +
	".jn-compare.jn-table>tbody>tr:last-child{border-bottom:0;}" +
	".jn-compare.jn-table>tbody>tr>:is(th,td){border:0;display:block;max-inline-size:100%;overflow-wrap:break-word;padding:0;white-space:normal;}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>tbody>tr>:is(th,td){border-bottom:1px solid var(--jn-hairline);display:table-cell;max-inline-size:none;overflow-wrap:anywhere;padding:.5625rem .75rem;}" +
	"}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>tbody>tr:last-child>:is(th,td){border-bottom:0;}" +
	"}" +
	".jn-compare.jn-table>tbody>tr>th{color:var(--jn-ink-muted);flex:1 1 100%;font-size:0.75rem;}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>tbody>tr>th{color:inherit;font-size:inherit;}" +
	"}" +
	".jn-compare.jn-table>tbody>tr>td:nth-child(2),.jn-compare.jn-table>tbody>tr>td:nth-child(3){flex:0 0 auto;}" +
	".jn-compare.jn-table>tbody>tr>td.jn-proposed::before{color:var(--jn-ink-muted);content:\"\\2192\" / \"\";font-weight:400;margin-inline-end:.5rem;}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>tbody>tr>td.jn-proposed::before{content:none;}" +
	"}" +
	"[dir=\"rtl\"] .jn-compare.jn-table>tbody>tr>td.jn-proposed::before{content:\"\\2190\" / \"\";}" +
	"@media (min-width:37.5rem){[dir=\"rtl\"] .jn-compare.jn-table>tbody>tr>td.jn-proposed::before{content:none;}" +
	"}" +
	".jn-compare.jn-table>tbody>tr:not([data-changed=\"true\"])>td.jn-proposed{display:none;}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>tbody>tr:not([data-changed=\"true\"])>td.jn-proposed{display:table-cell;}" +
	"}" +
	".jn-compare.jn-table>tbody>tr>td.jn-change{flex:1 1 100%;}" +
	".jn-compare.jn-table>tbody>tr:not([data-changed=\"true\"])>td{color:var(--jn-ink-muted);}" +
	"@media (min-width:37.5rem){.jn-compare.jn-table>tbody>tr:not([data-changed=\"true\"])>td{color:inherit;}" +
	"}"
