//go:build !(js && wasm)

package journeycss

import (
	"flag"
	"os"
	"strconv"
	"strings"
	"testing"
)

var updateStylesheetBlob = flag.Bool("update-blob", false, "rewrite stylesheet_blob.go from the typed declarations")

// TestStylesheetBlobMatchesBuilder holds the browser bundle's copy of the
// sheet (stylesheet_blob.go, returned by Stylesheet in stylesheet_wasm.go)
// byte-identical to what the typed declarations build for the server. The
// server pins sha256(Stylesheet()) in style-src, so a blob that differs by one
// byte is a page whose styles the browser refuses.
//
// After editing a typed_journey_*.go file, regenerate with
//
//	go test ./internal/experience/journeycss/ -run TestStylesheetBlobMatchesBuilder -update-blob
func TestStylesheetBlobMatchesBuilder(t *testing.T) {
	built := journeyTypedStylesheet()
	if *updateStylesheetBlob {
		if err := os.WriteFile("stylesheet_blob.go", []byte(renderStylesheetBlob(built)), 0o644); err != nil {
			t.Fatalf("write stylesheet_blob.go: %v", err)
		}
		t.Skip("stylesheet_blob.go rewritten; rerun without -update-blob")
	}
	if stylesheetBlob != built {
		t.Fatalf("stylesheet_blob.go is stale: blob is %d bytes, the typed declarations build %d bytes; run: go test ./internal/experience/journeycss/ -run TestStylesheetBlobMatchesBuilder -update-blob", len(stylesheetBlob), len(built))
	}
	if Stylesheet() != stylesheetBlob {
		t.Fatalf("Stylesheet() differs from the blob the browser bundle returns")
	}
}

// TestStylesheetBlobLayout pins the generated file's shape: one string
// constant, split after each closing brace so a diff reads rule by rule.
func TestStylesheetBlobLayout(t *testing.T) {
	built := journeyTypedStylesheet()
	rendered := renderStylesheetBlob(built)
	if !strings.HasPrefix(rendered, "// Code generated by TestStylesheetBlobMatchesBuilder") || !strings.Contains(rendered, "DO NOT EDIT.") {
		t.Fatalf("generated header missing: %.120q", rendered)
	}
	if strings.Count(rendered, "const stylesheetBlob") != 1 {
		t.Fatalf("want exactly one stylesheetBlob constant")
	}
	// Reassembling the quoted pieces must give back the sheet exactly.
	var rebuilt strings.Builder
	for _, line := range strings.Split(rendered, "\n") {
		piece := strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(line), "+"))
		piece = strings.TrimPrefix(piece, "const stylesheetBlob = ")
		if !strings.HasPrefix(piece, `"`) {
			continue
		}
		value, err := strconv.Unquote(piece)
		if err != nil {
			t.Fatalf("unquote %.80q: %v", piece, err)
		}
		rebuilt.WriteString(value)
	}
	if rebuilt.String() != built {
		t.Fatalf("rendered blob does not reassemble to the built sheet")
	}
}

func renderStylesheetBlob(sheet string) string {
	var b strings.Builder
	b.WriteString("// Code generated by TestStylesheetBlobMatchesBuilder (go test ./internal/experience/journeycss/ -run TestStylesheetBlobMatchesBuilder -update-blob); DO NOT EDIT.\n\npackage journeycss\n\n")
	b.WriteString("const stylesheetBlob = ")
	rest := sheet
	first := true
	for rest != "" {
		cut := strings.IndexByte(rest, '}')
		if cut < 0 {
			cut = len(rest) - 1
		}
		piece := rest[:cut+1]
		rest = rest[cut+1:]
		if !first {
			b.WriteString(" +\n\t")
		}
		first = false
		b.WriteString(strconv.Quote(piece))
	}
	if first {
		b.WriteString(`""`)
	}
	b.WriteString("\n")
	return b.String()
}
