// Code generated by tools/gen/clients from definitions/api/endpoint-manifest.json. DO NOT EDIT.

package clients

import (
	"context"

	"connectrpc.com/connect"
	dataopsv1 "github.com/monstercameron/human-capital-management-suite/gen/go/hcmnext/dataops/v1"
	"google.golang.org/grpc"
)

// Procedure paths for hcmnext.dataops.v1.DataOpsService, identical to the gRPC method's
// FullMethod and to connect.Spec.Procedure.
const (
	ProcedureCreateRepairPlan    = "/hcmnext.dataops.v1.DataOpsService/CreateRepairPlan"
	ProcedureDiffRecord          = "/hcmnext.dataops.v1.DataOpsService/DiffRecord"
	ProcedureExplainFieldHistory = "/hcmnext.dataops.v1.DataOpsService/ExplainFieldHistory"
	ProcedureSimulateRepair      = "/hcmnext.dataops.v1.DataOpsService/SimulateRepair"
)

// ProceduresDataOpsService returns every procedure path DataOpsClient
// publishes, in manifest order.
func ProceduresDataOpsService() []string {
	return []string{
		ProcedureCreateRepairPlan,
		ProcedureDiffRecord,
		ProcedureExplainFieldHistory,
		ProcedureSimulateRepair,
	}
}

// DataOpsClient is the transport-agnostic capability client for
// hcmnext.dataops.v1.DataOpsService. Both [NewDataOpsClientGRPC] and [NewDataOpsClientConnect]
// decode a failure into the identical *envelope.Error (DecodeGRPCError,
// DecodeConnectError), so calling code does not depend on which backend it
// was built with.
type DataOpsClient interface {
	// CreateRepairPlan calls hcmnext.dataops.v1.DataOpsService.CreateRepairPlan.
	CreateRepairPlan(ctx context.Context, req *dataopsv1.CreateRepairPlanRequest, opts ...CallOption) (*dataopsv1.CreateRepairPlanResponse, error)
	// DiffRecord calls hcmnext.dataops.v1.DataOpsService.DiffRecord.
	DiffRecord(ctx context.Context, req *dataopsv1.DiffRecordRequest, opts ...CallOption) (*dataopsv1.DiffRecordResponse, error)
	// ExplainFieldHistory calls hcmnext.dataops.v1.DataOpsService.ExplainFieldHistory.
	ExplainFieldHistory(ctx context.Context, req *dataopsv1.ExplainFieldHistoryRequest, opts ...CallOption) (*dataopsv1.ExplainFieldHistoryResponse, error)
	// SimulateRepair calls hcmnext.dataops.v1.DataOpsService.SimulateRepair.
	SimulateRepair(ctx context.Context, req *dataopsv1.SimulateRepairRequest, opts ...CallOption) (*dataopsv1.SimulateRepairResponse, error)
}

// dataOpsGRPCClient is the native gRPC backend for DataOpsClient.
type dataOpsGRPCClient struct {
	client dataopsv1.DataOpsServiceClient
}

// NewDataOpsClientGRPC builds a DataOpsClient that calls hcmnext.dataops.v1.DataOpsService
// over native gRPC on cc.
func NewDataOpsClientGRPC(cc grpc.ClientConnInterface) DataOpsClient {
	return &dataOpsGRPCClient{client: dataopsv1.NewDataOpsServiceClient(cc)}
}

// CreateRepairPlan calls hcmnext.dataops.v1.DataOpsService.CreateRepairPlan over native gRPC.
func (c *dataOpsGRPCClient) CreateRepairPlan(ctx context.Context, req *dataopsv1.CreateRepairPlanRequest, opts ...CallOption) (*dataopsv1.CreateRepairPlanResponse, error) {
	res, err := c.client.CreateRepairPlan(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// DiffRecord calls hcmnext.dataops.v1.DataOpsService.DiffRecord over native gRPC.
func (c *dataOpsGRPCClient) DiffRecord(ctx context.Context, req *dataopsv1.DiffRecordRequest, opts ...CallOption) (*dataopsv1.DiffRecordResponse, error) {
	res, err := c.client.DiffRecord(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ExplainFieldHistory calls hcmnext.dataops.v1.DataOpsService.ExplainFieldHistory over native gRPC.
func (c *dataOpsGRPCClient) ExplainFieldHistory(ctx context.Context, req *dataopsv1.ExplainFieldHistoryRequest, opts ...CallOption) (*dataopsv1.ExplainFieldHistoryResponse, error) {
	res, err := c.client.ExplainFieldHistory(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// SimulateRepair calls hcmnext.dataops.v1.DataOpsService.SimulateRepair over native gRPC.
func (c *dataOpsGRPCClient) SimulateRepair(ctx context.Context, req *dataopsv1.SimulateRepairRequest, opts ...CallOption) (*dataopsv1.SimulateRepairResponse, error) {
	res, err := c.client.SimulateRepair(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// dataOpsConnectClient is the connect-go backend for DataOpsClient.
type dataOpsConnectClient struct {
	createRepairPlan    *connect.Client[dataopsv1.CreateRepairPlanRequest, dataopsv1.CreateRepairPlanResponse]
	diffRecord          *connect.Client[dataopsv1.DiffRecordRequest, dataopsv1.DiffRecordResponse]
	explainFieldHistory *connect.Client[dataopsv1.ExplainFieldHistoryRequest, dataopsv1.ExplainFieldHistoryResponse]
	simulateRepair      *connect.Client[dataopsv1.SimulateRepairRequest, dataopsv1.SimulateRepairResponse]
}

// NewDataOpsClientConnect builds a DataOpsClient that calls the
// hcmnext.dataops.v1.DataOpsService procedures published at baseURL over connect-go.
func NewDataOpsClientConnect(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DataOpsClient {
	return &dataOpsConnectClient{
		createRepairPlan:    connect.NewClient[dataopsv1.CreateRepairPlanRequest, dataopsv1.CreateRepairPlanResponse](httpClient, baseURL+ProcedureCreateRepairPlan, opts...),
		diffRecord:          connect.NewClient[dataopsv1.DiffRecordRequest, dataopsv1.DiffRecordResponse](httpClient, baseURL+ProcedureDiffRecord, opts...),
		explainFieldHistory: connect.NewClient[dataopsv1.ExplainFieldHistoryRequest, dataopsv1.ExplainFieldHistoryResponse](httpClient, baseURL+ProcedureExplainFieldHistory, opts...),
		simulateRepair:      connect.NewClient[dataopsv1.SimulateRepairRequest, dataopsv1.SimulateRepairResponse](httpClient, baseURL+ProcedureSimulateRepair, opts...),
	}
}

// CreateRepairPlan calls hcmnext.dataops.v1.DataOpsService.CreateRepairPlan over connect-go.
func (c *dataOpsConnectClient) CreateRepairPlan(ctx context.Context, req *dataopsv1.CreateRepairPlanRequest, opts ...CallOption) (*dataopsv1.CreateRepairPlanResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.createRepairPlan.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// DiffRecord calls hcmnext.dataops.v1.DataOpsService.DiffRecord over connect-go.
func (c *dataOpsConnectClient) DiffRecord(ctx context.Context, req *dataopsv1.DiffRecordRequest, opts ...CallOption) (*dataopsv1.DiffRecordResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.diffRecord.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ExplainFieldHistory calls hcmnext.dataops.v1.DataOpsService.ExplainFieldHistory over connect-go.
func (c *dataOpsConnectClient) ExplainFieldHistory(ctx context.Context, req *dataopsv1.ExplainFieldHistoryRequest, opts ...CallOption) (*dataopsv1.ExplainFieldHistoryResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.explainFieldHistory.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// SimulateRepair calls hcmnext.dataops.v1.DataOpsService.SimulateRepair over connect-go.
func (c *dataOpsConnectClient) SimulateRepair(ctx context.Context, req *dataopsv1.SimulateRepairRequest, opts ...CallOption) (*dataopsv1.SimulateRepairResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.simulateRepair.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}
