// Code generated by tools/gen/clients from definitions/api/endpoint-manifest.json. DO NOT EDIT.

package clients

import (
	"context"

	"connectrpc.com/connect"
	integrationv1 "github.com/monstercameron/human-capital-management-suite/gen/go/hcmnext/integration/v1"
	"google.golang.org/grpc"
)

// Procedure paths for hcmnext.integration.v1.IntegrationService, identical to the gRPC method's
// FullMethod and to connect.Spec.Procedure.
const (
	ProcedureGetConnectorConnection   = "/hcmnext.integration.v1.IntegrationService/GetConnectorConnection"
	ProcedureGetConnectorDefinition   = "/hcmnext.integration.v1.IntegrationService/GetConnectorDefinition"
	ProcedureGetExternalObservation   = "/hcmnext.integration.v1.IntegrationService/GetExternalObservation"
	ProcedureListConnectorConnections = "/hcmnext.integration.v1.IntegrationService/ListConnectorConnections"
	ProcedureListConnectorDefinitions = "/hcmnext.integration.v1.IntegrationService/ListConnectorDefinitions"
	ProcedureListExternalObservations = "/hcmnext.integration.v1.IntegrationService/ListExternalObservations"
	ProcedureTestConnectorConnection  = "/hcmnext.integration.v1.IntegrationService/TestConnectorConnection"
)

// ProceduresIntegrationService returns every procedure path IntegrationClient
// publishes, in manifest order.
func ProceduresIntegrationService() []string {
	return []string{
		ProcedureGetConnectorConnection,
		ProcedureGetConnectorDefinition,
		ProcedureGetExternalObservation,
		ProcedureListConnectorConnections,
		ProcedureListConnectorDefinitions,
		ProcedureListExternalObservations,
		ProcedureTestConnectorConnection,
	}
}

// IntegrationClient is the transport-agnostic capability client for
// hcmnext.integration.v1.IntegrationService. Both [NewIntegrationClientGRPC] and [NewIntegrationClientConnect]
// decode a failure into the identical *envelope.Error (DecodeGRPCError,
// DecodeConnectError), so calling code does not depend on which backend it
// was built with.
type IntegrationClient interface {
	// GetConnectorConnection calls hcmnext.integration.v1.IntegrationService.GetConnectorConnection.
	GetConnectorConnection(ctx context.Context, req *integrationv1.GetConnectorConnectionRequest, opts ...CallOption) (*integrationv1.GetConnectorConnectionResponse, error)
	// GetConnectorDefinition calls hcmnext.integration.v1.IntegrationService.GetConnectorDefinition.
	GetConnectorDefinition(ctx context.Context, req *integrationv1.GetConnectorDefinitionRequest, opts ...CallOption) (*integrationv1.GetConnectorDefinitionResponse, error)
	// GetExternalObservation calls hcmnext.integration.v1.IntegrationService.GetExternalObservation.
	GetExternalObservation(ctx context.Context, req *integrationv1.GetExternalObservationRequest, opts ...CallOption) (*integrationv1.GetExternalObservationResponse, error)
	// ListConnectorConnections calls hcmnext.integration.v1.IntegrationService.ListConnectorConnections.
	ListConnectorConnections(ctx context.Context, req *integrationv1.ListConnectorConnectionsRequest, opts ...CallOption) (*integrationv1.ListConnectorConnectionsResponse, error)
	// ListConnectorDefinitions calls hcmnext.integration.v1.IntegrationService.ListConnectorDefinitions.
	ListConnectorDefinitions(ctx context.Context, req *integrationv1.ListConnectorDefinitionsRequest, opts ...CallOption) (*integrationv1.ListConnectorDefinitionsResponse, error)
	// ListExternalObservations calls hcmnext.integration.v1.IntegrationService.ListExternalObservations.
	ListExternalObservations(ctx context.Context, req *integrationv1.ListExternalObservationsRequest, opts ...CallOption) (*integrationv1.ListExternalObservationsResponse, error)
	// TestConnectorConnection calls hcmnext.integration.v1.IntegrationService.TestConnectorConnection.
	TestConnectorConnection(ctx context.Context, req *integrationv1.TestConnectorConnectionRequest, opts ...CallOption) (*integrationv1.TestConnectorConnectionResponse, error)
}

// integrationGRPCClient is the native gRPC backend for IntegrationClient.
type integrationGRPCClient struct {
	client integrationv1.IntegrationServiceClient
}

// NewIntegrationClientGRPC builds a IntegrationClient that calls hcmnext.integration.v1.IntegrationService
// over native gRPC on cc.
func NewIntegrationClientGRPC(cc grpc.ClientConnInterface) IntegrationClient {
	return &integrationGRPCClient{client: integrationv1.NewIntegrationServiceClient(cc)}
}

// GetConnectorConnection calls hcmnext.integration.v1.IntegrationService.GetConnectorConnection over native gRPC.
func (c *integrationGRPCClient) GetConnectorConnection(ctx context.Context, req *integrationv1.GetConnectorConnectionRequest, opts ...CallOption) (*integrationv1.GetConnectorConnectionResponse, error) {
	res, err := c.client.GetConnectorConnection(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetConnectorDefinition calls hcmnext.integration.v1.IntegrationService.GetConnectorDefinition over native gRPC.
func (c *integrationGRPCClient) GetConnectorDefinition(ctx context.Context, req *integrationv1.GetConnectorDefinitionRequest, opts ...CallOption) (*integrationv1.GetConnectorDefinitionResponse, error) {
	res, err := c.client.GetConnectorDefinition(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetExternalObservation calls hcmnext.integration.v1.IntegrationService.GetExternalObservation over native gRPC.
func (c *integrationGRPCClient) GetExternalObservation(ctx context.Context, req *integrationv1.GetExternalObservationRequest, opts ...CallOption) (*integrationv1.GetExternalObservationResponse, error) {
	res, err := c.client.GetExternalObservation(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListConnectorConnections calls hcmnext.integration.v1.IntegrationService.ListConnectorConnections over native gRPC.
func (c *integrationGRPCClient) ListConnectorConnections(ctx context.Context, req *integrationv1.ListConnectorConnectionsRequest, opts ...CallOption) (*integrationv1.ListConnectorConnectionsResponse, error) {
	res, err := c.client.ListConnectorConnections(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListConnectorDefinitions calls hcmnext.integration.v1.IntegrationService.ListConnectorDefinitions over native gRPC.
func (c *integrationGRPCClient) ListConnectorDefinitions(ctx context.Context, req *integrationv1.ListConnectorDefinitionsRequest, opts ...CallOption) (*integrationv1.ListConnectorDefinitionsResponse, error) {
	res, err := c.client.ListConnectorDefinitions(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListExternalObservations calls hcmnext.integration.v1.IntegrationService.ListExternalObservations over native gRPC.
func (c *integrationGRPCClient) ListExternalObservations(ctx context.Context, req *integrationv1.ListExternalObservationsRequest, opts ...CallOption) (*integrationv1.ListExternalObservationsResponse, error) {
	res, err := c.client.ListExternalObservations(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// TestConnectorConnection calls hcmnext.integration.v1.IntegrationService.TestConnectorConnection over native gRPC.
func (c *integrationGRPCClient) TestConnectorConnection(ctx context.Context, req *integrationv1.TestConnectorConnectionRequest, opts ...CallOption) (*integrationv1.TestConnectorConnectionResponse, error) {
	res, err := c.client.TestConnectorConnection(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// integrationConnectClient is the connect-go backend for IntegrationClient.
type integrationConnectClient struct {
	getConnectorConnection   *connect.Client[integrationv1.GetConnectorConnectionRequest, integrationv1.GetConnectorConnectionResponse]
	getConnectorDefinition   *connect.Client[integrationv1.GetConnectorDefinitionRequest, integrationv1.GetConnectorDefinitionResponse]
	getExternalObservation   *connect.Client[integrationv1.GetExternalObservationRequest, integrationv1.GetExternalObservationResponse]
	listConnectorConnections *connect.Client[integrationv1.ListConnectorConnectionsRequest, integrationv1.ListConnectorConnectionsResponse]
	listConnectorDefinitions *connect.Client[integrationv1.ListConnectorDefinitionsRequest, integrationv1.ListConnectorDefinitionsResponse]
	listExternalObservations *connect.Client[integrationv1.ListExternalObservationsRequest, integrationv1.ListExternalObservationsResponse]
	testConnectorConnection  *connect.Client[integrationv1.TestConnectorConnectionRequest, integrationv1.TestConnectorConnectionResponse]
}

// NewIntegrationClientConnect builds a IntegrationClient that calls the
// hcmnext.integration.v1.IntegrationService procedures published at baseURL over connect-go.
func NewIntegrationClientConnect(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IntegrationClient {
	return &integrationConnectClient{
		getConnectorConnection:   connect.NewClient[integrationv1.GetConnectorConnectionRequest, integrationv1.GetConnectorConnectionResponse](httpClient, baseURL+ProcedureGetConnectorConnection, opts...),
		getConnectorDefinition:   connect.NewClient[integrationv1.GetConnectorDefinitionRequest, integrationv1.GetConnectorDefinitionResponse](httpClient, baseURL+ProcedureGetConnectorDefinition, opts...),
		getExternalObservation:   connect.NewClient[integrationv1.GetExternalObservationRequest, integrationv1.GetExternalObservationResponse](httpClient, baseURL+ProcedureGetExternalObservation, opts...),
		listConnectorConnections: connect.NewClient[integrationv1.ListConnectorConnectionsRequest, integrationv1.ListConnectorConnectionsResponse](httpClient, baseURL+ProcedureListConnectorConnections, opts...),
		listConnectorDefinitions: connect.NewClient[integrationv1.ListConnectorDefinitionsRequest, integrationv1.ListConnectorDefinitionsResponse](httpClient, baseURL+ProcedureListConnectorDefinitions, opts...),
		listExternalObservations: connect.NewClient[integrationv1.ListExternalObservationsRequest, integrationv1.ListExternalObservationsResponse](httpClient, baseURL+ProcedureListExternalObservations, opts...),
		testConnectorConnection:  connect.NewClient[integrationv1.TestConnectorConnectionRequest, integrationv1.TestConnectorConnectionResponse](httpClient, baseURL+ProcedureTestConnectorConnection, opts...),
	}
}

// GetConnectorConnection calls hcmnext.integration.v1.IntegrationService.GetConnectorConnection over connect-go.
func (c *integrationConnectClient) GetConnectorConnection(ctx context.Context, req *integrationv1.GetConnectorConnectionRequest, opts ...CallOption) (*integrationv1.GetConnectorConnectionResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getConnectorConnection.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetConnectorDefinition calls hcmnext.integration.v1.IntegrationService.GetConnectorDefinition over connect-go.
func (c *integrationConnectClient) GetConnectorDefinition(ctx context.Context, req *integrationv1.GetConnectorDefinitionRequest, opts ...CallOption) (*integrationv1.GetConnectorDefinitionResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getConnectorDefinition.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetExternalObservation calls hcmnext.integration.v1.IntegrationService.GetExternalObservation over connect-go.
func (c *integrationConnectClient) GetExternalObservation(ctx context.Context, req *integrationv1.GetExternalObservationRequest, opts ...CallOption) (*integrationv1.GetExternalObservationResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getExternalObservation.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListConnectorConnections calls hcmnext.integration.v1.IntegrationService.ListConnectorConnections over connect-go.
func (c *integrationConnectClient) ListConnectorConnections(ctx context.Context, req *integrationv1.ListConnectorConnectionsRequest, opts ...CallOption) (*integrationv1.ListConnectorConnectionsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listConnectorConnections.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListConnectorDefinitions calls hcmnext.integration.v1.IntegrationService.ListConnectorDefinitions over connect-go.
func (c *integrationConnectClient) ListConnectorDefinitions(ctx context.Context, req *integrationv1.ListConnectorDefinitionsRequest, opts ...CallOption) (*integrationv1.ListConnectorDefinitionsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listConnectorDefinitions.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListExternalObservations calls hcmnext.integration.v1.IntegrationService.ListExternalObservations over connect-go.
func (c *integrationConnectClient) ListExternalObservations(ctx context.Context, req *integrationv1.ListExternalObservationsRequest, opts ...CallOption) (*integrationv1.ListExternalObservationsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listExternalObservations.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// TestConnectorConnection calls hcmnext.integration.v1.IntegrationService.TestConnectorConnection over connect-go.
func (c *integrationConnectClient) TestConnectorConnection(ctx context.Context, req *integrationv1.TestConnectorConnectionRequest, opts ...CallOption) (*integrationv1.TestConnectorConnectionResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.testConnectorConnection.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}
