// Code generated by tools/gen/clients from definitions/api/endpoint-manifest.json. DO NOT EDIT.

package clients

import (
	"context"

	"connectrpc.com/connect"
	intentsv1 "github.com/monstercameron/human-capital-management-suite/gen/go/hcmnext/intents/v1"
	"google.golang.org/grpc"
)

// Procedure paths for hcmnext.intents.v1.IntentService, identical to the gRPC method's
// FullMethod and to connect.Spec.Procedure.
const (
	ProcedureCancelIntent       = "/hcmnext.intents.v1.IntentService/CancelIntent"
	ProcedureCreateIntent       = "/hcmnext.intents.v1.IntentService/CreateIntent"
	ProcedureExecuteIntent      = "/hcmnext.intents.v1.IntentService/ExecuteIntent"
	ProcedureExplainIntent      = "/hcmnext.intents.v1.IntentService/ExplainIntent"
	ProcedureGetIntent          = "/hcmnext.intents.v1.IntentService/GetIntent"
	ProcedureListIntentTimeline = "/hcmnext.intents.v1.IntentService/ListIntentTimeline"
	ProcedureListIntents        = "/hcmnext.intents.v1.IntentService/ListIntents"
	ProcedureSimulateIntent     = "/hcmnext.intents.v1.IntentService/SimulateIntent"
	ProcedureSubmitIntent       = "/hcmnext.intents.v1.IntentService/SubmitIntent"
	ProcedureSupersedeIntent    = "/hcmnext.intents.v1.IntentService/SupersedeIntent"
)

// ProceduresIntentService returns every procedure path IntentClient
// publishes, in manifest order.
func ProceduresIntentService() []string {
	return []string{
		ProcedureCancelIntent,
		ProcedureCreateIntent,
		ProcedureExecuteIntent,
		ProcedureExplainIntent,
		ProcedureGetIntent,
		ProcedureListIntentTimeline,
		ProcedureListIntents,
		ProcedureSimulateIntent,
		ProcedureSubmitIntent,
		ProcedureSupersedeIntent,
	}
}

// IntentClient is the transport-agnostic capability client for
// hcmnext.intents.v1.IntentService. Both [NewIntentClientGRPC] and [NewIntentClientConnect]
// decode a failure into the identical *envelope.Error (DecodeGRPCError,
// DecodeConnectError), so calling code does not depend on which backend it
// was built with.
type IntentClient interface {
	// CancelIntent calls hcmnext.intents.v1.IntentService.CancelIntent.
	CancelIntent(ctx context.Context, req *intentsv1.CancelIntentRequest, opts ...CallOption) (*intentsv1.CancelIntentResponse, error)
	// CreateIntent calls hcmnext.intents.v1.IntentService.CreateIntent.
	CreateIntent(ctx context.Context, req *intentsv1.CreateIntentRequest, opts ...CallOption) (*intentsv1.CreateIntentResponse, error)
	// ExecuteIntent calls hcmnext.intents.v1.IntentService.ExecuteIntent. The method exists
	// on the wire for P1B forward compatibility; every P1A invocation is
	// refused (disposition REFUSED_P1A), identically on both backends.
	ExecuteIntent(ctx context.Context, req *intentsv1.ExecuteIntentRequest, opts ...CallOption) (*intentsv1.ExecuteIntentResponse, error)
	// ExplainIntent calls hcmnext.intents.v1.IntentService.ExplainIntent.
	ExplainIntent(ctx context.Context, req *intentsv1.ExplainIntentRequest, opts ...CallOption) (*intentsv1.ExplainIntentResponse, error)
	// GetIntent calls hcmnext.intents.v1.IntentService.GetIntent.
	GetIntent(ctx context.Context, req *intentsv1.GetIntentRequest, opts ...CallOption) (*intentsv1.GetIntentResponse, error)
	// ListIntentTimeline calls hcmnext.intents.v1.IntentService.ListIntentTimeline.
	ListIntentTimeline(ctx context.Context, req *intentsv1.ListIntentTimelineRequest, opts ...CallOption) (*intentsv1.ListIntentTimelineResponse, error)
	// ListIntents calls hcmnext.intents.v1.IntentService.ListIntents.
	ListIntents(ctx context.Context, req *intentsv1.ListIntentsRequest, opts ...CallOption) (*intentsv1.ListIntentsResponse, error)
	// SimulateIntent calls hcmnext.intents.v1.IntentService.SimulateIntent.
	SimulateIntent(ctx context.Context, req *intentsv1.SimulateIntentRequest, opts ...CallOption) (*intentsv1.SimulateIntentResponse, error)
	// SubmitIntent calls hcmnext.intents.v1.IntentService.SubmitIntent.
	SubmitIntent(ctx context.Context, req *intentsv1.SubmitIntentRequest, opts ...CallOption) (*intentsv1.SubmitIntentResponse, error)
	// SupersedeIntent calls hcmnext.intents.v1.IntentService.SupersedeIntent.
	SupersedeIntent(ctx context.Context, req *intentsv1.SupersedeIntentRequest, opts ...CallOption) (*intentsv1.SupersedeIntentResponse, error)
}

// intentGRPCClient is the native gRPC backend for IntentClient.
type intentGRPCClient struct {
	client intentsv1.IntentServiceClient
}

// NewIntentClientGRPC builds a IntentClient that calls hcmnext.intents.v1.IntentService
// over native gRPC on cc.
func NewIntentClientGRPC(cc grpc.ClientConnInterface) IntentClient {
	return &intentGRPCClient{client: intentsv1.NewIntentServiceClient(cc)}
}

// CancelIntent calls hcmnext.intents.v1.IntentService.CancelIntent over native gRPC.
func (c *intentGRPCClient) CancelIntent(ctx context.Context, req *intentsv1.CancelIntentRequest, opts ...CallOption) (*intentsv1.CancelIntentResponse, error) {
	res, err := c.client.CancelIntent(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// CreateIntent calls hcmnext.intents.v1.IntentService.CreateIntent over native gRPC.
func (c *intentGRPCClient) CreateIntent(ctx context.Context, req *intentsv1.CreateIntentRequest, opts ...CallOption) (*intentsv1.CreateIntentResponse, error) {
	res, err := c.client.CreateIntent(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ExecuteIntent calls hcmnext.intents.v1.IntentService.ExecuteIntent over native gRPC.
func (c *intentGRPCClient) ExecuteIntent(ctx context.Context, req *intentsv1.ExecuteIntentRequest, opts ...CallOption) (*intentsv1.ExecuteIntentResponse, error) {
	res, err := c.client.ExecuteIntent(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ExplainIntent calls hcmnext.intents.v1.IntentService.ExplainIntent over native gRPC.
func (c *intentGRPCClient) ExplainIntent(ctx context.Context, req *intentsv1.ExplainIntentRequest, opts ...CallOption) (*intentsv1.ExplainIntentResponse, error) {
	res, err := c.client.ExplainIntent(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetIntent calls hcmnext.intents.v1.IntentService.GetIntent over native gRPC.
func (c *intentGRPCClient) GetIntent(ctx context.Context, req *intentsv1.GetIntentRequest, opts ...CallOption) (*intentsv1.GetIntentResponse, error) {
	res, err := c.client.GetIntent(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListIntentTimeline calls hcmnext.intents.v1.IntentService.ListIntentTimeline over native gRPC.
func (c *intentGRPCClient) ListIntentTimeline(ctx context.Context, req *intentsv1.ListIntentTimelineRequest, opts ...CallOption) (*intentsv1.ListIntentTimelineResponse, error) {
	res, err := c.client.ListIntentTimeline(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListIntents calls hcmnext.intents.v1.IntentService.ListIntents over native gRPC.
func (c *intentGRPCClient) ListIntents(ctx context.Context, req *intentsv1.ListIntentsRequest, opts ...CallOption) (*intentsv1.ListIntentsResponse, error) {
	res, err := c.client.ListIntents(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// SimulateIntent calls hcmnext.intents.v1.IntentService.SimulateIntent over native gRPC.
func (c *intentGRPCClient) SimulateIntent(ctx context.Context, req *intentsv1.SimulateIntentRequest, opts ...CallOption) (*intentsv1.SimulateIntentResponse, error) {
	res, err := c.client.SimulateIntent(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// SubmitIntent calls hcmnext.intents.v1.IntentService.SubmitIntent over native gRPC.
func (c *intentGRPCClient) SubmitIntent(ctx context.Context, req *intentsv1.SubmitIntentRequest, opts ...CallOption) (*intentsv1.SubmitIntentResponse, error) {
	res, err := c.client.SubmitIntent(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// SupersedeIntent calls hcmnext.intents.v1.IntentService.SupersedeIntent over native gRPC.
func (c *intentGRPCClient) SupersedeIntent(ctx context.Context, req *intentsv1.SupersedeIntentRequest, opts ...CallOption) (*intentsv1.SupersedeIntentResponse, error) {
	res, err := c.client.SupersedeIntent(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// intentConnectClient is the connect-go backend for IntentClient.
type intentConnectClient struct {
	cancelIntent       *connect.Client[intentsv1.CancelIntentRequest, intentsv1.CancelIntentResponse]
	createIntent       *connect.Client[intentsv1.CreateIntentRequest, intentsv1.CreateIntentResponse]
	executeIntent      *connect.Client[intentsv1.ExecuteIntentRequest, intentsv1.ExecuteIntentResponse]
	explainIntent      *connect.Client[intentsv1.ExplainIntentRequest, intentsv1.ExplainIntentResponse]
	getIntent          *connect.Client[intentsv1.GetIntentRequest, intentsv1.GetIntentResponse]
	listIntentTimeline *connect.Client[intentsv1.ListIntentTimelineRequest, intentsv1.ListIntentTimelineResponse]
	listIntents        *connect.Client[intentsv1.ListIntentsRequest, intentsv1.ListIntentsResponse]
	simulateIntent     *connect.Client[intentsv1.SimulateIntentRequest, intentsv1.SimulateIntentResponse]
	submitIntent       *connect.Client[intentsv1.SubmitIntentRequest, intentsv1.SubmitIntentResponse]
	supersedeIntent    *connect.Client[intentsv1.SupersedeIntentRequest, intentsv1.SupersedeIntentResponse]
}

// NewIntentClientConnect builds a IntentClient that calls the
// hcmnext.intents.v1.IntentService procedures published at baseURL over connect-go.
func NewIntentClientConnect(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IntentClient {
	return &intentConnectClient{
		cancelIntent:       connect.NewClient[intentsv1.CancelIntentRequest, intentsv1.CancelIntentResponse](httpClient, baseURL+ProcedureCancelIntent, opts...),
		createIntent:       connect.NewClient[intentsv1.CreateIntentRequest, intentsv1.CreateIntentResponse](httpClient, baseURL+ProcedureCreateIntent, opts...),
		executeIntent:      connect.NewClient[intentsv1.ExecuteIntentRequest, intentsv1.ExecuteIntentResponse](httpClient, baseURL+ProcedureExecuteIntent, opts...),
		explainIntent:      connect.NewClient[intentsv1.ExplainIntentRequest, intentsv1.ExplainIntentResponse](httpClient, baseURL+ProcedureExplainIntent, opts...),
		getIntent:          connect.NewClient[intentsv1.GetIntentRequest, intentsv1.GetIntentResponse](httpClient, baseURL+ProcedureGetIntent, opts...),
		listIntentTimeline: connect.NewClient[intentsv1.ListIntentTimelineRequest, intentsv1.ListIntentTimelineResponse](httpClient, baseURL+ProcedureListIntentTimeline, opts...),
		listIntents:        connect.NewClient[intentsv1.ListIntentsRequest, intentsv1.ListIntentsResponse](httpClient, baseURL+ProcedureListIntents, opts...),
		simulateIntent:     connect.NewClient[intentsv1.SimulateIntentRequest, intentsv1.SimulateIntentResponse](httpClient, baseURL+ProcedureSimulateIntent, opts...),
		submitIntent:       connect.NewClient[intentsv1.SubmitIntentRequest, intentsv1.SubmitIntentResponse](httpClient, baseURL+ProcedureSubmitIntent, opts...),
		supersedeIntent:    connect.NewClient[intentsv1.SupersedeIntentRequest, intentsv1.SupersedeIntentResponse](httpClient, baseURL+ProcedureSupersedeIntent, opts...),
	}
}

// CancelIntent calls hcmnext.intents.v1.IntentService.CancelIntent over connect-go.
func (c *intentConnectClient) CancelIntent(ctx context.Context, req *intentsv1.CancelIntentRequest, opts ...CallOption) (*intentsv1.CancelIntentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.cancelIntent.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// CreateIntent calls hcmnext.intents.v1.IntentService.CreateIntent over connect-go.
func (c *intentConnectClient) CreateIntent(ctx context.Context, req *intentsv1.CreateIntentRequest, opts ...CallOption) (*intentsv1.CreateIntentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.createIntent.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ExecuteIntent calls hcmnext.intents.v1.IntentService.ExecuteIntent over connect-go.
func (c *intentConnectClient) ExecuteIntent(ctx context.Context, req *intentsv1.ExecuteIntentRequest, opts ...CallOption) (*intentsv1.ExecuteIntentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.executeIntent.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ExplainIntent calls hcmnext.intents.v1.IntentService.ExplainIntent over connect-go.
func (c *intentConnectClient) ExplainIntent(ctx context.Context, req *intentsv1.ExplainIntentRequest, opts ...CallOption) (*intentsv1.ExplainIntentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.explainIntent.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetIntent calls hcmnext.intents.v1.IntentService.GetIntent over connect-go.
func (c *intentConnectClient) GetIntent(ctx context.Context, req *intentsv1.GetIntentRequest, opts ...CallOption) (*intentsv1.GetIntentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getIntent.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListIntentTimeline calls hcmnext.intents.v1.IntentService.ListIntentTimeline over connect-go.
func (c *intentConnectClient) ListIntentTimeline(ctx context.Context, req *intentsv1.ListIntentTimelineRequest, opts ...CallOption) (*intentsv1.ListIntentTimelineResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listIntentTimeline.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListIntents calls hcmnext.intents.v1.IntentService.ListIntents over connect-go.
func (c *intentConnectClient) ListIntents(ctx context.Context, req *intentsv1.ListIntentsRequest, opts ...CallOption) (*intentsv1.ListIntentsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listIntents.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// SimulateIntent calls hcmnext.intents.v1.IntentService.SimulateIntent over connect-go.
func (c *intentConnectClient) SimulateIntent(ctx context.Context, req *intentsv1.SimulateIntentRequest, opts ...CallOption) (*intentsv1.SimulateIntentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.simulateIntent.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// SubmitIntent calls hcmnext.intents.v1.IntentService.SubmitIntent over connect-go.
func (c *intentConnectClient) SubmitIntent(ctx context.Context, req *intentsv1.SubmitIntentRequest, opts ...CallOption) (*intentsv1.SubmitIntentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.submitIntent.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// SupersedeIntent calls hcmnext.intents.v1.IntentService.SupersedeIntent over connect-go.
func (c *intentConnectClient) SupersedeIntent(ctx context.Context, req *intentsv1.SupersedeIntentRequest, opts ...CallOption) (*intentsv1.SupersedeIntentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.supersedeIntent.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}
