// Code generated by tools/gen/clients from definitions/api/endpoint-manifest.json. DO NOT EDIT.

package clients

// Procedures returns every procedure path every generated client publishes,
// across every service.
func Procedures() []string {
	var out []string
	out = append(out, ProceduresDataOpsService()...)
	out = append(out, ProceduresIntegrationService()...)
	out = append(out, ProceduresIntentService()...)
	out = append(out, ProceduresRegistryService()...)
	return out
}
