// Code generated by tools/gen/clients from definitions/api/endpoint-manifest.json. DO NOT EDIT.

package clients

import (
	"context"

	"connectrpc.com/connect"
	projectv1 "github.com/monstercameron/human-capital-management-suite/gen/go/hcmnext/project/v1"
	"google.golang.org/grpc"
)

// Procedure paths for hcmnext.project.v1.ProjectService, identical to the gRPC method's
// FullMethod and to connect.Spec.Procedure.
const (
	ProcedureAcceptProjectInvitation  = "/hcmnext.project.v1.ProjectService/AcceptProjectInvitation"
	ProcedureAddTaskComment           = "/hcmnext.project.v1.ProjectService/AddTaskComment"
	ProcedureAddTaskLink              = "/hcmnext.project.v1.ProjectService/AddTaskLink"
	ProcedureArchiveProject           = "/hcmnext.project.v1.ProjectService/ArchiveProject"
	ProcedureArchiveTask              = "/hcmnext.project.v1.ProjectService/ArchiveTask"
	ProcedureChangeProjectMemberRole  = "/hcmnext.project.v1.ProjectService/ChangeProjectMemberRole"
	ProcedureCreateProject            = "/hcmnext.project.v1.ProjectService/CreateProject"
	ProcedureCreateTask               = "/hcmnext.project.v1.ProjectService/CreateTask"
	ProcedureDeleteTaskComment        = "/hcmnext.project.v1.ProjectService/DeleteTaskComment"
	ProcedureEditTaskComment          = "/hcmnext.project.v1.ProjectService/EditTaskComment"
	ProcedureGetBoard                 = "/hcmnext.project.v1.ProjectService/GetBoard"
	ProcedureGetProject               = "/hcmnext.project.v1.ProjectService/GetProject"
	ProcedureGetProjectMembership     = "/hcmnext.project.v1.ProjectService/GetProjectMembership"
	ProcedureGetTask                  = "/hcmnext.project.v1.ProjectService/GetTask"
	ProcedureGetWorkflowConfiguration = "/hcmnext.project.v1.ProjectService/GetWorkflowConfiguration"
	ProcedureGetWorkflowDraft         = "/hcmnext.project.v1.ProjectService/GetWorkflowDraft"
	ProcedureInviteProjectMember      = "/hcmnext.project.v1.ProjectService/InviteProjectMember"
	ProcedureListBoardViews           = "/hcmnext.project.v1.ProjectService/ListBoardViews"
	ProcedureListProjectMembers       = "/hcmnext.project.v1.ProjectService/ListProjectMembers"
	ProcedureListProjects             = "/hcmnext.project.v1.ProjectService/ListProjects"
	ProcedureListTaskActivity         = "/hcmnext.project.v1.ProjectService/ListTaskActivity"
	ProcedureListTaskComments         = "/hcmnext.project.v1.ProjectService/ListTaskComments"
	ProcedureListTaskLinks            = "/hcmnext.project.v1.ProjectService/ListTaskLinks"
	ProcedureListTasks                = "/hcmnext.project.v1.ProjectService/ListTasks"
	ProcedureMoveTask                 = "/hcmnext.project.v1.ProjectService/MoveTask"
	ProcedurePatchTask                = "/hcmnext.project.v1.ProjectService/PatchTask"
	ProcedurePreviewWorkflowDraft     = "/hcmnext.project.v1.ProjectService/PreviewWorkflowDraft"
	ProcedurePublishWorkflowDraft     = "/hcmnext.project.v1.ProjectService/PublishWorkflowDraft"
	ProcedureRemoveTaskLink           = "/hcmnext.project.v1.ProjectService/RemoveTaskLink"
	ProcedureRestoreProject           = "/hcmnext.project.v1.ProjectService/RestoreProject"
	ProcedureRestoreTask              = "/hcmnext.project.v1.ProjectService/RestoreTask"
	ProcedureRevokeProjectMember      = "/hcmnext.project.v1.ProjectService/RevokeProjectMember"
	ProcedureSaveBoardView            = "/hcmnext.project.v1.ProjectService/SaveBoardView"
	ProcedureSaveWorkflowDraft        = "/hcmnext.project.v1.ProjectService/SaveWorkflowDraft"
	ProcedureSearchTasks              = "/hcmnext.project.v1.ProjectService/SearchTasks"
	ProcedureTransferProjectOwnership = "/hcmnext.project.v1.ProjectService/TransferProjectOwnership"
	ProcedureUpdateProjectSettings    = "/hcmnext.project.v1.ProjectService/UpdateProjectSettings"
)

// ProceduresProjectService returns every procedure path ProjectClient
// publishes, in manifest order.
func ProceduresProjectService() []string {
	return []string{
		ProcedureAcceptProjectInvitation,
		ProcedureAddTaskComment,
		ProcedureAddTaskLink,
		ProcedureArchiveProject,
		ProcedureArchiveTask,
		ProcedureChangeProjectMemberRole,
		ProcedureCreateProject,
		ProcedureCreateTask,
		ProcedureDeleteTaskComment,
		ProcedureEditTaskComment,
		ProcedureGetBoard,
		ProcedureGetProject,
		ProcedureGetProjectMembership,
		ProcedureGetTask,
		ProcedureGetWorkflowConfiguration,
		ProcedureGetWorkflowDraft,
		ProcedureInviteProjectMember,
		ProcedureListBoardViews,
		ProcedureListProjectMembers,
		ProcedureListProjects,
		ProcedureListTaskActivity,
		ProcedureListTaskComments,
		ProcedureListTaskLinks,
		ProcedureListTasks,
		ProcedureMoveTask,
		ProcedurePatchTask,
		ProcedurePreviewWorkflowDraft,
		ProcedurePublishWorkflowDraft,
		ProcedureRemoveTaskLink,
		ProcedureRestoreProject,
		ProcedureRestoreTask,
		ProcedureRevokeProjectMember,
		ProcedureSaveBoardView,
		ProcedureSaveWorkflowDraft,
		ProcedureSearchTasks,
		ProcedureTransferProjectOwnership,
		ProcedureUpdateProjectSettings,
	}
}

// ProjectClient is the transport-agnostic capability client for
// hcmnext.project.v1.ProjectService. Both [NewProjectClientGRPC] and [NewProjectClientConnect]
// decode a failure into the identical *envelope.Error (DecodeGRPCError,
// DecodeConnectError), so calling code does not depend on which backend it
// was built with.
type ProjectClient interface {
	// AcceptProjectInvitation calls hcmnext.project.v1.ProjectService.AcceptProjectInvitation.
	AcceptProjectInvitation(ctx context.Context, req *projectv1.AcceptProjectInvitationRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error)
	// AddTaskComment calls hcmnext.project.v1.ProjectService.AddTaskComment.
	AddTaskComment(ctx context.Context, req *projectv1.AddTaskCommentRequest, opts ...CallOption) (*projectv1.AddTaskCommentResponse, error)
	// AddTaskLink calls hcmnext.project.v1.ProjectService.AddTaskLink.
	AddTaskLink(ctx context.Context, req *projectv1.AddTaskLinkRequest, opts ...CallOption) (*projectv1.AddTaskLinkResponse, error)
	// ArchiveProject calls hcmnext.project.v1.ProjectService.ArchiveProject.
	ArchiveProject(ctx context.Context, req *projectv1.SetProjectLifecycleRequest, opts ...CallOption) (*projectv1.SetProjectLifecycleResponse, error)
	// ArchiveTask calls hcmnext.project.v1.ProjectService.ArchiveTask.
	ArchiveTask(ctx context.Context, req *projectv1.ArchiveTaskRequest, opts ...CallOption) (*projectv1.ArchiveTaskResponse, error)
	// ChangeProjectMemberRole calls hcmnext.project.v1.ProjectService.ChangeProjectMemberRole.
	ChangeProjectMemberRole(ctx context.Context, req *projectv1.ChangeProjectMemberRoleRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error)
	// CreateProject calls hcmnext.project.v1.ProjectService.CreateProject.
	CreateProject(ctx context.Context, req *projectv1.CreateProjectRequest, opts ...CallOption) (*projectv1.CreateProjectResponse, error)
	// CreateTask calls hcmnext.project.v1.ProjectService.CreateTask.
	CreateTask(ctx context.Context, req *projectv1.CreateTaskRequest, opts ...CallOption) (*projectv1.CreateTaskResponse, error)
	// DeleteTaskComment calls hcmnext.project.v1.ProjectService.DeleteTaskComment.
	DeleteTaskComment(ctx context.Context, req *projectv1.DeleteTaskCommentRequest, opts ...CallOption) (*projectv1.DeleteTaskCommentResponse, error)
	// EditTaskComment calls hcmnext.project.v1.ProjectService.EditTaskComment.
	EditTaskComment(ctx context.Context, req *projectv1.EditTaskCommentRequest, opts ...CallOption) (*projectv1.EditTaskCommentResponse, error)
	// GetBoard calls hcmnext.project.v1.ProjectService.GetBoard.
	GetBoard(ctx context.Context, req *projectv1.GetBoardRequest, opts ...CallOption) (*projectv1.GetBoardResponse, error)
	// GetProject calls hcmnext.project.v1.ProjectService.GetProject.
	GetProject(ctx context.Context, req *projectv1.GetProjectRequest, opts ...CallOption) (*projectv1.GetProjectResponse, error)
	// GetProjectMembership calls hcmnext.project.v1.ProjectService.GetProjectMembership.
	GetProjectMembership(ctx context.Context, req *projectv1.GetProjectMembershipRequest, opts ...CallOption) (*projectv1.GetProjectMembershipResponse, error)
	// GetTask calls hcmnext.project.v1.ProjectService.GetTask.
	GetTask(ctx context.Context, req *projectv1.GetTaskRequest, opts ...CallOption) (*projectv1.GetTaskResponse, error)
	// GetWorkflowConfiguration calls hcmnext.project.v1.ProjectService.GetWorkflowConfiguration.
	GetWorkflowConfiguration(ctx context.Context, req *projectv1.GetWorkflowConfigurationRequest, opts ...CallOption) (*projectv1.GetWorkflowConfigurationResponse, error)
	// GetWorkflowDraft calls hcmnext.project.v1.ProjectService.GetWorkflowDraft.
	GetWorkflowDraft(ctx context.Context, req *projectv1.GetWorkflowDraftRequest, opts ...CallOption) (*projectv1.GetWorkflowDraftResponse, error)
	// InviteProjectMember calls hcmnext.project.v1.ProjectService.InviteProjectMember.
	InviteProjectMember(ctx context.Context, req *projectv1.InviteProjectMemberRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error)
	// ListBoardViews calls hcmnext.project.v1.ProjectService.ListBoardViews.
	ListBoardViews(ctx context.Context, req *projectv1.ListBoardViewsRequest, opts ...CallOption) (*projectv1.ListBoardViewsResponse, error)
	// ListProjectMembers calls hcmnext.project.v1.ProjectService.ListProjectMembers.
	ListProjectMembers(ctx context.Context, req *projectv1.ListProjectMembersRequest, opts ...CallOption) (*projectv1.ListProjectMembersResponse, error)
	// ListProjects calls hcmnext.project.v1.ProjectService.ListProjects.
	ListProjects(ctx context.Context, req *projectv1.ListProjectsRequest, opts ...CallOption) (*projectv1.ListProjectsResponse, error)
	// ListTaskActivity calls hcmnext.project.v1.ProjectService.ListTaskActivity.
	ListTaskActivity(ctx context.Context, req *projectv1.ListTaskActivityRequest, opts ...CallOption) (*projectv1.ListTaskActivityResponse, error)
	// ListTaskComments calls hcmnext.project.v1.ProjectService.ListTaskComments.
	ListTaskComments(ctx context.Context, req *projectv1.ListTaskCommentsRequest, opts ...CallOption) (*projectv1.ListTaskCommentsResponse, error)
	// ListTaskLinks calls hcmnext.project.v1.ProjectService.ListTaskLinks.
	ListTaskLinks(ctx context.Context, req *projectv1.ListTaskLinksRequest, opts ...CallOption) (*projectv1.ListTaskLinksResponse, error)
	// ListTasks calls hcmnext.project.v1.ProjectService.ListTasks.
	ListTasks(ctx context.Context, req *projectv1.ListTasksRequest, opts ...CallOption) (*projectv1.ListTasksResponse, error)
	// MoveTask calls hcmnext.project.v1.ProjectService.MoveTask.
	MoveTask(ctx context.Context, req *projectv1.MoveTaskRequest, opts ...CallOption) (*projectv1.MoveTaskResponse, error)
	// PatchTask calls hcmnext.project.v1.ProjectService.PatchTask.
	PatchTask(ctx context.Context, req *projectv1.PatchTaskRequest, opts ...CallOption) (*projectv1.PatchTaskResponse, error)
	// PreviewWorkflowDraft calls hcmnext.project.v1.ProjectService.PreviewWorkflowDraft.
	PreviewWorkflowDraft(ctx context.Context, req *projectv1.PreviewWorkflowDraftRequest, opts ...CallOption) (*projectv1.PreviewWorkflowDraftResponse, error)
	// PublishWorkflowDraft calls hcmnext.project.v1.ProjectService.PublishWorkflowDraft.
	PublishWorkflowDraft(ctx context.Context, req *projectv1.PublishWorkflowDraftRequest, opts ...CallOption) (*projectv1.PublishWorkflowDraftResponse, error)
	// RemoveTaskLink calls hcmnext.project.v1.ProjectService.RemoveTaskLink.
	RemoveTaskLink(ctx context.Context, req *projectv1.RemoveTaskLinkRequest, opts ...CallOption) (*projectv1.RemoveTaskLinkResponse, error)
	// RestoreProject calls hcmnext.project.v1.ProjectService.RestoreProject.
	RestoreProject(ctx context.Context, req *projectv1.SetProjectLifecycleRequest, opts ...CallOption) (*projectv1.SetProjectLifecycleResponse, error)
	// RestoreTask calls hcmnext.project.v1.ProjectService.RestoreTask.
	RestoreTask(ctx context.Context, req *projectv1.RestoreTaskRequest, opts ...CallOption) (*projectv1.RestoreTaskResponse, error)
	// RevokeProjectMember calls hcmnext.project.v1.ProjectService.RevokeProjectMember.
	RevokeProjectMember(ctx context.Context, req *projectv1.RevokeProjectMemberRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error)
	// SaveBoardView calls hcmnext.project.v1.ProjectService.SaveBoardView.
	SaveBoardView(ctx context.Context, req *projectv1.SaveBoardViewRequest, opts ...CallOption) (*projectv1.SaveBoardViewResponse, error)
	// SaveWorkflowDraft calls hcmnext.project.v1.ProjectService.SaveWorkflowDraft.
	SaveWorkflowDraft(ctx context.Context, req *projectv1.SaveWorkflowDraftRequest, opts ...CallOption) (*projectv1.SaveWorkflowDraftResponse, error)
	// SearchTasks calls hcmnext.project.v1.ProjectService.SearchTasks.
	SearchTasks(ctx context.Context, req *projectv1.SearchTasksRequest, opts ...CallOption) (*projectv1.SearchTasksResponse, error)
	// TransferProjectOwnership calls hcmnext.project.v1.ProjectService.TransferProjectOwnership.
	TransferProjectOwnership(ctx context.Context, req *projectv1.TransferProjectOwnershipRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error)
	// UpdateProjectSettings calls hcmnext.project.v1.ProjectService.UpdateProjectSettings.
	UpdateProjectSettings(ctx context.Context, req *projectv1.UpdateProjectSettingsRequest, opts ...CallOption) (*projectv1.UpdateProjectSettingsResponse, error)
}

// projectGRPCClient is the native gRPC backend for ProjectClient.
type projectGRPCClient struct {
	client projectv1.ProjectServiceClient
}

// NewProjectClientGRPC builds a ProjectClient that calls hcmnext.project.v1.ProjectService
// over native gRPC on cc.
func NewProjectClientGRPC(cc grpc.ClientConnInterface) ProjectClient {
	return &projectGRPCClient{client: projectv1.NewProjectServiceClient(cc)}
}

// AcceptProjectInvitation calls hcmnext.project.v1.ProjectService.AcceptProjectInvitation over native gRPC.
func (c *projectGRPCClient) AcceptProjectInvitation(ctx context.Context, req *projectv1.AcceptProjectInvitationRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	res, err := c.client.AcceptProjectInvitation(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// AddTaskComment calls hcmnext.project.v1.ProjectService.AddTaskComment over native gRPC.
func (c *projectGRPCClient) AddTaskComment(ctx context.Context, req *projectv1.AddTaskCommentRequest, opts ...CallOption) (*projectv1.AddTaskCommentResponse, error) {
	res, err := c.client.AddTaskComment(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// AddTaskLink calls hcmnext.project.v1.ProjectService.AddTaskLink over native gRPC.
func (c *projectGRPCClient) AddTaskLink(ctx context.Context, req *projectv1.AddTaskLinkRequest, opts ...CallOption) (*projectv1.AddTaskLinkResponse, error) {
	res, err := c.client.AddTaskLink(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ArchiveProject calls hcmnext.project.v1.ProjectService.ArchiveProject over native gRPC.
func (c *projectGRPCClient) ArchiveProject(ctx context.Context, req *projectv1.SetProjectLifecycleRequest, opts ...CallOption) (*projectv1.SetProjectLifecycleResponse, error) {
	res, err := c.client.ArchiveProject(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ArchiveTask calls hcmnext.project.v1.ProjectService.ArchiveTask over native gRPC.
func (c *projectGRPCClient) ArchiveTask(ctx context.Context, req *projectv1.ArchiveTaskRequest, opts ...CallOption) (*projectv1.ArchiveTaskResponse, error) {
	res, err := c.client.ArchiveTask(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ChangeProjectMemberRole calls hcmnext.project.v1.ProjectService.ChangeProjectMemberRole over native gRPC.
func (c *projectGRPCClient) ChangeProjectMemberRole(ctx context.Context, req *projectv1.ChangeProjectMemberRoleRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	res, err := c.client.ChangeProjectMemberRole(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// CreateProject calls hcmnext.project.v1.ProjectService.CreateProject over native gRPC.
func (c *projectGRPCClient) CreateProject(ctx context.Context, req *projectv1.CreateProjectRequest, opts ...CallOption) (*projectv1.CreateProjectResponse, error) {
	res, err := c.client.CreateProject(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// CreateTask calls hcmnext.project.v1.ProjectService.CreateTask over native gRPC.
func (c *projectGRPCClient) CreateTask(ctx context.Context, req *projectv1.CreateTaskRequest, opts ...CallOption) (*projectv1.CreateTaskResponse, error) {
	res, err := c.client.CreateTask(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// DeleteTaskComment calls hcmnext.project.v1.ProjectService.DeleteTaskComment over native gRPC.
func (c *projectGRPCClient) DeleteTaskComment(ctx context.Context, req *projectv1.DeleteTaskCommentRequest, opts ...CallOption) (*projectv1.DeleteTaskCommentResponse, error) {
	res, err := c.client.DeleteTaskComment(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// EditTaskComment calls hcmnext.project.v1.ProjectService.EditTaskComment over native gRPC.
func (c *projectGRPCClient) EditTaskComment(ctx context.Context, req *projectv1.EditTaskCommentRequest, opts ...CallOption) (*projectv1.EditTaskCommentResponse, error) {
	res, err := c.client.EditTaskComment(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetBoard calls hcmnext.project.v1.ProjectService.GetBoard over native gRPC.
func (c *projectGRPCClient) GetBoard(ctx context.Context, req *projectv1.GetBoardRequest, opts ...CallOption) (*projectv1.GetBoardResponse, error) {
	res, err := c.client.GetBoard(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetProject calls hcmnext.project.v1.ProjectService.GetProject over native gRPC.
func (c *projectGRPCClient) GetProject(ctx context.Context, req *projectv1.GetProjectRequest, opts ...CallOption) (*projectv1.GetProjectResponse, error) {
	res, err := c.client.GetProject(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetProjectMembership calls hcmnext.project.v1.ProjectService.GetProjectMembership over native gRPC.
func (c *projectGRPCClient) GetProjectMembership(ctx context.Context, req *projectv1.GetProjectMembershipRequest, opts ...CallOption) (*projectv1.GetProjectMembershipResponse, error) {
	res, err := c.client.GetProjectMembership(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetTask calls hcmnext.project.v1.ProjectService.GetTask over native gRPC.
func (c *projectGRPCClient) GetTask(ctx context.Context, req *projectv1.GetTaskRequest, opts ...CallOption) (*projectv1.GetTaskResponse, error) {
	res, err := c.client.GetTask(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetWorkflowConfiguration calls hcmnext.project.v1.ProjectService.GetWorkflowConfiguration over native gRPC.
func (c *projectGRPCClient) GetWorkflowConfiguration(ctx context.Context, req *projectv1.GetWorkflowConfigurationRequest, opts ...CallOption) (*projectv1.GetWorkflowConfigurationResponse, error) {
	res, err := c.client.GetWorkflowConfiguration(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetWorkflowDraft calls hcmnext.project.v1.ProjectService.GetWorkflowDraft over native gRPC.
func (c *projectGRPCClient) GetWorkflowDraft(ctx context.Context, req *projectv1.GetWorkflowDraftRequest, opts ...CallOption) (*projectv1.GetWorkflowDraftResponse, error) {
	res, err := c.client.GetWorkflowDraft(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// InviteProjectMember calls hcmnext.project.v1.ProjectService.InviteProjectMember over native gRPC.
func (c *projectGRPCClient) InviteProjectMember(ctx context.Context, req *projectv1.InviteProjectMemberRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	res, err := c.client.InviteProjectMember(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListBoardViews calls hcmnext.project.v1.ProjectService.ListBoardViews over native gRPC.
func (c *projectGRPCClient) ListBoardViews(ctx context.Context, req *projectv1.ListBoardViewsRequest, opts ...CallOption) (*projectv1.ListBoardViewsResponse, error) {
	res, err := c.client.ListBoardViews(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListProjectMembers calls hcmnext.project.v1.ProjectService.ListProjectMembers over native gRPC.
func (c *projectGRPCClient) ListProjectMembers(ctx context.Context, req *projectv1.ListProjectMembersRequest, opts ...CallOption) (*projectv1.ListProjectMembersResponse, error) {
	res, err := c.client.ListProjectMembers(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListProjects calls hcmnext.project.v1.ProjectService.ListProjects over native gRPC.
func (c *projectGRPCClient) ListProjects(ctx context.Context, req *projectv1.ListProjectsRequest, opts ...CallOption) (*projectv1.ListProjectsResponse, error) {
	res, err := c.client.ListProjects(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListTaskActivity calls hcmnext.project.v1.ProjectService.ListTaskActivity over native gRPC.
func (c *projectGRPCClient) ListTaskActivity(ctx context.Context, req *projectv1.ListTaskActivityRequest, opts ...CallOption) (*projectv1.ListTaskActivityResponse, error) {
	res, err := c.client.ListTaskActivity(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListTaskComments calls hcmnext.project.v1.ProjectService.ListTaskComments over native gRPC.
func (c *projectGRPCClient) ListTaskComments(ctx context.Context, req *projectv1.ListTaskCommentsRequest, opts ...CallOption) (*projectv1.ListTaskCommentsResponse, error) {
	res, err := c.client.ListTaskComments(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListTaskLinks calls hcmnext.project.v1.ProjectService.ListTaskLinks over native gRPC.
func (c *projectGRPCClient) ListTaskLinks(ctx context.Context, req *projectv1.ListTaskLinksRequest, opts ...CallOption) (*projectv1.ListTaskLinksResponse, error) {
	res, err := c.client.ListTaskLinks(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListTasks calls hcmnext.project.v1.ProjectService.ListTasks over native gRPC.
func (c *projectGRPCClient) ListTasks(ctx context.Context, req *projectv1.ListTasksRequest, opts ...CallOption) (*projectv1.ListTasksResponse, error) {
	res, err := c.client.ListTasks(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// MoveTask calls hcmnext.project.v1.ProjectService.MoveTask over native gRPC.
func (c *projectGRPCClient) MoveTask(ctx context.Context, req *projectv1.MoveTaskRequest, opts ...CallOption) (*projectv1.MoveTaskResponse, error) {
	res, err := c.client.MoveTask(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// PatchTask calls hcmnext.project.v1.ProjectService.PatchTask over native gRPC.
func (c *projectGRPCClient) PatchTask(ctx context.Context, req *projectv1.PatchTaskRequest, opts ...CallOption) (*projectv1.PatchTaskResponse, error) {
	res, err := c.client.PatchTask(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// PreviewWorkflowDraft calls hcmnext.project.v1.ProjectService.PreviewWorkflowDraft over native gRPC.
func (c *projectGRPCClient) PreviewWorkflowDraft(ctx context.Context, req *projectv1.PreviewWorkflowDraftRequest, opts ...CallOption) (*projectv1.PreviewWorkflowDraftResponse, error) {
	res, err := c.client.PreviewWorkflowDraft(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// PublishWorkflowDraft calls hcmnext.project.v1.ProjectService.PublishWorkflowDraft over native gRPC.
func (c *projectGRPCClient) PublishWorkflowDraft(ctx context.Context, req *projectv1.PublishWorkflowDraftRequest, opts ...CallOption) (*projectv1.PublishWorkflowDraftResponse, error) {
	res, err := c.client.PublishWorkflowDraft(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// RemoveTaskLink calls hcmnext.project.v1.ProjectService.RemoveTaskLink over native gRPC.
func (c *projectGRPCClient) RemoveTaskLink(ctx context.Context, req *projectv1.RemoveTaskLinkRequest, opts ...CallOption) (*projectv1.RemoveTaskLinkResponse, error) {
	res, err := c.client.RemoveTaskLink(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// RestoreProject calls hcmnext.project.v1.ProjectService.RestoreProject over native gRPC.
func (c *projectGRPCClient) RestoreProject(ctx context.Context, req *projectv1.SetProjectLifecycleRequest, opts ...CallOption) (*projectv1.SetProjectLifecycleResponse, error) {
	res, err := c.client.RestoreProject(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// RestoreTask calls hcmnext.project.v1.ProjectService.RestoreTask over native gRPC.
func (c *projectGRPCClient) RestoreTask(ctx context.Context, req *projectv1.RestoreTaskRequest, opts ...CallOption) (*projectv1.RestoreTaskResponse, error) {
	res, err := c.client.RestoreTask(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// RevokeProjectMember calls hcmnext.project.v1.ProjectService.RevokeProjectMember over native gRPC.
func (c *projectGRPCClient) RevokeProjectMember(ctx context.Context, req *projectv1.RevokeProjectMemberRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	res, err := c.client.RevokeProjectMember(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// SaveBoardView calls hcmnext.project.v1.ProjectService.SaveBoardView over native gRPC.
func (c *projectGRPCClient) SaveBoardView(ctx context.Context, req *projectv1.SaveBoardViewRequest, opts ...CallOption) (*projectv1.SaveBoardViewResponse, error) {
	res, err := c.client.SaveBoardView(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// SaveWorkflowDraft calls hcmnext.project.v1.ProjectService.SaveWorkflowDraft over native gRPC.
func (c *projectGRPCClient) SaveWorkflowDraft(ctx context.Context, req *projectv1.SaveWorkflowDraftRequest, opts ...CallOption) (*projectv1.SaveWorkflowDraftResponse, error) {
	res, err := c.client.SaveWorkflowDraft(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// SearchTasks calls hcmnext.project.v1.ProjectService.SearchTasks over native gRPC.
func (c *projectGRPCClient) SearchTasks(ctx context.Context, req *projectv1.SearchTasksRequest, opts ...CallOption) (*projectv1.SearchTasksResponse, error) {
	res, err := c.client.SearchTasks(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// TransferProjectOwnership calls hcmnext.project.v1.ProjectService.TransferProjectOwnership over native gRPC.
func (c *projectGRPCClient) TransferProjectOwnership(ctx context.Context, req *projectv1.TransferProjectOwnershipRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	res, err := c.client.TransferProjectOwnership(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// UpdateProjectSettings calls hcmnext.project.v1.ProjectService.UpdateProjectSettings over native gRPC.
func (c *projectGRPCClient) UpdateProjectSettings(ctx context.Context, req *projectv1.UpdateProjectSettingsRequest, opts ...CallOption) (*projectv1.UpdateProjectSettingsResponse, error) {
	res, err := c.client.UpdateProjectSettings(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// projectConnectClient is the connect-go backend for ProjectClient.
type projectConnectClient struct {
	acceptProjectInvitation  *connect.Client[projectv1.AcceptProjectInvitationRequest, projectv1.MutateProjectMembershipResponse]
	addTaskComment           *connect.Client[projectv1.AddTaskCommentRequest, projectv1.AddTaskCommentResponse]
	addTaskLink              *connect.Client[projectv1.AddTaskLinkRequest, projectv1.AddTaskLinkResponse]
	archiveProject           *connect.Client[projectv1.SetProjectLifecycleRequest, projectv1.SetProjectLifecycleResponse]
	archiveTask              *connect.Client[projectv1.ArchiveTaskRequest, projectv1.ArchiveTaskResponse]
	changeProjectMemberRole  *connect.Client[projectv1.ChangeProjectMemberRoleRequest, projectv1.MutateProjectMembershipResponse]
	createProject            *connect.Client[projectv1.CreateProjectRequest, projectv1.CreateProjectResponse]
	createTask               *connect.Client[projectv1.CreateTaskRequest, projectv1.CreateTaskResponse]
	deleteTaskComment        *connect.Client[projectv1.DeleteTaskCommentRequest, projectv1.DeleteTaskCommentResponse]
	editTaskComment          *connect.Client[projectv1.EditTaskCommentRequest, projectv1.EditTaskCommentResponse]
	getBoard                 *connect.Client[projectv1.GetBoardRequest, projectv1.GetBoardResponse]
	getProject               *connect.Client[projectv1.GetProjectRequest, projectv1.GetProjectResponse]
	getProjectMembership     *connect.Client[projectv1.GetProjectMembershipRequest, projectv1.GetProjectMembershipResponse]
	getTask                  *connect.Client[projectv1.GetTaskRequest, projectv1.GetTaskResponse]
	getWorkflowConfiguration *connect.Client[projectv1.GetWorkflowConfigurationRequest, projectv1.GetWorkflowConfigurationResponse]
	getWorkflowDraft         *connect.Client[projectv1.GetWorkflowDraftRequest, projectv1.GetWorkflowDraftResponse]
	inviteProjectMember      *connect.Client[projectv1.InviteProjectMemberRequest, projectv1.MutateProjectMembershipResponse]
	listBoardViews           *connect.Client[projectv1.ListBoardViewsRequest, projectv1.ListBoardViewsResponse]
	listProjectMembers       *connect.Client[projectv1.ListProjectMembersRequest, projectv1.ListProjectMembersResponse]
	listProjects             *connect.Client[projectv1.ListProjectsRequest, projectv1.ListProjectsResponse]
	listTaskActivity         *connect.Client[projectv1.ListTaskActivityRequest, projectv1.ListTaskActivityResponse]
	listTaskComments         *connect.Client[projectv1.ListTaskCommentsRequest, projectv1.ListTaskCommentsResponse]
	listTaskLinks            *connect.Client[projectv1.ListTaskLinksRequest, projectv1.ListTaskLinksResponse]
	listTasks                *connect.Client[projectv1.ListTasksRequest, projectv1.ListTasksResponse]
	moveTask                 *connect.Client[projectv1.MoveTaskRequest, projectv1.MoveTaskResponse]
	patchTask                *connect.Client[projectv1.PatchTaskRequest, projectv1.PatchTaskResponse]
	previewWorkflowDraft     *connect.Client[projectv1.PreviewWorkflowDraftRequest, projectv1.PreviewWorkflowDraftResponse]
	publishWorkflowDraft     *connect.Client[projectv1.PublishWorkflowDraftRequest, projectv1.PublishWorkflowDraftResponse]
	removeTaskLink           *connect.Client[projectv1.RemoveTaskLinkRequest, projectv1.RemoveTaskLinkResponse]
	restoreProject           *connect.Client[projectv1.SetProjectLifecycleRequest, projectv1.SetProjectLifecycleResponse]
	restoreTask              *connect.Client[projectv1.RestoreTaskRequest, projectv1.RestoreTaskResponse]
	revokeProjectMember      *connect.Client[projectv1.RevokeProjectMemberRequest, projectv1.MutateProjectMembershipResponse]
	saveBoardView            *connect.Client[projectv1.SaveBoardViewRequest, projectv1.SaveBoardViewResponse]
	saveWorkflowDraft        *connect.Client[projectv1.SaveWorkflowDraftRequest, projectv1.SaveWorkflowDraftResponse]
	searchTasks              *connect.Client[projectv1.SearchTasksRequest, projectv1.SearchTasksResponse]
	transferProjectOwnership *connect.Client[projectv1.TransferProjectOwnershipRequest, projectv1.MutateProjectMembershipResponse]
	updateProjectSettings    *connect.Client[projectv1.UpdateProjectSettingsRequest, projectv1.UpdateProjectSettingsResponse]
}

// NewProjectClientConnect builds a ProjectClient that calls the
// hcmnext.project.v1.ProjectService procedures published at baseURL over connect-go.
func NewProjectClientConnect(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectClient {
	return &projectConnectClient{
		acceptProjectInvitation:  connect.NewClient[projectv1.AcceptProjectInvitationRequest, projectv1.MutateProjectMembershipResponse](httpClient, baseURL+ProcedureAcceptProjectInvitation, opts...),
		addTaskComment:           connect.NewClient[projectv1.AddTaskCommentRequest, projectv1.AddTaskCommentResponse](httpClient, baseURL+ProcedureAddTaskComment, opts...),
		addTaskLink:              connect.NewClient[projectv1.AddTaskLinkRequest, projectv1.AddTaskLinkResponse](httpClient, baseURL+ProcedureAddTaskLink, opts...),
		archiveProject:           connect.NewClient[projectv1.SetProjectLifecycleRequest, projectv1.SetProjectLifecycleResponse](httpClient, baseURL+ProcedureArchiveProject, opts...),
		archiveTask:              connect.NewClient[projectv1.ArchiveTaskRequest, projectv1.ArchiveTaskResponse](httpClient, baseURL+ProcedureArchiveTask, opts...),
		changeProjectMemberRole:  connect.NewClient[projectv1.ChangeProjectMemberRoleRequest, projectv1.MutateProjectMembershipResponse](httpClient, baseURL+ProcedureChangeProjectMemberRole, opts...),
		createProject:            connect.NewClient[projectv1.CreateProjectRequest, projectv1.CreateProjectResponse](httpClient, baseURL+ProcedureCreateProject, opts...),
		createTask:               connect.NewClient[projectv1.CreateTaskRequest, projectv1.CreateTaskResponse](httpClient, baseURL+ProcedureCreateTask, opts...),
		deleteTaskComment:        connect.NewClient[projectv1.DeleteTaskCommentRequest, projectv1.DeleteTaskCommentResponse](httpClient, baseURL+ProcedureDeleteTaskComment, opts...),
		editTaskComment:          connect.NewClient[projectv1.EditTaskCommentRequest, projectv1.EditTaskCommentResponse](httpClient, baseURL+ProcedureEditTaskComment, opts...),
		getBoard:                 connect.NewClient[projectv1.GetBoardRequest, projectv1.GetBoardResponse](httpClient, baseURL+ProcedureGetBoard, opts...),
		getProject:               connect.NewClient[projectv1.GetProjectRequest, projectv1.GetProjectResponse](httpClient, baseURL+ProcedureGetProject, opts...),
		getProjectMembership:     connect.NewClient[projectv1.GetProjectMembershipRequest, projectv1.GetProjectMembershipResponse](httpClient, baseURL+ProcedureGetProjectMembership, opts...),
		getTask:                  connect.NewClient[projectv1.GetTaskRequest, projectv1.GetTaskResponse](httpClient, baseURL+ProcedureGetTask, opts...),
		getWorkflowConfiguration: connect.NewClient[projectv1.GetWorkflowConfigurationRequest, projectv1.GetWorkflowConfigurationResponse](httpClient, baseURL+ProcedureGetWorkflowConfiguration, opts...),
		getWorkflowDraft:         connect.NewClient[projectv1.GetWorkflowDraftRequest, projectv1.GetWorkflowDraftResponse](httpClient, baseURL+ProcedureGetWorkflowDraft, opts...),
		inviteProjectMember:      connect.NewClient[projectv1.InviteProjectMemberRequest, projectv1.MutateProjectMembershipResponse](httpClient, baseURL+ProcedureInviteProjectMember, opts...),
		listBoardViews:           connect.NewClient[projectv1.ListBoardViewsRequest, projectv1.ListBoardViewsResponse](httpClient, baseURL+ProcedureListBoardViews, opts...),
		listProjectMembers:       connect.NewClient[projectv1.ListProjectMembersRequest, projectv1.ListProjectMembersResponse](httpClient, baseURL+ProcedureListProjectMembers, opts...),
		listProjects:             connect.NewClient[projectv1.ListProjectsRequest, projectv1.ListProjectsResponse](httpClient, baseURL+ProcedureListProjects, opts...),
		listTaskActivity:         connect.NewClient[projectv1.ListTaskActivityRequest, projectv1.ListTaskActivityResponse](httpClient, baseURL+ProcedureListTaskActivity, opts...),
		listTaskComments:         connect.NewClient[projectv1.ListTaskCommentsRequest, projectv1.ListTaskCommentsResponse](httpClient, baseURL+ProcedureListTaskComments, opts...),
		listTaskLinks:            connect.NewClient[projectv1.ListTaskLinksRequest, projectv1.ListTaskLinksResponse](httpClient, baseURL+ProcedureListTaskLinks, opts...),
		listTasks:                connect.NewClient[projectv1.ListTasksRequest, projectv1.ListTasksResponse](httpClient, baseURL+ProcedureListTasks, opts...),
		moveTask:                 connect.NewClient[projectv1.MoveTaskRequest, projectv1.MoveTaskResponse](httpClient, baseURL+ProcedureMoveTask, opts...),
		patchTask:                connect.NewClient[projectv1.PatchTaskRequest, projectv1.PatchTaskResponse](httpClient, baseURL+ProcedurePatchTask, opts...),
		previewWorkflowDraft:     connect.NewClient[projectv1.PreviewWorkflowDraftRequest, projectv1.PreviewWorkflowDraftResponse](httpClient, baseURL+ProcedurePreviewWorkflowDraft, opts...),
		publishWorkflowDraft:     connect.NewClient[projectv1.PublishWorkflowDraftRequest, projectv1.PublishWorkflowDraftResponse](httpClient, baseURL+ProcedurePublishWorkflowDraft, opts...),
		removeTaskLink:           connect.NewClient[projectv1.RemoveTaskLinkRequest, projectv1.RemoveTaskLinkResponse](httpClient, baseURL+ProcedureRemoveTaskLink, opts...),
		restoreProject:           connect.NewClient[projectv1.SetProjectLifecycleRequest, projectv1.SetProjectLifecycleResponse](httpClient, baseURL+ProcedureRestoreProject, opts...),
		restoreTask:              connect.NewClient[projectv1.RestoreTaskRequest, projectv1.RestoreTaskResponse](httpClient, baseURL+ProcedureRestoreTask, opts...),
		revokeProjectMember:      connect.NewClient[projectv1.RevokeProjectMemberRequest, projectv1.MutateProjectMembershipResponse](httpClient, baseURL+ProcedureRevokeProjectMember, opts...),
		saveBoardView:            connect.NewClient[projectv1.SaveBoardViewRequest, projectv1.SaveBoardViewResponse](httpClient, baseURL+ProcedureSaveBoardView, opts...),
		saveWorkflowDraft:        connect.NewClient[projectv1.SaveWorkflowDraftRequest, projectv1.SaveWorkflowDraftResponse](httpClient, baseURL+ProcedureSaveWorkflowDraft, opts...),
		searchTasks:              connect.NewClient[projectv1.SearchTasksRequest, projectv1.SearchTasksResponse](httpClient, baseURL+ProcedureSearchTasks, opts...),
		transferProjectOwnership: connect.NewClient[projectv1.TransferProjectOwnershipRequest, projectv1.MutateProjectMembershipResponse](httpClient, baseURL+ProcedureTransferProjectOwnership, opts...),
		updateProjectSettings:    connect.NewClient[projectv1.UpdateProjectSettingsRequest, projectv1.UpdateProjectSettingsResponse](httpClient, baseURL+ProcedureUpdateProjectSettings, opts...),
	}
}

// AcceptProjectInvitation calls hcmnext.project.v1.ProjectService.AcceptProjectInvitation over connect-go.
func (c *projectConnectClient) AcceptProjectInvitation(ctx context.Context, req *projectv1.AcceptProjectInvitationRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.acceptProjectInvitation.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// AddTaskComment calls hcmnext.project.v1.ProjectService.AddTaskComment over connect-go.
func (c *projectConnectClient) AddTaskComment(ctx context.Context, req *projectv1.AddTaskCommentRequest, opts ...CallOption) (*projectv1.AddTaskCommentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.addTaskComment.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// AddTaskLink calls hcmnext.project.v1.ProjectService.AddTaskLink over connect-go.
func (c *projectConnectClient) AddTaskLink(ctx context.Context, req *projectv1.AddTaskLinkRequest, opts ...CallOption) (*projectv1.AddTaskLinkResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.addTaskLink.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ArchiveProject calls hcmnext.project.v1.ProjectService.ArchiveProject over connect-go.
func (c *projectConnectClient) ArchiveProject(ctx context.Context, req *projectv1.SetProjectLifecycleRequest, opts ...CallOption) (*projectv1.SetProjectLifecycleResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.archiveProject.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ArchiveTask calls hcmnext.project.v1.ProjectService.ArchiveTask over connect-go.
func (c *projectConnectClient) ArchiveTask(ctx context.Context, req *projectv1.ArchiveTaskRequest, opts ...CallOption) (*projectv1.ArchiveTaskResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.archiveTask.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ChangeProjectMemberRole calls hcmnext.project.v1.ProjectService.ChangeProjectMemberRole over connect-go.
func (c *projectConnectClient) ChangeProjectMemberRole(ctx context.Context, req *projectv1.ChangeProjectMemberRoleRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.changeProjectMemberRole.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// CreateProject calls hcmnext.project.v1.ProjectService.CreateProject over connect-go.
func (c *projectConnectClient) CreateProject(ctx context.Context, req *projectv1.CreateProjectRequest, opts ...CallOption) (*projectv1.CreateProjectResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.createProject.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// CreateTask calls hcmnext.project.v1.ProjectService.CreateTask over connect-go.
func (c *projectConnectClient) CreateTask(ctx context.Context, req *projectv1.CreateTaskRequest, opts ...CallOption) (*projectv1.CreateTaskResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.createTask.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// DeleteTaskComment calls hcmnext.project.v1.ProjectService.DeleteTaskComment over connect-go.
func (c *projectConnectClient) DeleteTaskComment(ctx context.Context, req *projectv1.DeleteTaskCommentRequest, opts ...CallOption) (*projectv1.DeleteTaskCommentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.deleteTaskComment.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// EditTaskComment calls hcmnext.project.v1.ProjectService.EditTaskComment over connect-go.
func (c *projectConnectClient) EditTaskComment(ctx context.Context, req *projectv1.EditTaskCommentRequest, opts ...CallOption) (*projectv1.EditTaskCommentResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.editTaskComment.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetBoard calls hcmnext.project.v1.ProjectService.GetBoard over connect-go.
func (c *projectConnectClient) GetBoard(ctx context.Context, req *projectv1.GetBoardRequest, opts ...CallOption) (*projectv1.GetBoardResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getBoard.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetProject calls hcmnext.project.v1.ProjectService.GetProject over connect-go.
func (c *projectConnectClient) GetProject(ctx context.Context, req *projectv1.GetProjectRequest, opts ...CallOption) (*projectv1.GetProjectResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getProject.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetProjectMembership calls hcmnext.project.v1.ProjectService.GetProjectMembership over connect-go.
func (c *projectConnectClient) GetProjectMembership(ctx context.Context, req *projectv1.GetProjectMembershipRequest, opts ...CallOption) (*projectv1.GetProjectMembershipResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getProjectMembership.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetTask calls hcmnext.project.v1.ProjectService.GetTask over connect-go.
func (c *projectConnectClient) GetTask(ctx context.Context, req *projectv1.GetTaskRequest, opts ...CallOption) (*projectv1.GetTaskResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getTask.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetWorkflowConfiguration calls hcmnext.project.v1.ProjectService.GetWorkflowConfiguration over connect-go.
func (c *projectConnectClient) GetWorkflowConfiguration(ctx context.Context, req *projectv1.GetWorkflowConfigurationRequest, opts ...CallOption) (*projectv1.GetWorkflowConfigurationResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getWorkflowConfiguration.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetWorkflowDraft calls hcmnext.project.v1.ProjectService.GetWorkflowDraft over connect-go.
func (c *projectConnectClient) GetWorkflowDraft(ctx context.Context, req *projectv1.GetWorkflowDraftRequest, opts ...CallOption) (*projectv1.GetWorkflowDraftResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getWorkflowDraft.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// InviteProjectMember calls hcmnext.project.v1.ProjectService.InviteProjectMember over connect-go.
func (c *projectConnectClient) InviteProjectMember(ctx context.Context, req *projectv1.InviteProjectMemberRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.inviteProjectMember.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListBoardViews calls hcmnext.project.v1.ProjectService.ListBoardViews over connect-go.
func (c *projectConnectClient) ListBoardViews(ctx context.Context, req *projectv1.ListBoardViewsRequest, opts ...CallOption) (*projectv1.ListBoardViewsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listBoardViews.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListProjectMembers calls hcmnext.project.v1.ProjectService.ListProjectMembers over connect-go.
func (c *projectConnectClient) ListProjectMembers(ctx context.Context, req *projectv1.ListProjectMembersRequest, opts ...CallOption) (*projectv1.ListProjectMembersResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listProjectMembers.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListProjects calls hcmnext.project.v1.ProjectService.ListProjects over connect-go.
func (c *projectConnectClient) ListProjects(ctx context.Context, req *projectv1.ListProjectsRequest, opts ...CallOption) (*projectv1.ListProjectsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listProjects.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListTaskActivity calls hcmnext.project.v1.ProjectService.ListTaskActivity over connect-go.
func (c *projectConnectClient) ListTaskActivity(ctx context.Context, req *projectv1.ListTaskActivityRequest, opts ...CallOption) (*projectv1.ListTaskActivityResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listTaskActivity.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListTaskComments calls hcmnext.project.v1.ProjectService.ListTaskComments over connect-go.
func (c *projectConnectClient) ListTaskComments(ctx context.Context, req *projectv1.ListTaskCommentsRequest, opts ...CallOption) (*projectv1.ListTaskCommentsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listTaskComments.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListTaskLinks calls hcmnext.project.v1.ProjectService.ListTaskLinks over connect-go.
func (c *projectConnectClient) ListTaskLinks(ctx context.Context, req *projectv1.ListTaskLinksRequest, opts ...CallOption) (*projectv1.ListTaskLinksResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listTaskLinks.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListTasks calls hcmnext.project.v1.ProjectService.ListTasks over connect-go.
func (c *projectConnectClient) ListTasks(ctx context.Context, req *projectv1.ListTasksRequest, opts ...CallOption) (*projectv1.ListTasksResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listTasks.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// MoveTask calls hcmnext.project.v1.ProjectService.MoveTask over connect-go.
func (c *projectConnectClient) MoveTask(ctx context.Context, req *projectv1.MoveTaskRequest, opts ...CallOption) (*projectv1.MoveTaskResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.moveTask.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// PatchTask calls hcmnext.project.v1.ProjectService.PatchTask over connect-go.
func (c *projectConnectClient) PatchTask(ctx context.Context, req *projectv1.PatchTaskRequest, opts ...CallOption) (*projectv1.PatchTaskResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.patchTask.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// PreviewWorkflowDraft calls hcmnext.project.v1.ProjectService.PreviewWorkflowDraft over connect-go.
func (c *projectConnectClient) PreviewWorkflowDraft(ctx context.Context, req *projectv1.PreviewWorkflowDraftRequest, opts ...CallOption) (*projectv1.PreviewWorkflowDraftResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.previewWorkflowDraft.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// PublishWorkflowDraft calls hcmnext.project.v1.ProjectService.PublishWorkflowDraft over connect-go.
func (c *projectConnectClient) PublishWorkflowDraft(ctx context.Context, req *projectv1.PublishWorkflowDraftRequest, opts ...CallOption) (*projectv1.PublishWorkflowDraftResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.publishWorkflowDraft.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// RemoveTaskLink calls hcmnext.project.v1.ProjectService.RemoveTaskLink over connect-go.
func (c *projectConnectClient) RemoveTaskLink(ctx context.Context, req *projectv1.RemoveTaskLinkRequest, opts ...CallOption) (*projectv1.RemoveTaskLinkResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.removeTaskLink.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// RestoreProject calls hcmnext.project.v1.ProjectService.RestoreProject over connect-go.
func (c *projectConnectClient) RestoreProject(ctx context.Context, req *projectv1.SetProjectLifecycleRequest, opts ...CallOption) (*projectv1.SetProjectLifecycleResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.restoreProject.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// RestoreTask calls hcmnext.project.v1.ProjectService.RestoreTask over connect-go.
func (c *projectConnectClient) RestoreTask(ctx context.Context, req *projectv1.RestoreTaskRequest, opts ...CallOption) (*projectv1.RestoreTaskResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.restoreTask.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// RevokeProjectMember calls hcmnext.project.v1.ProjectService.RevokeProjectMember over connect-go.
func (c *projectConnectClient) RevokeProjectMember(ctx context.Context, req *projectv1.RevokeProjectMemberRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.revokeProjectMember.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// SaveBoardView calls hcmnext.project.v1.ProjectService.SaveBoardView over connect-go.
func (c *projectConnectClient) SaveBoardView(ctx context.Context, req *projectv1.SaveBoardViewRequest, opts ...CallOption) (*projectv1.SaveBoardViewResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.saveBoardView.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// SaveWorkflowDraft calls hcmnext.project.v1.ProjectService.SaveWorkflowDraft over connect-go.
func (c *projectConnectClient) SaveWorkflowDraft(ctx context.Context, req *projectv1.SaveWorkflowDraftRequest, opts ...CallOption) (*projectv1.SaveWorkflowDraftResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.saveWorkflowDraft.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// SearchTasks calls hcmnext.project.v1.ProjectService.SearchTasks over connect-go.
func (c *projectConnectClient) SearchTasks(ctx context.Context, req *projectv1.SearchTasksRequest, opts ...CallOption) (*projectv1.SearchTasksResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.searchTasks.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// TransferProjectOwnership calls hcmnext.project.v1.ProjectService.TransferProjectOwnership over connect-go.
func (c *projectConnectClient) TransferProjectOwnership(ctx context.Context, req *projectv1.TransferProjectOwnershipRequest, opts ...CallOption) (*projectv1.MutateProjectMembershipResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.transferProjectOwnership.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// UpdateProjectSettings calls hcmnext.project.v1.ProjectService.UpdateProjectSettings over connect-go.
func (c *projectConnectClient) UpdateProjectSettings(ctx context.Context, req *projectv1.UpdateProjectSettingsRequest, opts ...CallOption) (*projectv1.UpdateProjectSettingsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.updateProjectSettings.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}
