package clients_test

import (
	"context"
	"net"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/test/bufconn"
	"google.golang.org/protobuf/proto"

	intentsv1 "github.com/monstercameron/human-capital-management-suite/gen/go/hcmnext/intents/v1"
	"github.com/monstercameron/human-capital-management-suite/internal/transport/clients"
	"github.com/monstercameron/human-capital-management-suite/internal/transport/edge"
	"github.com/monstercameron/human-capital-management-suite/internal/transport/grpcserver"
	"github.com/monstercameron/human-capital-management-suite/internal/transport/transporttest"
)

func rev00301Root(t testing.TB) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	// this file is internal/transport/clients/rev00301_test.go
	return filepath.Join(filepath.Dir(file), "..", "..", "..")
}

// TestTodo_REV_003_01 is the REV-003-01 primary test.
//
// RED: the superseded hand-written edge client still exists alongside the
// generated capability clients.
// GREEN: exactly one IntentClient/RegistryClient implementation exists — the
// generated one — and the drift check covers it.
func TestTodo_REV_003_01(t *testing.T) {
	root := rev00301Root(t)

	// The superseded duplicate must be gone.
	if _, err := os.Stat(filepath.Join(root, "internal", "transport", "edge", "client.go")); !os.IsNotExist(err) {
		t.Fatalf("internal/transport/edge/client.go still exists: exactly one IntentClient/RegistryClient implementation must remain (the generated one)")
	}

	// The canonical generated clients must exist with the generated header.
	for _, name := range []string{"intent_client.go", "registry_client.go", "procedures.go", "support.go"} {
		path := filepath.Join(root, "internal", "transport", "clients", name)
		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		if !strings.Contains(string(body), "Code generated by tools/gen/clients") {
			t.Errorf("%s lacks the generated header: not the canonical generated implementation", name)
		}
	}

	// No other non-test, non-generated package may still define the duplicate
	// client types. The edge package keeps its server (handler/procedures);
	// it must not keep a client.
	edgeFiles, err := filepath.Glob(filepath.Join(root, "internal", "transport", "edge", "*.go"))
	if err != nil {
		t.Fatalf("glob edge package: %v", err)
	}
	for _, path := range edgeFiles {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		text := string(body)
		if strings.Contains(text, "type IntentClient") || strings.Contains(text, "type RegistryClient") ||
			strings.Contains(text, "func NewIntentClient(") || strings.Contains(text, "func NewRegistryClient(") {
			t.Errorf("%s still defines an IntentClient/RegistryClient implementation", filepath.Base(path))
		}
	}
}

// TestTodo_REV_003_01_Golden pins the canonical generated client surface so a
// regression that renames, drops or duplicates a procedure fails here.
func TestTodo_REV_003_01_Golden(t *testing.T) {
	got := clients.Procedures()
	want := []string{
		"/hcmnext.dataops.v1.DataOpsService/CreateRepairPlan",
		"/hcmnext.dataops.v1.DataOpsService/DiffRecord",
		"/hcmnext.dataops.v1.DataOpsService/ExplainFieldHistory",
		"/hcmnext.dataops.v1.DataOpsService/SimulateRepair",
		"/hcmnext.integration.v1.IntegrationService/GetConnectorConnection",
		"/hcmnext.integration.v1.IntegrationService/GetConnectorDefinition",
		"/hcmnext.integration.v1.IntegrationService/GetExternalObservation",
		"/hcmnext.integration.v1.IntegrationService/ListConnectorConnections",
		"/hcmnext.integration.v1.IntegrationService/ListConnectorDefinitions",
		"/hcmnext.integration.v1.IntegrationService/ListExternalObservations",
		"/hcmnext.integration.v1.IntegrationService/TestConnectorConnection",
		"/hcmnext.intents.v1.IntentService/CancelIntent",
		"/hcmnext.intents.v1.IntentService/CreateIntent",
		"/hcmnext.intents.v1.IntentService/ExecuteIntent",
		"/hcmnext.intents.v1.IntentService/ExplainIntent",
		"/hcmnext.intents.v1.IntentService/ExportIntentFields",
		"/hcmnext.intents.v1.IntentService/GetIntent",
		"/hcmnext.intents.v1.IntentService/GetIntentDeepLink",
		"/hcmnext.intents.v1.IntentService/InspectIntentFields",
		"/hcmnext.intents.v1.IntentService/ListIntentTimeline",
		"/hcmnext.intents.v1.IntentService/ListIntents",
		"/hcmnext.intents.v1.IntentService/RecommendIntentAction",
		"/hcmnext.intents.v1.IntentService/SimulateIntent",
		"/hcmnext.intents.v1.IntentService/SubmitIntent",
		"/hcmnext.intents.v1.IntentService/SupersedeIntent",
		"/hcmnext.registry.v1.RegistryService/GetCapability",
		"/hcmnext.registry.v1.RegistryService/GetIntentDefinition",
		"/hcmnext.registry.v1.RegistryService/ListCapabilities",
		"/hcmnext.registry.v1.RegistryService/ListIntentDefinitions",
	}
	sortedGot := append([]string(nil), got...)
	sortedWant := append([]string(nil), want...)
	sort.Strings(sortedGot)
	sort.Strings(sortedWant)
	if len(sortedGot) != len(sortedWant) {
		t.Fatalf("procedure count = %d, want %d (%v)", len(sortedGot), len(sortedWant), sortedGot)
	}
	for i := range sortedWant {
		if sortedGot[i] != sortedWant[i] {
			t.Fatalf("procedure %d = %q, want %q (full: %v)", i, sortedGot[i], sortedWant[i], sortedGot)
		}
	}
}

// TestTodo_REV_003_01_Integration proves the generated clients are the callers
// actually used: one vector through the generated connect backend agrees with
// the same vector through the generated gRPC backend against the real edge
// and gRPC servers.
func TestTodo_REV_003_01_Integration(t *testing.T) {
	now := time.Date(2026, 9, 3, 12, 0, 0, 0, time.UTC)
	clock := func() time.Time { return now }
	verifier, err := transporttest.NewVerifier(clock)
	if err != nil {
		t.Fatalf("NewVerifier: %v", err)
	}
	token, err := transporttest.BearerToken(verifier, transporttest.DefaultClaims(now))
	if err != nil {
		t.Fatalf("BearerToken: %v", err)
	}
	intent := &transporttest.IntentHandler{}
	registry := &transporttest.RegistryHandler{}
	cfg := transporttest.Config(verifier, clock, "req-rev00301-0001", nil)

	grpcServer, err := grpcserver.NewServer(grpcserver.Options{Config: cfg, Intent: intent, Registry: registry})
	if err != nil {
		t.Fatalf("grpcserver.NewServer: %v", err)
	}
	listener := bufconn.Listen(1 << 20)
	go func() { _ = grpcServer.Serve(listener) }()
	t.Cleanup(func() {
		grpcServer.Stop()
		_ = listener.Close()
	})
	conn, err := grpc.NewClient("passthrough:///rev00301",
		grpc.WithContextDialer(func(ctx context.Context, _ string) (net.Conn, error) {
			return listener.DialContext(ctx)
		}),
		grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatalf("grpc.NewClient: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close() })

	edgeHandler, err := edge.NewHandler(edge.Options{Config: cfg, Intent: intent, Registry: registry})
	if err != nil {
		t.Fatalf("edge.NewHandler: %v", err)
	}
	httpServer := httptest.NewServer(edgeHandler)
	t.Cleanup(httpServer.Close)

	grpcIntent := clients.NewIntentClientGRPC(conn)
	connectIntent := clients.NewIntentClientConnect(httpServer.Client(), httpServer.URL)

	ctx := context.Background()
	vector := transporttest.CanonicalCreateIntentRequest()
	opts := []clients.CallOption{
		clients.WithAuthorization(token),
		clients.WithRequestID("req-rev00301-0001"),
	}

	viaGRPC, err := grpcIntent.CreateIntent(ctx, proto.Clone(vector).(*intentsv1.CreateIntentRequest), opts...)
	if err != nil {
		t.Fatalf("gRPC CreateIntent: %v", err)
	}
	viaConnect, err := connectIntent.CreateIntent(ctx, proto.Clone(vector).(*intentsv1.CreateIntentRequest), opts...)
	if err != nil {
		t.Fatalf("connect CreateIntent: %v", err)
	}
	if !proto.Equal(viaGRPC, viaConnect) {
		t.Fatalf("generated backends disagree:\ngrpc: %v\nconnect: %v", viaGRPC, viaConnect)
	}
	if got := viaGRPC.GetIntent().GetIntentId(); got != transporttest.DeterministicIntentID(vector.GetIdempotencyKey()) {
		t.Errorf("intent id = %q, want the deterministic fixture id", got)
	}
}
