package clients_test

import (
	"context"
	"reflect"
	"strings"
	"testing"
	"time"

	"connectrpc.com/connect"
	"google.golang.org/protobuf/proto"

	intentsv1 "github.com/monstercameron/human-capital-management-suite/gen/go/hcmnext/intents/v1"
	"github.com/monstercameron/human-capital-management-suite/internal/transport"
	"github.com/monstercameron/human-capital-management-suite/internal/transport/clients"
	"github.com/monstercameron/human-capital-management-suite/internal/transport/envelope"
	"github.com/monstercameron/human-capital-management-suite/internal/transport/transporttest"
)

// TestGeneratedClientParity is the TOOL-007 primary test.
//
// RED: missing method metadata (a method the manifest names but the
// generated client does not expose or routes to the wrong procedure),
// broken presence semantics (an unset optional field arrives set, or vice
// versa), a typed error that decodes differently on the two backends, or a
// blocked call whose cancellation never reaches the server.
//
// GREEN: clients.NewIntentClientGRPC and clients.NewIntentClientConnect —
// both generated by tools/gen/clients from the same manifest row — agree on
// all of it, calling the same transporttest fake handlers.
func TestGeneratedClientParity(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()

	t.Run("identical domain result", func(t *testing.T) {
		vector := transporttest.CanonicalCreateIntentRequest()

		viaGRPC, err := h.grpcIntent.CreateIntent(ctx, clone(vector), h.authOpts()...)
		if err != nil {
			t.Fatalf("gRPC CreateIntent: %v", err)
		}
		viaConnect, err := h.connectIntent.CreateIntent(ctx, clone(vector), h.authOpts()...)
		if err != nil {
			t.Fatalf("connect CreateIntent: %v", err)
		}
		if !proto.Equal(viaGRPC, viaConnect) {
			t.Fatalf("domain result differs:\ngrpc: %v\nconnect: %v", viaGRPC, viaConnect)
		}
		if got := viaGRPC.GetIntent().GetIntentId(); got != transporttest.DeterministicIntentID(vector.GetIdempotencyKey()) {
			t.Errorf("intent id = %q, want the deterministic fixture id", got)
		}
	})

	t.Run("request presence is preserved on both paths", func(t *testing.T) {
		for _, tc := range []struct {
			name   string
			parent *string
		}{
			{"absent optional field", nil},
			{"present empty optional field", proto.String("")},
			{"present populated optional field", proto.String("intent-parent")},
		} {
			t.Run(tc.name, func(t *testing.T) {
				h.intent.Reset()
				vector := transporttest.CanonicalCreateIntentRequest()
				vector.ParentIntentId = tc.parent

				if _, err := h.grpcIntent.CreateIntent(ctx, clone(vector), h.authOpts()...); err != nil {
					t.Fatalf("gRPC CreateIntent: %v", err)
				}
				if _, err := h.connectIntent.CreateIntent(ctx, clone(vector), h.authOpts()...); err != nil {
					t.Fatalf("connect CreateIntent: %v", err)
				}

				calls := h.intent.Calls()
				if len(calls) != 2 {
					t.Fatalf("recorded %d calls, want 2", len(calls))
				}
				grpcSeen := calls[0].Request.(*intentsv1.CreateIntentRequest).ParentIntentId
				connectSeen := calls[1].Request.(*intentsv1.CreateIntentRequest).ParentIntentId
				if (grpcSeen == nil) != (tc.parent == nil) {
					t.Errorf("gRPC presence = %v, want present=%v", grpcSeen != nil, tc.parent != nil)
				}
				if (connectSeen == nil) != (tc.parent == nil) {
					t.Errorf("connect presence = %v, want present=%v", connectSeen != nil, tc.parent != nil)
				}
				if grpcSeen != nil && connectSeen != nil && *grpcSeen != *connectSeen {
					t.Errorf("value differs: grpc=%q connect=%q", *grpcSeen, *connectSeen)
				}
			})
		}
	})

	t.Run("typed error is identical", func(t *testing.T) {
		request := &intentsv1.GetIntentRequest{IntentId: transporttest.MissingIntentID}

		_, grpcErr := h.grpcIntent.GetIntent(ctx, clone(request), h.authOpts()...)
		if grpcErr == nil {
			t.Fatal("gRPC GetIntent(missing) succeeded, want NOT_FOUND")
		}
		_, connectErr := h.connectIntent.GetIntent(ctx, clone(request), h.authOpts()...)
		if connectErr == nil {
			t.Fatal("connect GetIntent(missing) succeeded, want NOT_FOUND")
		}

		viaGRPC := ownedError(t, grpcErr)
		viaConnect := ownedError(t, connectErr)
		if viaGRPC.Code() != envelope.CodeNotFound {
			t.Errorf("owned code = %v, want NOT_FOUND", viaGRPC.Code())
		}
		assertOwnedParity(t, "GetIntent(missing)", viaGRPC, viaConnect)
	})

	t.Run("cancellation propagates on both paths", func(t *testing.T) {
		request := &intentsv1.SimulateIntentRequest{IntentId: transporttest.BlockingIntentID}

		for _, tc := range []struct {
			name string
			call func(ctx context.Context) error
		}{
			{"grpc", func(ctx context.Context) error {
				_, err := h.grpcIntent.SimulateIntent(ctx, clone(request), h.authOpts()...)
				return err
			}},
			{"connect", func(ctx context.Context) error {
				_, err := h.connectIntent.SimulateIntent(ctx, clone(request), h.authOpts()...)
				return err
			}},
		} {
			t.Run(tc.name, func(t *testing.T) {
				h.resetRecords()
				callCtx, cancel := context.WithCancel(ctx)
				go func() {
					time.Sleep(75 * time.Millisecond)
					cancel()
				}()
				defer cancel()

				if err := tc.call(callCtx); err == nil {
					t.Fatal("a canceled call returned success")
				}
				record, ok := h.awaitRecord(func(r transport.LogRecord) bool {
					return strings.HasSuffix(r.Method, "SimulateIntent") && !r.Succeeded()
				})
				if !ok {
					t.Fatal("the server never recorded a failed SimulateIntent, so cancellation did not propagate")
				}
				if record.Succeeded() {
					t.Fatalf("server recorded a success for a canceled call")
				}
			})
		}
	})
}

// TestTodo_TOOL_007_Golden pins the fixture vector's result so that a change
// in either backend, or in the generator's output, has to be an intentional
// golden update rather than a quiet drift.
func TestTodo_TOOL_007_Golden(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	vector := transporttest.CanonicalCreateIntentRequest()

	viaGRPC, err := h.grpcIntent.CreateIntent(ctx, clone(vector), h.authOpts()...)
	if err != nil {
		t.Fatalf("gRPC CreateIntent: %v", err)
	}
	viaConnect, err := h.connectIntent.CreateIntent(ctx, clone(vector), h.authOpts()...)
	if err != nil {
		t.Fatalf("connect CreateIntent: %v", err)
	}

	intent := viaGRPC.GetIntent()
	golden := map[string]string{
		"intent_id":             transporttest.DeterministicIntentID(vector.GetIdempotencyKey()),
		"tenant_id":             transporttest.Tenant,
		"organization_scope_id": transporttest.OrganizationScopeID,
		"purpose":               transporttest.PurposeOperations,
		"initiator.principal":   transporttest.Subject,
		"definition":            transporttest.KnownDefinitionID,
	}
	got := map[string]string{
		"intent_id":             intent.GetIntentId(),
		"tenant_id":             intent.GetTenantId(),
		"organization_scope_id": intent.GetOrganizationScopeId(),
		"purpose":               intent.GetPurpose(),
		"initiator.principal":   intent.GetInitiator().GetPrincipalId(),
		"definition":            intent.GetDefinition().GetIntentTypeId(),
	}
	for key, want := range golden {
		if got[key] != want {
			t.Errorf("golden %s = %q, want %q", key, got[key], want)
		}
	}

	// Byte-level equality, not just proto.Equal: deterministic serialization
	// is the strongest available statement that the two backends produced
	// the same result.
	grpcBytes, err := proto.MarshalOptions{Deterministic: true}.Marshal(viaGRPC)
	if err != nil {
		t.Fatalf("marshal gRPC response: %v", err)
	}
	connectBytes, err := proto.MarshalOptions{Deterministic: true}.Marshal(viaConnect)
	if err != nil {
		t.Fatalf("marshal connect response: %v", err)
	}
	if string(grpcBytes) != string(connectBytes) {
		t.Errorf("serialized responses differ:\ngrpc: %x\nconnect: %x", grpcBytes, connectBytes)
	}

	if intent.GetCorrelationId() == "" || !strings.HasPrefix(intent.GetCorrelationId(), "ev:authn:") {
		t.Errorf("correlation id = %q, want the authentication evidence reference", intent.GetCorrelationId())
	}
}

// TestTodo_TOOL_007_Integration runs every Intent and Registry RPC through
// both generated backends. DataOps and Integration RPC parity is exercised by
// TestTodo_PROTO_006_DataOpsIntegration.
func TestTodo_TOOL_007_Integration(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	cases := h.methodCases(t)

	manifest := loadEndpointManifest(t)
	want := map[string]bool{}
	for _, endpoint := range manifest.Endpoints {
		if strings.HasPrefix(endpoint.GRPCProcedure, "/hcmnext.intents.v1.IntentService/") ||
			strings.HasPrefix(endpoint.GRPCProcedure, "/hcmnext.registry.v1.RegistryService/") {
			want[endpoint.MethodName] = false
		}
	}
	for _, tc := range cases {
		covered, ok := want[tc.Name]
		if !ok {
			t.Errorf("fixture includes ungoverned Intent or Registry method %q", tc.Name)
			continue
		}
		if covered {
			t.Errorf("fixture repeats method %q", tc.Name)
			continue
		}
		want[tc.Name] = true
	}
	for method, covered := range want {
		if !covered {
			t.Errorf("fixture omits manifest method %q", method)
		}
	}

	for _, tc := range cases {
		t.Run(tc.Name, func(t *testing.T) {
			viaGRPC, grpcErr := tc.GRPC(ctx, h.authOpts()...)
			viaConnect, connectErr := tc.Connect(ctx, h.authOpts()...)

			if (grpcErr == nil) != (connectErr == nil) {
				t.Fatalf("outcome differs: grpc err=%v connect err=%v", grpcErr, connectErr)
			}
			if grpcErr != nil {
				assertOwnedParity(t, tc.Name, ownedError(t, grpcErr), ownedError(t, connectErr))
				return
			}
			if !proto.Equal(viaGRPC, viaConnect) {
				t.Fatalf("result differs:\ngrpc: %v\nconnect: %v", viaGRPC, viaConnect)
			}
		})
	}
}

// TestTodo_TOOL_007_Conformance checks that the generated clients publish
// exactly the canonical 29-method surface under typed signatures — no
// untyped map payload anywhere in the interface.
func TestTodo_TOOL_007_Conformance(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()

	t.Run("published procedures match the manifest exactly", func(t *testing.T) {
		published := make(map[string]bool, len(clients.Procedures()))
		for _, p := range clients.Procedures() {
			published[p] = true
		}
		doc := loadEndpointManifest(t)
		if len(doc.Endpoints) != len(published) {
			t.Fatalf("manifest names %d endpoints, generated clients publish %d", len(doc.Endpoints), len(published))
		}
		for _, e := range doc.Endpoints {
			if !published[e.GRPCProcedure] {
				t.Errorf("the generated clients do not publish %s", e.GRPCProcedure)
			}
		}
	})

	t.Run("every client method takes and returns a concrete proto.Message, never an untyped payload", func(t *testing.T) {
		protoMessageType := reflect.TypeOf((*proto.Message)(nil)).Elem()
		for _, iface := range []reflect.Type{
			reflect.TypeOf((*clients.IntentClient)(nil)).Elem(),
			reflect.TypeOf((*clients.RegistryClient)(nil)).Elem(),
			reflect.TypeOf((*clients.DataOpsClient)(nil)).Elem(),
			reflect.TypeOf((*clients.IntegrationClient)(nil)).Elem(),
		} {
			for i := 0; i < iface.NumMethod(); i++ {
				m := iface.Method(i)
				sig := m.Type
				if sig.NumIn() < 2 {
					t.Fatalf("%s.%s takes %d arguments, want at least (ctx, req)", iface, m.Name, sig.NumIn())
				}
				if got := sig.In(0).String(); got != "context.Context" {
					t.Errorf("%s.%s first argument is %s, want context.Context", iface, m.Name, got)
				}
				reqType := sig.In(1)
				if reqType.Kind() != reflect.Pointer || !reqType.Implements(protoMessageType) {
					t.Errorf("%s.%s request type %s is not a concrete *proto.Message", iface, m.Name, reqType)
				}
				if sig.NumOut() != 2 {
					t.Fatalf("%s.%s returns %d values, want (response, error)", iface, m.Name, sig.NumOut())
				}
				respType := sig.Out(0)
				if respType.Kind() != reflect.Pointer || !respType.Implements(protoMessageType) {
					t.Errorf("%s.%s response type %s is not a concrete *proto.Message", iface, m.Name, respType)
				}
			}
		}
	})

	t.Run("JSON and binary connect encodings agree", func(t *testing.T) {
		vector := transporttest.CanonicalCreateIntentRequest()

		binary, err := h.connectIntent.CreateIntent(ctx, clone(vector), h.authOpts()...)
		if err != nil {
			t.Fatalf("connect CreateIntent (binary): %v", err)
		}
		jsonClient := clients.NewIntentClientConnect(h.httpClient, h.edgeURL, connect.WithProtoJSON())
		asJSON, err := jsonClient.CreateIntent(ctx, clone(vector), h.authOpts()...)
		if err != nil {
			t.Fatalf("connect CreateIntent (json): %v", err)
		}
		if !proto.Equal(binary, asJSON) {
			t.Errorf("binary and JSON results differ:\nbinary: %v\njson:   %v", binary, asJSON)
		}
	})

	t.Run("an unauthenticated call is refused, not silently served", func(t *testing.T) {
		request := &intentsv1.GetIntentRequest{IntentId: transporttest.KnownIntentID}
		_, grpcErr := h.grpcIntent.GetIntent(ctx, clone(request), h.noCredentialOpts()...)
		_, connectErr := h.connectIntent.GetIntent(ctx, clone(request), h.noCredentialOpts()...)
		if grpcErr == nil || connectErr == nil {
			t.Fatalf("an unauthenticated call succeeded: grpc=%v connect=%v", grpcErr, connectErr)
		}
		viaGRPC, viaConnect := ownedError(t, grpcErr), ownedError(t, connectErr)
		if viaGRPC.Code() != envelope.CodeUnauthenticated {
			t.Errorf("owned code = %v, want UNAUTHENTICATED", viaGRPC.Code())
		}
		assertOwnedParity(t, "no credential", viaGRPC, viaConnect)
	})
}
