package timeclockapp

// catalog is the kiosk's complete string table. Every locale carries every
// key (TestTodo_TCLOCK_016_I18n). Weekday and month names live here too so
// the date line never depends on the browser's Intl data.
var catalog = map[Locale]map[string]string{
	LocaleEnUS: {
		"app.title":                  "Time clock",
		"enroll.heading":             "Set up this time clock",
		"enroll.help":                "Enter or scan the enrollment code from your administrator. You only do this once for this device.",
		"enroll.code_label":          "Enrollment code",
		"enroll.submit":              "Enroll device",
		"enroll.busy":                "Enrolling…",
		"enroll.error.empty":         "Enter the enrollment code.",
		"enroll.error.rejected":      "That code was not accepted. It may already be used or expired. Ask for a new one.",
		"enroll.error.offline":       "Can't reach the server. Check the network and try again.",
		"bar.site":                   "Site {site}",
		"bar.online":                 "Online",
		"bar.offline":                "Offline",
		"bar.queue_none":             "All punches sent",
		"bar.queue":                  "{n} waiting to send",
		"idle.start":                 "Clock in or out",
		"idle.hint":                  "Tap to enter your PIN, or scan your badge.",
		"badge.label":                "Badge or QR code",
		"badge.submit":               "Use badge",
		"identify.heading":           "Enter your PIN",
		"identify.pin_label":         "PIN, {n} digits entered",
		"identify.keypad":            "PIN keypad",
		"identify.backspace":         "Delete last digit",
		"identify.clear":             "Clear",
		"identify.submit":            "Continue",
		"identify.busy":              "Checking…",
		"identify.error.short":       "Enter at least 4 digits.",
		"identify.error.unknown":     "That PIN or badge wasn't recognized. Try again or ask your manager.",
		"identify.error.offline_pin": "PINs can't be checked while the clock is offline. Scan your badge instead, or try again shortly.",
		"identify.error.no_action":   "Clocking in or out isn't available for you right now. Ask your manager.",
		"common.cancel":              "Cancel",
		"confirm.greeting":           "Hello, {name}",
		"confirm.offline_name":       "Badge scanned",
		"confirm.status_in":          "You are clocked in",
		"confirm.status_out":         "You are clocked out",
		"confirm.status_unknown":     "The clock is offline, so your status can't be checked. Choose what you are doing.",
		"confirm.now":                "Punch time {time}",
		"action.in":                  "Clock in",
		"action.out":                 "Clock out",
		"countdown":                  "Back to the start screen in {s} s",
		"receipt.accepted_in":        "Clocked in",
		"receipt.accepted_out":       "Clocked out",
		"receipt.accepted_detail":    "Your punch was recorded.",
		"receipt.duplicate":          "Already recorded",
		"receipt.duplicate_detail":   "This punch was received earlier. There is nothing else to do.",
		"receipt.held":               "Recorded for review",
		"receipt.held_detail":        "Your punch was saved and a manager will review it.",
		"receipt.rejected":           "Not recorded",
		"receipt.rejected_detail":    "Tell your manager: {reason}",
		"receipt.queued":             "Saved on this clock",
		"receipt.queued_detail":      "The clock is offline. Your punch will be sent when the connection returns.",
		"receipt.time":               "Punch time",
		"receipt.sequence":           "Punch {n} on this clock",
		"receipt.done":               "Done",
		"reason.unspecified":         "the server did not give a reason.",
		"reason.unknown_worker":      "the worker could not be identified.",
		"reason.not_on_roster":       "you are not on this site's roster.",
		"reason.device_not_eligible": "this clock is not allowed to record punches.",
		"reason.policy_violation":    "the punch breaks a time-keeping rule.",
		"reason.sequence_gap":        "an earlier punch from this clock is missing.",
		"reason.malformed":           "the punch was incomplete.",
		"reason.stale_roster":        "this clock's worker list is out of date.",
		"reason.duplicate_rejected":  "the same punch was rejected before.",
		"revoked.heading":            "This time clock is no longer active",
		"revoked.help":               "Ask your administrator to enroll it again. Punches waiting on this clock stay saved.",
		"locale.label":               "Language",
		"meridiem.am":                "AM",
		"meridiem.pm":                "PM",
		"date.format":                "{weekday}, {month} {day}",
		"day.0":                      "Sunday",
		"day.1":                      "Monday",
		"day.2":                      "Tuesday",
		"day.3":                      "Wednesday",
		"day.4":                      "Thursday",
		"day.5":                      "Friday",
		"day.6":                      "Saturday",
		"month.1":                    "January",
		"month.2":                    "February",
		"month.3":                    "March",
		"month.4":                    "April",
		"month.5":                    "May",
		"month.6":                    "June",
		"month.7":                    "July",
		"month.8":                    "August",
		"month.9":                    "September",
		"month.10":                   "October",
		"month.11":                   "November",
		"month.12":                   "December",
	},
	LocaleDeDE: {
		"app.title":                  "Stempeluhr",
		"enroll.heading":             "Diese Stempeluhr einrichten",
		"enroll.help":                "Geben Sie den Registrierungscode Ihrer Verwaltung ein oder scannen Sie ihn. Das ist nur einmal pro Gerät nötig.",
		"enroll.code_label":          "Registrierungscode",
		"enroll.submit":              "Gerät registrieren",
		"enroll.busy":                "Wird registriert…",
		"enroll.error.empty":         "Geben Sie den Registrierungscode ein.",
		"enroll.error.rejected":      "Dieser Code wurde nicht akzeptiert. Er ist vielleicht schon verwendet oder abgelaufen. Fordern Sie einen neuen an.",
		"enroll.error.offline":       "Der Server ist nicht erreichbar. Prüfen Sie das Netzwerk und versuchen Sie es erneut.",
		"bar.site":                   "Standort {site}",
		"bar.online":                 "Online",
		"bar.offline":                "Offline",
		"bar.queue_none":             "Alle Buchungen gesendet",
		"bar.queue":                  "{n} warten auf Versand",
		"idle.start":                 "Ein- oder ausstempeln",
		"idle.hint":                  "Tippen Sie, um Ihre PIN einzugeben, oder scannen Sie Ihren Ausweis.",
		"badge.label":                "Ausweis oder QR-Code",
		"badge.submit":               "Ausweis verwenden",
		"identify.heading":           "PIN eingeben",
		"identify.pin_label":         "PIN, {n} Ziffern eingegeben",
		"identify.keypad":            "PIN-Tastenfeld",
		"identify.backspace":         "Letzte Ziffer löschen",
		"identify.clear":             "Leeren",
		"identify.submit":            "Weiter",
		"identify.busy":              "Wird geprüft…",
		"identify.error.short":       "Geben Sie mindestens 4 Ziffern ein.",
		"identify.error.unknown":     "PIN oder Ausweis wurde nicht erkannt. Versuchen Sie es erneut oder fragen Sie Ihre Führungskraft.",
		"identify.error.offline_pin": "Solange die Uhr offline ist, können PINs nicht geprüft werden. Scannen Sie stattdessen Ihren Ausweis oder versuchen Sie es gleich noch einmal.",
		"identify.error.no_action":   "Ein- oder Ausstempeln ist für Sie gerade nicht möglich. Fragen Sie Ihre Führungskraft.",
		"common.cancel":              "Abbrechen",
		"confirm.greeting":           "Hallo, {name}",
		"confirm.offline_name":       "Ausweis gescannt",
		"confirm.status_in":          "Sie sind eingestempelt",
		"confirm.status_out":         "Sie sind ausgestempelt",
		"confirm.status_unknown":     "Die Uhr ist offline, Ihr Status kann nicht geprüft werden. Wählen Sie, was Sie tun.",
		"confirm.now":                "Buchungszeit {time}",
		"action.in":                  "Einstempeln",
		"action.out":                 "Ausstempeln",
		"countdown":                  "Zurück zum Startbildschirm in {s} s",
		"receipt.accepted_in":        "Eingestempelt",
		"receipt.accepted_out":       "Ausgestempelt",
		"receipt.accepted_detail":    "Ihre Buchung wurde erfasst.",
		"receipt.duplicate":          "Bereits erfasst",
		"receipt.duplicate_detail":   "Diese Buchung ist schon eingegangen. Sie müssen nichts weiter tun.",
		"receipt.held":               "Zur Prüfung erfasst",
		"receipt.held_detail":        "Ihre Buchung wurde gespeichert und wird von einer Führungskraft geprüft.",
		"receipt.rejected":           "Nicht erfasst",
		"receipt.rejected_detail":    "Bitte informieren Sie Ihre Führungskraft: {reason}",
		"receipt.queued":             "Auf dieser Uhr gespeichert",
		"receipt.queued_detail":      "Die Uhr ist offline. Ihre Buchung wird gesendet, sobald die Verbindung zurück ist.",
		"receipt.time":               "Buchungszeit",
		"receipt.sequence":           "Buchung {n} auf dieser Uhr",
		"receipt.done":               "Fertig",
		"reason.unspecified":         "Der Server hat keinen Grund genannt.",
		"reason.unknown_worker":      "Die Person konnte nicht erkannt werden.",
		"reason.not_on_roster":       "Sie stehen nicht auf der Liste dieses Standorts.",
		"reason.device_not_eligible": "Diese Uhr darf keine Buchungen erfassen.",
		"reason.policy_violation":    "Die Buchung verstößt gegen eine Zeiterfassungsregel.",
		"reason.sequence_gap":        "Eine frühere Buchung dieser Uhr fehlt.",
		"reason.malformed":           "Die Buchung war unvollständig.",
		"reason.stale_roster":        "Die Personenliste dieser Uhr ist veraltet.",
		"reason.duplicate_rejected":  "Dieselbe Buchung wurde bereits abgelehnt.",
		"revoked.heading":            "Diese Stempeluhr ist nicht mehr aktiv",
		"revoked.help":               "Bitten Sie Ihre Verwaltung, sie neu zu registrieren. Wartende Buchungen bleiben auf der Uhr gespeichert.",
		"locale.label":               "Sprache",
		"meridiem.am":                "",
		"meridiem.pm":                "",
		"date.format":                "{weekday}, {day}. {month}",
		"day.0":                      "Sonntag",
		"day.1":                      "Montag",
		"day.2":                      "Dienstag",
		"day.3":                      "Mittwoch",
		"day.4":                      "Donnerstag",
		"day.5":                      "Freitag",
		"day.6":                      "Samstag",
		"month.1":                    "Januar",
		"month.2":                    "Februar",
		"month.3":                    "März",
		"month.4":                    "April",
		"month.5":                    "Mai",
		"month.6":                    "Juni",
		"month.7":                    "Juli",
		"month.8":                    "August",
		"month.9":                    "September",
		"month.10":                   "Oktober",
		"month.11":                   "November",
		"month.12":                   "Dezember",
	},
	LocaleAr: {
		"app.title":                  "ساعة الدوام",
		"enroll.heading":             "إعداد ساعة الدوام هذه",
		"enroll.help":                "أدخل رمز التسجيل الذي أرسله المسؤول أو امسحه ضوئيًا. يتم ذلك مرة واحدة فقط لهذا الجهاز.",
		"enroll.code_label":          "رمز التسجيل",
		"enroll.submit":              "تسجيل الجهاز",
		"enroll.busy":                "جارٍ التسجيل…",
		"enroll.error.empty":         "أدخل رمز التسجيل.",
		"enroll.error.rejected":      "لم يُقبل هذا الرمز. ربما استُخدم من قبل أو انتهت صلاحيته. اطلب رمزًا جديدًا.",
		"enroll.error.offline":       "تعذّر الوصول إلى الخادم. تحقّق من الشبكة وحاول مرة أخرى.",
		"bar.site":                   "الموقع {site}",
		"bar.online":                 "متصل",
		"bar.offline":                "غير متصل",
		"bar.queue_none":             "أُرسلت جميع التسجيلات",
		"bar.queue":                  "{n} بانتظار الإرسال",
		"idle.start":                 "تسجيل الحضور أو الانصراف",
		"idle.hint":                  "انقر لإدخال رقمك السري، أو امسح شارتك.",
		"badge.label":                "الشارة أو رمز QR",
		"badge.submit":               "استخدام الشارة",
		"identify.heading":           "أدخل رقمك السري",
		"identify.pin_label":         "الرقم السري، عدد الأرقام المُدخلة {n}",
		"identify.keypad":            "لوحة أرقام الرقم السري",
		"identify.backspace":         "حذف آخر رقم",
		"identify.clear":             "مسح",
		"identify.submit":            "متابعة",
		"identify.busy":              "جارٍ التحقق…",
		"identify.error.short":       "أدخل 4 أرقام على الأقل.",
		"identify.error.unknown":     "لم يتم التعرّف على الرقم السري أو الشارة. حاول مرة أخرى أو اسأل مديرك.",
		"identify.error.offline_pin": "لا يمكن التحقق من الرقم السري والساعة غير متصلة. امسح شارتك بدلًا من ذلك، أو حاول بعد قليل.",
		"identify.error.no_action":   "تسجيل الحضور أو الانصراف غير متاح لك الآن. اسأل مديرك.",
		"common.cancel":              "إلغاء",
		"confirm.greeting":           "مرحبًا، {name}",
		"confirm.offline_name":       "تم مسح الشارة",
		"confirm.status_in":          "أنت في الدوام الآن",
		"confirm.status_out":         "أنت خارج الدوام",
		"confirm.status_unknown":     "الساعة غير متصلة، لذا لا يمكن التحقق من حالتك. اختر ما تريد فعله.",
		"confirm.now":                "وقت التسجيل {time}",
		"action.in":                  "تسجيل الحضور",
		"action.out":                 "تسجيل الانصراف",
		"countdown":                  "العودة إلى شاشة البدء خلال {s} ث",
		"receipt.accepted_in":        "تم تسجيل الحضور",
		"receipt.accepted_out":       "تم تسجيل الانصراف",
		"receipt.accepted_detail":    "تم تسجيل وقتك.",
		"receipt.duplicate":          "مسجَّل من قبل",
		"receipt.duplicate_detail":   "وصل هذا التسجيل من قبل. لا حاجة لفعل أي شيء آخر.",
		"receipt.held":               "سُجِّل بانتظار المراجعة",
		"receipt.held_detail":        "حُفظ تسجيلك وسيراجعه أحد المديرين.",
		"receipt.rejected":           "لم يُسجَّل",
		"receipt.rejected_detail":    "أبلغ مديرك: {reason}",
		"receipt.queued":             "حُفظ على هذه الساعة",
		"receipt.queued_detail":      "الساعة غير متصلة. سيُرسل تسجيلك عند عودة الاتصال.",
		"receipt.time":               "وقت التسجيل",
		"receipt.sequence":           "التسجيل رقم {n} على هذه الساعة",
		"receipt.done":               "تم",
		"reason.unspecified":         "لم يذكر الخادم سببًا.",
		"reason.unknown_worker":      "تعذّر التعرّف على الموظف.",
		"reason.not_on_roster":       "أنت غير مدرج في قائمة هذا الموقع.",
		"reason.device_not_eligible": "هذه الساعة غير مسموح لها بتسجيل الأوقات.",
		"reason.policy_violation":    "التسجيل يخالف إحدى قواعد احتساب الوقت.",
		"reason.sequence_gap":        "تسجيل سابق من هذه الساعة مفقود.",
		"reason.malformed":           "التسجيل غير مكتمل.",
		"reason.stale_roster":        "قائمة الموظفين على هذه الساعة قديمة.",
		"reason.duplicate_rejected":  "رُفض التسجيل نفسه من قبل.",
		"revoked.heading":            "ساعة الدوام هذه لم تعد مفعّلة",
		"revoked.help":               "اطلب من المسؤول تسجيلها من جديد. التسجيلات المنتظرة على هذه الساعة تبقى محفوظة.",
		"locale.label":               "اللغة",
		"meridiem.am":                "ص",
		"meridiem.pm":                "م",
		"date.format":                "{weekday}، {day} {month}",
		"day.0":                      "الأحد",
		"day.1":                      "الاثنين",
		"day.2":                      "الثلاثاء",
		"day.3":                      "الأربعاء",
		"day.4":                      "الخميس",
		"day.5":                      "الجمعة",
		"day.6":                      "السبت",
		"month.1":                    "يناير",
		"month.2":                    "فبراير",
		"month.3":                    "مارس",
		"month.4":                    "أبريل",
		"month.5":                    "مايو",
		"month.6":                    "يونيو",
		"month.7":                    "يوليو",
		"month.8":                    "أغسطس",
		"month.9":                    "سبتمبر",
		"month.10":                   "أكتوبر",
		"month.11":                   "نوفمبر",
		"month.12":                   "ديسمبر",
	},
}
