package chatui

const AgentUXChat2Styles = `.conversation-heading{min-width:0}.conversation-heading h1{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}` +
	`.mention-chip-details{display:inline;position:relative}.mention-chip{display:inline;padding:2px 4px;border:0;border-radius:4px;background:color-mix(in srgb,var(--accent) 12%,var(--surface));color:var(--ink);font:inherit;font-size:inherit;font-weight:650;line-height:inherit;vertical-align:baseline;cursor:pointer;width:auto;height:auto;text-decoration:none}.mention-chip:hover,.mention-chip:focus-visible{background:color-mix(in srgb,var(--accent) 20%,var(--surface));text-decoration:none}.mention-chip-details>summary{list-style:none}.mention-chip-details>summary::-webkit-details-marker{display:none}.mention-chip-details>.mention-profile-card{position:absolute;z-index:40;inset-block-start:calc(100% + 4px);inset-inline-start:0;width:min(320px,calc(100vw - 24px));background:var(--surface);border:1px solid var(--line);border-radius:var(--hcm-radius-surface);box-shadow:var(--hcm-shadow-raised)}` +
	`.agent-feedback{display:flex;flex-wrap:wrap;gap:6px;margin-block-start:8px}.agent-feedback-button{min-height:32px;padding-inline:10px;border:1px solid var(--line);border-radius:999px;background:var(--surface);color:var(--ink);font:inherit;font-size:.8125rem;cursor:pointer}.agent-feedback-button:hover,.agent-feedback-button:focus-visible{border-color:var(--accent);color:var(--accent)}.agent-feedback-sent{margin:8px 0 0;color:var(--muted);font-size:.8125rem}` +
	`.agent-reply-answer,.agent-reply-sources,.agent-reply-backlink{width:min(100%,var(--chat-measure));box-sizing:border-box}.agent-reply-backlink{display:flex;padding:8px 10px;border:1px solid var(--line);border-radius:var(--hcm-radius-control);background:var(--soft);text-decoration:none}` +
	`.message{grid-template-columns:56px minmax(0,1fr)}.gutter-time{overflow:visible;font-variant-numeric:tabular-nums}.message-content{text-align:start}.message-actions{top:-38px}.message-stats{min-height:32px}.conversation-title{min-width:0}` +
	`@media(pointer:coarse){.message-stats,.mention-agent-info,.rail-row-more,.agent-feedback-button{min-height:44px}.rail-row-more{min-width:44px}}` +
	`@media(hover:none){.chat-row:not(.selected):hover{background:transparent;color:inherit}}` +
	`@media(max-width:767px){.chat-layout,.chat-workspace[data-details-open="true"] .chat-layout{grid-template-columns:minmax(0,1fr)}.chat-rail{display:none}.mobile-chat-toggle,.mobile-chat-close{display:inline-flex}.chat-workspace[data-sidebar-open="true"] .chat-rail{display:flex;position:fixed;inset:0 auto 0 0;width:min(88vw,320px);z-index:1200;box-shadow:var(--hcm-shadow-raised)}.mention-menu{inset-inline:0;width:100%;max-width:none;inset-block-end:calc(100% + 4px);max-height:min(52vh,380px);border-radius:var(--hcm-radius-surface) var(--hcm-radius-surface) 0 0}.chat-composer{position:relative;z-index:5;margin-bottom:max(8px,env(safe-area-inset-bottom))}.message{grid-template-columns:44px minmax(0,1fr)}.message.continued{padding-inline-start:54px}.message-actions{top:2px}.message-stats{min-height:44px}}`
