package chatui

// AgentUXChat3Styles is intentionally last in the chat stylesheet. These
// rules are the design-review contract for agent answers and the one-pane
// phone flow, so older generic chat breakpoints cannot turn the list back
// into a drawer or re-tint answer cards.
const AgentUXChat3Styles = `.agent-reply-row,.persona-task-card{box-sizing:border-box;width:100%;margin-block:8px;padding:10px 12px;border:1px solid var(--line);border-inline-start:3px solid var(--accent);border-radius:var(--hcm-radius-control);background:var(--surface);color:var(--ink)}` +
	`.chat-system-line{display:flex;align-items:center;justify-content:center;gap:6px;margin-block:8px;color:var(--muted);font-size:.8125rem}.chat-system-line .chat-icon{width:14px;height:14px}.chat-system-line time{font-variant-numeric:tabular-nums}` +
	`.message.search-target .agent-reply-row,.message.thread-active .agent-reply-row{background:var(--surface)}` +
	`.persona-progress-failure{border-inline-start-color:var(--hcm-color-warning);background:var(--surface)}.agent-failure-heading{display:flex;align-items:center;gap:6px;font-weight:650}.agent-failure-heading .chat-icon{width:18px;height:18px;color:var(--hcm-color-warning)}` +
	`.agent-reply-private{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:.8125rem}.agent-reply-private .chat-icon{width:15px;height:15px}.agent-reply-private time{margin-inline-start:auto;font-variant-numeric:tabular-nums}` +
	`.agent-reply-state-line{display:flex;align-items:center;gap:8px;margin-block:8px 2px;min-width:0}.agent-reply-state-copy{min-width:0}.agent-reply-counter{margin-inline-start:auto;font-variant-numeric:tabular-nums;white-space:nowrap}.agent-reply-state-divider{color:var(--muted)}.agent-progress-cancel{min-height:36px;border:0;background:none;color:var(--accent);font:inherit;font-weight:650;cursor:pointer;padding:4px}.agent-progress-cancel:disabled{color:var(--muted);cursor:not-allowed}.agent-working-dots{display:inline-flex;gap:3px;margin-inline-start:3px;vertical-align:middle}.agent-working-dots>span{width:4px;height:4px;border-radius:50%;background:currentColor;opacity:.35}.agent-working-dots>span:nth-child(2){animation-delay:var(--hcm-motion-fast)}.agent-working-dots>span:nth-child(3){animation-delay:var(--hcm-motion-normal)}@keyframes agent-working-dot{50%{opacity:1;transform:translateY(-2px)}}` +
	`@media(prefers-reduced-motion:no-preference){:root:not([data-hcm-motion-preference="reduce"]):not([data-hcm-motion-preference="limited"]) .agent-working-dots>span{animation:agent-working-dot var(--hcm-motion-slow) ease-in-out infinite}}` +
	`.agent-reply-answer,.agent-reply-sources,.agent-reply-backlink{width:100%;max-width:100%;box-sizing:border-box}.agent-reply-sources{display:flex;align-items:flex-start;gap:8px;margin-block:.65rem 0;padding-block-start:.55rem}.agent-reply-sources h4{flex:none;margin:2px 0 0;color:var(--muted);font-size:.8125rem}.agent-reply-sources ul{display:flex;flex-wrap:wrap;gap:6px 12px;margin:0;padding:0;list-style:none}.agent-reply-sources li{display:inline-flex;align-items:center;gap:5px}.agent-reply-sources .chat-icon{width:16px;height:16px;flex:none;color:var(--muted)}` +
	`.agent-question-context{display:grid;gap:4px;width:100%;box-sizing:border-box;margin-block:0 .55rem;padding:8px 10px;border:1px solid var(--line);border-radius:var(--hcm-radius-control);background:var(--canvas);color:var(--ink)}.agent-question-context-line{display:flex;flex-wrap:wrap;gap:4px;color:var(--muted);font-size:.8125rem}.agent-question-context blockquote{margin:0;font-style:normal}.agent-question-context a{color:var(--accent)}` +
	`.agent-feedback{align-items:center}.agent-feedback-button{display:inline-flex;align-items:center;gap:5px;min-height:36px;color:var(--ink);border-color:var(--line);background:var(--surface)}.agent-feedback-button .chat-icon{width:16px;height:16px}.agent-feedback-button[aria-pressed="true"]{background:var(--accent);border-color:var(--accent);color:var(--on-brand)}.agent-feedback-sent{display:flex;align-items:center;flex-wrap:wrap;gap:8px;color:var(--ink)}.agent-feedback-undo{border:0;background:none;color:var(--accent);font:inherit;font-weight:600;cursor:pointer;padding:4px}` +
	`.message-actions{top:2px}.thread-back-label{display:none}.thread-agent-continue{margin:10px 0;color:var(--muted);font-size:.875rem}.timeline-frame.away .message-list{padding-bottom:52px}.jump-newest{inset-inline:auto;left:50%;bottom:8px;transform:translate(-50%,6px)}.timeline-frame.away .jump-newest{transform:translateX(-50%)}` +
	`.composer-agent-token{padding:6px 8px 2px}.composer-agent-token+.composer-input{padding-block-start:5px}.send-button:disabled,.chat-composer:has(.composer-input:placeholder-shown) .send-button,.thread-composer:has(.composer-input:placeholder-shown) .send-button{background:var(--accent);border-color:transparent;color:var(--on-brand);opacity:.45}` +
	`.chat-workspace[dir="rtl"] .composer-input{unicode-bidi:plaintext;text-align:start}.chat-workspace[dir="rtl"] .chat-row{justify-content:flex-start}.chat-workspace[dir="rtl"] .chat-row-name{flex:0 1 auto;text-align:start}` +
	`@media(hover:none){.chat-rail-row .rail-row-more{position:absolute;opacity:0}.chat-rail-row:focus-within .rail-row-more,.rail-row-more[aria-expanded="true"]{opacity:1}.chat-rail-row:focus-within .agent-badge{margin-inline-end:34px}}` +
	`@media(max-width:767px){.chat-workspace[data-sidebar-open="true"] .chat-layout,.chat-workspace[data-has-selection="false"] .chat-layout{display:block}.chat-workspace[data-sidebar-open="true"] .chat-rail,.chat-workspace[data-has-selection="false"] .chat-rail{display:flex;position:absolute;inset:0;width:100%;max-width:none;z-index:8;box-shadow:none}.chat-workspace[data-sidebar-open="true"] .chat-main,.chat-workspace[data-sidebar-open="true"] .chat-side,.chat-workspace[data-has-selection="false"] .chat-main,.chat-workspace[data-has-selection="false"] .chat-side{display:none}.chat-workspace[data-sidebar-open="true"] .chat-scrim{display:none}.chat-rail{display:none}.mobile-chat-toggle,.mobile-chat-close{display:inline-flex}.chat-side.thread-pane{position:fixed;inset:0;width:100%;max-width:none;z-index:1300;background:var(--surface);box-shadow:none}.thread-back{display:inline-flex}.thread-back{width:auto;padding-inline:10px}.thread-back-label{display:inline}.thread-pane .side-heading{padding-top:max(8px,env(safe-area-inset-top))}.chat-composer{position:sticky;bottom:0;z-index:7;margin-bottom:0;padding-bottom:max(6px,env(safe-area-inset-bottom));background:var(--surface)}.mention-menu{position:absolute;inset-inline:0;inset-block:auto calc(100% + 4px);width:100%;max-width:none;max-height:min(55dvh,420px);border-radius:var(--hcm-radius-surface) var(--hcm-radius-surface) 0 0}.chat-composer:not(:focus-within){display:flex;flex-direction:column;align-items:stretch;padding:5px 6px 6px}.chat-composer:not(:focus-within) .composer-input{min-height:68px;padding:9px 7px}.chat-composer:not(:focus-within) .composer-toolbar{display:flex;min-height:40px;padding:4px 2px 0;border-top:1px solid var(--line)}.chat-composer:not(:focus-within) .composer-tools{display:flex;opacity:.62}.chat-composer:not(:focus-within) .composer-embeds{display:flex}.agent-feedback-button,.mention-agent-info,.message-stats{min-height:44px}.agent-feedback-button{padding-inline:12px}.agent-reply-row{margin-inline:0}.conversation-header>.conversation-actions{display:none}}`
