package chatui

// Joined last so the wave panels inherit the same shell controls and geometry.
const ChatPolishStyles = `
[hidden]{display:none!important}
.chat-search-layer-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-block-end:8px}.chat-search-layer .chat-search{inline-size:100%;min-inline-size:0}.rail-search .chat-search{font:inherit;text-align:start}
.reaction-picker,.emoji-picker{display:block}.reaction-picker>label{display:block}.emoji-search{display:block;inline-size:100%;min-inline-size:0}.emoji-category h3{white-space:nowrap}.emoji-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:4px}
[data-chat-layer]{position:fixed;inset:auto;margin:0;z-index:1600;max-inline-size:calc(100vw - 16px);max-block-size:calc(100dvh - 16px);overflow:auto;background:var(--hcm-color-surface);color:var(--hcm-color-text);border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-surface);box-shadow:var(--hcm-shadow-raised);padding:12px}
.chat-disclosure-button{display:flex;align-items:center;gap:8px;inline-size:100%;min-block-size:34px;padding:6px 8px;border:0;border-radius:var(--hcm-radius-control);background:transparent;color:inherit;font:inherit;text-align:start;cursor:pointer}.chat-disclosure-button>.chat-icon:last-child{margin-inline-start:auto;width:16px;height:16px}.chat-disclosure-button:hover,.chat-disclosure-button[aria-expanded=true]{background:var(--soft)}.chat-disclosure-button[aria-expanded=true]>.chat-icon:last-child{transform:rotate(180deg)}.chat-disclosure-button:focus-visible,.tool-button:focus-visible,.message-action:focus-visible,.menu-item:focus-visible{outline:2px solid var(--hcm-color-focus);outline-offset:2px}.chat-disclosure-button:disabled{cursor:default;opacity:.6}.chat-disclosure-body{min-inline-size:0;padding-block:8px}
.chat-settings-layer{inline-size:360px}.rail-prefs{flex:none}.rail-prefs .chat-disclosure-button{color:var(--muted)}.rail-prefs-body{display:grid;gap:12px;padding:8px}.chat-settings-layer>.rail-prefs-body{position:static;inset:auto;z-index:auto;max-width:none;padding:4px;border:0;border-radius:0;background:transparent;box-shadow:none}.prefs-row{display:flex;align-items:center;gap:8px}.prefs-field{display:grid;gap:4px;min-inline-size:0}.prefs-times{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.prefs-field input,.prefs-field select{inline-size:100%;min-inline-size:0}.chatrender-check input{margin:0}.chatrender-settings fieldset{margin:0}.chatrender-settings h3{font-size:1rem;margin:0}
.composer-toolbar{flex-wrap:nowrap;align-items:center;gap:4px}.composer-tools{display:flex;flex:1;flex-wrap:nowrap!important;align-items:center;gap:2px;min-inline-size:0}.tool-button,.composer-tools .tool-button{display:inline-flex;align-items:center;justify-content:center;inline-size:30px;min-inline-size:30px;block-size:30px;min-block-size:30px;padding:6px;border:0;border-radius:var(--hcm-radius-control);background:transparent;color:var(--muted);font:inherit;cursor:pointer}.tool-button .chat-icon,.message-action .chat-icon,.icon-button .chat-icon,.menu-item .chat-icon{inline-size:16px;block-size:16px}.tool-button:hover,.tool-button[aria-expanded=true],.icon-button[aria-pressed=true]{background:var(--soft);color:var(--accent)}.tool-button:active,.message-action:active,.menu-item:active{background:var(--soft)}
.format-tools>.chat-disclosure-button{inline-size:30px;min-inline-size:30px}.format-tools [data-chat-layer] [role=group]{display:flex;align-items:center;gap:4px;flex-wrap:wrap}.format-tools{flex:none;padding-inline-end:0;margin-inline-end:0;border-inline-end:0}.thread-composer .format-inline,.thread-composer .format-kind{display:none}.thread-composer .format-tools-menu{display:block}.thread-composer .send-button{inline-size:30px;min-inline-size:30px;padding:0}.thread-composer .send-label{display:none}
.chattone{display:flex;flex:none;gap:2px}.chattone[hidden],.chattone[data-available=false]{display:none}.chattone-toolbar-choices{display:flex;align-items:center;gap:2px}.chattone-options{inline-size:360px}.chattone-status{block-size:auto;min-block-size:0;margin:4px 0}.chattone-status:empty{display:none}.chattone-notice{inline-size:100%;margin:8px 0;line-height:1.5}.chattone-options>[role=group]{display:grid;gap:8px}.chattone-preview{min-inline-size:0}.chattone-suggested[data-suggested=false]{display:none}.chattone .chattone-style{min-block-size:30px;padding:6px}.chattone-toolbar-choices .chattone-suggested{display:none}.chattone-options .chattone-style{inline-size:100%}.chattone-choice{display:block}.chattone-tooltip{display:none}
.thread-composer{flex:none;min-block-size:0;max-block-size:40%;overflow:visible}.thread-composer>.composer-input{min-block-size:44px;max-block-size:120px;block-size:44px}.thread-message{position:relative}.thread-message-actions{position:absolute;inset-block-start:0;inset-inline-end:4px;transform:translateY(-50%);display:flex;gap:2px}.thread-message .message-actions,.thread-root .message-actions{visibility:hidden;pointer-events:none}.thread-message:hover .message-actions,.thread-message:focus-within .message-actions,.thread-message:has(.message-menu) .message-actions,.thread-root:hover .message-actions,.thread-root:focus-within .message-actions,.thread-root:has(.message-menu) .message-actions{visibility:visible;pointer-events:auto}.thread-message .message-meta{padding-inline-end:60px}.thread-message-body{min-inline-size:0}
.menu-item{display:flex;align-items:center;gap:8px;inline-size:100%;min-block-size:34px;padding:8px 12px;border:0;border-radius:var(--hcm-radius-control);background:transparent;color:var(--ink);font:inherit;text-decoration:none;text-align:start;white-space:normal;cursor:pointer}.menu-item:hover{background:var(--soft)}.menu-item.danger{color:var(--hcm-color-danger)}.menu-separator{block-size:1px;background:var(--line);margin-block:6px}.message-menu{padding:6px;inline-size:280px}.message-menu .menu-item{min-block-size:34px}.message-menu .chat-icon,.message-menu .chatsave-bookmark{inline-size:16px;block-size:16px}
.chatsave-panel{inset-block:var(--chatsave-top,82px) 0;inset-inline:auto 0;inline-size:min(var(--chat-details,400px),calc(100vw - 16px));block-size:auto;max-inline-size:calc(100vw - 16px);padding:0}.chatsave-sidebar-row{inline-size:100%;display:flex;align-items:center;gap:8px;border:0;background:transparent;font:inherit;text-align:start}.chatsave-sidebar-row[aria-expanded=true]{background:var(--soft);color:var(--accent)}.chatsave-sidebar-row .chat-badge{position:static}
.chat-agent-here p,.mention-profile-card p{font-size:.8125rem;line-height:1.5}.chat-agent-here .avatar{flex:none}.agent-dm-avatar{display:inline-flex;align-items:center;justify-content:center;vertical-align:middle;flex:none}.agent-dm-avatar .agent-icon,.agent-reply-avatar .agent-icon{inline-size:100%;block-size:100%;display:block}.chat-row .avatar.tiny{inline-size:24px;block-size:24px}.chat-row .agent-dm-avatar{align-self:center}.agent-reply-footer{display:flex;flex-wrap:wrap;align-items:center;gap:8px 12px;margin-block-start:8px}.agent-reply-footer .agent-follow-up{margin:0}.agent-reply-footer .agent-reply-open{margin:0;inline-size:auto}.agent-reply-sources li{display:grid;grid-template-columns:16px minmax(0,1fr);gap:4px 8px;min-inline-size:0}.agent-reply-source-unavailable{grid-column:2;display:block;color:var(--muted);font-size:.8125rem}.agent-reply-sources ul{min-inline-size:0}
.chatmap-control{display:flex;flex:none}.chatmap-sheet{inline-size:400px;padding:12px}.chatmap-sheet label{display:grid;gap:4px}.chatmap-segments{display:flex;gap:4px}.chatmap-segments button{flex:1;min-inline-size:0;font:inherit;font-size:.8125rem;overflow-wrap:anywhere}.chatmap-segments button[aria-pressed=true]{background:var(--soft);color:var(--accent);border-color:var(--accent)}.chatmap-choice{margin-block:8px}.chatmap-preview-frame{position:relative;border:1px solid var(--line);border-radius:var(--hcm-radius-control);overflow:hidden;background:var(--canvas)}.chatmap-preview{display:grid;place-items:center;min-block-size:140px}.chatmap-preview .chat-icon{inline-size:32px;block-size:32px;color:var(--accent)}.chatmap-nudges{display:flex;flex-wrap:wrap;justify-content:center;gap:4px;padding:6px}.chatmap-nudges button{padding:6px;min-block-size:30px;font:inherit}.chatmap-sheet textarea{inline-size:100%;min-inline-size:0;box-sizing:border-box;padding:8px;border:1px solid var(--line);border-radius:var(--hcm-radius-control);background:var(--surface);color:var(--ink);font:inherit;resize:vertical}.chatmap-sheet .chatmap-send{background:var(--accent);color:var(--hcm-color-on-brand);border-color:var(--accent);font:inherit;cursor:pointer}.chatmap-sheet p{font-size:.8125rem;line-height:1.5}.chatmap-sheet .chatmap-picture[hidden]{display:none}.chatmap-card button{font:inherit}
@container chatmain (max-width:560px){.format-inline,.format-tools .format-kind{display:none}.format-tools-menu{display:block}}
@media(max-width:800px){.composer-help{display:none}.chat-settings-layer,.chattone-options{max-inline-size:calc(100vw - 16px)}}@media(max-width:390px){.composer-tools{gap:0}.tool-button,.composer-tools .tool-button{inline-size:28px;min-inline-size:28px;block-size:30px;padding:5px}.composer-toolbar{gap:2px}.send-button{flex:none}.chat-composer .send-label{display:none}.chat-composer .send-button{inline-size:30px;min-inline-size:30px;padding:0}.chatmap-nudges button{font-size:.75rem}.chatmap-segments{flex-wrap:wrap}}
.chatrender-personal-slot{display:none}.chat-settings-layer{overflow-x:hidden}.chat-settings-layer :is(select,input[type=time],input[type=text]){max-inline-size:100%;box-sizing:border-box}
.channel-tray-card[data-chat-layer]{display:block;overflow-x:hidden;overflow-y:auto;box-sizing:border-box;padding:12px 14px 14px;max-block-size:calc(100dvh - 16px);max-height:calc(100dvh - 16px)}.channel-tray-card[data-chat-layer]:has(.channel-poll-form){max-inline-size:calc(100vw - 16px);margin-inline-start:0}.channel-tray-card[data-chat-layer] .channel-poll-form{max-inline-size:none;min-inline-size:0}.channel-tray-card[data-chat-layer] .channel-poll-actions{position:static;display:flex;justify-content:flex-end;margin:8px 0 0;padding:0;background:transparent}.channel-tray-card[data-chat-layer] .channel-todo-list,.channel-tray-card[data-chat-layer] .channel-todo-row{min-inline-size:0}
.chat-workspace .channel-todo-trigger:hover,.chat-workspace .channel-poll-trigger:hover{background:var(--soft);border-color:var(--line);color:var(--ink)}.chat-workspace .channel-poll-trigger.active:not([aria-pressed=true]):not(:hover){border-color:transparent;background:transparent}.chat-workspace .channel-todo-trigger[aria-pressed=true],.chat-workspace .channel-poll-trigger[aria-pressed=true]{background:var(--soft);border-color:var(--accent);color:var(--accent)}.chat-workspace .channel-poll-trigger.active .channel-poll-active-indicator{color:var(--accent)}
@media(prefers-reduced-motion:reduce){.chat-disclosure-button>.chat-icon,.chat-workspace button{transition:none;animation:none}}
`
