package chatui

import "strings"

func chatcmd003Text(m Model, key string) string {
	copy := map[string]string{
		"cost": "Each tidy request uses the workspace’s daily AI budget.", "apply-settings": "Apply settings", "review-settings": "Settings updated. Review this preview, then press Post.", "former-member": "Former member", "confirm": "Confirm these details", "tick-policy": "Who may complete items", "anyone": "Any member", "assignee": "The assignee", "author": "The author", "poll": "Poll", "todo": "To-do list", "preview": "Preview", "draft": "Write your draft", "post": "Post", "edit": "Edit", "cancel": "Cancel", "original": "Use what I typed", "tidy": "Tidy with AI", "working": "Preparing your preview…", "changes": "Tidied: {n} changes", "multiple": "Allow several choices", "anonymous": "Keep votes anonymous", "results": "Show results", "always": "Always", "after-voting": "After voting", "after-closing": "After closing", "yes": "Yes", "no": "No", "closes": "Closing time", "closes-hint": "Never, in an hour, Friday, or YYYY-MM-DD", "closed": "Closed", "close": "Close", "reopen": "Reopen", "vote": "Vote", "voted": "Your choice", "tick": "Mark complete", "untick": "Mark incomplete", "completed": "Completed by {name} at {date}", "due": "Due {date}", "assigned": "Assigned to {name}", "waiting-results": "Vote to see results, or return after the poll closes.", "unavailable": "Polls and lists are unavailable here. Keep your draft and try again later.", "parse": "Check the quotes and settings, then preview again.", "post-error": "Could not post. Your draft is kept; press Post to try again.", "tidy-fallback": "Could not tidy. Review your original draft and post when ready.", "ai-notice": "Tidy with AI sends this draft to the workspace’s approved model. Review every change before posting.", "separate-question": "Check the question and options. Use Edit to separate them before posting.", "ambiguous-assignee": "This name is ambiguous or unavailable. Use Edit to choose a member explicitly.", "date": "Confirm the date in Edit using YYYY-MM-DD.", "past-date": "This due date has passed. Confirm a future date in Edit.", "add-tasks": "Add to my tasks", "move-channel": "Move to channel list", "poll-usage": "Write a question, then 1=\"First option\" 2=\"Second option\". Double quotes inside quoted text.", "todo-usage": "Write a title, then 1=\"Task\" 2=\"Task @Name by Friday\", or put each task on a new line.",
	}
	chatbug039English := copy[key]
	switch {
	case strings.HasPrefix(strings.ToLower(m.Locale), "de"):
		copy = map[string]string{"former-member": "Ehemaliges Mitglied", "review-settings": "Einstellungen aktualisiert. Prüfen Sie die Vorschau und veröffentlichen Sie anschließend.", "apply-settings": "Einstellungen anwenden", "cost": "Jede Überarbeitung nutzt das tägliche KI-Budget des Arbeitsbereichs.", "confirm": "Diese Angaben bestätigen", "tick-policy": "Wer Aufgaben erledigen darf", "anyone": "Jedes Mitglied", "assignee": "Die zugewiesene Person", "author": "Die verfassende Person", "poll": "Umfrage", "todo": "Aufgabenliste", "preview": "Vorschau", "draft": "Entwurf schreiben", "post": "Veröffentlichen", "edit": "Bearbeiten", "cancel": "Abbrechen", "original": "Meine Eingabe verwenden", "tidy": "Mit KI überarbeiten", "working": "Vorschau wird vorbereitet…", "changes": "Überarbeitet: {n} Änderungen", "multiple": "Mehrere Antworten zulassen", "anonymous": "Anonym abstimmen", "results": "Ergebnisse anzeigen", "always": "Immer", "after-voting": "Nach der Abstimmung", "after-closing": "Nach Abschluss", "yes": "Ja", "no": "Nein", "closes": "Endzeit", "closes-hint": "In einer Stunde, Freitag oder JJJJ-MM-TT", "closed": "Geschlossen", "close": "Schließen", "reopen": "Wieder öffnen", "vote": "Abstimmen", "voted": "Ihre Auswahl", "tick": "Als erledigt markieren", "untick": "Als offen markieren", "completed": "Erledigt von {name} am {date}", "due": "Fällig am {date}", "assigned": "Zugewiesen an {name}", "waiting-results": "Stimmen Sie ab oder kehren Sie nach Abschluss zurück, um Ergebnisse zu sehen.", "unavailable": "Umfragen und Listen sind hier nicht verfügbar. Behalten Sie Ihren Entwurf und versuchen Sie es später erneut.", "parse": "Prüfen Sie Anführungszeichen und Einstellungen, dann öffnen Sie die Vorschau erneut.", "post-error": "Veröffentlichung fehlgeschlagen. Ihr Entwurf bleibt erhalten; versuchen Sie es erneut.", "tidy-fallback": "Überarbeitung nicht möglich. Prüfen Sie Ihren Entwurf vor der Veröffentlichung.", "ai-notice": "Die KI-Überarbeitung sendet diesen Entwurf an das freigegebene Modell. Prüfen Sie jede Änderung vor der Veröffentlichung.", "separate-question": "Prüfen Sie Frage und Antworten. Trennen Sie diese unter Bearbeiten vor der Veröffentlichung.", "ambiguous-assignee": "Dieser Name ist mehrdeutig oder nicht verfügbar. Wählen Sie unter Bearbeiten ein Mitglied ausdrücklich aus.", "date": "Bestätigen Sie das Datum unter Bearbeiten im Format JJJJ-MM-TT.", "past-date": "Dieses Datum liegt in der Vergangenheit. Bestätigen Sie ein künftiges Datum unter Bearbeiten.", "add-tasks": "Zu meinen Aufgaben hinzufügen", "move-channel": "In die Kanalliste verschieben", "poll-usage": "Frage eingeben, dann 1=\"Erste Antwort\" 2=\"Zweite Antwort\". Anführungszeichen im Text verdoppeln.", "todo-usage": "Titel eingeben, dann 1=\"Aufgabe\" 2=\"Aufgabe @Name by Friday\", oder jede Aufgabe in eine neue Zeile setzen."}
	case strings.HasPrefix(strings.ToLower(m.Locale), "ar"):
		copy = map[string]string{"former-member": "عضو سابق", "review-settings": "تم تحديث الإعدادات. راجع المعاينة ثم اضغط نشر.", "apply-settings": "تطبيق الإعدادات", "cost": "يستخدم كل طلب تنسيق ميزانية الذكاء الاصطناعي اليومية لمساحة العمل.", "confirm": "تأكيد هذه التفاصيل", "tick-policy": "من يمكنه إكمال المهام", "anyone": "أي عضو", "assignee": "الشخص المكلّف", "author": "الكاتب", "poll": "استطلاع", "todo": "قائمة مهام", "preview": "معاينة", "draft": "اكتب المسودة", "post": "نشر", "edit": "تعديل", "cancel": "إلغاء", "original": "استخدام ما كتبته", "tidy": "تنسيق بالذكاء الاصطناعي", "working": "جارٍ إعداد المعاينة…", "changes": "تم التنسيق: {n} تغييرات", "multiple": "السماح بعدة اختيارات", "anonymous": "تصويت مجهول الهوية", "results": "عرض النتائج", "always": "دائمًا", "after-voting": "بعد التصويت", "after-closing": "بعد الإغلاق", "yes": "نعم", "no": "لا", "closes": "وقت الإغلاق", "closes-hint": "بعد ساعة أو الجمعة أو YYYY-MM-DD", "closed": "مغلق", "close": "إغلاق", "reopen": "إعادة الفتح", "vote": "تصويت", "voted": "اختيارك", "tick": "تحديد كمكتملة", "untick": "تحديد كغير مكتملة", "completed": "أكملها {name} في {date}", "due": "موعدها {date}", "assigned": "مسندة إلى {name}", "waiting-results": "صوّت لعرض النتائج أو عد بعد إغلاق الاستطلاع.", "unavailable": "الاستطلاعات والقوائم غير متاحة هنا. احتفظ بالمسودة وحاول لاحقًا.", "parse": "تحقق من علامات الاقتباس والإعدادات ثم عاين مجددًا.", "post-error": "تعذر النشر. تم الاحتفاظ بالمسودة؛ اضغط نشر للمحاولة مجددًا.", "tidy-fallback": "تعذر التنسيق. راجع مسودتك الأصلية وانشرها عندما تكون جاهزة.", "ai-notice": "يرسل التنسيق هذه المسودة إلى نموذج معتمد. راجع كل تغيير قبل النشر.", "separate-question": "تحقق من السؤال والخيارات. استخدم التعديل لفصلها قبل النشر.", "ambiguous-assignee": "الاسم ملتبس أو غير متاح. استخدم التعديل لاختيار عضو بشكل صريح.", "date": "أكد التاريخ في التعديل باستخدام YYYY-MM-DD.", "past-date": "هذا الموعد قد مضى. أكد موعدًا قادمًا في التعديل.", "add-tasks": "إضافة إلى مهامي", "move-channel": "نقل إلى قائمة القناة", "poll-usage": "اكتب سؤالًا ثم 1=\"الخيار الأول\" 2=\"الخيار الثاني\". ضاعف علامات الاقتباس داخل النص.", "todo-usage": "اكتب عنوانًا ثم 1=\"مهمة\" 2=\"مهمة @Name by Friday\" أو ضع كل مهمة في سطر جديد."}
	}
	return chatbug039Text(key, copy[key], chatbug039English)
}
