package chatui

// chatcmd003Copy is the reviewed copy of polls and to-do lists posted as
// messages and of their preview, in the three product languages (English,
// German, Arabic). A key missing here would reach the page as nothing at all,
// never as the key, because chatbug039Text refuses to print one.
var chatcmd003Copy = map[string][3]string{
	"poll":            {"Poll", "Umfrage", "استطلاع"},
	"todo":            {"To-do list", "Aufgabenliste", "قائمة مهام"},
	"preview":         {"Preview", "Vorschau", "معاينة"},
	"poll-preview":    {"Poll preview", "Vorschau der Umfrage", "معاينة الاستطلاع"},
	"todo-preview":    {"To-do list preview", "Vorschau der Aufgabenliste", "معاينة قائمة المهام"},
	"post":            {"Post", "Veröffentlichen", "نشر"},
	"poll-post":       {"Post poll", "Umfrage veröffentlichen", "نشر الاستطلاع"},
	"todo-post":       {"Post list", "Liste veröffentlichen", "نشر القائمة"},
	"cancel":          {"Cancel", "Abbrechen", "إلغاء"},
	"keys":            {"Enter posts · Shift+Enter adds a line · Esc cancels", "Enter veröffentlicht · Umschalt+Enter neue Zeile · Esc bricht ab", "Enter للنشر · Shift+Enter لسطر جديد · Esc للإلغاء"},
	"original":        {"Use what I typed", "Meine Eingabe verwenden", "استخدام ما كتبته"},
	"tidied":          {"Tidy the wording", "Wortlaut überarbeiten", "تنسيق الصياغة"},
	"as-typed":        {"Shown as you typed it.", "Wie eingegeben angezeigt.", "معروض كما كتبته."},
	"tidy":            {"Tidy with AI", "Mit KI überarbeiten", "تنسيق بالذكاء الاصطناعي"},
	"working":         {"Tidying your draft…", "Entwurf wird überarbeitet…", "جارٍ تنسيق المسودة…"},
	"posting":         {"Posting…", "Wird veröffentlicht…", "جارٍ النشر…"},
	"changes":         {"Tidied: {n} changes", "Überarbeitet: {n} Änderungen", "تم التنسيق: {n} تغييرات"},
	"change-one":      {"Tidied: 1 change", "Überarbeitet: 1 Änderung", "تم التنسيق: تغيير واحد"},
	"merged":          {"Repeated option merged: {text}", "Doppelte Antwort zusammengeführt: {text}", "تم دمج خيار مكرر: {text}"},
	"change-split":    {"One line became {n} tasks", "Aus einer Zeile wurden {n} Aufgaben", "أصبح سطر واحد {n} مهام"},
	"change-assignee": {"{task}: assigned to {name}", "{task}: zugewiesen an {name}", "{task}: مسندة إلى {name}"},
	"change-due":      {"{task}: due {date}", "{task}: fällig am {date}", "{task}: موعدها {date}"},
	"multiple":        {"Allow several choices", "Mehrere Antworten zulassen", "السماح بعدة اختيارات"},
	"anonymous":       {"Keep votes anonymous", "Anonym abstimmen", "تصويت مجهول الهوية"},
	"results":         {"Show results", "Ergebnisse anzeigen", "عرض النتائج"},
	"always":          {"Always", "Immer", "دائمًا"},
	"after-voting":    {"After voting", "Nach der Abstimmung", "بعد التصويت"},
	"after-closing":   {"After closing", "Nach Abschluss", "بعد الإغلاق"},
	"closes":          {"Closes", "Endet", "يُغلق"},
	"closes-never":    {"Never", "Nie", "أبدًا"},
	"closes-hour":     {"In an hour", "In einer Stunde", "بعد ساعة"},
	"closes-today":    {"End of day", "Tagesende", "نهاية اليوم"},
	"closes-tomorrow": {"Tomorrow", "Morgen", "غدًا"},
	"closes-week":     {"In a week", "In einer Woche", "بعد أسبوع"},
	"closed":          {"Closed", "Geschlossen", "مغلق"},
	"close":           {"Close", "Schließen", "إغلاق"},
	"reopen":          {"Reopen", "Wieder öffnen", "إعادة الفتح"},
	"close-poll":      {"Close poll", "Umfrage schließen", "إغلاق الاستطلاع"},
	"reopen-poll":     {"Reopen poll", "Umfrage wieder öffnen", "إعادة فتح الاستطلاع"},
	"close-list":      {"Close list", "Liste schließen", "إغلاق القائمة"},
	"reopen-list":     {"Reopen list", "Liste wieder öffnen", "إعادة فتح القائمة"},
	"vote":            {"Vote", "Abstimmen", "تصويت"},
	"voted":           {"Your choice", "Ihre Auswahl", "اختيارك"},
	"withdraw":        {"Press to withdraw your vote", "Drücken, um Ihre Stimme zurückzuziehen", "اضغط لسحب تصويتك"},
	"cast":            {"Cast vote", "Stimme abgeben", "إرسال التصويت"},
	"cast-hint":       {"An anonymous vote cannot be changed once it is cast.", "Eine anonyme Stimme kann nach der Abgabe nicht geändert werden.", "لا يمكن تغيير التصويت المجهول بعد إرساله."},
	"cast-done":       {"Your vote is recorded. Nobody can see what you chose.", "Ihre Stimme wurde gezählt. Niemand sieht, was Sie gewählt haben.", "تم تسجيل تصويتك. لا أحد يرى ما اخترته."},
	"votes":           {"{n} votes", "{n} Stimmen", "{n} أصوات"},
	"vote-one":        {"1 vote", "1 Stimme", "صوت واحد"},
	"votes-none":      {"No votes yet", "Noch keine Stimmen", "لا توجد أصوات بعد"},
	"chip-multiple":   {"Several choices", "Mehrere Antworten", "عدة اختيارات"},
	"chip-anonymous":  {"Anonymous", "Anonym", "مجهول الهوية"},
	"closes-at":       {"Closes {date}", "Endet am {date}", "يُغلق في {date}"},
	"closed-at":       {"Closed {date}", "Geschlossen am {date}", "أُغلق في {date}"},
	"done-count":      {"{done} of {total} done", "{done} von {total} erledigt", "تم {done} من {total}"},
	"tick":            {"Mark complete", "Als erledigt markieren", "تحديد كمكتملة"},
	"untick":          {"Mark incomplete", "Als offen markieren", "تحديد كغير مكتملة"},
	"completed":       {"Completed by {name} at {date}", "Erledigt von {name} am {date}", "أكملها {name} في {date}"},
	"completed-by":    {"Done by {name}", "Erledigt von {name}", "أكملها {name}"},
	"due":             {"Due {date}", "Fällig am {date}", "موعدها {date}"},
	"assigned":        {"Assigned to {name}", "Zugewiesen an {name}", "مسندة إلى {name}"},
	"former-member":   {"Former member", "Ehemaliges Mitglied", "عضو سابق"},
	"tick-policy":     {"Who may complete items", "Wer Aufgaben erledigen darf", "من يمكنه إكمال المهام"},
	"anyone":          {"Any member", "Jedes Mitglied", "أي عضو"},
	"assignee":        {"The assignee", "Die zugewiesene Person", "الشخص المكلّف"},
	"author":          {"The author", "Die verfassende Person", "الكاتب"},
	"add-tasks":       {"Add to my tasks", "Zu meinen Aufgaben hinzufügen", "إضافة إلى مهامي"},
	"move-channel":    {"Copy to channel list", "In die Kanalliste kopieren", "نسخ إلى قائمة القناة"},
	"waiting-results": {"Vote to see results, or return after the poll closes.", "Stimmen Sie ab oder kehren Sie nach Abschluss zurück, um Ergebnisse zu sehen.",
		"صوّت لعرض النتائج أو عد بعد إغلاق الاستطلاع."},
	"waiting-closing": {"Results are shown when the poll closes.", "Die Ergebnisse werden angezeigt, wenn die Umfrage endet.", "تظهر النتائج عند إغلاق الاستطلاع."},
	"unavailable": {"Polls and lists are unavailable here. Keep your draft and try again later.", "Umfragen und Listen sind hier nicht verfügbar. Behalten Sie Ihren Entwurf und versuchen Sie es später erneut.",
		"الاستطلاعات والقوائم غير متاحة هنا. احتفظ بالمسودة وحاول لاحقًا."},
	"parse": {"A quote is not closed, or a number or setting is repeated or unknown. Fix it in the message box to see the preview.", "Ein Anführungszeichen ist nicht geschlossen, oder eine Nummer oder Einstellung ist doppelt oder unbekannt. Korrigieren Sie es im Nachrichtenfeld, um die Vorschau zu sehen.",
		"علامة اقتباس غير مغلقة، أو رقم أو إعداد مكرر أو غير معروف. صحّحه في مربع الرسالة لعرض المعاينة."},
	"post-error": {"Could not post: the server did not answer. Your draft is kept; press Enter to try again.", "Veröffentlichung fehlgeschlagen: Der Server hat nicht geantwortet. Ihr Entwurf bleibt erhalten; drücken Sie Enter, um es erneut zu versuchen.",
		"تعذر النشر: لم يستجب الخادم. تم الاحتفاظ بالمسودة؛ اضغط Enter للمحاولة مجددًا."},
	"post-denied": {"Not posted: you cannot post here, or a person a task names is not a member of this conversation. Your draft is kept.", "Nicht veröffentlicht: Sie dürfen hier nicht schreiben, oder eine in einer Aufgabe genannte Person ist kein Mitglied dieser Unterhaltung. Ihr Entwurf bleibt erhalten.",
		"لم يُنشر: لا يمكنك النشر هنا، أو أن شخصًا مذكورًا في مهمة ليس عضوًا في هذه المحادثة. تم الاحتفاظ بالمسودة."},
	"post-refused": {"Not posted: the server did not accept this card. Check its text, then press Enter to try again. Your draft is kept.", "Nicht veröffentlicht: Der Server hat diese Karte nicht angenommen. Prüfen Sie den Text und drücken Sie dann Enter. Ihr Entwurf bleibt erhalten.",
		"لم يُنشر: لم يقبل الخادم هذه البطاقة. تحقق من نصها ثم اضغط Enter للمحاولة مجددًا. تم الاحتفاظ بالمسودة."},
	"post-gone": {"Not posted: this conversation is no longer available. Your draft is kept.", "Nicht veröffentlicht: Diese Unterhaltung ist nicht mehr verfügbar. Ihr Entwurf bleibt erhalten.",
		"لم يُنشر: هذه المحادثة لم تعد متاحة. تم الاحتفاظ بالمسودة."},
	"tidy-fallback": {"Could not tidy with AI. The preview shows your text with the basic tidy; post when ready.", "KI-Überarbeitung nicht möglich. Die Vorschau zeigt Ihren Text mit der einfachen Überarbeitung.",
		"تعذر التنسيق بالذكاء الاصطناعي. تعرض المعاينة نصك بالتنسيق الأساسي؛ انشر عندما تكون جاهزًا."},
	"ai-notice": {"Tidy with AI sends this draft to the workspace’s approved model. Review every change before posting.", "Die KI-Überarbeitung sendet diesen Entwurf an das freigegebene Modell. Prüfen Sie jede Änderung vor der Veröffentlichung.",
		"يرسل التنسيق هذه المسودة إلى نموذج معتمد. راجع كل تغيير قبل النشر."},
	"cost": {"Each tidy request uses the workspace’s daily AI budget.", "Jede Überarbeitung nutzt das tägliche KI-Budget des Arbeitsbereichs.", "يستخدم كل طلب تنسيق ميزانية الذكاء الاصطناعي اليومية لمساحة العمل."},
	"separate-question": {"Check that the question and the options were separated the way you meant. A question mark after the question makes it certain.", "Prüfen Sie, ob Frage und Antworten wie gewünscht getrennt wurden. Ein Fragezeichen nach der Frage macht es eindeutig.",
		"تحقق من أن السؤال والخيارات فُصلت كما قصدت. علامة استفهام بعد السؤال تجعل ذلك مؤكدًا."},
	"ambiguous-assignee": {"A name fits no member here, or more than one, so it stays in the task’s text. Write the member’s full name after @ to assign the task.", "Ein Name passt hier zu keinem oder zu mehreren Mitgliedern und bleibt deshalb im Text der Aufgabe. Schreiben Sie den vollen Namen nach @, um die Aufgabe zuzuweisen.",
		"اسم لا يطابق أي عضو هنا أو يطابق أكثر من عضو، لذا بقي في نص المهمة. اكتب الاسم الكامل بعد @ لإسناد المهمة."},
	"date": {"A date after “by” was not understood and stays in the task’s text. Write a weekday, a day such as “Oct 9”, or YYYY-MM-DD.", "Ein Datum nach „bis“ wurde nicht verstanden und bleibt im Text der Aufgabe. Schreiben Sie einen Wochentag, einen Tag wie „9. Okt“ oder JJJJ-MM-TT.",
		"تاريخ بعد «بحلول» لم يُفهم وبقي في نص المهمة. اكتب يومًا من الأسبوع أو يومًا مثل «9 أكتوبر» أو YYYY-MM-DD."},
	"past-date": {"A due date has already passed. Change it in the message box if that is not what you meant.", "Ein Fälligkeitsdatum liegt bereits in der Vergangenheit. Ändern Sie es im Nachrichtenfeld, wenn das nicht gemeint war.", "أحد المواعيد قد مضى. غيّره في مربع الرسالة إن لم يكن ذلك مقصودًا."},
	"poll-usage": {"Write the question, then the options: Where for lunch? Tacos, pho or pizza. Shift+Enter starts a new line, and each line after the question is one option.",
		"Schreiben Sie die Frage und dann die Antworten: Wohin zum Mittagessen? Tacos, Pho oder Pizza. Umschalt+Enter beginnt eine neue Zeile, und jede Zeile nach der Frage ist eine Antwort.",
		"اكتب السؤال ثم الخيارات: أين نتغدى؟ تاكو، فو أو بيتزا. Shift+Enter يبدأ سطرًا جديدًا، وكل سطر بعد السؤال خيار."},
	"todo-usage": {"Write the tasks, one on each line (Shift+Enter) or with a semicolon between them. @Name assigns a task, and “Friday”, “tomorrow” or “Oct 9” sets its date.",
		"Schreiben Sie die Aufgaben, jede in eine eigene Zeile (Umschalt+Enter) oder durch Semikolon getrennt. @Name weist eine Aufgabe zu, und „Freitag“, „morgen“ oder „9. Okt“ legt ihr Datum fest.",
		"اكتب المهام، كل مهمة في سطر (Shift+Enter) أو افصل بينها بفاصلة منقوطة. @الاسم يسند المهمة، و«الجمعة» أو «غدًا» أو «9 أكتوبر» يحدد موعدها."},
	"need-options":   {"A poll needs a question and at least two different options.", "Eine Umfrage braucht eine Frage und mindestens zwei verschiedene Antworten.", "يحتاج الاستطلاع إلى سؤال وخيارين مختلفين على الأقل."},
	"too-many":       {"A poll takes at most twelve options.", "Eine Umfrage hat höchstens zwölf Antworten.", "يقبل الاستطلاع اثني عشر خيارًا على الأكثر."},
	"need-items":     {"Add at least one task.", "Fügen Sie mindestens eine Aufgabe hinzu.", "أضف مهمة واحدة على الأقل."},
	"too-many-items": {"A list takes at most thirty tasks.", "Eine Liste hat höchstens dreißig Aufgaben.", "تقبل القائمة ثلاثين مهمة على الأكثر."},
	"too-long":       {"One of the lines is too long. Shorten it in the message box.", "Eine der Zeilen ist zu lang. Kürzen Sie sie im Nachrichtenfeld.", "أحد الأسطر طويل جدًا. اختصره في مربع الرسالة."},
	"card-conflict":  {"This changed while you were looking. It is up to date now; try again.", "Dies hat sich inzwischen geändert. Es ist jetzt aktuell; versuchen Sie es erneut.", "تغيّر هذا أثناء عرضك له. أصبح محدّثًا الآن؛ حاول مجددًا."},
	"card-final":     {"Your vote was already recorded. An anonymous vote cannot be changed.", "Ihre Stimme wurde bereits gezählt. Eine anonyme Stimme kann nicht geändert werden.", "سبق تسجيل تصويتك. لا يمكن تغيير التصويت المجهول."},
	"card-denied":    {"You cannot change this here.", "Sie können dies hier nicht ändern.", "لا يمكنك تغيير هذا هنا."},
	"card-failed":    {"Could not save that. Try again.", "Das konnte nicht gespeichert werden. Versuchen Sie es erneut.", "تعذر حفظ ذلك. حاول مجددًا."},
	"standing-none":  {"This channel has no poll. A poll is posted in the conversation, where everyone can vote.", "Dieser Kanal hat keine Umfrage. Eine Umfrage wird in der Unterhaltung veröffentlicht, wo alle abstimmen können.", "لا يوجد استطلاع في هذه القناة. يُنشر الاستطلاع في المحادثة حيث يصوّت الجميع."},
	"standing-start": {"Start a poll", "Umfrage starten", "بدء استطلاع"},
	"standing-move-note": {"This channel still has a standing poll from before polls were messages: “{question}”.", "Dieser Kanal hat noch eine feste Umfrage aus der Zeit, bevor Umfragen Nachrichten waren: „{question}“.",
		"ما زال في هذه القناة استطلاع ثابت من قبل أن تصبح الاستطلاعات رسائل: «{question}»."},
	"standing-move": {"Move it here", "Hierher verschieben", "انقله إلى هنا"},
	"standing-closes": {"Posting this closes the channel’s standing poll. Its votes ({n}) are not carried over: people vote again on the card.", "Mit der Veröffentlichung wird die feste Umfrage des Kanals geschlossen. Ihre Stimmen ({n}) werden nicht übernommen: Auf der Karte wird neu abgestimmt.",
		"نشر هذه البطاقة يغلق الاستطلاع الثابت للقناة. أصواته ({n}) لا تُنقل: يصوّت الأعضاء من جديد على البطاقة."},
	"rule-creator":  {"Creator only", "Nur Ersteller", "المنشئ فقط"},
	"rule-selected": {"Selected people", "Ausgewählte Personen", "أشخاص محددون"},
	"cmd-poll":      {"Ask a question and let people vote", "Eine Frage stellen und abstimmen lassen", "اطرح سؤالًا ودع الآخرين يصوّتون"},
	"cmd-todo":      {"Post a to-do list people can tick off", "Eine Aufgabenliste zum Abhaken veröffentlichen", "انشر قائمة مهام يمكن إنجازها"},
	"cmd-ask":       {"Ask an agent in this conversation", "Einen Agenten in dieser Unterhaltung fragen", "اسأل وكيلًا في هذه المحادثة"},
	"cmd-keys":      {"↑↓ to move · Enter or Tab to choose · Esc to close", "↑↓ bewegen · Enter oder Tab wählen · Esc schließen", "↑↓ للتنقل · Enter أو Tab للاختيار · Esc للإغلاق"},
	"cmd-usage":     {"Usage", "Verwendung", "طريقة الاستخدام"},
	"cmd-example":   {"Example", "Beispiel", "مثال"},
	"cmd-invalid":   {"A quote is not closed, or a number or setting is repeated. Fix it to continue.", "Ein Anführungszeichen ist nicht geschlossen oder eine Nummer oder Einstellung wiederholt sich. Korrigieren Sie es, um fortzufahren.", "علامة اقتباس غير مغلقة أو رقم أو إعداد مكرر. صحّحه للمتابعة."},
	"cmd-unknown":   {"/{name} is not a command here.", "/{name} ist hier kein Befehl.", "/{name} ليس أمرًا هنا."},
	"cmd-suggest":   {"Did you mean /{name}?", "Meinten Sie /{name}?", "هل تقصد /{name}؟"},
	"cmd-use":       {"Use /{name}", "/{name} verwenden", "استخدام /{name}"},
	"cmd-as-text":   {"Send as text", "Als Text senden", "إرسال كنص"},
	"go-to-message": {"Go to this message", "Zu dieser Nachricht", "الانتقال إلى هذه الرسالة"},
	"card-choose":   {"Choose an option first.", "Wählen Sie zuerst eine Antwort.", "اختر خيارًا أولًا."},
}

func chatcmd003Text(m Model, key string) string {
	copy := chatcmd003Copy[key]
	return chatbug039Text(key, copy[chatbug039LocaleIndex(m.Locale)], copy[0])
}
