package gensources

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeFixture(t *testing.T, root, rel, body string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestGeneratedOwnershipRejectsMixedTrees is the ARCH-GO-014 primary test.
// It proves both directions of the ownership boundary: generated material
// cannot be placed in schema/, and an unheaded hand edit cannot be placed in
// gen/. A headed model output is accepted and classified as internal output.
func TestGeneratedOwnershipRejectsMixedTrees(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "schema/source.proto", "syntax = \"proto3\";\n")
	writeFixture(t, root, "schema/generated.proto", "// Code generated by protoc-gen-go. DO NOT EDIT.\n")
	writeFixture(t, root, "gen/hand.go", "package hand\n")
	writeFixture(t, root, "gen/go/hcmnext/model/model_generated.go", "// Code generated by tools/gen/modelgen. DO NOT EDIT.\n")

	report, err := ScanWithConfig(root, Config{AuthoredAllowlist: map[string]string{}})
	if err != nil {
		t.Fatal(err)
	}
	if report.Count(Authored) != 2 {
		t.Fatalf("authored count = %d, want 2", report.Count(Authored))
	}
	if report.Count(WireGenerated) != 1 {
		t.Fatalf("wire-generated count = %d, want 1", report.Count(WireGenerated))
	}
	if report.Count(InternalGenerated) != 1 {
		t.Fatalf("internal-generated count = %d, want 1", report.Count(InternalGenerated))
	}
	if !hasRule(report.Violations, "generated-header-in-authored-root") || !hasRule(report.Violations, "hand-edit-in-generated-root") {
		t.Fatalf("violations = %v, want both mixed-tree rules", report.Violations)
	}
}

// TestTodo_ARCH_GO_014_Golden pins the real-tree classification counts. The
// findings are intentionally not ignored: the companion conformance test
// names the pre-existing violations so the lane cannot hide them.
func TestTodo_ARCH_GO_014_Golden(t *testing.T) {
	report, err := Scan(repoRoot(t))
	if err != nil {
		t.Fatal(err)
	}
	if got, want := len(report.Files), 220; got != want {
		t.Fatalf("classified file count = %d, want pinned count %d", got, want)
	}
	if got, want := report.Count(Authored), 166; got != want {
		t.Fatalf("authored count = %d, want pinned count %d", got, want)
	}
	if got, want := report.Count(WireGenerated), 33; got != want {
		t.Fatalf("wire-generated count = %d, want pinned count %d", got, want)
	}
	if got, want := report.Count(InternalGenerated), 21; got != want {
		t.Fatalf("internal-generated count = %d, want pinned count %d", got, want)
	}
	t.Logf("classification counts: AUTHORED=%d WIRE_GENERATED=%d INTERNAL_GENERATED=%d violations=%d", report.Count(Authored), report.Count(WireGenerated), report.Count(InternalGenerated), len(report.Violations))
}

// TestTodo_ARCH_GO_014_Fault proves a one-byte edit to the checked-in model
// output is visible to the in-memory generator drift check.
func TestTodo_ARCH_GO_014_Fault(t *testing.T) {
	root := repoRoot(t)
	path := filepath.Join(root, filepath.FromSlash("gen/go/hcmnext/model/model_generated.go"))
	original, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	tempRoot := t.TempDir()
	writeFixture(t, tempRoot, "gen/go/hcmnext/model/model_generated.go", string(append(original, '\n')))
	report, err := Scan(tempRoot)
	if err != nil {
		t.Fatal(err)
	}
	if !hasRule(report.Violations, "generated-drift") {
		t.Fatalf("violations = %v, want generated-drift", report.Violations)
	}
}

// TestTodo_ARCH_GO_014_Conformance ensures every discovered file has one of
// the three explicit ownership classes and that findings are deterministic.
func TestTodo_ARCH_GO_014_Conformance(t *testing.T) {
	report, err := Scan(repoRoot(t))
	if err != nil {
		t.Fatal(err)
	}
	for _, file := range report.Files {
		if file.Path == "" || (file.Classification != Authored && file.Classification != WireGenerated && file.Classification != InternalGenerated) {
			t.Fatalf("invalid classification record: %+v", file)
		}
	}
	for i := 1; i < len(report.Violations); i++ {
		if report.Violations[i-1].Error() > report.Violations[i].Error() {
			t.Fatalf("findings are not deterministic: %v", report.Violations)
		}
	}
}

// TestDefinitionTreeRejectsHardcodedOrMisownedConfiguration is the ARCH-GO-015
// primary test. It requires an owner for authored definitions, rejects a Go
// file below definitions, and requires generated_by on generated definitions.
func TestDefinitionTreeRejectsHardcodedOrMisownedConfiguration(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "definitions/owned/source.yaml", "version: 1\n")
	writeFixture(t, root, "definitions/unowned/source.yaml", "version: 1\n")
	writeFixture(t, root, "definitions/owned/generated.yaml", "# Generated by tools/gen/example. DO NOT EDIT.\n")
	writeFixture(t, root, "definitions/owned/illegal.go", "package illegal\n")

	report, err := ScanWithConfig(root, Config{AuthoredAllowlist: map[string]string{"definitions/owned/": "owner"}})
	if err != nil {
		t.Fatal(err)
	}
	for _, rule := range []string{"definition-not-in-authored-allowlist", "generated-definition-missing-generated_by", "generated-definition-missing-drift-test", "go-under-definitions"} {
		if !hasRule(report.Violations, rule) {
			t.Fatalf("violations = %v, want %s", report.Violations, rule)
		}
	}
}

// TestTodo_ARCH_GO_015_Property checks that an authored definition cannot
// acquire generator semantics merely by being moved under a generated path.
func TestTodo_ARCH_GO_015_Property(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "definitions/authored/source.yaml", "generated_by: tools/gen/not-a-real-generator\n")
	report, err := ScanWithConfig(root, Config{AuthoredAllowlist: map[string]string{"definitions/authored/": "owner"}})
	if err != nil {
		t.Fatal(err)
	}
	if !hasRule(report.Violations, "generated-definition-missing-drift-test") {
		t.Fatalf("violations = %v, want missing drift test", report.Violations)
	}
}

// TestTodo_ARCH_GO_015_Golden pins the real definition-file denominator and
// verifies that the current legacy generatedby spelling is reported rather
// than silently accepted as the new definitions contract.
func TestTodo_ARCH_GO_015_Golden(t *testing.T) {
	report, err := Scan(repoRoot(t))
	if err != nil {
		t.Fatal(err)
	}
	var definitions int
	for _, file := range report.Files {
		if strings.HasPrefix(file.Path, "definitions/") && (strings.HasSuffix(file.Path, ".yaml") || strings.HasSuffix(file.Path, ".json")) {
			definitions++
		}
	}
	if definitions != 118 {
		t.Fatalf("definitions YAML/JSON count = %d, want pinned count 118", definitions)
	}
	if !hasRule(report.Violations, "generated-definition-missing-generated_by") {
		t.Fatal("real tree no longer reports the legacy generatedby definitions that need migration")
	}
}

// TestTodo_ARCH_GO_015_Fault rejects a generated definition whose declared
// generator package has no drift test.
func TestTodo_ARCH_GO_015_Fault(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "definitions/model/output.yaml", "generated_by: tools/gen/missing\n")
	report, err := ScanWithConfig(root, Config{})
	if err != nil {
		t.Fatal(err)
	}
	if !hasRule(report.Violations, "generated-definition-missing-drift-test") {
		t.Fatalf("violations = %v, want missing drift test", report.Violations)
	}
}

// TestTodo_ARCH_GO_015_Security rejects executable content in definitions.
func TestTodo_ARCH_GO_015_Security(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "definitions/security/escape.go", "package escape\n")
	report, err := ScanWithConfig(root, Config{})
	if err != nil {
		t.Fatal(err)
	}
	if !hasRule(report.Violations, "go-under-definitions") {
		t.Fatalf("violations = %v, want go-under-definitions", report.Violations)
	}
}

// TestTodo_ARCH_GO_015_Conformance covers the real tree without changing it:
// all current definitions are classified and every authored row resolves to
// either an explicit owner or an explicit generated-header finding.
func TestTodo_ARCH_GO_015_Conformance(t *testing.T) {
	report, err := Scan(repoRoot(t))
	if err != nil {
		t.Fatal(err)
	}
	for _, file := range report.Files {
		if strings.HasPrefix(file.Path, "definitions/") && (strings.HasSuffix(file.Path, ".yaml") || strings.HasSuffix(file.Path, ".json")) && file.Classification == Authored && file.Owner == "" {
			t.Fatalf("definition has no owner: %+v", file)
		}
	}
}

func hasRule(violations []Violation, rule string) bool {
	for _, violation := range violations {
		if violation.Rule == rule {
			return true
		}
	}
	return false
}

func repoRoot(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root, err := findRoot(wd)
	if err != nil {
		t.Fatal(err)
	}
	return root
}

func findRoot(dir string) (string, error) {
	for {
		if info, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil && !info.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", os.ErrNotExist
		}
		dir = parent
	}
}
