package gensources

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/monstercameron/human-capital-management-suite/tools/gen/schemaflux/drift"
)

// TestTodo_REV_101_08 proves unheaded authored files are rejected from the
// generator-owned tree, while generated files remain classifiable.
func TestTodo_REV_101_08(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "gen/wire/adapter.go", "package wire\n")
	writeFixture(t, root, "gen/go/example/api.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n")
	writeFixture(t, root, "tools/gen/schemaflux/generated/models_generated.go", "package generated\n")
	report, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	if !hasRule(report.Violations, "hand-edit-in-generated-root") {
		t.Fatalf("violations = %v, want hand-edit-in-generated-root", report.Violations)
	}
	if !hasViolationPath(report.Violations, "tools/gen/schemaflux/generated/models_generated.go", "hand-edit-in-generated-root") {
		t.Fatalf("violations = %v, want headerless moved generator output rejected", report.Violations)
	}
	for _, file := range report.Files {
		if strings.HasPrefix(file.Path, "gen/go/") && file.Classification != WireGenerated {
			t.Fatalf("generated fixture classification = %s, want %s", file.Classification, WireGenerated)
		}
	}

	indexRoot := t.TempDir()
	for path, body := range map[string]string{
		"worker.exe": "binary fixture",
		"internal/generated/schemaflux/models_generated.go":           "// Code generated.\n",
		"internal/humanwork/workspace/assets/journey.wasm.gz":         "compressed bundle",
		"internal/humanwork/workspace/assets/person-hc-001-small.jpg": "persona image",
		"internal/humanwork/workspace/assets/harborcare-logo.svg":     "approved static brand art",
	} {
		writeFixture(t, indexRoot, path, body)
	}
	runGit(t, indexRoot, "init", "-q")
	runGit(t, indexRoot, "add", "--", "worker.exe", "internal/generated/schemaflux/models_generated.go", "internal/humanwork/workspace/assets/journey.wasm.gz", "internal/humanwork/workspace/assets/person-hc-001-small.jpg", "internal/humanwork/workspace/assets/harborcare-logo.svg")
	indexValue, hadIndex := os.LookupEnv("GIT_INDEX_FILE")
	if err := os.Unsetenv("GIT_INDEX_FILE"); err != nil {
		t.Fatal(err)
	}
	violations, err := CheckTrackedArtifacts(indexRoot)
	if hadIndex {
		_ = os.Setenv("GIT_INDEX_FILE", indexValue)
	}
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"worker.exe": "committed-build-artifact",
		"internal/generated/schemaflux/models_generated.go":           "generated-tool-output-in-runtime-root",
		"internal/humanwork/workspace/assets/journey.wasm.gz":         "committed-build-artifact",
		"internal/humanwork/workspace/assets/person-hc-001-small.jpg": "committed-demo-media",
	}
	for _, violation := range violations {
		if rule, ok := want[violation.Path]; !ok || rule != violation.Rule {
			t.Errorf("unexpected tracked artifact finding: %+v", violation)
		} else {
			delete(want, violation.Path)
		}
	}
	if len(want) > 0 {
		t.Errorf("missing expected tracked artifact findings: %v", want)
	}
}

func hasViolationPath(violations []Violation, path, rule string) bool {
	for _, violation := range violations {
		if violation.Path == path && violation.Rule == rule {
			return true
		}
	}
	return false
}

// TestTodo_REV_101_08_Golden pins the generated SchemaFlux package to the
// byte-for-byte output of its current source compiler.
func TestTodo_REV_101_08_Golden(t *testing.T) {
	root := repoRoot(t)
	report := drift.Check(drift.Config{
		Root:          root,
		GeneratedPath: "tools/gen/schemaflux/generated/models_generated.go",
	})
	if !report.Clean() {
		t.Fatalf("generated model drift: %+v", report.Findings)
	}
}

// TestTodo_REV_101_08_Integration checks the actual Git index. The policy
// must catch artifacts even after .gitignore has been updated because ignore
// rules do not remove already tracked paths.
func TestTodo_REV_101_08_Integration(t *testing.T) {
	root := repoRoot(t)
	violations, err := CheckTrackedArtifacts(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(violations) != 0 {
		var paths []string
		for _, violation := range violations {
			paths = append(paths, violation.Error())
		}
		t.Fatalf("tracked build outputs or demo persona assets remain:\n%s", strings.Join(paths, "\n"))
	}

	// Keep the real generated-root header check in this integration matrix too;
	// the synthetic fixture above proves its failure mode.
	report, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	for _, violation := range report.Violations {
		if strings.HasPrefix(violation.Path, "gen/") && violation.Rule == "hand-edit-in-generated-root" {
			t.Errorf("generated-tree violation remains: %s", violation)
		}
	}

	// Ensure this test's Git-root assumption is explicit and that the inventory
	// operation cannot silently resolve against a neighboring checkout.
	if _, err := os.Stat(filepath.Join(root, ".git")); err != nil {
		t.Fatalf("repository root has no .git entry: %v", err)
	}
}

func runGit(t *testing.T, root string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", root}, args...)...)
	// Synthetic repository operations must not inherit a caller's alternate
	// index; the Integration test uses one to model the post-removal index.
	cmd.Env = make([]string, 0, len(os.Environ()))
	for _, variable := range os.Environ() {
		if !strings.HasPrefix(variable, "GIT_INDEX_FILE=") {
			cmd.Env = append(cmd.Env, variable)
		}
	}
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, output)
	}
}
