package productui

// Keeping this small surface's copy together prevents translated labels from
// becoming policy values. Commands always carry canonical action identifiers.
func agentControlsText(locale LocaleContext, key string) string {
	copy := map[string][3]string{
		"denied":                      {"Only the agent's owner or steward can pause or stop it. Ask a workspace administrator to grant access.", "Nur Eigentümer oder Verantwortliche des Agenten können ihn pausieren oder stoppen. Bitten Sie die Arbeitsbereich-Administration um Zugriff.", "يمكن فقط لمالك الوكيل أو المسؤول عنه إيقافه مؤقتًا أو إنهاؤه. اطلب من مسؤول مساحة العمل منحك صلاحية الوصول."},
		"denied_owner":                {"Only the agent's owner or steward can pause or stop it. Owner: {owner}.", "Nur Eigentümer oder Verantwortliche des Agenten können ihn pausieren oder stoppen. Eigentümer: {owner}.", "يمكن فقط لمالك الوكيل أو المسؤول عنه إيقافه مؤقتًا أو إنهاؤه. المالك: {owner}."},
		"title":                       {"Activity", "Aktivität", "النشاط"},
		"region_help":                 {"See what is running, pause or resume a task, or cancel it. Pause an agent to prevent new answers.", "Sehen Sie, was läuft. Pausieren Sie eine Aufgabe, setzen Sie sie fort oder brechen Sie sie ab. Pausieren Sie den Agenten, um neue Antworten zu verhindern.", "اطّلع على المهام الجارية وأوقف مهمة مؤقتًا أو استأنفها أو ألغها. أوقف الوكيل مؤقتًا لمنع إجابات جديدة."},
		"loading":                     {"Loading authorized controls…", "Berechtigte Aktionen werden geladen…", "جارٍ تحميل الإجراءات المصرح بها…"},
		"refresh":                     {"Refresh running agents", "Laufende Agenten aktualisieren", "تحديث الوكلاء قيد التشغيل"},
		"refresh_help":                {"Reload current states and available actions.", "Aktuelle Status und verfügbare Aktionen neu laden.", "أعد تحميل الحالات الحالية والإجراءات المتاحة."},
		"invalid":                     {"Enter a valid nonnegative whole number.", "Geben Sie eine gültige nichtnegative Ganzzahl ein.", "أدخل عددًا صحيحًا صالحًا غير سالب."},
		"misfire_skip":                {"Skip missed occurrences", "Verpasste Termine überspringen", "تخطي المواعيد الفائتة"},
		"misfire_catch_up_once":       {"Catch up once", "Einmal nachholen", "تعويض مرة واحدة"},
		"misfire_review":              {"Require review", "Prüfung erforderlich", "طلب المراجعة"},
		"overlap_skip":                {"Skip overlapping run", "Überlappende Ausführung überspringen", "تخطي التشغيل المتداخل"},
		"overlap_queue":               {"Queue overlapping run", "Überlappende Ausführung einreihen", "إدراج التشغيل المتداخل في الانتظار"},
		"overlap_refuse":              {"Refuse overlap", "Überlappung ablehnen", "رفض التداخل"},
		"dst_reject":                  {"Refuse ambiguous time", "Mehrdeutige Zeit ablehnen", "رفض الوقت الغامض"},
		"dst_earlier":                 {"Use earlier offset", "Früheren Versatz verwenden", "استخدام الإزاحة الأسبق"},
		"dst_later":                   {"Use later offset", "Späteren Versatz verwenden", "استخدام الإزاحة اللاحقة"},
		"unavailable":                 {"Couldn't load running agents.", "Laufende Agenten konnten nicht geladen werden.", "تعذر تحميل الوكلاء قيد التشغيل."},
		"unavailable_cause":           {"The agent service is unavailable right now.", "Der Agentendienst ist derzeit nicht verfügbar.", "خدمة الوكلاء غير متاحة الآن."},
		"timed_out_cause":             {"The agent service took too long to respond.", "Der Agentendienst hat zu lange für eine Antwort gebraucht.", "استغرقت خدمة الوكلاء وقتًا طويلاً للاستجابة."},
		"access_denied_cause":         {"You do not have permission to load these running agents.", "Sie haben keine Berechtigung, diese laufenden Agenten zu laden.", "ليس لديك الإذن لتحميل هؤلاء الوكلاء قيد التشغيل."},
		"unavailable_fallback_before": {"To pause an agent now, open ", "Um einen Agenten jetzt zu pausieren, öffnen Sie ", "لإيقاف وكيل مؤقتًا الآن، افتح "},
		"unavailable_fallback_link":   {"Setup", "Einrichtung", "الإعداد"},
		"unavailable_fallback_after":  {".", ".", "."},
		"unavailable_help":            {"If this keeps happening, ask your platform administrator.", "Wenn das weiter passiert, wenden Sie sich an Ihre Plattformadministration.", "إذا استمر هذا، فاطلب المساعدة من مسؤول المنصة."},
		"unavailable_contact":         {"If this keeps happening, ask {contact}.", "Wenn das weiter passiert, wenden Sie sich an {contact}.", "إذا استمر هذا، فاطلب المساعدة من {contact}."},
		"retry":                       {"Retry", "Erneut versuchen", "إعادة المحاولة"},
		"updated":                     {"Updated {time}", "Aktualisiert {time}", "تم التحديث {time}"},
		"empty":                       {"No agents are running right now.", "Derzeit werden keine Agenten ausgeführt.", "لا توجد وكلاء قيد التشغيل الآن."},
		"empty_help":                  {"Recent finished runs are listed below. You can pause an agent above to prevent new answers.", "Kürzlich beendete Ausführungen stehen unten. Pausieren Sie oben einen Agenten, um neue Antworten zu verhindern.", "تظهر عمليات التشغيل المنتهية حديثًا أدناه. يمكنك إيقاف وكيل مؤقتًا أعلاه لمنع إجابات جديدة."},
		"recent":                      {"Recent finished runs", "Kürzlich beendete Ausführungen", "عمليات التشغيل المنتهية حديثًا"},
		"recent_empty":                {"No recent finished runs.", "Keine kürzlich beendeten Ausführungen.", "لا توجد عمليات تشغيل منتهية حديثًا."},
		"who_asked":                   {"Who asked", "Angefragt von", "من طلب"},
		"where":                       {"Where", "Ort", "المكان"},
		"started":                     {"Started", "Gestartet", "بدأ"},
		"duration":                    {"Duration", "Dauer", "المدة"},
		"outcome":                     {"Outcome", "Ergebnis", "النتيجة"},
		"workspace_member":            {"A workspace member", "Ein Mitglied des Arbeitsbereichs", "عضو في مساحة العمل"},
		"hidden_conversation":         {"A conversation you cannot see", "Eine Unterhaltung, die Sie nicht sehen können", "محادثة لا يمكنك رؤيتها"},
		"failure_reason":              {"What happened", "Was passiert ist", "ما الذي حدث"},
		"suggested_action":            {"What to do", "Nächster Schritt", "ما يجب فعله"},
		"failure_context_unavailable": {"The agent could not load the information it needed.", "Der Agent konnte die benötigten Informationen nicht laden.", "تعذر على الوكيل تحميل المعلومات التي يحتاج إليها."},
		"action_context_unavailable":  {"Check the agent's document and conversation access, then try again.", "Prüfen Sie den Dokument- und Unterhaltungszugriff des Agenten und versuchen Sie es erneut.", "تحقق من وصول الوكيل إلى المستندات والمحادثة، ثم حاول مرة أخرى."},
		"failure_model_unavailable":   {"The agent could not answer because the service it needed was unavailable.", "Der Agent konnte nicht antworten, weil der benötigte Dienst nicht verfügbar war.", "تعذر على الوكيل الإجابة لأن الخدمة المطلوبة لم تكن متاحة."},
		"action_model_unavailable":    {"Try again; if it keeps failing, ask the technical contact to check the service connection.", "Versuchen Sie es erneut; wenn der Fehler bleibt, lassen Sie die Verbindung zum Dienst vom technischen Kontakt prüfen.", "حاول مرة أخرى؛ وإذا استمر الفشل، فاطلب من جهة الاتصال التقنية التحقق من اتصال الخدمة."},
		"failure_model_incomplete":    {"The agent could not complete a usable answer.", "Der Agent konnte keine vollständige nutzbare Antwort liefern.", "لم يتمكن الوكيل من إكمال إجابة قابلة للاستخدام."},
		"action_model_incomplete":     {"Review the agent's instructions and try the request again.", "Prüfen Sie die Anweisungen des Agenten und versuchen Sie die Anfrage erneut.", "راجع تعليمات الوكيل وحاول تنفيذ الطلب مرة أخرى."},
		"failure_tool":                {"A service the agent needed did not complete its work.", "Ein benötigter Dienst konnte seine Arbeit nicht abschließen.", "لم تتمكن خدمة احتاج إليها الوكيل من إكمال عملها."},
		"action_tool":                 {"Check the connected service and the agent's permission, then try again.", "Prüfen Sie den verbundenen Dienst und die Berechtigung des Agenten und versuchen Sie es erneut.", "تحقق من الخدمة المتصلة وصلاحية الوكيل، ثم حاول مرة أخرى."},
		"failure_output":              {"The answer did not pass the workspace's safety checks.", "Die Antwort hat die Sicherheitsprüfungen des Arbeitsbereichs nicht bestanden.", "لم تجتز الإجابة فحوصات أمان مساحة العمل."},
		"action_output":               {"Review the agent's instructions and workspace policy before trying again.", "Prüfen Sie die Anweisungen des Agenten und die Arbeitsbereichsrichtlinie, bevor Sie es erneut versuchen.", "راجع تعليمات الوكيل وسياسة مساحة العمل قبل المحاولة مرة أخرى."},
		"failure_delivery":            {"The answer was ready but could not be delivered.", "Die Antwort war fertig, konnte aber nicht zugestellt werden.", "كانت الإجابة جاهزة، ولكن تعذر تسليمها."},
		"action_delivery":             {"Check that the conversation is available and try again.", "Prüfen Sie, ob die Unterhaltung verfügbar ist, und versuchen Sie es erneut.", "تحقق من أن المحادثة متاحة، ثم حاول مرة أخرى."},
		"failure_out_of_scope":        {"The request was outside what this agent is allowed to do.", "Die Anfrage lag außerhalb dessen, was dieser Agent tun darf.", "كان الطلب خارج نطاق ما يُسمح لهذا الوكيل بفعله."},
		"action_out_of_scope":         {"Use an agent whose purpose covers this request, or update this agent through review.", "Verwenden Sie einen Agenten, dessen Zweck diese Anfrage abdeckt, oder aktualisieren Sie diesen Agenten nach einer Prüfung.", "استخدم وكيلاً يغطي غرضه هذا الطلب، أو حدّث هذا الوكيل من خلال المراجعة."},
		"schedules_empty":             {"No agent schedules are available.", "Es sind keine Agentenzeitpläne verfügbar.", "لا تتوفر جداول للوكلاء."},
		"memory_empty":                {"No retained agent records are available.", "Es sind keine aufbewahrten Agentendatensätze verfügbar.", "لا تتوفر سجلات وكلاء محفوظة."},
		"schedules":                   {"Schedules", "Zeitpläne", "الجداول"},
		"runs":                        {"Runs and incidents", "Ausführungen und Vorfälle", "التشغيل والحوادث"},
		"memory":                      {"Derived memory and retention", "Abgeleiteter Speicher und Aufbewahrung", "الذاكرة المشتقة والاحتفاظ"},
		"state":                       {"Status", "Status", "الحالة"},
		"since":                       {"Since", "Seit", "منذ"},
		"state_active":                {"Active", "Aktiv", "نشط"},
		"state_draft":                 {"Draft", "Entwurf", "مسودة"},
		"state_paused":                {"Paused", "Pausiert", "متوقف مؤقتًا"},
		"state_retired":               {"Retired", "Stillgelegt", "متوقف نهائيًا"},
		"state_running":               {"Running", "Wird ausgeführt", "قيد التشغيل"},
		"state_waiting":               {"Waiting", "Wartend", "في الانتظار"},
		"state_completed":             {"Completed", "Abgeschlossen", "مكتمل"},
		"state_failed":                {"Failed", "Fehlgeschlagen", "فشل"},
		"state_cancelled":             {"Cancelled", "Abgebrochen", "ملغى"},
		"state_expired":               {"Expired", "Abgelaufen", "منتهي الصلاحية"},
		"state_stopped_responding":    {"Stopped responding", "Antwortet nicht mehr", "توقف عن الاستجابة"},
		"version":                     {"Pinned agent version", "Feste Agentenversion", "إصدار الوكيل المثبت"},
		"zone":                        {"Timezone", "Zeitzone", "المنطقة الزمنية"},
		"calendar":                    {"Calendar", "Kalender", "التقويم"},
		"destination":                 {"Approved destination", "Genehmigtes Ziel", "الوجهة المعتمدة"},
		"misfire":                     {"Missed occurrence policy", "Regel für verpasste Termine", "سياسة المواعيد الفائتة"},
		"overlap":                     {"Overlap policy", "Überschneidungsregel", "سياسة التداخل"},
		"budget":                      {"Budget", "Budget", "الميزانية"},
		"occurrences":                 {"Occurrence preview", "Terminvorschau", "معاينة المواعيد"},
		"occurrence":                  {"Occurrence to skip", "Zu überspringender Termin", "الموعد المراد تخطيه"},
		"max_cost":                    {"Maximum cost (microunits)", "Maximale Kosten (Mikroeinheiten)", "التكلفة القصوى (وحدات دقيقة)"},
		"max_input":                   {"Maximum input tokens", "Maximale Eingabetoken", "الحد الأقصى لرموز الإدخال"},
		"max_output":                  {"Maximum output tokens", "Maximale Ausgabetoken", "الحد الأقصى لرموز الإخراج"},
		"installation":                {"Conversation where added", "Unterhaltung, der der Agent hinzugefügt wurde", "المحادثة التي أُضيف إليها الوكيل"},
		"cause":                       {"Run cause", "Auslöser", "سبب التشغيل"},
		"lag":                         {"Queue lag", "Wartezeit", "تأخير قائمة الانتظار"},
		"spend":                       {"Spend", "Ausgaben", "الإنفاق"},
		"failure":                     {"Failure", "Fehler", "الفشل"},
		"denials":                     {"Tool denials", "Abgelehnte Werkzeugaufrufe", "رفض الأدوات"},
		"citations":                   {"Citations", "Quellen", "المراجع"},
		"evals":                       {"Evaluations", "Bewertungen", "التقييمات"},
		"incident":                    {"Incident reference", "Vorfallsreferenz", "مرجع الحادث"},
		"source":                      {"Source reference", "Quellenreferenz", "مرجع المصدر"},
		"audience":                    {"Audience", "Zielgruppe", "الجمهور"},
		"purpose":                     {"Purpose", "Zweck", "الغرض"},
		"class":                       {"Classification", "Klassifizierung", "التصنيف"},
		"expires":                     {"Retention expiry", "Aufbewahrungsende", "انتهاء الاحتفاظ"},
		"held":                        {"Legal hold", "Aufbewahrungssperre", "الحفظ القانوني"},
		"technical":                   {"Run details", "Ausführungsdetails", "تفاصيل التشغيل"},
		"record_id":                   {"Record identifier", "Datensatzkennung", "معرّف السجل"},
		"scheduled_agent":             {"Scheduled agent", "Geplanter Agent", "وكيل مجدول"},
		"agent_run":                   {"Agent run", "Agentenausführung", "تشغيل الوكيل"},
		"memory_record":               {"Memory record", "Speicherdatensatz", "سجل الذاكرة"},
		"yes":                         {"Yes", "Ja", "نعم"}, "no": {"No", "Nein", "لا"},
		"publish":       {"Publish", "Veröffentlichen", "نشر"},
		"pause":         {"Pause", "Pausieren", "إيقاف مؤقت"},
		"skip":          {"Skip next occurrence", "Nächsten Termin überspringen", "تخطي الموعد التالي"},
		"resume":        {"Resume", "Fortsetzen", "استئناف"},
		"stop":          {"Stop", "Stoppen", "إنهاء"},
		"dry_run":       {"Dry run", "Probelauf", "تشغيل تجريبي"},
		"retire":        {"Retire", "Stilllegen", "إيقاف نهائي"},
		"quarantine":    {"Quarantine", "Isolieren", "عزل"},
		"export":        {"Export authorized records", "Berechtigte Datensätze exportieren", "تصدير السجلات المصرح بها"},
		"delete":        {"Delete derived item", "Abgeleiteten Eintrag löschen", "حذف العنصر المشتق"},
		"revoke":        {"Revoke source", "Quelle widerrufen", "إلغاء المصدر"},
		"hold":          {"Apply legal hold", "Aufbewahrungssperre setzen", "تطبيق الحفظ القانوني"},
		"id":            {"Schedule ID", "Zeitplan-ID", "معرف الجدول"},
		"recurrence":    {"Recurrence rule", "Wiederholungsregel", "قاعدة التكرار"},
		"revision":      {"Expected revision (0 for new)", "Erwartete Revision (0 für neu)", "المراجعة المتوقعة (0 للجديد)"},
		"dst":           {"DST ambiguity policy", "Regel bei Zeitumstellung", "سياسة غموض التوقيت الصيفي"},
		"draft":         {"Save schedule draft", "Zeitplanentwurf speichern", "حفظ مسودة الجدول"},
		"preview":       {"Preview occurrences", "Termine anzeigen", "معاينة المواعيد"},
		"draft_help":    {"Preview uses the declared timezone and DST policy. Publication requires an authorized reviewer.", "Die Vorschau nutzt Zeitzone und Sommerzeitregel. Die Veröffentlichung erfordert eine berechtigte Prüfung.", "تستخدم المعاينة المنطقة الزمنية وسياسة التوقيت الصيفي. يتطلب النشر مراجعًا مخولًا."},
		"working":       {"Applying authorized action…", "Berechtigte Aktion wird ausgeführt…", "جارٍ تطبيق الإجراء المصرح به…"},
		"working_short": {"Working…", "Wird ausgeführt…", "جارٍ التنفيذ…"},
		"done":          {"Agent states and available actions are up to date.", "Agentenstatus und verfügbare Aktionen sind aktuell.", "حالات الوكلاء والإجراءات المتاحة محدثة."},
		"action_done":   {"The requested agent action was completed. Current states and actions are shown below.", "Die angeforderte Agentenaktion wurde abgeschlossen. Aktuelle Status und Aktionen werden unten angezeigt.", "اكتمل إجراء الوكيل المطلوب. تظهر الحالات والإجراءات الحالية أدناه."},
		"error":         {"Action refused. Refresh records and review your access before retrying.", "Aktion abgelehnt. Aktualisieren Sie die Daten und prüfen Sie Ihren Zugriff.", "تم رفض الإجراء. حدّث السجلات وراجع صلاحياتك قبل إعادة المحاولة."},
		"conflict":      {"The record changed. Refresh before retrying.", "Der Datensatz wurde geändert. Aktualisieren Sie vor einem erneuten Versuch.", "تغير السجل. حدّثه قبل إعادة المحاولة."},
		"reason":        {"Reason for the action", "Grund für die Aktion", "سبب الإجراء"},
		"reason_help":   {"Add context for the audit record before changing a running agent.", "Fügen Sie vor einer Änderung am laufenden Agenten Kontext für den Prüfdatensatz hinzu.", "أضف سياقًا إلى سجل التدقيق قبل تغيير وكيل قيد التشغيل."},
		"action_help":   {"This action is checked against your current owner permission before it runs.", "Diese Aktion wird vor der Ausführung anhand Ihrer aktuellen Eigentümerberechtigung geprüft.", "يتم التحقق من هذا الإجراء مقابل صلاحية المالك الحالية قبل تنفيذه."},
	}
	index := 0
	if locale.Resolved == "de-DE" {
		index = 1
	} else if locale.Resolved == "ar" {
		index = 2
	}
	if values, ok := copy[key]; ok {
		return values[index]
	}
	return ""
}
