package productui

import (
	"github.com/monstercameron/human-capital-management-suite/internal/experience/localize"
	"github.com/monstercameron/human-capital-management-suite/internal/humanwork/chatui"
)

// chatMessages registers the chat workspace's reviewed English copy in the
// product catalog. chatui owns the source strings so its own tests and the
// script-free shell render the same words the browser client does.
func chatMessages() map[string]localize.Message {
	out := map[string]localize.Message{}
	for key, text := range chatui.EnglishCopy() {
		out[key] = localize.Message{Text: text}
	}
	return out
}

// chatTranslations supplies the reviewed German and Arabic copy for every
// chat key. Person names, channel names and message bodies stay data.
func chatTranslations(locale string) map[string]string {
	switch locale {
	case "de-DE":
		return map[string]string{
			chatui.KeyPollTitle: "Kanalumfrage", chatui.KeyPollQuestion: "Frage", chatui.KeyPollOptions: "Antworten, eine pro Zeile", chatui.KeyPollOptionsHint: "Fügen Sie 2 bis 10 Antworten ein, eine pro Zeile.", chatui.KeyPollCreate: "Umfrage erstellen", chatui.KeyPollVote: "Abstimmen", chatui.KeyPollChangeVote: "Stimme ändern", chatui.KeyPollResults: "Umfrageergebnisse", chatui.KeyPollVoteOne: "{n} Stimme", chatui.KeyPollVotes: "{n} Stimmen", chatui.KeyPollVoted: "Ihre Auswahl", chatui.KeyPollLoading: "Umfrage wird geladen …", chatui.KeyPollError: "Die Umfrage konnte nicht geladen oder gespeichert werden. Aktualisieren Sie die Seite und versuchen Sie es erneut.", chatui.KeyPollNoPoll: "Noch keine Umfrage",
			chatui.KeyChannelManager: "Kanalmanager", chatui.KeyChannelMember: "Kanalmitglied",
			chatui.KeyTeamWidget: "Kanalteam", chatui.KeyTeamPurpose: "Zweck", chatui.KeyTeamRole: "Kanalrollenbezeichnung", chatui.KeyTeamNote: "Kanalbezeichnungen sind informell und ändern keine Organisationsrollen.", chatui.KeyProjectWidget: "Kanalprojekt", chatui.KeyProjectNote: "Planungsnotizen für diesen Kanal", chatui.KeyProjectTitle: "Projekttitel", chatui.KeyProjectSummary: "Zusammenfassung", chatui.KeyMilestone: "Meilenstein", chatui.KeyMilestoneStatus: "Status", chatui.KeyMilestoneOwner: "Verantwortlich", chatui.KeyMilestoneDue: "Fälligkeitsdatum", chatui.KeyPlanned: "Geplant", chatui.KeyInProgress: "In Arbeit", chatui.KeyBlocked: "Blockiert", chatui.KeyDone: "Erledigt", chatui.KeyWidgetSave: "Speichern", chatui.KeyWidgetAdd: "Meilenstein hinzufügen", chatui.KeyWidgetDelete: "Meilenstein löschen", chatui.KeyWidgetPin: "Widget anheften", chatui.KeyWidgetUnpin: "Widget lösen", chatui.KeyWidgetLoading: "Kanal-Widgets werden geladen …", chatui.KeyWidgetError: "Kanal-Widgets konnten nicht geladen oder gespeichert werden. Aktualisieren und erneut versuchen.", chatui.KeyWidgetEmpty: "Noch keine Meilensteine",
			chatui.KeyPinCopyGuestUnavailable: "Verweise aus einem Gastkanal können nicht kopiert werden",
			chatui.KeyTodoSaveError:           "Die Aufgabenliste konnte nicht gespeichert werden. Aktualisieren Sie sie und versuchen Sie es erneut.",
			chatui.KeyTodoNoOpen:              "Keine offenen Aufgaben",
			chatui.KeyTodoCompletedBy:         "Erledigt von {name}", chatui.KeyTodoMemberFallback: "einem Kanalmitglied",
			chatui.KeyTodoModeEveryone: "Alle", chatui.KeyTodoModeMe: "Ich", chatui.KeyTodoModeSelected: "Ich und Ausgewählte", chatui.KeyTodoModeLabel: "Wer diese Aufgabe erledigen oder erneut öffnen darf", chatui.KeyTodoAddMember: "Mitglied hinzufügen", chatui.KeyTodoRemoveMember: "{name} entfernen", chatui.KeyTodoOnlyCreator: "Nur die Person, die die Aufgabe erstellt hat, darf sie erledigen oder erneut öffnen", chatui.KeyTodoOnlySelected: "Nur die Person, die die Aufgabe erstellt hat, und ausgewählte Mitglieder dürfen sie erledigen oder erneut öffnen", chatui.KeyTodoSelectedMember: "Ausgewähltes Mitglied",
			chatui.KeyPinJump: "Zur Nachricht springen", chatui.KeyPinCopy: "Verweis kopieren", chatui.KeyTodoTitle: "Aufgabenliste", chatui.KeyTodoLoading: "Aufgabenliste wird geladen …", chatui.KeyTodoError: "Die Aufgabenliste konnte nicht geladen werden. Versuchen Sie es erneut.", chatui.KeyTodoEmpty: "Noch keine Aufgaben", chatui.KeyTodoNew: "Neue Aufgabe", chatui.KeyTodoAdd: "Aufgabe hinzufügen", chatui.KeyTodoComplete: "Aufgabe abschließen", chatui.KeyTodoReopen: "Aufgabe erneut öffnen", chatui.KeyTodoDelete: "Aufgabe löschen", chatui.KeyTodoPin: "Aufgabenliste anheften", chatui.KeyTodoUnpin: "Aufgabenliste lösen", chatui.KeyTodoOpen: "Aufgabenliste öffnen", chatui.KeyTodoRemaining: "{n} offen", chatui.KeyTodoAttachPin: "Angeheftete Nachricht verknüpfen", chatui.KeyTodoNoPin: "Keine verknüpfte Nachricht", chatui.KeyTodoSource: "Verknüpfte Nachricht",
			chatui.KeySearchResults: "Suchergebnisse für {query}", chatui.KeySearchChannels: "Kanäle", chatui.KeySearchPeople: "Personen", chatui.KeySearchMessages: "Nachrichten", chatui.KeySearchLoading: "Suche läuft …", chatui.KeySearchCount: "{n} Ergebnisse", chatui.KeySearchCountOne: "1 Ergebnis", chatui.KeySearchError: "Die Suche ist nicht verfügbar. Versuchen Sie es erneut.", chatui.KeySearchNoResults: "Keine Ergebnisse gefunden.", chatui.KeySearchMessageIn: "in {channel}", chatui.KeySearchOpenMessage: "Nachricht von {author} in {channel} öffnen", chatui.KeySearchMore: "Weitere Nachrichten laden", chatui.KeySearchLoadingMore: "Weitere Nachrichten werden geladen …", chatui.KeySearchMoreError: "Weitere Nachrichten konnten nicht geladen werden. Versuchen Sie es erneut.", chatui.KeySearchBrowseChannel: "{channel} durchsuchen und beitreten", chatui.KeySearchChannelUnavailable: "Dieser Kanal ist nicht mehr verfügbar.", chatui.KeySearchMessageUnavailable: "Diese Nachricht ist nicht mehr verfügbar.", chatui.KeySearchMoreChannels: "Weitere Kanäle laden", chatui.KeySearchLoadingMoreChannels: "Weitere Kanäle werden geladen …", chatui.KeySearchMoreChannelsError: "Weitere Kanäle konnten nicht geladen werden. Versuchen Sie es erneut.",
			chatui.KeyPersonDetails: "Personendetails", chatui.KeyClosePerson: "Personendetails schließen", chatui.KeyViewPerson: "Details zu {name} anzeigen", chatui.KeyStartDirectMessage: "Nachricht senden",
			chatui.KeyManager: "Führungskraft", chatui.KeyDepartment: "Abteilung", chatui.KeyJobTitle: "Position", chatui.KeyPhone: "Telefon", chatui.KeyEmail: "E-Mail", chatui.KeyLocation: "Standort", chatui.KeyCompany: "Unternehmen", chatui.KeyBusinessUnit: "Geschäftsbereich", chatui.KeyNotAvailable: "Nicht verfügbar",
			chatui.KeySkip: "Zur Unterhaltung springen", chatui.KeyNav: "Chat-Navigation",
			chatui.KeyRailTitle: "Unterhaltungen", chatui.KeyRailEmpty: "Sie sind noch in keiner Unterhaltung. Durchsuchen Sie die Kanäle oder starten Sie eine.",
			chatui.KeyNewConversation: "Neue Unterhaltung", chatui.KeySearch: "Kanäle, Personen und Nachrichten durchsuchen", chatui.KeySearchPlaceholder: "Suchen",
			chatui.KeySectionChannels: "Kanäle", chatui.KeySectionDirect: "Direktnachrichten",
			chatui.KeyNewSection: "Neue Gruppe", chatui.KeySectionName: "Gruppenname", chatui.KeyRemoveSection: "Gruppe entfernen", chatui.KeyMoveToSection: "Nach {name} verschieben",
			chatui.KeyMoveSectionUp: "Abschnitt nach oben", chatui.KeyMoveSectionDown: "Abschnitt nach unten",
			chatui.KeyBrowse: "Kanäle durchsuchen", chatui.KeyBrowseTitle: "Kanäle durchsuchen", chatui.KeyBrowseEmpty: "Noch keine Kanäle zum Beitreten.",
			chatui.KeyJoin: "Beitreten", chatui.KeyJoined: "Beigetreten",
			chatui.KeyOpenConversations: "Unterhaltungen öffnen", chatui.KeyCloseConversations: "Unterhaltungen schließen", chatui.KeyConversation: "Unterhaltung",
			chatui.KeyKindPublic: "Öffentlicher Kanal", chatui.KeyKindPrivate: "Privater Kanal", chatui.KeyKindDirect: "Direktnachricht", chatui.KeyKindGroup: "Private Gruppe",
			chatui.KeyMemberCount: "{n} Mitglieder", chatui.KeyMemberCountOne: "1 Mitglied", chatui.KeyUnreadCount: "{n} ungelesen", chatui.KeyMentionCount: "{n} Erwähnungen",
			chatui.KeyDetails: "Details zur Unterhaltung", chatui.KeyCloseDetails: "Details schließen", chatui.KeyMembers: "Mitglieder", chatui.KeyRefreshMembers: "Mitglieder aktualisieren",
			chatui.KeyOnline: "Online", chatui.KeyOffline: "Offline",
			chatui.KeyNotifications: "Benachrichtigungen", chatui.KeyNotifyAll: "Alle Nachrichten", chatui.KeyNotifyMentions: "Nur Erwähnungen", chatui.KeyNotifyMute: "Stummgeschaltet",
			chatui.KeyQuietHours: "Ruhezeiten", chatui.KeyQuietHoursOn: "Benachrichtigungen über Nacht pausieren", chatui.KeyQuietTimezone: "Zeitzone", chatui.KeyQuietStart: "Von", chatui.KeyQuietEnd: "Bis",
			chatui.KeyMessagesRegion: "Nachrichten der Unterhaltung", chatui.KeyMessageActions: "Nachrichtenaktionen",
			chatui.KeyLoading: "Unterhaltung wird geladen …", chatui.KeyErrorTitle: "Unterhaltung nicht verfügbar", chatui.KeyRetry: "Erneut versuchen",
			chatui.KeyEmptyTitle: "Beginnen Sie die Unterhaltung", chatui.KeyEmptyBody: "Hier gibt es noch keine Nachrichten. Schreiben Sie die erste, wenn Sie so weit sind.",
			chatui.KeyNoneTitle: "Wählen Sie eine Unterhaltung", chatui.KeyNoneBody: "Wählen Sie links einen Kanal oder eine Direktnachricht, oder starten Sie eine neue Unterhaltung.",
			chatui.KeyNoMessages: "Noch keine Nachrichten", chatui.KeyLoadOlder: "Frühere Nachrichten anzeigen", chatui.KeyLoadNewer: "Neuere Nachrichten anzeigen", chatui.KeyLoadOlderThread: "Frühere Antworten anzeigen", chatui.KeyLoadNewerThread: "Neuere Antworten anzeigen",
			chatui.KeyToday: "Heute", chatui.KeyYesterday: "Gestern", chatui.KeyEdited: "bearbeitet", chatui.KeyPinned: "Angeheftet",
			chatui.KeyReplies: "{n} Antworten", chatui.KeyReactions: "{n} Reaktionen", chatui.KeyRepliesOne: "1 Antwort",
			chatui.KeyCopyConversationAPICurl: "API-cURL kopieren", chatui.KeyCopyConversationAPICurlSuccess: "API-cURL kopiert", chatui.KeyCopyConversationAPICurlFailure: "API-cURL konnte nicht kopiert werden. Prüfen Sie den Zugriff auf die Zwischenablage und versuchen Sie es erneut.",
			chatui.KeyGiphyPicker: "GIF einfügen", chatui.KeyGiphyPickerTitle: "GIF auswählen", chatui.KeyGiphySearch: "GIFs suchen", chatui.KeyGiphyMore: "Weitere GIFs laden", chatui.KeyGiphyUnavailable: "GIFs benötigen einen von einem Administrator konfigurierten GIPHY-Schlüssel", chatui.KeyGiphyLoading: "GIFs werden geladen …", chatui.KeyGiphyLoadError: "GIFs konnten nicht geladen werden.", chatui.KeyGiphyNoResults: "Keine GIFs gefunden.", chatui.KeyGiphyClose: "GIF-Auswahl schließen",
			chatui.KeyNew: "Neu", chatui.KeyJumpNewest: "Zur neuesten Nachricht", chatui.KeyMore: "Weitere Aktionen", chatui.KeyConversationMore: "Weitere Optionen für {name}", chatui.KeyCopyConversationReference: "Name und Link kopieren", chatui.KeyCopyConversationSuccess: "Unterhaltungslink kopiert", chatui.KeyCopyConversationFailure: "Unterhaltungslink konnte nicht kopiert werden. Prüfen Sie den Zugriff auf die Zwischenablage und versuchen Sie es erneut.", chatui.KeyConversationLinkUnavailable: "Unterhaltung nicht verfügbar", chatui.KeyCopyLink: "Link kopieren", chatui.KeyCopyContents: "Nachrichtentext kopieren", chatui.KeyCopyContentsEmpty: "Kein Nachrichtentext zum Kopieren", chatui.KeyCopyContentsSuccess: "Nachrichtentext kopiert", chatui.KeyCopyContentsFailure: "Nachrichtentext konnte nicht kopiert werden. Prüfen Sie den Zugriff auf die Zwischenablage und versuchen Sie es erneut.",
			chatui.KeyShareToChannel: "In Kanal teilen", chatui.KeyShareTitle: "Nachricht in einem Kanal teilen", chatui.KeyShareDestination: "Zielkanal", chatui.KeyShareFilter: "Ihre Kanäle durchsuchen", chatui.KeyShareEmpty: "Keine passenden Kanäle gefunden", chatui.KeyShareLoading: "Ihre Kanäle werden geladen…", chatui.KeyShareDisclosure: "Mitglieder des Zielkanals können diese Nachricht sehen.", chatui.KeyShareAttachments: "Nur der Nachrichtentext wird geteilt. Anhänge sind nicht enthalten.", chatui.KeyShareSubmit: "Teilen", chatui.KeySharePending: "Wird geteilt…", chatui.KeyShareLoadError: "Kanäle konnten nicht geladen werden. Versuchen Sie es erneut.", chatui.KeyShareError: "Nachricht konnte nicht geteilt werden. Prüfen Sie Ihren Zugriff und versuchen Sie es erneut.", chatui.KeyShareSuccess: "Nachricht im Kanal geteilt", chatui.KeyShareUnavailable: "Teilen ist nicht verfügbar. Versuchen Sie es erneut.", chatui.KeyForwardedFrom: "Weitergeleitet von {name}",
			chatui.KeyEmbedTitle: "Verknüpfte Nachricht", chatui.KeyEmbedLoading: "Nachrichtenvorschau wird geladen…", chatui.KeyEmbedUnavailable: "Nachrichtenvorschau nicht verfügbar", chatui.KeyEmbedOpen: "Quellkanal öffnen", chatui.KeyEmbedAttachments: "Anhänge: {count}",
			chatui.KeyPickReaction: "Reaktion wählen", chatui.KeyReactionChip: "{n} haben mit {emoji} reagiert", chatui.KeyReactWith: "Mit {emoji} reagieren",
			chatui.KeyResizeRail: "Unterhaltungsliste in der Breite ändern. Ziehen oder Pfeiltasten verwenden; Pos1 stellt die Standardbreite wieder her.", chatui.KeyResizeSide: "Seitenbereich in der Breite ändern. Ziehen oder Pfeiltasten verwenden; Pos1 stellt die Standardbreite wieder her.",
			chatui.KeyActiveJustNow: "gerade aktiv", chatui.KeyActiveHoursAgo: "vor {n} Std. aktiv", chatui.KeyActiveDaysAgo: "vor {n} Tagen aktiv", chatui.KeyActiveOn: "aktiv am {date}", chatui.KeyNoActivity: "noch keine Nachrichten", chatui.KeyYou: "du", chatui.KeyMemberFilter: "Mitglieder filtern", chatui.KeyThreadIn: "Thread · {name}", chatui.KeyBrowseCount: "{n} Kanäle zum Beitreten",
			chatui.KeyReply: "Im Thread antworten", chatui.KeyReact: "Reaktion hinzufügen", chatui.KeyRemoveReaction: "Eigene Reaktion entfernen",
			chatui.KeyPin: "Nachricht anheften", chatui.KeyUnpin: "Nachricht lösen", chatui.KeyEdit: "Nachricht bearbeiten", chatui.KeyDelete: "Nachricht löschen",
			chatui.KeySaveEdit: "Änderungen speichern", chatui.KeyCancel: "Abbrechen", chatui.KeyClose: "Schließen",
			chatui.KeyThread: "Thread", chatui.KeyThreadRegion: "Thread-Antworten", chatui.KeyThreadEmpty: "Noch keine Antworten. Ihre Antwort eröffnet diesen Thread.", chatui.KeyThreadLoading: "Antworten werden geladen …", chatui.KeyCloseThread: "Thread schließen",
			chatui.KeyFollow: "Folgen", chatui.KeyFollowing: "Folge ich",
			chatui.KeyComposeRegion: "Nachricht senden", chatui.KeyMessage: "Nachricht", chatui.KeyComposePlaceholder: "Nachricht an {name}", chatui.KeyComposeUnselected: "Wählen Sie eine Unterhaltung, um zu schreiben",
			chatui.KeyComposeHint: "Eingabe sendet, Umschalt+Eingabe für eine neue Zeile", chatui.KeyEmojiPicker: "Emoji einfügen", chatui.KeyEmojiPickerTitle: "Emoji auswählen", chatui.KeyEmojiItem: "Emoji {emoji}", chatui.KeyAttach: "Anhang hinzufügen", chatui.KeySend: "Senden",
			chatui.KeyCreateTitle: "Unterhaltung erstellen", chatui.KeyName: "Name", chatui.KeyNamePlaceholder: "Zum Beispiel design-reviews", chatui.KeyKind: "Art der Unterhaltung",
			chatui.KeyMembersOptional: "Mitglieder (optional)", chatui.KeyMembersPlaceholder: "Namen oder IDs, durch Kommas getrennt", chatui.KeyCreate: "Erstellen",
			chatui.KeyRefresh: "Aktualisieren", chatui.KeyOn: "An", chatui.KeyOff: "Aus", chatui.KeyReplyPlaceholder: "Antworten …", chatui.KeyReplySend: "Antworten", chatui.KeyBrowseCreate: "Kanal erstellen",
			chatui.KeyIntroTitle: "Hier beginnt {name}", chatui.KeyIntroPublic: "Alle im Unternehmen können diesen Kanal finden und beitreten. Nachrichten hier sind für alle Mitglieder sichtbar.", chatui.KeyIntroPrivate: "Nur eingeladene Mitglieder sehen diesen Kanal und seine Nachrichten.", chatui.KeyIntroDirect: "Diese Unterhaltung ist privat für die beteiligten Personen.", chatui.KeyDMEmpty: "Noch keine Direktnachrichten", chatui.KeyBrowseFilter: "Kanäle filtern", chatui.KeyAttachmentLoading: "Anhang wird geladen …", chatui.KeyAttachmentUnavailable: "Vorschau nicht verfügbar", chatui.KeyDownloadAttachment: "Herunterladen", chatui.KeyOpenImage: "Bild öffnen", chatui.KeyImageViewer: "Bildanzeige", chatui.KeyCloseImageViewer: "Bildanzeige schließen", chatui.KeyGIF: "GIF",
		}
	case "ar":
		return map[string]string{
			chatui.KeyPollTitle: "استطلاع القناة", chatui.KeyPollQuestion: "السؤال", chatui.KeyPollOptions: "الخيارات، خيار واحد في كل سطر", chatui.KeyPollOptionsHint: "أضف من خيارين إلى 10 خيارات، خيار واحد في كل سطر.", chatui.KeyPollCreate: "إنشاء استطلاع", chatui.KeyPollVote: "تصويت", chatui.KeyPollChangeVote: "تغيير تصويتك", chatui.KeyPollResults: "نتائج الاستطلاع", chatui.KeyPollVoteOne: "{n} صوت", chatui.KeyPollVotes: "{n} أصوات", chatui.KeyPollVoted: "اختيارك", chatui.KeyPollLoading: "جارٍ تحميل الاستطلاع…", chatui.KeyPollError: "تعذر تحميل الاستطلاع أو حفظه. حدّث الصفحة وحاول مرة أخرى.", chatui.KeyPollNoPoll: "لا يوجد استطلاع بعد",
			chatui.KeyChannelManager: "مدير القناة", chatui.KeyChannelMember: "عضو القناة",
			chatui.KeyTeamWidget: "فريق القناة", chatui.KeyTeamPurpose: "الغرض", chatui.KeyTeamRole: "تسمية الدور في القناة", chatui.KeyTeamNote: "تسميات القناة غير رسمية ولا تغيّر أدوار المؤسسة.", chatui.KeyProjectWidget: "مشروع القناة", chatui.KeyProjectNote: "ملاحظات تخطيط لهذه القناة", chatui.KeyProjectTitle: "عنوان المشروع", chatui.KeyProjectSummary: "الملخص", chatui.KeyMilestone: "مرحلة رئيسية", chatui.KeyMilestoneStatus: "الحالة", chatui.KeyMilestoneOwner: "المسؤول", chatui.KeyMilestoneDue: "تاريخ الاستحقاق", chatui.KeyPlanned: "مخطط", chatui.KeyInProgress: "قيد التنفيذ", chatui.KeyBlocked: "متعطل", chatui.KeyDone: "مكتمل", chatui.KeyWidgetSave: "حفظ", chatui.KeyWidgetAdd: "إضافة مرحلة", chatui.KeyWidgetDelete: "حذف المرحلة", chatui.KeyWidgetPin: "تثبيت الأداة", chatui.KeyWidgetUnpin: "إلغاء تثبيت الأداة", chatui.KeyWidgetLoading: "جارٍ تحميل أدوات القناة…", chatui.KeyWidgetError: "تعذر تحميل أدوات القناة أو حفظها. حدّث الصفحة وحاول مجددًا.", chatui.KeyWidgetEmpty: "لا توجد مراحل بعد",
			chatui.KeyPinCopyGuestUnavailable: "لا يمكن نسخ مراجع قناة ضيف",
			chatui.KeyTodoSaveError:           "تعذر حفظ قائمة المهام. حدّثها وحاول مرة أخرى.",
			chatui.KeyTodoNoOpen:              "لا توجد مهام مفتوحة",
			chatui.KeyTodoCompletedBy:         "أكملها {name}", chatui.KeyTodoMemberFallback: "عضو في القناة",
			chatui.KeyTodoModeEveryone: "الجميع", chatui.KeyTodoModeMe: "أنا", chatui.KeyTodoModeSelected: "أنا وأعضاء محددون", chatui.KeyTodoModeLabel: "من يمكنه إكمال هذه المهمة أو إعادة فتحها", chatui.KeyTodoAddMember: "إضافة عضو", chatui.KeyTodoRemoveMember: "إزالة {name}", chatui.KeyTodoOnlyCreator: "يمكن لمنشئ المهمة فقط إكمالها أو إعادة فتحها", chatui.KeyTodoOnlySelected: "يمكن لمنشئ المهمة والأعضاء المحددين فقط إكمالها أو إعادة فتحها", chatui.KeyTodoSelectedMember: "عضو محدد",
			chatui.KeyPinJump: "الانتقال إلى الرسالة", chatui.KeyPinCopy: "نسخ المرجع", chatui.KeyTodoTitle: "قائمة المهام", chatui.KeyTodoLoading: "جارٍ تحميل قائمة المهام…", chatui.KeyTodoError: "تعذر تحميل قائمة المهام. حاول مرة أخرى.", chatui.KeyTodoEmpty: "لا توجد مهام بعد", chatui.KeyTodoNew: "مهمة جديدة", chatui.KeyTodoAdd: "إضافة مهمة", chatui.KeyTodoComplete: "إكمال المهمة", chatui.KeyTodoReopen: "إعادة فتح المهمة", chatui.KeyTodoDelete: "حذف المهمة", chatui.KeyTodoPin: "تثبيت قائمة المهام", chatui.KeyTodoUnpin: "إلغاء تثبيت قائمة المهام", chatui.KeyTodoOpen: "فتح قائمة المهام", chatui.KeyTodoRemaining: "{n} مفتوحة", chatui.KeyTodoAttachPin: "ربط رسالة مثبّتة", chatui.KeyTodoNoPin: "لا توجد رسالة مرتبطة", chatui.KeyTodoSource: "رسالة مرتبطة",
			chatui.KeySearchResults: "نتائج البحث عن {query}", chatui.KeySearchChannels: "القنوات", chatui.KeySearchPeople: "الأشخاص", chatui.KeySearchMessages: "الرسائل", chatui.KeySearchLoading: "جارٍ البحث…", chatui.KeySearchCount: "{n} نتيجة", chatui.KeySearchCountOne: "نتيجة واحدة", chatui.KeySearchError: "البحث غير متاح. حاول مرة أخرى.", chatui.KeySearchNoResults: "لم يتم العثور على نتائج.", chatui.KeySearchMessageIn: "في {channel}", chatui.KeySearchOpenMessage: "فتح رسالة {author} في {channel}", chatui.KeySearchMore: "تحميل رسائل أخرى", chatui.KeySearchLoadingMore: "جارٍ تحميل رسائل أخرى…", chatui.KeySearchMoreError: "تعذر تحميل رسائل أخرى. حاول مرة أخرى.", chatui.KeySearchBrowseChannel: "تصفح {channel} والانضمام", chatui.KeySearchChannelUnavailable: "لم تعد هذه القناة متاحة.", chatui.KeySearchMessageUnavailable: "لم تعد هذه الرسالة متاحة.", chatui.KeySearchMoreChannels: "تحميل قنوات أخرى", chatui.KeySearchLoadingMoreChannels: "جارٍ تحميل قنوات أخرى…", chatui.KeySearchMoreChannelsError: "تعذر تحميل قنوات أخرى. حاول مرة أخرى.",
			chatui.KeyPersonDetails: "تفاصيل الشخص", chatui.KeyClosePerson: "إغلاق تفاصيل الشخص", chatui.KeyViewPerson: "عرض تفاصيل {name}", chatui.KeyStartDirectMessage: "إرسال رسالة",
			chatui.KeyManager: "المدير", chatui.KeyDepartment: "القسم", chatui.KeyJobTitle: "المسمى الوظيفي", chatui.KeyPhone: "الهاتف", chatui.KeyEmail: "البريد الإلكتروني", chatui.KeyLocation: "الموقع", chatui.KeyCompany: "الشركة", chatui.KeyBusinessUnit: "وحدة الأعمال", chatui.KeyNotAvailable: "غير متاح",
			chatui.KeySkip: "الانتقال إلى المحادثة", chatui.KeyNav: "تنقل الدردشة",
			chatui.KeyRailTitle: "المحادثات", chatui.KeyRailEmpty: "لست في أي محادثة بعد. تصفح القنوات أو ابدأ محادثة.",
			chatui.KeyNewConversation: "محادثة جديدة", chatui.KeySearch: "البحث في القنوات والأشخاص والرسائل", chatui.KeySearchPlaceholder: "بحث",
			chatui.KeySectionChannels: "القنوات", chatui.KeySectionDirect: "الرسائل المباشرة",
			chatui.KeyNewSection: "مجموعة جديدة", chatui.KeySectionName: "اسم المجموعة", chatui.KeyRemoveSection: "إزالة المجموعة", chatui.KeyMoveToSection: "نقل إلى {name}",
			chatui.KeyMoveSectionUp: "نقل القسم لأعلى", chatui.KeyMoveSectionDown: "نقل القسم لأسفل",
			chatui.KeyBrowse: "تصفح القنوات", chatui.KeyBrowseTitle: "تصفح القنوات", chatui.KeyBrowseEmpty: "لا توجد قنوات للانضمام إليها بعد.",
			chatui.KeyJoin: "انضمام", chatui.KeyJoined: "منضم",
			chatui.KeyOpenConversations: "فتح المحادثات", chatui.KeyCloseConversations: "إغلاق المحادثات", chatui.KeyConversation: "محادثة",
			chatui.KeyKindPublic: "قناة عامة", chatui.KeyKindPrivate: "قناة خاصة", chatui.KeyKindDirect: "رسالة مباشرة", chatui.KeyKindGroup: "مجموعة خاصة",
			chatui.KeyMemberCount: "{n} أعضاء", chatui.KeyMemberCountOne: "عضو واحد", chatui.KeyUnreadCount: "{n} غير مقروءة", chatui.KeyMentionCount: "{n} إشارات",
			chatui.KeyDetails: "تفاصيل المحادثة", chatui.KeyCloseDetails: "إغلاق التفاصيل", chatui.KeyMembers: "الأعضاء", chatui.KeyRefreshMembers: "تحديث الأعضاء",
			chatui.KeyOnline: "متصل", chatui.KeyOffline: "غير متصل",
			chatui.KeyNotifications: "الإشعارات", chatui.KeyNotifyAll: "كل الرسائل", chatui.KeyNotifyMentions: "الإشارات فقط", chatui.KeyNotifyMute: "مكتوم",
			chatui.KeyQuietHours: "ساعات الهدوء", chatui.KeyQuietHoursOn: "إيقاف الإشعارات ليلًا", chatui.KeyQuietTimezone: "المنطقة الزمنية", chatui.KeyQuietStart: "من", chatui.KeyQuietEnd: "حتى",
			chatui.KeyMessagesRegion: "رسائل المحادثة", chatui.KeyMessageActions: "إجراءات الرسالة",
			chatui.KeyLoading: "جارٍ تحميل المحادثة…", chatui.KeyErrorTitle: "المحادثة غير متاحة", chatui.KeyRetry: "حاول مرة أخرى",
			chatui.KeyEmptyTitle: "ابدأ المحادثة", chatui.KeyEmptyBody: "لا توجد رسائل هنا بعد. أرسل الرسالة الأولى عندما تكون جاهزًا.",
			chatui.KeyNoneTitle: "اختر محادثة", chatui.KeyNoneBody: "اختر قناة أو رسالة مباشرة من القائمة، أو ابدأ محادثة جديدة.",
			chatui.KeyNoMessages: "لا توجد رسائل بعد", chatui.KeyLoadOlder: "عرض الرسائل السابقة", chatui.KeyLoadNewer: "عرض الرسائل الأحدث", chatui.KeyLoadOlderThread: "عرض الردود السابقة", chatui.KeyLoadNewerThread: "عرض الردود الأحدث",
			chatui.KeyToday: "اليوم", chatui.KeyYesterday: "أمس", chatui.KeyEdited: "معدّلة", chatui.KeyPinned: "مثبّتة",
			chatui.KeyReplies: "{n} ردود", chatui.KeyReactions: "{n} تفاعلات", chatui.KeyRepliesOne: "رد واحد",
			chatui.KeyCopyConversationAPICurl: "نسخ أمر API curl", chatui.KeyCopyConversationAPICurlSuccess: "تم نسخ أمر API curl", chatui.KeyCopyConversationAPICurlFailure: "تعذر نسخ أمر API curl. تحقق من الوصول إلى الحافظة وحاول مرة أخرى.",
			chatui.KeyGiphyPicker: "إدراج GIF", chatui.KeyGiphyPickerTitle: "اختر GIF", chatui.KeyGiphySearch: "البحث عن GIFs", chatui.KeyGiphyMore: "تحميل المزيد من GIFs", chatui.KeyGiphyUnavailable: "تتطلب GIFs مفتاح GIPHY يهيئه المسؤول", chatui.KeyGiphyLoading: "جارٍ تحميل GIFs…", chatui.KeyGiphyLoadError: "تعذر تحميل GIFs.", chatui.KeyGiphyNoResults: "لم يُعثر على GIFs.", chatui.KeyGiphyClose: "إغلاق منتقي GIF",
			chatui.KeyNew: "جديد", chatui.KeyJumpNewest: "الانتقال إلى الأحدث", chatui.KeyMore: "إجراءات إضافية", chatui.KeyConversationMore: "خيارات إضافية لـ {name}", chatui.KeyCopyConversationReference: "نسخ الاسم والرابط", chatui.KeyCopyConversationSuccess: "تم نسخ رابط المحادثة", chatui.KeyCopyConversationFailure: "تعذر نسخ رابط المحادثة. تحقق من الوصول إلى الحافظة وحاول مرة أخرى.", chatui.KeyConversationLinkUnavailable: "المحادثة غير متاحة", chatui.KeyCopyLink: "نسخ الرابط", chatui.KeyCopyContents: "نسخ نص الرسالة", chatui.KeyCopyContentsEmpty: "لا يوجد نص في الرسالة لنسخه", chatui.KeyCopyContentsSuccess: "تم نسخ نص الرسالة", chatui.KeyCopyContentsFailure: "تعذر نسخ نص الرسالة. تحقق من الوصول إلى الحافظة وحاول مرة أخرى.",
			chatui.KeyShareToChannel: "مشاركة في قناة", chatui.KeyShareTitle: "مشاركة الرسالة في قناة", chatui.KeyShareDestination: "القناة المستهدفة", chatui.KeyShareFilter: "البحث في قنواتك", chatui.KeyShareEmpty: "لم يُعثر على قنوات مناسبة", chatui.KeyShareLoading: "جارٍ تحميل قنواتك…", chatui.KeyShareDisclosure: "سيتمكن أعضاء القناة المستهدفة من رؤية هذه الرسالة.", chatui.KeyShareAttachments: "سيُشارك نص الرسالة فقط. لن تُضمَّن المرفقات.", chatui.KeyShareSubmit: "مشاركة", chatui.KeySharePending: "جارٍ المشاركة…", chatui.KeyShareLoadError: "تعذر تحميل القنوات. حاول مرة أخرى.", chatui.KeyShareError: "تعذرت مشاركة الرسالة. تحقق من صلاحياتك وحاول مرة أخرى.", chatui.KeyShareSuccess: "تمت مشاركة الرسالة في القناة", chatui.KeyShareUnavailable: "المشاركة غير متاحة. حاول مرة أخرى.", chatui.KeyForwardedFrom: "معاد توجيهها من {name}",
			chatui.KeyEmbedTitle: "رسالة مرتبطة", chatui.KeyEmbedLoading: "جارٍ تحميل معاينة الرسالة…", chatui.KeyEmbedUnavailable: "معاينة الرسالة غير متاحة", chatui.KeyEmbedOpen: "فتح القناة الأصلية", chatui.KeyEmbedAttachments: "المرفقات: {count}",
			chatui.KeyPickReaction: "اختر تفاعلاً", chatui.KeyReactionChip: "{n} تفاعلوا بـ {emoji}", chatui.KeyReactWith: "التفاعل بـ {emoji}",
			chatui.KeyResizeRail: "تغيير عرض قائمة المحادثات. اسحب أو استخدم مفاتيح الأسهم؛ Home يعيد العرض الافتراضي.", chatui.KeyResizeSide: "تغيير عرض اللوحة الجانبية. اسحب أو استخدم مفاتيح الأسهم؛ Home يعيد العرض الافتراضي.",
			chatui.KeyActiveJustNow: "نشطة الآن", chatui.KeyActiveHoursAgo: "نشطة قبل {n} س", chatui.KeyActiveDaysAgo: "نشطة قبل {n} يوم", chatui.KeyActiveOn: "نشطة في {date}", chatui.KeyNoActivity: "لا رسائل بعد", chatui.KeyYou: "أنت", chatui.KeyMemberFilter: "تصفية الأعضاء", chatui.KeyThreadIn: "سلسلة · {name}", chatui.KeyBrowseCount: "{n} قنوات يمكنك الانضمام إليها",
			chatui.KeyReply: "الرد في سلسلة", chatui.KeyReact: "إضافة تفاعل", chatui.KeyRemoveReaction: "إزالة تفاعلك",
			chatui.KeyPin: "تثبيت الرسالة", chatui.KeyUnpin: "إلغاء تثبيت الرسالة", chatui.KeyEdit: "تعديل الرسالة", chatui.KeyDelete: "حذف الرسالة",
			chatui.KeySaveEdit: "حفظ التغييرات", chatui.KeyCancel: "إلغاء", chatui.KeyClose: "إغلاق",
			chatui.KeyThread: "السلسلة", chatui.KeyThreadRegion: "ردود السلسلة", chatui.KeyThreadEmpty: "لا توجد ردود بعد. ردك سيبدأ هذه السلسلة.", chatui.KeyThreadLoading: "جارٍ تحميل الردود…", chatui.KeyCloseThread: "إغلاق السلسلة",
			chatui.KeyFollow: "متابعة", chatui.KeyFollowing: "تتابع",
			chatui.KeyComposeRegion: "إرسال رسالة", chatui.KeyMessage: "رسالة", chatui.KeyComposePlaceholder: "رسالة إلى {name}", chatui.KeyComposeUnselected: "اختر محادثة لبدء الكتابة",
			chatui.KeyComposeHint: "Enter للإرسال، Shift+Enter لسطر جديد", chatui.KeyEmojiPicker: "إدراج رمز تعبيري", chatui.KeyEmojiPickerTitle: "اختر رمزًا تعبيريًا", chatui.KeyEmojiItem: "رمز تعبيري {emoji}", chatui.KeyAttach: "إضافة مرفق", chatui.KeySend: "إرسال",
			chatui.KeyCreateTitle: "إنشاء محادثة", chatui.KeyName: "الاسم", chatui.KeyNamePlaceholder: "مثلًا design-reviews", chatui.KeyKind: "نوع المحادثة",
			chatui.KeyMembersOptional: "الأعضاء (اختياري)", chatui.KeyMembersPlaceholder: "أسماء أو معرّفات مفصولة بفواصل", chatui.KeyCreate: "إنشاء",
			chatui.KeyRefresh: "تحديث", chatui.KeyOn: "مفعّل", chatui.KeyOff: "متوقف", chatui.KeyReplyPlaceholder: "رد…", chatui.KeyReplySend: "رد", chatui.KeyBrowseCreate: "إنشاء قناة",
			chatui.KeyIntroTitle: "هذه بداية {name}", chatui.KeyIntroPublic: "يمكن لأي شخص في الشركة العثور على هذه القناة والانضمام إليها. الرسائل هنا مرئية لكل أعضائها.", chatui.KeyIntroPrivate: "الأعضاء المدعوون فقط يرون هذه القناة ورسائلها.", chatui.KeyDMEmpty: "لا توجد رسائل مباشرة بعد", chatui.KeyBrowseFilter: "تصفية القنوات", chatui.KeyAttachmentLoading: "جارٍ تحميل المرفق…", chatui.KeyAttachmentUnavailable: "المعاينة غير متاحة", chatui.KeyDownloadAttachment: "تنزيل", chatui.KeyOpenImage: "فتح الصورة", chatui.KeyImageViewer: "عارض الصور", chatui.KeyCloseImageViewer: "إغلاق عارض الصور", chatui.KeyGIF: "GIF",
		}
	}
	return nil
}
