package productui

// docsLibraryCopy is the vocabulary of the Docs library: saved views, the
// viewer's folders, the list and the share dialog. Counted strings have a
// "_one" form for exactly one.
var docsLibraryCopy = map[string]map[string]string{
	"en-US": {
		"document_unavailable": "You can't open this document.", "document_unavailable_hint": "It may have been removed, or it hasn't been shared with you. Ask its owner to share it.",
		"back_to_documents": "Back to documents", "copy_text": "Copy text", "copy_text_help": "Copy this document's text (Markdown) to the clipboard", "text_copied": "Text copied",
		"diagram_failed": "This diagram could not be drawn, so its source is shown.", "editor_diagram": "Diagram",
		"comment_pin": "Comment {n}: {quote}", "comment_pins": "Comments on passages",
		"comments_none_open": "No open comments. Select text in the document to comment on a passage.", "comments_none_resolved": "No resolved comments.", "comments_show_resolved": "Resolved ({n})", "comments_show_open": "Open ({n})", "comment_on": "Commenting on", "comment_clear_quote": "Comment on the whole document instead", "comment_placeholder": "Add a comment", "comment_placeholder_quote": "What about this passage?", "comment_hint": "Select text to quote it. Ctrl+Enter sends.", "comment_hint_send": "Ctrl+Enter sends.", "comment_hint_select": "Select text to quote it.", "comments_none_readonly": "No open comments.", "comments_readonly_note": "Your access lets you read comments but not add them.", "comment_jump": "Show this passage", "comment_orphaned": "This passage was changed in a later version.", "comment_reply": "Reply", "comment_reply_placeholder": "Reply to this thread", "comment_reopen": "Reopen", "comment_resolve": "Resolve", "resolve_failed": "The thread could not be updated. Try again.", "comment_on_selection": "Comment",
		"table_label": "Table", "indexing_n": "Meaning search is still indexing {n} documents. They join the results as they finish.", "indexing_n_one": "Meaning search is still indexing 1 document. It joins the results when it finishes.",
		"sort_owner": "Owner A–Z", "sort_owner_desc": "Owner Z–A", "sort_by": "Sort by {column}",
		"sort_relevance": "Best match", "sort_updated_asc": "Oldest first", "sort_title_desc": "Title Z–A",
		"mode_label": "Search in", "mode_smart": "Titles and text", "mode_contains": "Contains", "mode_fuzzy": "Fuzzy", "mode_meaning": "Meaning", "mode_meaning_off": "Meaning (unavailable)",
		"mode_help_smart": "Exact words, parts of words, near spellings and similar meaning", "mode_help_contains": "The exact text anywhere in the title or body", "mode_help_fuzzy": "Tolerates typos and near spellings", "mode_help_meaning": "Documents about the same idea, even in other words",
		"match_title": "In title", "match_text": "Text", "match_fuzzy": "Close spelling", "match_meaning": "Similar meaning",
		"range_of": "{first}–{last} of {total}", "page_n": "Page {n}", "page_previous": "Previous page", "page_next": "Next page", "pages_label": "Pages", "rows_per_page": "Rows per page",
		"nav_all": "All documents", "nav_starred": "Starred", "nav_private": "My documents", "nav_shared": "Shared with me",
		"documents_n": "{n} documents", "documents_n_one": "1 document",
		"search_results_heading": "Results for “{query}”", "searching": "Searching…", "library_subtitle": "Everything you can read in this workspace.", "search_results_n": "{n} results", "search_results_n_one": "1 result", "search_results_uncertain": "{n}+ results",
		"search_placeholder": "Search titles and text", "chip_search": "Search", "clear_owner": "Show every owner",
		"sort_label": "Sort", "sort_updated": "Recently updated", "sort_title": "Title A–Z",
		"selected_n": "{n} selected", "move_action": "Move", "star_action": "Star", "clear_selection": "Clear selection", "bulk_label": "Selected documents",
		"select_all": "Select all documents on this page", "select": "Select",
		"access": "Access", "actions": "Actions", "showing_of": "Showing {shown} of {total}", "show_more": "Show 50 more",
		"you": "You", "you_named": "{name} (you)", "star": "Star", "unstar": "Remove star", "owner_filter": "Documents by {name}",
		"access_private": "Only you", "access_readers": "You and {n} people", "access_readers_one": "You and 1 person", "access_shared": "Shared", "access_with_you": "Shared with you",
		"reviewed": "Reviewed", "access_private_compact": "Private", "access_shared_compact": "Shared", "access_with_you_compact": "Shared", "access_readers_compact": "You +{n}",
		"copy_failed": "Couldn't copy. The browser blocked the clipboard.", "copy_failed_link": "Couldn't copy. The link is selected below: press Ctrl+C to copy it.", "share_link_label": "Document link",
		"create_discard_confirm": "Discard this draft? What you typed will be lost.", "create_discard": "Discard draft", "create_keep": "Keep editing",
		"share_open": "Share", "copy_link": "Copy link", "link_copied": "Link copied", "move_to_folder": "Move to folder",
		"empty": "No documents yet.", "empty_hint": "Create a document to start your library.",
		"browse_no_match": "No documents match.", "browse_no_match_hint": "Try fewer words, or clear the filters above.",
		"empty_folder": "This folder is empty.", "empty_folder_hint": "Select documents in any view and choose Move to file them here.",
		"empty_starred": "Nothing starred yet.", "empty_starred_hint": "Star the documents you open often and they collect here.",
		"browse_no_shared": "Nothing has been shared with you.", "browse_no_shared_hint": "Documents other people share with you appear here.",
		"browse_no_private": "You have not created a document yet.", "browse_no_private_hint": "New documents start private; only you can read them until you share.",
		"folders": "Folders", "folder_new": "New folder", "folder_name": "Folder name", "folder_create": "Create", "folder_save": "Save",
		"folders_empty": "No folders yet.", "folders_note": "Folders are yours alone. Filing a document never changes who can read it.",
		"folder_rename": "Rename", "folder_delete": "Delete folder", "folder_delete_confirm": "Delete “{folder}”? Its documents stay in your library.",
		"folder_created": "Created “{folder}”.", "folder_deleted": "Deleted “{folder}”. Its documents are still in your library.",
		"folder_create_failed": "The folder could not be created. Pick a name you have not used.", "folder_rename_failed": "The folder could not be renamed. Pick a name you have not used.", "folder_delete_failed": "The folder could not be deleted. Try again.",
		"star_failed": "The star could not be saved. Try again.", "starred_n": "Starred {n} documents.", "starred_n_one": "Starred 1 document.",
		"move_failed": "The documents could not be moved. Try again.", "moved_n": "Moved {n} documents to “{folder}”.", "moved_n_one": "Moved 1 document to “{folder}”.",
		"unfiled_n": "Took {n} documents out of their folders.", "unfiled_n_one": "Took 1 document out of its folder.",
		"move_title": "Move {n} documents", "move_title_one": "Move 1 document", "move_current": "Current", "move_unfiled": "Not in a folder",
		"move_new_folder": "Or put them in a new folder", "move_create_and_move": "Create and move",
		"share_title": "Share “{title}”", "share_add_people": "Add people", "share_placeholder": "Type a name", "share_no_people": "No one else matches that name.",
		"share_with_n": "Share with {n} people", "share_with_n_one": "Share with 1 person", "shared_n": "Shared with {n} people.", "shared_n_one": "Shared with 1 person.",
		"share_failed_names": "Could not share with {names}. Try again.", "role_label": "Permission", "role_commenter": "Can comment", "role_viewer": "Can view", "role_owner": "Owner",
		"role_label_for": "Permission for {name}", "role_change_failed": "The permission could not be changed. Try again.", "role_changed": "Permission updated.",
		"access_heading": "People with access", "access_loading": "Loading who has access…", "access_failed": "The access list could not be loaded. Close and try again.",
		"remove": "Remove", "revoked": "{name} can no longer read this document.", "revoke_failed": "Access could not be removed. Try again.",
		"link_note": "Only people with access can open this link.", "close": "Close", "outline": "On this page", "breadcrumb": "You are here",
	},
	"de-DE": {
		"document_unavailable": "Dieses Dokument kann nicht geöffnet werden.", "document_unavailable_hint": "Es wurde möglicherweise entfernt oder nicht mit Ihnen geteilt. Bitten Sie die verantwortliche Person, es zu teilen.",
		"back_to_documents": "Zurück zu den Dokumenten", "copy_text": "Text kopieren", "copy_text_help": "Den Text dieses Dokuments (Markdown) in die Zwischenablage kopieren", "text_copied": "Text kopiert",
		"diagram_failed": "Dieses Diagramm konnte nicht gezeichnet werden; der Quelltext wird angezeigt.", "editor_diagram": "Diagramm",
		"comment_pin": "Kommentar {n}: {quote}", "comment_pins": "Kommentare zu Textstellen",
		"comments_none_open": "Keine offenen Kommentare. Markieren Sie Text, um eine Stelle zu kommentieren.", "comments_none_resolved": "Keine erledigten Kommentare.", "comments_show_resolved": "Erledigt ({n})", "comments_show_open": "Offen ({n})", "comment_on": "Kommentar zu", "comment_clear_quote": "Stattdessen das ganze Dokument kommentieren", "comment_placeholder": "Kommentar hinzufügen", "comment_placeholder_quote": "Was ist mit dieser Stelle?", "comment_hint": "Text markieren, um ihn zu zitieren. Strg+Enter sendet.", "comment_hint_send": "Strg+Enter sendet.", "comment_hint_select": "Text markieren, um ihn zu zitieren.", "comments_none_readonly": "Keine offenen Kommentare.", "comments_readonly_note": "Mit Ihrem Zugriff können Sie Kommentare lesen, aber keine hinzufügen.", "comment_jump": "Stelle anzeigen", "comment_orphaned": "Diese Stelle wurde in einer späteren Version geändert.", "comment_reply": "Antworten", "comment_reply_placeholder": "Auf diesen Thread antworten", "comment_reopen": "Wieder öffnen", "comment_resolve": "Erledigen", "resolve_failed": "Der Thread konnte nicht aktualisiert werden.", "comment_on_selection": "Kommentieren",
		"table_label": "Tabelle", "indexing_n": "Die Bedeutungssuche indiziert noch {n} Dokumente. Sie erscheinen, sobald sie fertig sind.", "indexing_n_one": "Die Bedeutungssuche indiziert noch 1 Dokument.",
		"sort_owner": "Verantwortlich A–Z", "sort_owner_desc": "Verantwortlich Z–A", "sort_by": "Nach {column} sortieren",
		"sort_relevance": "Beste Treffer", "sort_updated_asc": "Älteste zuerst", "sort_title_desc": "Titel Z–A",
		"mode_label": "Suchen in", "mode_smart": "Titel und Text", "mode_contains": "Enthält", "mode_fuzzy": "Unscharf", "mode_meaning": "Bedeutung", "mode_meaning_off": "Bedeutung (nicht verfügbar)",
		"mode_help_smart": "Genaue Wörter, Wortteile, ähnliche Schreibweisen und ähnliche Bedeutung", "mode_help_contains": "Der genaue Text irgendwo in Titel oder Inhalt", "mode_help_fuzzy": "Toleriert Tippfehler", "mode_help_meaning": "Dokumente zum selben Thema, auch in anderen Worten",
		"match_title": "Im Titel", "match_text": "Text", "match_fuzzy": "Ähnliche Schreibweise", "match_meaning": "Ähnliche Bedeutung",
		"range_of": "{first}–{last} von {total}", "page_n": "Seite {n}", "page_previous": "Vorherige Seite", "page_next": "Nächste Seite", "pages_label": "Seiten", "rows_per_page": "Zeilen pro Seite",
		"nav_all": "Alle Dokumente", "nav_starred": "Markiert", "nav_private": "Meine Dokumente", "nav_shared": "Mit mir geteilt",
		"documents_n": "{n} Dokumente", "documents_n_one": "1 Dokument",
		"search_results_heading": "Ergebnisse für „{query}“", "searching": "Suche läuft…", "library_subtitle": "Alles, was Sie in diesem Arbeitsbereich lesen können.", "search_results_n": "{n} Ergebnisse", "search_results_n_one": "1 Ergebnis", "search_results_uncertain": "{n}+ Ergebnisse",
		"search_placeholder": "Titel und Text durchsuchen", "chip_search": "Suche", "clear_owner": "Alle Verantwortlichen zeigen",
		"sort_label": "Sortieren", "sort_updated": "Zuletzt aktualisiert", "sort_title": "Titel A–Z",
		"selected_n": "{n} ausgewählt", "move_action": "Verschieben", "star_action": "Markieren", "clear_selection": "Auswahl aufheben", "bulk_label": "Ausgewählte Dokumente",
		"select_all": "Alle Dokumente dieser Seite auswählen", "select": "Auswählen",
		"access": "Zugriff", "actions": "Aktionen", "showing_of": "{shown} von {total}", "show_more": "50 weitere zeigen",
		"you": "Sie", "you_named": "{name} (Sie)", "star": "Markieren", "unstar": "Markierung entfernen", "owner_filter": "Dokumente von {name}",
		"access_private": "Nur Sie", "access_readers": "Sie und {n} Personen", "access_readers_one": "Sie und 1 Person", "access_shared": "Geteilt", "access_with_you": "Mit Ihnen geteilt",
		"reviewed": "Geprüft", "access_private_compact": "Privat", "access_shared_compact": "Geteilt", "access_with_you_compact": "Geteilt", "access_readers_compact": "Sie +{n}",
		"copy_failed": "Kopieren nicht möglich. Der Browser hat die Zwischenablage blockiert.", "copy_failed_link": "Kopieren nicht möglich. Der Link ist unten markiert: Drücken Sie Strg+C, um ihn zu kopieren.", "share_link_label": "Dokumentlink",
		"create_discard_confirm": "Diesen Entwurf verwerfen? Ihre Eingaben gehen verloren.", "create_discard": "Entwurf verwerfen", "create_keep": "Weiter bearbeiten",
		"share_open": "Teilen", "copy_link": "Link kopieren", "link_copied": "Link kopiert", "move_to_folder": "In Ordner verschieben",
		"empty": "Noch keine Dokumente.", "empty_hint": "Erstellen Sie ein Dokument, um Ihre Bibliothek zu beginnen.",
		"browse_no_match": "Keine passenden Dokumente.", "browse_no_match_hint": "Versuchen Sie weniger Wörter oder entfernen Sie die Filter oben.",
		"empty_folder": "Dieser Ordner ist leer.", "empty_folder_hint": "Wählen Sie Dokumente in einer beliebigen Ansicht und dann Verschieben.",
		"empty_starred": "Noch nichts markiert.", "empty_starred_hint": "Markieren Sie häufig genutzte Dokumente, dann sammeln sie sich hier.",
		"browse_no_shared": "Es wurde nichts mit Ihnen geteilt.", "browse_no_shared_hint": "Dokumente, die andere mit Ihnen teilen, erscheinen hier.",
		"browse_no_private": "Sie haben noch kein Dokument erstellt.", "browse_no_private_hint": "Neue Dokumente sind privat, bis Sie sie teilen.",
		"folders": "Ordner", "folder_new": "Neuer Ordner", "folder_name": "Ordnername", "folder_create": "Erstellen", "folder_save": "Speichern",
		"folders_empty": "Noch keine Ordner.", "folders_note": "Ordner gehören nur Ihnen. Das Ablegen ändert nie, wer ein Dokument lesen kann.",
		"folder_rename": "Umbenennen", "folder_delete": "Ordner löschen", "folder_delete_confirm": "„{folder}“ löschen? Die Dokumente bleiben in Ihrer Bibliothek.",
		"folder_created": "„{folder}“ erstellt.", "folder_deleted": "„{folder}“ gelöscht. Die Dokumente sind weiterhin in Ihrer Bibliothek.",
		"folder_create_failed": "Der Ordner konnte nicht erstellt werden. Wählen Sie einen neuen Namen.", "folder_rename_failed": "Der Ordner konnte nicht umbenannt werden. Wählen Sie einen neuen Namen.", "folder_delete_failed": "Der Ordner konnte nicht gelöscht werden. Versuchen Sie es erneut.",
		"star_failed": "Die Markierung konnte nicht gespeichert werden.", "starred_n": "{n} Dokumente markiert.", "starred_n_one": "1 Dokument markiert.",
		"move_failed": "Die Dokumente konnten nicht verschoben werden.", "moved_n": "{n} Dokumente nach „{folder}“ verschoben.", "moved_n_one": "1 Dokument nach „{folder}“ verschoben.",
		"unfiled_n": "{n} Dokumente aus ihren Ordnern genommen.", "unfiled_n_one": "1 Dokument aus seinem Ordner genommen.",
		"move_title": "{n} Dokumente verschieben", "move_title_one": "1 Dokument verschieben", "move_current": "Aktuell", "move_unfiled": "In keinem Ordner",
		"move_new_folder": "Oder in einen neuen Ordner legen", "move_create_and_move": "Erstellen und verschieben",
		"share_title": "„{title}“ teilen", "share_add_people": "Personen hinzufügen", "share_placeholder": "Namen eingeben", "share_no_people": "Niemand sonst passt zu diesem Namen.",
		"share_with_n": "Mit {n} Personen teilen", "share_with_n_one": "Mit 1 Person teilen", "shared_n": "Mit {n} Personen geteilt.", "shared_n_one": "Mit 1 Person geteilt.",
		"share_failed_names": "Teilen mit {names} fehlgeschlagen. Versuchen Sie es erneut.", "role_label": "Berechtigung", "role_commenter": "Kann kommentieren", "role_viewer": "Kann ansehen", "role_owner": "Verantwortlich",
		"role_label_for": "Berechtigung für {name}", "role_change_failed": "Die Berechtigung konnte nicht geändert werden. Versuchen Sie es erneut.", "role_changed": "Berechtigung aktualisiert.",
		"access_heading": "Personen mit Zugriff", "access_loading": "Zugriffsliste wird geladen…", "access_failed": "Die Zugriffsliste konnte nicht geladen werden.",
		"remove": "Entfernen", "revoked": "{name} kann dieses Dokument nicht mehr lesen.", "revoke_failed": "Der Zugriff konnte nicht entfernt werden.",
		"link_note": "Nur Personen mit Zugriff können diesen Link öffnen.", "close": "Schließen", "outline": "Auf dieser Seite", "breadcrumb": "Sie sind hier",
	},
	"ar": {
		"document_unavailable": "لا يمكنك فتح هذا المستند.", "document_unavailable_hint": "ربما أُزيل أو لم تتم مشاركته معك. اطلب من مالكه مشاركته.",
		"back_to_documents": "العودة إلى المستندات", "copy_text": "نسخ النص", "copy_text_help": "نسخ نص هذا المستند (Markdown) إلى الحافظة", "text_copied": "تم نسخ النص",
		"diagram_failed": "تعذر رسم هذا المخطط، لذلك يظهر نصه المصدري.", "editor_diagram": "مخطط",
		"comment_pin": "التعليق {n}: {quote}", "comment_pins": "تعليقات على مقاطع",
		"comments_none_open": "لا توجد تعليقات مفتوحة. حدد نصًا في المستند للتعليق على مقطع.", "comments_none_resolved": "لا توجد تعليقات محلولة.", "comments_show_resolved": "المحلولة ({n})", "comments_show_open": "المفتوحة ({n})", "comment_on": "تعليق على", "comment_clear_quote": "التعليق على المستند كله بدلًا من ذلك", "comment_placeholder": "أضف تعليقًا", "comment_placeholder_quote": "ماذا عن هذا المقطع؟", "comment_hint": "حدد نصًا لاقتباسه. Ctrl+Enter للإرسال.", "comment_hint_send": "Ctrl+Enter للإرسال.", "comment_hint_select": "حدد نصًا لاقتباسه.", "comments_none_readonly": "لا توجد تعليقات مفتوحة.", "comments_readonly_note": "يتيح لك مستوى وصولك قراءة التعليقات دون إضافتها.", "comment_jump": "إظهار هذا المقطع", "comment_orphaned": "تغيّر هذا المقطع في نسخة لاحقة.", "comment_reply": "رد", "comment_reply_placeholder": "رد على هذا النقاش", "comment_reopen": "إعادة فتح", "comment_resolve": "حل", "resolve_failed": "تعذر تحديث النقاش. حاول مرة أخرى.", "comment_on_selection": "تعليق",
		"table_label": "جدول", "indexing_n": "لا يزال البحث بالمعنى يفهرس {n} مستندات، وستظهر في النتائج عند اكتمالها.", "indexing_n_one": "لا يزال البحث بالمعنى يفهرس مستندًا واحدًا.",
		"sort_owner": "المالك أ–ي", "sort_owner_desc": "المالك ي–أ", "sort_by": "الترتيب حسب {column}",
		"sort_relevance": "الأفضل تطابقًا", "sort_updated_asc": "الأقدم أولًا", "sort_title_desc": "العنوان ي–أ",
		"mode_label": "البحث في", "mode_smart": "العناوين والنص", "mode_contains": "يحتوي", "mode_fuzzy": "تقريبي", "mode_meaning": "المعنى", "mode_meaning_off": "المعنى (غير متاح)",
		"mode_help_smart": "كلمات مطابقة وأجزاء كلمات وتهجئة قريبة ومعنى مشابه", "mode_help_contains": "النص نفسه في أي مكان من العنوان أو المحتوى", "mode_help_fuzzy": "يتسامح مع الأخطاء الإملائية", "mode_help_meaning": "مستندات عن الفكرة نفسها ولو بكلمات أخرى",
		"match_title": "في العنوان", "match_text": "النص", "match_fuzzy": "تهجئة قريبة", "match_meaning": "معنى مشابه",
		"range_of": "{first}–{last} من {total}", "page_n": "الصفحة {n}", "page_previous": "الصفحة السابقة", "page_next": "الصفحة التالية", "pages_label": "الصفحات", "rows_per_page": "صفوف في الصفحة",
		"nav_all": "كل المستندات", "nav_starred": "المميزة بنجمة", "nav_private": "مستنداتي", "nav_shared": "مشتركة معي",
		"documents_n": "{n} مستند", "documents_n_one": "مستند واحد",
		"search_results_heading": "نتائج البحث عن “{query}”", "searching": "جارٍ البحث…", "library_subtitle": "كل ما يمكنك قراءته في مساحة العمل هذه.", "search_results_n": "{n} نتيجة", "search_results_n_one": "نتيجة واحدة", "search_results_uncertain": "{n}+ نتيجة",
		"search_placeholder": "ابحث في العناوين والنص", "chip_search": "بحث", "clear_owner": "عرض كل المالكين",
		"sort_label": "الترتيب", "sort_updated": "الأحدث تحديثًا", "sort_title": "العنوان أ–ي",
		"selected_n": "تم تحديد {n}", "move_action": "نقل", "star_action": "تمييز بنجمة", "clear_selection": "إلغاء التحديد", "bulk_label": "المستندات المحددة",
		"select_all": "تحديد كل المستندات في هذه الصفحة", "select": "تحديد",
		"access": "الوصول", "actions": "إجراءات", "showing_of": "عرض {shown} من {total}", "show_more": "عرض 50 أخرى",
		"you": "أنت", "you_named": "{name} (أنت)", "star": "تمييز بنجمة", "unstar": "إزالة النجمة", "owner_filter": "مستندات {name}",
		"access_private": "أنت فقط", "access_readers": "أنت و{n} أشخاص", "access_readers_one": "أنت وشخص واحد", "access_shared": "مشترك", "access_with_you": "مشترك معك",
		"reviewed": "آخر مراجعة", "access_private_compact": "خاص", "access_shared_compact": "مشترك", "access_with_you_compact": "مشترك", "access_readers_compact": "أنت \u2066+{n}\u2069",
		"copy_failed": "تعذر النسخ. منع المتصفح الوصول إلى الحافظة.", "copy_failed_link": "تعذر النسخ. الرابط محدد أدناه: اضغط Ctrl+C لنسخه.", "share_link_label": "رابط المستند",
		"create_discard_confirm": "هل تريد تجاهل هذه المسودة؟ سيُفقد ما كتبته.", "create_discard": "تجاهل المسودة", "create_keep": "متابعة التحرير",
		"share_open": "مشاركة", "copy_link": "نسخ الرابط", "link_copied": "تم نسخ الرابط", "move_to_folder": "نقل إلى مجلد",
		"empty": "لا توجد مستندات بعد.", "empty_hint": "أنشئ مستندًا لبدء مكتبتك.",
		"browse_no_match": "لا توجد مستندات مطابقة.", "browse_no_match_hint": "جرّب كلمات أقل أو امسح عوامل التصفية أعلاه.",
		"empty_folder": "هذا المجلد فارغ.", "empty_folder_hint": "حدد مستندات في أي عرض ثم اختر نقل.",
		"empty_starred": "لا شيء مميز بنجمة بعد.", "empty_starred_hint": "ميّز المستندات التي تفتحها كثيرًا لتجدها هنا.",
		"browse_no_shared": "لم تتم مشاركة أي شيء معك.", "browse_no_shared_hint": "تظهر هنا المستندات التي يشاركها الآخرون معك.",
		"browse_no_private": "لم تنشئ مستندًا بعد.", "browse_no_private_hint": "تبدأ المستندات الجديدة خاصة حتى تشاركها.",
		"folders": "المجلدات", "folder_new": "مجلد جديد", "folder_name": "اسم المجلد", "folder_create": "إنشاء", "folder_save": "حفظ",
		"folders_empty": "لا توجد مجلدات بعد.", "folders_note": "المجلدات خاصة بك وحدك. ترتيب المستند لا يغيّر من يستطيع قراءته.",
		"folder_rename": "إعادة تسمية", "folder_delete": "حذف المجلد", "folder_delete_confirm": "حذف «{folder}»؟ تبقى مستنداته في مكتبتك.",
		"folder_created": "تم إنشاء «{folder}».", "folder_deleted": "تم حذف «{folder}». لا تزال مستنداته في مكتبتك.",
		"folder_create_failed": "تعذر إنشاء المجلد. اختر اسمًا لم تستخدمه.", "folder_rename_failed": "تعذرت إعادة تسمية المجلد. اختر اسمًا لم تستخدمه.", "folder_delete_failed": "تعذر حذف المجلد. حاول مرة أخرى.",
		"star_failed": "تعذر حفظ النجمة. حاول مرة أخرى.", "starred_n": "تم تمييز {n} مستندات.", "starred_n_one": "تم تمييز مستند واحد.",
		"move_failed": "تعذر نقل المستندات. حاول مرة أخرى.", "moved_n": "تم نقل {n} مستندات إلى «{folder}».", "moved_n_one": "تم نقل مستند واحد إلى «{folder}».",
		"unfiled_n": "تمت إزالة {n} مستندات من مجلداتها.", "unfiled_n_one": "تمت إزالة مستند واحد من مجلده.",
		"move_title": "نقل {n} مستندات", "move_title_one": "نقل مستند واحد", "move_current": "الحالي", "move_unfiled": "ليس في مجلد",
		"move_new_folder": "أو ضعها في مجلد جديد", "move_create_and_move": "إنشاء ونقل",
		"share_title": "مشاركة «{title}»", "share_add_people": "إضافة أشخاص", "share_placeholder": "اكتب اسمًا", "share_no_people": "لا أحد آخر يطابق هذا الاسم.",
		"share_with_n": "مشاركة مع {n} أشخاص", "share_with_n_one": "مشاركة مع شخص واحد", "shared_n": "تمت المشاركة مع {n} أشخاص.", "shared_n_one": "تمت المشاركة مع شخص واحد.",
		"share_failed_names": "تعذرت المشاركة مع {names}. حاول مرة أخرى.", "role_label": "الصلاحية", "role_commenter": "يمكنه التعليق", "role_viewer": "يمكنه العرض", "role_owner": "المالك",
		"role_label_for": "صلاحية {name}", "role_change_failed": "تعذر تغيير الصلاحية. حاول مرة أخرى.", "role_changed": "تم تحديث الصلاحية.",
		"access_heading": "الأشخاص الذين لديهم وصول", "access_loading": "جارٍ تحميل قائمة الوصول…", "access_failed": "تعذر تحميل قائمة الوصول.",
		"remove": "إزالة", "revoked": "لم يعد بإمكان {name} قراءة هذا المستند.", "revoke_failed": "تعذرت إزالة الوصول. حاول مرة أخرى.",
		"link_note": "يمكن فقط للأشخاص الذين لديهم وصول فتح هذا الرابط.", "close": "إغلاق", "outline": "في هذه الصفحة", "breadcrumb": "أنت هنا",
	},
}
