package productui

// personaAdminStylesheet gives the persona catalog and editors a scoped,
// responsive layout. Every selector stays under the persona administration
// page so workspace controls keep their existing visual contract.
func personaAdminStylesheet() string {
	return `.persona-admin-page{display:grid;gap:1.5rem;min-width:0;width:100%}
.persona-admin-page .persona-admin-hero,.persona-admin-page .persona-admin-catalog,.persona-admin-page .persona-admin-editor,.persona-admin-page .persona-admin-preview{min-width:0}
.persona-admin-page .persona-admin-hero,.persona-admin-page .persona-admin-catalog-heading{padding-inline:0}
.persona-admin-page .persona-admin-hero{display:grid;gap:.65rem}.persona-admin-page .persona-admin-hero>*{margin:0}.persona-admin-page .persona-admin-title-row{display:flex;align-items:center;justify-content:space-between;gap:1rem;min-width:0}.persona-admin-page .persona-admin-title-row h1{margin:0}.persona-admin-page .persona-admin-catalog-heading{display:grid;justify-items:start;gap:.35rem}.persona-admin-page .persona-admin-catalog-heading>*{margin:0}.persona-admin-page .persona-admin-new-agent-note{max-width:68ch}
.persona-admin-page .persona-admin-catalog,.persona-admin-page .persona-admin-editor,.persona-admin-page .persona-admin-preview{display:grid;gap:1rem}
.persona-admin-page .persona-admin-editor[hidden]{display:none}
.persona-admin-page .persona-admin-editor{padding:clamp(1rem,2.5vw,1.5rem);border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface)}
.persona-admin-page .persona-admin-lifecycle-list,.persona-admin-page .persona-admin-lifecycle,.persona-admin-page .persona-admin-cards,.persona-admin-page .persona-admin-entry{display:grid;gap:1rem;min-width:0}.persona-admin-page .persona-admin-lifecycle>h2{margin-inline:clamp(1rem,2.5vw,1.5rem)}
.persona-admin-page .persona-admin-card{display:grid;gap:1rem;min-width:0;padding:clamp(1rem,2.5vw,1.5rem);overflow-wrap:anywhere}
.persona-admin-page .persona-admin-card-heading{display:flex;align-items:center;justify-content:space-between;gap:.75rem;min-width:0}.persona-admin-page .persona-admin-card-title{flex:1 1 0;min-width:0}.persona-admin-page .persona-admin-status{flex:none;white-space:nowrap;overflow-wrap:normal;border:1px solid currentColor;background:transparent}.persona-admin-page .persona-admin-status[data-status-tone="in_review"]{color:var(--hcm-color-brand-primary)}
.persona-admin-page .persona-admin-actions,.persona-admin-page .persona-admin-primary-actions,.persona-admin-page .persona-admin-secondary-actions{display:grid;gap:.75rem;min-width:0}
.persona-admin-page .persona-admin-action-row{display:flex;flex-wrap:wrap;align-items:center;gap:.5rem .75rem}
.persona-admin-page .persona-admin-card h3,.persona-admin-page .persona-admin-card h4,.persona-admin-page .persona-admin-card p,.persona-admin-page .persona-admin-card ul{margin:0}
.persona-admin-page .persona-admin-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;min-width:0}
.persona-admin-page .persona-admin-fact{display:grid;gap:.25rem;min-width:0;overflow-wrap:anywhere}.persona-admin-page .persona-admin-fact dt,.persona-admin-page .persona-admin-fact dd{margin:0}
.persona-admin-page .persona-admin-review{display:grid;gap:.5rem;min-width:0}
.persona-admin-page .persona-admin-lifecycle-progress{display:grid;gap:.5rem}.persona-admin-page .persona-admin-progress-label{font-weight:600}.persona-admin-page .persona-admin-lifecycle-progress ol{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.25rem;list-style:none;margin:0;padding:0}.persona-admin-page .persona-admin-lifecycle-progress li{display:flex;align-items:center;justify-content:center;min-width:0;min-height:1.75rem;padding:.2rem .35rem;border-block-start:.25rem solid var(--hcm-color-border);color:var(--hcm-color-text-muted);font-size:.75rem;text-align:center}.persona-admin-page .persona-admin-lifecycle-progress li[data-step-state="complete"]{border-color:var(--hcm-color-brand-primary);color:var(--hcm-color-brand-primary);font-weight:700}.persona-admin-page .persona-admin-lifecycle-progress li[data-step-state="current"]{border-color:var(--hcm-color-brand-primary);color:var(--hcm-color-text);font-weight:700}
.persona-admin-page .persona-admin-skill-list,.persona-admin-page .persona-admin-installation-list,.persona-admin-page .persona-admin-preview-skills,.persona-admin-page .persona-admin-preview-warnings{display:grid;gap:.65rem;padding-inline-start:1.25rem}.persona-admin-page .persona-admin-skill,.persona-admin-page .persona-admin-preview-skill{display:flex;align-items:start;justify-content:space-between;gap:.75rem;min-width:0}.persona-admin-page .persona-admin-skill-copy{display:grid;flex:1 1 0;gap:.2rem;min-width:0}.persona-admin-page .persona-admin-tier{flex:none;white-space:nowrap;overflow-wrap:normal}.persona-admin-page .persona-admin-empty{margin:0}
.persona-admin-page .persona-admin-confirm{max-width:40rem}.persona-admin-page .persona-admin-confirm summary,.persona-admin-page .persona-admin-more-actions summary,.persona-admin-page .persona-admin-version-section>summary{cursor:pointer;font-weight:600}.persona-admin-page .persona-admin-more-actions{max-width:44rem}.persona-admin-page .persona-admin-next-action{display:grid;justify-items:start;gap:.5rem}.persona-admin-page .persona-admin-next-action p{max-width:64ch}.persona-admin-page .persona-admin-command-status:empty{display:none}.persona-admin-page .persona-admin-technical{padding-block-start:.5rem;border-block-start:1px solid var(--hcm-color-border)}.persona-admin-page .persona-admin-technical summary{cursor:pointer}.persona-admin-page .persona-admin-technical dl{display:grid;gap:.5rem}.persona-admin-page .persona-admin-technical dl>div{display:grid;grid-template-columns:minmax(7rem,.4fr) minmax(0,1fr);gap:.5rem}.persona-admin-page .persona-admin-technical dt,.persona-admin-page .persona-admin-technical dd{margin:0;overflow-wrap:anywhere}
.persona-admin-page .persona-admin-editor h2,.persona-admin-page .persona-admin-editor p{margin:0}
.persona-admin-page .persona-admin-editor-form,.persona-admin-page .persona-admin-version-editor{display:grid;gap:1rem;min-width:0}
.persona-admin-page .persona-admin-editor-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;min-width:0}
.persona-admin-page .persona-admin-editor-field{display:grid;align-content:start;gap:.45rem;min-width:0}
.persona-admin-page .persona-admin-editor-field label{font-weight:600;line-height:1.4;overflow-wrap:anywhere}
.persona-admin-page .persona-admin-editor-field input,.persona-admin-page .persona-admin-editor-field select,.persona-admin-page .persona-admin-editor-field textarea{display:block;box-sizing:border-box;width:100%;max-width:100%;min-width:0;min-height:2.75rem;padding:.65rem .75rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface);color:var(--hcm-color-text);font:inherit;line-height:1.4}
.persona-admin-page .persona-admin-editor-field textarea{min-height:7rem;resize:vertical;white-space:pre-wrap}
.persona-admin-page .persona-admin-editor-field input[readonly],.persona-admin-page .persona-admin-editor-field textarea[readonly]{background:var(--hcm-color-canvas);color:var(--hcm-color-text-muted)}
.persona-admin-page .persona-admin-instructions-meta{display:grid;gap:.25rem}.persona-admin-page .persona-admin-instructions-meta p{margin:0}
.persona-admin-page .persona-admin-built-in-instructions{min-width:0;padding:.75rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-canvas)}.persona-admin-page .persona-admin-built-in-instructions summary{cursor:pointer;font-weight:600}.persona-admin-page .persona-admin-built-in-instructions p{margin:.75rem 0 0;white-space:pre-wrap;overflow-wrap:anywhere}
.persona-admin-page .persona-admin-channel-choices{display:flex;flex-wrap:wrap;align-items:center;gap:.75rem 1.25rem;min-width:0;margin:0;padding:.75rem 1rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control)}
.persona-admin-page .persona-admin-channel-choices legend{padding-inline:.25rem;font-weight:600}
.persona-admin-page .persona-admin-channel{display:inline-flex;align-items:center;gap:.5rem;min-height:2.75rem;max-width:100%;overflow-wrap:anywhere}
.persona-admin-page .persona-admin-editor-form .button,.persona-admin-page .persona-admin-version-editor .button{justify-self:start;min-height:2.75rem;max-width:100%;white-space:normal}
.persona-admin-page .persona-admin-version-section{display:grid;gap:1rem;padding:clamp(1rem,2.5vw,1.5rem)}.persona-admin-page .persona-admin-version-section>summary{justify-self:start}.persona-admin-page .persona-admin-version-editor{margin-block-start:1rem;padding-block-start:1rem;border-block-start:1px solid var(--hcm-color-border)}
.persona-admin-page .persona-admin-version-fields{display:grid;gap:1rem;border:0;padding:0;margin:0;min-width:0}
.persona-admin-page .persona-admin-version-editor .persona-admin-channel-choices{margin-block-end:.25rem}
.persona-admin-page .persona-admin-reference-documents,.persona-admin-page .persona-admin-reference-documents ul{display:grid;gap:.5rem;min-width:0}.persona-admin-page .persona-admin-reference-documents ul{margin:0;padding-inline-start:1.25rem}
.persona-admin-page .persona-admin-instructions{display:grid;gap:.5rem}.persona-admin-page .persona-admin-instructions summary{cursor:pointer;font-weight:600}.persona-admin-page .persona-admin-instruction-chip{display:inline-flex;max-width:100%;margin-inline:.15rem;padding:.1rem .4rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-canvas);font-weight:600;overflow-wrap:anywhere}
.persona-admin-page .agentdoc-picker,.persona-admin-page .agentdoc-picker-unavailable{display:grid;gap:.75rem;min-width:0}.persona-admin-page .agentdoc-picker h5,.persona-admin-page .agentdoc-picker-unavailable h5,.persona-admin-page .agentdoc-picker p,.persona-admin-page .agentdoc-picker-unavailable p{margin:0}
.persona-admin-page .agentdoc-picker-combobox{position:relative;display:grid;gap:.4rem;min-width:0}.persona-admin-page .agentdoc-picker-combobox label{font-weight:600}.persona-admin-page .agentdoc-picker-combobox input,.persona-admin-page .agentdoc-picker-row select{box-sizing:border-box;width:100%;min-width:0;min-height:2.75rem;padding:.65rem .75rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-canvas);color:var(--hcm-color-text);font:inherit}
.persona-admin-page .agentdoc-picker-results{position:absolute;z-index:10;inset-block-start:100%;inset-inline:0;display:grid;gap:.25rem;max-height:18rem;overflow:auto;margin:.25rem 0 0;padding:.4rem;list-style:none;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface);box-shadow:var(--hcm-shadow-raised)}.persona-admin-page .agentdoc-picker-results[hidden]{display:none}.persona-admin-page .agentdoc-picker-option{display:grid;gap:.2rem;padding:.65rem;border-radius:var(--hcm-radius-control);cursor:pointer}.persona-admin-page .agentdoc-picker-option[aria-selected="true"]{outline:var(--hcm-focus-ring-width) solid var(--hcm-color-focus);background:var(--hcm-color-canvas)}
.persona-admin-page .agentdoc-picker-state{display:flex;align-items:center;flex-wrap:wrap;gap:.5rem}.persona-admin-page .agentdoc-picker-selected{display:grid;gap:.5rem;margin:0;padding:0;list-style:none}.persona-admin-page .agentdoc-picker-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(12rem,.55fr) auto;align-items:center;gap:.5rem;min-width:0;padding:.65rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control)}.persona-admin-page .agentdoc-picker-row>a,.persona-admin-page .agentdoc-picker-row-copy{min-width:0;overflow-wrap:anywhere}.persona-admin-page .agentdoc-picker-row-copy{display:grid;gap:.15rem}.persona-admin-page .agentdoc-picker-row.is-unreadable{grid-template-columns:minmax(0,1fr) auto}.persona-admin-page .agentdoc-picker-footer{display:grid;gap:.35rem}.persona-admin-page .agentdoc-picker-footer p{max-width:68ch}
.persona-admin-page .persona-admin-preview-controls{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));align-items:start;gap:.75rem;min-width:0}.persona-admin-page .persona-admin-preview-picker{display:grid;gap:.4rem;min-width:0}
.persona-admin-page .persona-admin-preview-controls label{font-weight:600;line-height:1.4;overflow-wrap:anywhere}
.persona-admin-page .persona-admin-preview-controls select,.persona-admin-page .persona-admin-preview-controls input{box-sizing:border-box;width:100%;min-width:0;min-height:2.75rem;padding:.65rem .75rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-canvas);color:var(--hcm-color-text);font:inherit;line-height:1.4}
.persona-admin-page .persona-admin-preview-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.75rem;min-width:0}
.persona-admin-page .persona-admin-preview-summary .persona-admin-fact{min-width:0;padding:.75rem;background:var(--hcm-color-canvas)}
.persona-admin-page .persona-admin-preview-summary .persona-admin-fact small{display:block;line-height:1.35;overflow-wrap:anywhere}
.persona-admin-page .persona-admin-preview-summary .persona-admin-fact strong{display:block;margin-block-start:.25rem;overflow-wrap:anywhere;word-break:break-word}
.persona-admin-page .persona-admin-page-links{display:flex;flex-wrap:wrap;gap:.5rem}.persona-admin-page .persona-admin-page-links [aria-current="page"]{font-weight:700}
.persona-admin-page .persona-admin-card-heading{align-items:flex-start}.persona-admin-page .persona-admin-card-controls{display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-end;gap:.5rem;min-width:0}.persona-admin-page .persona-admin-status[data-status-tone="published"]{border-color:var(--hcm-color-success);background:var(--hcm-color-success-surface);color:var(--hcm-color-success)}
.persona-admin-page .persona-admin-facts{align-items:start}.persona-admin-page .persona-admin-person-chip{display:inline-flex;align-items:center;gap:.5rem;max-width:100%}.persona-admin-page .persona-admin-person-chip .avatar{flex:none}.persona-admin-page .persona-admin-audience-details summary{cursor:pointer}.persona-admin-page .persona-admin-audience-details ul{margin:.4rem 0 0;padding-inline-start:1.25rem}.persona-admin-page .persona-admin-step-content{display:inline-flex;align-items:center;gap:.25rem}
.persona-admin-page .persona-admin-placements{display:grid;gap:.75rem}.persona-admin-page .persona-admin-subhead{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:.5rem}.persona-admin-page .persona-admin-installation-list{display:grid;gap:.65rem;margin:0;padding:0;list-style:none}.persona-admin-page .persona-admin-installation{display:grid;grid-template-columns:minmax(12rem,1fr) minmax(15rem,1.2fr) auto;align-items:start;gap:.75rem;padding:.75rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control)}.persona-admin-page .persona-admin-placement-main{display:flex;flex-wrap:wrap;align-items:center;gap:.35rem;min-width:0}.persona-admin-page .persona-admin-conversation-link{font-weight:700}.persona-admin-page .persona-admin-placement-documents{display:grid;gap:.35rem;margin:0}.persona-admin-page .persona-admin-placement-document-titles{margin:0;padding-inline-start:1.25rem}.persona-admin-page .persona-admin-placement-warning{margin:0;color:var(--hcm-color-warning)}.persona-admin-page .persona-admin-add-placement{position:relative}.persona-admin-page .persona-admin-add-placement-form{position:absolute;z-index:3;inset-inline-end:0;display:grid;gap:.5rem;width:min(22rem,calc(100vw - 2rem));margin-block-start:.4rem;padding:1rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface);box-shadow:var(--hcm-shadow-raised)}.persona-admin-page .persona-admin-add-placement-form select{box-sizing:border-box;width:100%;min-height:2.75rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface);color:var(--hcm-color-text);font:inherit}
.persona-admin-page .persona-admin-version-section{display:grid;gap:.75rem;padding:0}.persona-admin-page .persona-admin-version-section>summary{list-style:none;justify-self:start}.persona-admin-page .persona-admin-version-section>summary::-webkit-details-marker{display:none}.persona-admin-page .persona-admin-version-editor{width:100%;margin-block-start:.4rem;padding:1rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface)}
.persona-admin-page .persona-admin-preview{padding:clamp(1rem,2.5vw,1.5rem)}.persona-admin-page .persona-admin-preview-form{display:grid;justify-items:start;gap:1rem}.persona-admin-page .persona-admin-preview-controls{width:100%}.persona-admin-page .persona-admin-preview-controls input{background:var(--hcm-color-surface)}.persona-admin-page .persona-admin-published-approval,.persona-admin-page .persona-admin-evaluation-fallback{margin:0}.persona-admin-page .persona-admin-evaluation-fallback[hidden]{display:none}
.persona-admin-page .persona-admin-hero>p,.persona-admin-page .persona-admin-catalog-heading>p{max-inline-size:45rem}.persona-admin-page .persona-admin-hero-actions{display:flex;align-items:center;gap:.5rem}.persona-admin-page .persona-admin-breadcrumb{display:flex;align-items:center;gap:.35rem;font-size:.875rem}.persona-admin-page .persona-admin-card-identity{display:flex;align-items:center;gap:.75rem;min-width:0}.persona-admin-page .persona-admin-card-title{display:grid;text-align:start}.persona-admin-page .persona-admin-card-title h3{justify-self:start}.persona-admin-page .persona-admin-card-controls{flex-wrap:nowrap;align-items:center}.persona-admin-page .persona-admin-card-controls .button{display:inline-flex;align-items:center;justify-content:center;min-height:2.75rem}.persona-admin-page .persona-admin-skill-list{padding-inline-start:0;list-style:none}.persona-admin-page .persona-admin-tier{border:1px solid var(--hcm-color-success);border-radius:var(--hcm-radius-control);padding:.1rem .4rem;background:var(--hcm-color-success-surface);color:var(--hcm-color-success)}
.persona-admin-page .persona-admin-lifecycle-progress li[data-step-state="complete"]{border-color:var(--hcm-color-success);color:var(--hcm-color-success)}.persona-admin-page .persona-admin-page-links{flex-wrap:nowrap;gap:0;max-width:100%;overflow-x:auto}.persona-admin-page .persona-admin-page-links .button{border-radius:0;white-space:nowrap}.persona-admin-page .persona-admin-page-links .button:first-child{border-start-start-radius:var(--hcm-radius-control);border-end-start-radius:var(--hcm-radius-control)}.persona-admin-page .persona-admin-page-links .button:last-child{border-start-end-radius:var(--hcm-radius-control);border-end-end-radius:var(--hcm-radius-control)}.persona-admin-page .persona-admin-page-links .button+.button{margin-inline-start:-1px}.persona-admin-page .persona-admin-page-links [aria-current="page"]{background:var(--hcm-color-canvas)}
.persona-admin-page .agentdoc-instruction-control{position:relative;min-width:0}.persona-admin-page .agentdoc-mention-menu{position:absolute;z-index:11;inset-inline:0;inset-block-start:100%;display:grid;gap:.25rem;max-height:18rem;overflow:auto;margin-block-start:.25rem;padding:.4rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface);box-shadow:var(--hcm-shadow-raised)}.persona-admin-page .agentdoc-mention-menu[hidden]{display:none}.persona-admin-page .agentdoc-mention-menu p,.persona-admin-page .agentdoc-mention-results{margin:0}.persona-admin-page .agentdoc-mention-results{display:grid;gap:.25rem;padding:0;list-style:none}.persona-admin-page .field-error{margin:0;color:var(--hcm-color-danger)}.persona-admin-page .field-error[hidden]{display:none}
.persona-admin-page .persona-admin-installation{grid-template-columns:minmax(0,1fr) auto;width:100%}.persona-admin-page .persona-admin-placement-main>*{white-space:nowrap}.persona-admin-page .persona-admin-placement-documents,.persona-admin-page .persona-admin-placement-warning{grid-column:1}.persona-admin-page .persona-admin-placement-remove{grid-column:2;grid-row:1 / span 2;align-self:center}.persona-admin-page .persona-admin-preview-heading{display:grid;gap:.35rem;max-inline-size:45rem}.persona-admin-page .persona-admin-preview-heading>*{margin:0}.persona-admin-page .persona-admin-preview-controls select{background:var(--hcm-color-surface)}.persona-admin-page .persona-admin-date{white-space:nowrap;unicode-bidi:isolate}.persona-admin-page .persona-admin-next-step,.persona-admin-page .persona-admin-version-status{max-inline-size:45rem}
.persona-admin-page .persona-admin-more-actions>summary,.persona-admin-page .persona-admin-audience-details>summary,.persona-admin-page .persona-admin-technical>summary{list-style:none}.persona-admin-page .persona-admin-more-actions>summary::-webkit-details-marker,.persona-admin-page .persona-admin-audience-details>summary::-webkit-details-marker,.persona-admin-page .persona-admin-technical>summary::-webkit-details-marker{display:none}.persona-admin-page .persona-admin-audience-details>summary::before,.persona-admin-page .persona-admin-technical>summary::before{content:"›";display:inline-block;margin-inline-end:.4rem;transform:rotate(0deg)}.persona-admin-page [dir="rtl"] .persona-admin-audience-details>summary::before,.persona-admin-page[dir="rtl"] .persona-admin-technical>summary::before{transform:rotate(180deg)}.persona-admin-page .persona-admin-audience-details[open]>summary::before,.persona-admin-page .persona-admin-technical[open]>summary::before{transform:rotate(90deg)}
@media(max-width:50rem){.persona-admin-page{gap:1rem}.persona-admin-page .persona-admin-editor-grid,.persona-admin-page .persona-admin-preview-controls,.persona-admin-page .agentdoc-picker-row,.persona-admin-page .persona-admin-installation{grid-template-columns:minmax(0,1fr)}.persona-admin-page .persona-admin-editor{padding:1rem}.persona-admin-page .agentdoc-picker-row .button,.persona-admin-page .persona-admin-placement-remove{justify-self:start}}
@media(max-width:36rem){.persona-admin-page .persona-admin-title-row{align-items:flex-start;flex-direction:column}.persona-admin-page .persona-admin-preview-summary,.persona-admin-page .persona-admin-facts{grid-template-columns:minmax(0,1fr)}.persona-admin-page .persona-admin-card-heading{align-items:flex-start;flex-direction:column}.persona-admin-page .persona-admin-card-controls{justify-content:flex-start}.persona-admin-page .persona-admin-tier{align-self:flex-start}.persona-admin-page .persona-admin-skill{flex-direction:column}.persona-admin-page .persona-admin-lifecycle-progress ol{grid-template-columns:repeat(4,minmax(0,1fr))}.persona-admin-page .persona-admin-current-step{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.persona-admin-page .persona-admin-technical dl>div{grid-template-columns:minmax(0,1fr)}}
@media(max-width:30rem){.persona-admin-page .persona-admin-lifecycle-progress ol{grid-template-columns:minmax(0,1fr)}.persona-admin-page .persona-admin-lifecycle-progress li:not([data-step-state="current"]){display:none}.persona-admin-page .persona-admin-lifecycle-progress li[data-step-state="current"]{justify-content:flex-start}.persona-admin-page .persona-admin-page-links .button{flex:1 1 auto}.persona-admin-page .persona-admin-card-controls{width:100%}}
@media(max-width:50rem){.persona-admin-page .persona-admin-placement-documents,.persona-admin-page .persona-admin-placement-warning,.persona-admin-page .persona-admin-placement-remove{grid-column:1;grid-row:auto}.persona-admin-page .persona-admin-placement-remove{justify-self:end}}
@media(max-width:30rem){.persona-admin-page .persona-admin-card-heading{width:100%}.persona-admin-page .persona-admin-card-identity{width:100%;justify-content:space-between}.persona-admin-page .persona-admin-card-controls{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));width:100%}.persona-admin-page .persona-admin-card-controls>*{min-width:0}.persona-admin-page .persona-admin-card-controls .button{width:100%;padding-inline:.4rem}.persona-admin-page .persona-admin-version-section>summary,.persona-admin-page .persona-admin-more-actions>summary{width:100%}.persona-admin-page .persona-admin-page-links .button{flex:0 0 auto}.persona-admin-page .persona-admin-card[data-lifecycle="PUBLISHED"] .persona-admin-lifecycle-progress li[data-step-state="complete"]{display:flex;justify-content:flex-start}}
@media(max-width:22rem){.persona-admin-page .persona-admin-editor-form .button,.persona-admin-page .persona-admin-version-editor .button{width:100%}}
.persona-admin-page .persona-admin-card{position:relative}.persona-admin-page .persona-admin-card-heading{align-items:center}.persona-admin-page .persona-admin-card-identity{align-items:flex-start;flex-wrap:wrap}.persona-admin-page .persona-admin-statuses{display:inline-flex;align-items:center;flex-wrap:wrap;gap:.4rem}.persona-admin-page .persona-admin-card-controls,.persona-admin-page .persona-admin-card-controls>*{align-self:center}.persona-admin-page .persona-admin-card-controls .button{height:2.75rem;white-space:nowrap}.persona-admin-page .persona-admin-purpose{max-inline-size:none}.persona-admin-page .persona-admin-hero>p,.persona-admin-page .persona-admin-catalog-heading>p,.persona-admin-page .persona-admin-preview-heading,.persona-admin-page .persona-admin-version-status{max-inline-size:none;width:100%}
.persona-admin-page .persona-admin-version-editor{box-sizing:border-box;display:grid;width:100%;margin:0;padding:clamp(1rem,2.5vw,1.5rem);border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface)}.persona-admin-page .persona-admin-version-editor[hidden]{display:none}.persona-admin-page .persona-admin-version-actions{display:flex;flex-wrap:wrap;gap:.75rem}.persona-admin-page .persona-admin-version-actions .button{margin:0}.persona-admin-page .persona-admin-instruction-mentions{display:flex;align-items:center;flex-wrap:wrap;gap:.35rem}.persona-admin-page .persona-admin-editor-field textarea[name="purpose"]{min-height:4.5rem}.persona-admin-page .persona-admin-channel[data-persona-channel-display]{padding-inline:.2rem}.persona-admin-page .persona-admin-skill{display:block}.persona-admin-page .persona-admin-skill-title{display:flex;align-items:center;flex-wrap:wrap;gap:.5rem}.persona-admin-page .persona-admin-tier{align-self:auto}
.persona-admin-page .persona-admin-secondary-actions{box-sizing:border-box;display:grid;gap:.75rem;width:min(28rem,calc(100vw - 2rem));margin:0;padding:1rem;border:1px solid var(--hcm-color-border);border-radius:var(--hcm-radius-control);background:var(--hcm-color-surface);box-shadow:var(--hcm-shadow-raised)}.persona-admin-page .persona-admin-secondary-actions:popover-open{display:grid}.persona-admin-page .persona-admin-secondary-actions .persona-admin-action-row{display:grid;gap:.35rem}.persona-admin-page .persona-admin-secondary-actions .button{justify-self:start}
.persona-admin-page .persona-admin-installation{box-sizing:border-box;grid-template-columns:minmax(0,1fr) auto;width:100%}.persona-admin-page .persona-admin-installation-list{box-sizing:border-box;width:100%;padding-inline-start:0}.persona-admin-page .persona-admin-placement-document-titles{padding-inline-start:1.25rem;text-align:start}.persona-admin-page .persona-admin-placement-document-titles li{padding-inline-start:.15rem}.persona-admin-page .persona-admin-placement-document-titles a{unicode-bidi:isolate}.persona-admin-page .persona-admin-popover-actions{display:flex;flex-wrap:wrap;gap:.5rem}
.persona-admin-page .persona-admin-reference-documents>ul{margin:0;padding-inline-start:1.25rem}.persona-admin-page .persona-admin-reference-documents li{display:grid;grid-template-columns:max-content max-content;align-items:baseline;justify-content:start;gap:0}.persona-admin-page .persona-admin-reference-documents .persona-admin-document-warning{grid-column:1 / -1;color:var(--hcm-color-warning)}.persona-admin-page .agentdoc-picker-error{padding:.75rem;border:1px solid var(--hcm-color-warning);border-radius:var(--hcm-radius-control);background:var(--hcm-color-canvas)}
.persona-admin-page .persona-admin-lifecycle-progress li{font-size:.875rem}.persona-admin-page .persona-admin-lifecycle-progress li[data-step-state="current"]{font-weight:600}.persona-admin-page .persona-admin-mobile-progress{display:none;margin:.4rem 0 0;font-size:.875rem;font-weight:600}.persona-admin-page .persona-admin-lifecycle-block{display:grid;justify-items:start;gap:.6rem}.persona-admin-page .persona-admin-lifecycle-block>*{margin:0}.persona-admin-page .persona-admin-command-status:not(:empty){margin:0;padding:.75rem;border:1px solid var(--hcm-color-success);border-radius:var(--hcm-radius-control);background:var(--hcm-color-success-surface);color:var(--hcm-color-success)}.persona-admin-page .persona-admin-unreadable-review{display:grid;justify-items:start;gap:.65rem}.persona-admin-page .persona-admin-unreadable-review label{display:flex;align-items:flex-start;gap:.5rem}
.persona-admin-page .persona-admin-audience-details>summary,.persona-admin-page .persona-admin-technical>summary,.persona-admin-page .persona-admin-instructions>summary,.persona-admin-page .persona-admin-built-in-instructions>summary{list-style:none;cursor:pointer;font-size:1rem;font-weight:600}.persona-admin-page .persona-admin-audience-details>summary::-webkit-details-marker,.persona-admin-page .persona-admin-technical>summary::-webkit-details-marker,.persona-admin-page .persona-admin-instructions>summary::-webkit-details-marker,.persona-admin-page .persona-admin-built-in-instructions>summary::-webkit-details-marker{display:none}.persona-admin-page .persona-admin-audience-details>summary::before,.persona-admin-page .persona-admin-technical>summary::before,.persona-admin-page .persona-admin-instructions>summary::before,.persona-admin-page .persona-admin-built-in-instructions>summary::before{content:"›";display:inline-block;margin-inline-end:.4rem}.persona-admin-page .persona-admin-audience-details[open]>summary::before,.persona-admin-page .persona-admin-technical[open]>summary::before,.persona-admin-page .persona-admin-instructions[open]>summary::before,.persona-admin-page .persona-admin-built-in-instructions[open]>summary::before{transform:rotate(90deg)}.persona-admin-page .persona-admin-built-in-instructions{padding:0;border:0;background:transparent}
@media(max-width:50rem){.persona-admin-page .persona-admin-card-heading{align-items:flex-start}.persona-admin-page .persona-admin-card-controls{align-self:flex-start}.persona-admin-page .persona-admin-version-editor{width:100%}.persona-admin-page .persona-admin-installation{grid-template-columns:minmax(0,1fr)}.persona-admin-page .persona-admin-placement-remove{justify-self:start}.persona-admin-page .persona-admin-add-placement-form{position:fixed;inset:auto 1rem 1rem;width:auto;max-height:calc(100vh - 2rem);overflow:auto}}
@media(max-width:30rem){.persona-admin-page .persona-admin-lifecycle-progress ol{grid-template-columns:repeat(4,minmax(0,1fr))}.persona-admin-page .persona-admin-lifecycle-progress li,.persona-admin-page .persona-admin-lifecycle-progress li:not([data-step-state="current"]){display:flex;min-width:0}.persona-admin-page .persona-admin-lifecycle-progress .persona-admin-step-label{position:absolute;inline-size:1px;block-size:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}.persona-admin-page .persona-admin-mobile-progress{display:block}.persona-admin-page .persona-admin-card-identity{justify-content:flex-start}.persona-admin-page .persona-admin-card-controls{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));width:100%}.persona-admin-page .persona-admin-card-controls .button{height:2.75rem}.persona-admin-page .persona-admin-statuses{width:100%}.persona-admin-page .persona-admin-reference-documents li{grid-template-columns:minmax(0,1fr)}}
@media(max-width:24.375rem){.persona-admin-page .persona-admin-card,.persona-admin-page .persona-admin-version-editor,.persona-admin-page .persona-admin-installation{min-width:0;max-width:100%}}
@media(max-width:20rem){.persona-admin-page .persona-admin-card-controls{gap:.35rem}.persona-admin-page .persona-admin-card-controls .button{padding-inline:.3rem;font-size:.875rem}}
.persona-admin-page [popover]:not(:popover-open){display:none}
.persona-admin-page .persona-admin-secondary-actions:popover-open,.persona-admin-page .persona-admin-add-placement-form:popover-open{position:fixed;inset:auto;inset-block-start:anchor(bottom);inset-inline-end:anchor(end);margin-block-start:.25rem}`
}
