package productui

import "github.com/monstercameron/human-capital-management-suite/internal/experience/localize"

// workflowEditorMessages is the reviewed English copy for the draft editor.
// It is merged into the default catalog, so coverage tooling counts every key
// here against the other locales.
//
// The effect, reversal, lock, overlay and source vocabularies had no catalog
// entries at all: the editor fell back to a title-cased token, which reads as
// plausible English and so passed every "no missing key marker" check while
// showing "Internal Mutation" to German and Arabic authors.
func workflowEditorMessages() map[string]localize.Message {
	return map[string]localize.Message{
		"workflow_editor.back":                    {Text: "Workflows"},
		"workflow_editor.name_label":              {Text: "Workflow name"},
		"workflow_editor.version":                 {Text: "Draft {version}"},
		"workflow_editor.path_label":              {Text: "Workflow path"},
		"workflow_editor.inspector_label":         {Text: "Step settings"},
		"workflow_editor.pick_step":               {Text: "Choose a step to see its settings."},
		"workflow_editor.empty_detail":            {Text: "Pick one here, or add any step from the library."},
		"workflow_editor.ready":                   {Text: "Nothing left to finish"},
		"workflow_editor.problem_count":           {Plural: map[string]string{"one": "{count} thing to finish", "other": "{count} things to finish"}},
		"workflow_editor.problem_loose":           {Text: "{step} isn't connected to the path."},
		"workflow_editor.problem_open":            {Text: "{step}: choose where {route} goes."},
		"workflow_editor.problem_unbound":         {Text: "{step}: choose a value for {input}."},
		"workflow_editor.problem_no_exit":         {Text: "Add an End step so the workflow can finish."},
		"workflow_editor.loose_title":             {Text: "Not connected yet"},
		"workflow_editor.loose_detail":            {Text: "Nothing leads to these steps yet. Pick one, then choose the earlier result that should lead to it under “Connect this step”."},
		"workflow_editor.exits_title":             {Text: "Exits"},
		"workflow_editor.exit_routes":             {Plural: map[string]string{"one": "{count} route ends here", "other": "{count} routes end here"}},
		"workflow_editor.route_to":                {Text: "{route} goes to {target}"},
		"workflow_editor.jump":                    {Text: "{route} goes to {target}"},
		"workflow_editor.jump_back":               {Text: "{route} goes back to {target}"},
		"workflow_editor.open_count":              {Plural: map[string]string{"one": "{count} result isn't connected", "other": "{count} results aren't connected"}},
		"workflow_editor.todo_count":              {Plural: map[string]string{"one": "{count} to finish", "other": "{count} to finish"}},
		"workflow_editor.required":                {Text: "Required control"},
		"workflow_editor.locked_detail":           {Text: "Required control ({kind}). Its settings can change, but it can't be removed or replaced."},
		"workflow_editor.settings":                {Text: "Settings"},
		"workflow_editor.outcomes":                {Text: "When this step ends"},
		"workflow_editor.uses":                    {Text: "Uses"},
		"workflow_editor.uses_help":               {Text: "Values this step takes from earlier steps."},
		"workflow_editor.target_steps":            {Text: "Steps"},
		"workflow_editor.target_exits":            {Text: "Exits"},
		"workflow_editor.also_goes_to":            {Text: "Also goes to {targets}."},
		"workflow_editor.binding_option":          {Text: "{field} · {step}"},
		"workflow_editor.remove_step":             {Text: "Remove step"},
		"workflow_editor.change":                  {Text: "{kind}: {subject} {field}"},
		"workflow_editor.saved":                   {Text: "Saved"},
		"workflow_editor.error_conflict":          {Text: "This draft changed somewhere else. The latest version is loaded, so make the change again."},
		"workflow_editor.error_refused":           {Text: "That change isn't allowed here."},
		"workflow_editor.error_denied":            {Text: "You don't have access to change this draft."},
		"workflow_editor.error_gone":              {Text: "This draft is no longer available."},
		"workflow_editor.error_offline":           {Text: "Couldn't reach the server. Check your connection and try again."},
		"workflow_editor.empty_title":             {Text: "Start with a first step"},
		"workflow_editor.history_position":        {Text: "Change {position} of {length}"},
		"workflow_editor.exceptions":              {Text: "If something goes wrong"},
		"workflow_editor.not_set":                 {Text: "Not set"},
		"workflow_editor.step_name_label":         {Text: "Step name"},
		"workflow_editor.connect_from":            {Text: "Connect this step"},
		"workflow_editor.connect_from_help":       {Text: "Choose the earlier result that should lead here."},
		"workflow_editor.connect_from_choose":     {Text: "Choose a result"},
		"workflow_editor.connect_from_option":     {Text: "{step}: {route}"},
		"workflow_editor.parity_template_exact":   {Text: "Matches the approved template"},
		"workflow_editor.parity_template_changed": {Text: "Changed from the approved template"},
		"workflow_editor.parity_exact":            {Text: "Matches the released version"},
		"workflow_editor.parity_changed":          {Text: "Changed from the released version"},
		"workflow_editor.library_title":           {Text: "Add a step"},
		"workflow_editor.edit_step":               {Text: "Edit {step}"},
		"workflow_editor.choose_replacement":      {Text: "Choose a replacement"},
		"workflow_editor.exceptions_unset":        {Plural: map[string]string{"one": "{count} not set", "other": "{count} not set"}},
		"workflow_editor.decision_basis":          {Text: "Chooses between {choices} using {inputs}."},
		"workflow_editor.decision_basis_plain":    {Text: "Chooses between {choices}."},
		"workflow_editor.library_show_all":        {Plural: map[string]string{"one": "Show {count} step", "other": "Show all {count} steps"}},
		"workflow_editor.library_show_fewer":      {Plural: map[string]string{"one": "Show fewer", "other": "Show fewer"}},
		"workflow_editor.open_others":             {Text: "Other results lead nowhere yet"},
		"workflow_editor.open_some":               {Text: "Some results lead nowhere yet"},
		"workflow_editor.open_none_lead":          {Text: "No result leads anywhere yet"},
		"workflow_editor.exits_hint_end":          {Text: "An End is not a row. It shows as a chip on every step that reaches it, and here."},
		"workflow_editor.decision_rule_note":      {Text: "These choices come from the decision rule on this step. Rules can't be edited here yet."},
		"workflow_editor.library_count":           {Plural: map[string]string{"one": "{count} step", "other": "{count} steps"}},
		"workflow_editor.all_results_end":         {Text: "Every result of this step ends the workflow"},
		"workflow_editor.binding_from":            {Text: "from {step}"},
		"workflow_editor.problems_title":          {Text: "Still to finish"},
		"workflow_editor.selected_step":           {Text: "Editing {step}"},
		"workflow_editor.rail_skip":               {Text: "Solid line: skips ahead"},
		"workflow_editor.rail_loop":               {Text: "Dashed line: loops back"},
		"workflow_editor.continues":               {Text: "{route} continues below to {target}"},
		"workflow_editor.arrives_from":            {Text: "Arrives from {step} ({route})"},
		"workflow_editor.ways_out":                {Plural: map[string]string{"one": "{count} way out", "other": "{count} ways out"}},
		"workflow_editor.ends_here":               {Text: "Nothing continues from here"},
		"workflow_editor.problem_exceptions":      {Plural: map[string]string{"one": "{step}: {count} result for when something goes wrong leads nowhere.", "other": "{step}: {count} results for when something goes wrong lead nowhere."}},
		"workflow_editor.jump_many":               {Text: "{route} go to {target}"},
		"workflow_editor.jump_back_many":          {Text: "{route} go back to {target}"},
		"workflow_editor.list_join":               {Text: " and "},
		"workflow_editor.exits_hint_selected":     {Text: "Highlighted: where {step} can finish."},
		"workflow_editor.more_exits":              {Text: "+{count} more"},
		"workflow_editor.nothing_follows":         {Text: "Nothing follows this step yet"},
		"workflow_editor.exit_route_count":        {Plural: map[string]string{"one": "{count} route", "other": "{count} routes"}},
		"workflow_editor.exits_hint":              {Text: "Where this workflow can finish."},
		"workflow_editor.history":                 {Text: "History"},
		"workflow_editor.saved_all":               {Text: "All changes saved"},
		"workflow_editor.exceptions_summary":      {Plural: map[string]string{"one": "{count} result", "other": "{count} results"}},
		"workflow_editor.decision_needs_rule":     {Text: "This decision has no choices yet. Choices come from a decision rule, and rules can't be written in the editor yet."},
		"workflow_palette.domain.rewards":         {Text: "Pay"},
		"workflow_editor.bulk_label":              {Plural: map[string]string{"one": "Send {count} unset result to", "other": "Send all {count} unset results to"}},
		"workflow_editor.bulk_choose":             {Text: "Choose an exit"},
		"workflow_editor.bulk_needs_exit":         {Text: "Add an End step, then send these results to it in one go."},
		"workflow_editor.back_to_path":            {Text: "Back to the path"},
		"workflow_palette.domain.control_flow":    {Text: "Flow"},
		"workflow_palette.domain.people":          {Text: "People"},
		"workflow_palette.domain.intelligence":    {Text: "Insight"},
		"workflow_palette.domain.operations":      {Text: "Operations"},
		"workflow_palette.domain.registry":        {Text: "Reference"},
		"workflow_viewer.outcome.succeeded":       {Text: "Done"},
		"workflow_viewer.outcome.ambiguous":       {Text: "Unclear result"},
		"workflow_viewer.outcome.unknown":         {Text: "Any other result"},
		"workflow_viewer.outcome.pass":            {Text: "Matches"},
		"workflow_viewer.outcome.fail":            {Text: "Doesn't match"},
		"workflow_viewer.outcome.partial":         {Text: "Partly matches"},
		"workflow_viewer.outcome.fired":           {Text: "Time reached"},
		"workflow_viewer.outcome.late":            {Text: "Too late"},
		"workflow_viewer.outcome.compensated":     {Text: "Undone"},
		"workflow_viewer.outcome.repair_required": {Text: "Needs repair"},
		"workflow_viewer.outcome.consistent":      {Text: "Consistent"},
		"workflow_viewer.outcome.degraded":        {Text: "Partly consistent"},
		"workflow_viewer.outcome.blocked":         {Text: "Blocked"},
		"workflow_viewer.outcome.valid":           {Text: "Still valid"},
		"workflow_viewer.outcome.complete":        {Text: "Complete"},
		"workflow_viewer.outcome.repair_plan":     {Text: "Needs repair"},

		"workflow_editor.parameter.display_name":           {Text: "Name"},
		"workflow_editor.parameter.retry_max_attempts":     {Text: "Maximum attempts"},
		"workflow_editor.parameter.signal_event_type":      {Text: "Event type"},
		"workflow_editor.parameter.signal_timeout_seconds": {Text: "Stop waiting after (seconds)"},
		"workflow_editor.parameter.wait_wake_kind":         {Text: "Wake on"},
		"workflow_editor.parameter.wait_zone":              {Text: "Time zone"},
		"workflow_editor.parameter.wait_calendar":          {Text: "Business calendar"},

		"workflow_palette.cannot_add":       {Text: "A template can only start an empty workflow."},
		"workflow_palette.step.approval":    {Text: "Ask someone to approve before work continues."},
		"workflow_palette.step.decision":    {Text: "Choose the next step from what is known so far."},
		"workflow_palette.step.end":         {Text: "Finish the workflow with a named outcome."},
		"workflow_palette.step.join":        {Text: "Wait for parallel branches to finish."},
		"workflow_palette.step.observe":     {Text: "Check that another system shows the expected result."},
		"workflow_palette.step.parallel":    {Text: "Run several branches at the same time."},
		"workflow_palette.step.signal":      {Text: "Wait for an event from another system."},
		"workflow_palette.step.subworkflow": {Text: "Run another published workflow."},
		"workflow_palette.step.task":        {Text: "Give a person something to do."},
		"workflow_palette.step.transform":   {Text: "Reshape values for a later step."},
		"workflow_palette.step.wait":        {Text: "Pause until a date or time."},

		"workflow_viewer.effect.pure":                           {Text: "No side effects"},
		"workflow_viewer.effect.read_only":                      {Text: "Reads data"},
		"workflow_viewer.effect.internal_mutation":              {Text: "Changes HR data"},
		"workflow_viewer.effect.external_mutation":              {Text: "Changes another system"},
		"workflow_viewer.effect.irreversible_external_mutation": {Text: "Changes another system permanently"},
		"workflow_viewer.reversal.no_effect":                    {Text: "Nothing to undo"},
		"workflow_viewer.reversal.compensation_required":        {Text: "Undone by a compensating step"},
		"workflow_viewer.reversal.compensate_or_correct":        {Text: "Undone or corrected afterwards"},
		"workflow_viewer.reversal.forward_correction":           {Text: "Can only be corrected afterwards"},
		"workflow_viewer.reversal.unresolved":                   {Text: "Reversal not defined"},
		"workflow_viewer.lock.start":                            {Text: "start"},
		"workflow_viewer.lock.governance":                       {Text: "approval"},
		"workflow_viewer.lock.revalidation":                     {Text: "revalidation"},
		"workflow_viewer.lock.reconciliation":                   {Text: "reconciliation"},
		"workflow_viewer.lock.closure":                          {Text: "closing"},
		"workflow_viewer.overlay.add":                           {Text: "Added"},
		"workflow_viewer.overlay.omit":                          {Text: "Left out"},
		"workflow_viewer.overlay.replace":                       {Text: "Replaced"},
		"workflow_viewer.source.workflow_input":                 {Text: "From the request that starts this workflow"},
		"workflow_viewer.source.context":                        {Text: "From the run's context"},
		"workflow_viewer.source.constant":                       {Text: "A fixed value"},
		"workflow_viewer.source.node_output":                    {Text: "From an earlier step"},
	}
}

// workflowEditorTranslations returns the editor's copy for one non-default
// locale. Arabic carries all six plural categories; the two-form shortcut it
// replaces produced "2 خطوة".
func workflowEditorTranslations(locale string) map[string]localize.Message {
	text := func(value string) localize.Message { return localize.Message{Text: value} }
	switch locale {
	case "de-DE":
		return map[string]localize.Message{
			"workflow_editor.back":                    text("Workflows"),
			"workflow_editor.name_label":              text("Name des Workflows"),
			"workflow_editor.version":                 text("Entwurf {version}"),
			"workflow_editor.path_label":              text("Ablauf des Workflows"),
			"workflow_editor.inspector_label":         text("Einstellungen des Schritts"),
			"workflow_editor.pick_step":               text("Wählen Sie einen Schritt, um seine Einstellungen zu sehen."),
			"workflow_editor.empty_detail":            text("Wählen Sie hier einen aus oder fügen Sie einen beliebigen Schritt aus der Bibliothek hinzu."),
			"workflow_editor.ready":                   text("Nichts mehr offen"),
			"workflow_editor.problem_count":           {Plural: map[string]string{"one": "{count} offener Punkt", "other": "{count} offene Punkte"}},
			"workflow_editor.problem_loose":           text("{step} ist nicht mit dem Ablauf verbunden."),
			"workflow_editor.problem_open":            text("{step}: Legen Sie fest, wohin {route} führt."),
			"workflow_editor.problem_unbound":         text("{step}: Wählen Sie einen Wert für {input}."),
			"workflow_editor.problem_no_exit":         text("Fügen Sie einen Ende-Schritt hinzu, damit der Workflow abschließen kann."),
			"workflow_editor.loose_title":             text("Noch nicht verbunden"),
			"workflow_editor.loose_detail":            text("Noch führt nichts zu diesen Schritten. Wählen Sie einen aus und legen Sie mit „Diesen Schritt verbinden“ fest, welches Ergebnis hierher führen soll."),
			"workflow_editor.exits_title":             text("Ausgänge"),
			"workflow_editor.exit_routes":             {Plural: map[string]string{"one": "{count} Weg endet hier", "other": "{count} Wege enden hier"}},
			"workflow_editor.route_to":                text("{route} führt zu {target}"),
			"workflow_editor.jump":                    text("{route} führt zu {target}"),
			"workflow_editor.jump_back":               text("{route} führt zurück zu {target}"),
			"workflow_editor.open_count":              {Plural: map[string]string{"one": "{count} Ergebnis ist nicht verbunden", "other": "{count} Ergebnisse sind nicht verbunden"}},
			"workflow_editor.todo_count":              {Plural: map[string]string{"one": "{count} offen", "other": "{count} offen"}},
			"workflow_editor.required":                text("Pflichtkontrolle"),
			"workflow_editor.locked_detail":           text("Pflichtkontrolle ({kind}). Die Einstellungen lassen sich ändern, der Schritt kann aber nicht entfernt oder ersetzt werden."),
			"workflow_editor.settings":                text("Einstellungen"),
			"workflow_editor.outcomes":                text("Wenn dieser Schritt endet"),
			"workflow_editor.uses":                    text("Verwendet"),
			"workflow_editor.uses_help":               text("Werte, die dieser Schritt aus früheren Schritten übernimmt."),
			"workflow_editor.target_steps":            text("Schritte"),
			"workflow_editor.target_exits":            text("Ausgänge"),
			"workflow_editor.also_goes_to":            text("Führt außerdem zu {targets}."),
			"workflow_editor.binding_option":          text("{field} · {step}"),
			"workflow_editor.remove_step":             text("Schritt entfernen"),
			"workflow_editor.change":                  text("{kind}: {subject} {field}"),
			"workflow_editor.saved":                   text("Gespeichert"),
			"workflow_editor.error_conflict":          text("Dieser Entwurf wurde an anderer Stelle geändert. Die aktuelle Fassung ist geladen; nehmen Sie die Änderung bitte erneut vor."),
			"workflow_editor.error_refused":           text("Diese Änderung ist hier nicht zulässig."),
			"workflow_editor.error_denied":            text("Sie haben keine Berechtigung, diesen Entwurf zu ändern."),
			"workflow_editor.error_gone":              text("Dieser Entwurf ist nicht mehr verfügbar."),
			"workflow_editor.error_offline":           text("Der Server ist nicht erreichbar. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut."),
			"workflow_editor.empty_title":             text("Beginnen Sie mit einem ersten Schritt"),
			"workflow_editor.history_position":        text("Änderung {position} von {length}"),
			"workflow_editor.exceptions":              text("Wenn etwas schiefgeht"),
			"workflow_editor.not_set":                 text("Nicht festgelegt"),
			"workflow_editor.step_name_label":         text("Name des Schritts"),
			"workflow_editor.connect_from":            text("Diesen Schritt verbinden"),
			"workflow_editor.connect_from_help":       text("Wählen Sie das frühere Ergebnis, das hierher führen soll."),
			"workflow_editor.connect_from_choose":     text("Ergebnis wählen"),
			"workflow_editor.connect_from_option":     text("{step}: {route}"),
			"workflow_editor.parity_template_exact":   text("Entspricht der Vorlage"),
			"workflow_editor.parity_template_changed": text("Weicht von der Vorlage ab"),
			"workflow_editor.parity_exact":            text("Entspricht der Freigabe"),
			"workflow_editor.parity_changed":          text("Weicht von der Freigabe ab"),
			"workflow_editor.library_title":           text("Schritt hinzufügen"),
			"workflow_editor.edit_step":               text("{step} bearbeiten"),
			"workflow_editor.choose_replacement":      text("Ersatz wählen"),
			"workflow_editor.exceptions_unset":        {Plural: map[string]string{"one": "{count} nicht festgelegt", "other": "{count} nicht festgelegt"}},
			"workflow_editor.decision_basis":          text("Wählt zwischen {choices} anhand von {inputs}."),
			"workflow_editor.decision_basis_plain":    text("Wählt zwischen {choices}."),
			"workflow_editor.library_show_all":        {Plural: map[string]string{"one": "{count} Schritt anzeigen", "other": "Alle {count} Schritte anzeigen"}},
			"workflow_editor.library_show_fewer":      {Plural: map[string]string{"one": "Weniger anzeigen", "other": "Weniger anzeigen"}},
			"workflow_editor.open_others":             text("Andere Ergebnisse führen noch nirgendwohin"),
			"workflow_editor.open_some":               text("Einige Ergebnisse führen noch nirgendwohin"),
			"workflow_editor.open_none_lead":          text("Noch führt kein Ergebnis irgendwohin"),
			"workflow_editor.exits_hint_end":          text("Ein Ende ist keine Zeile. Es erscheint als Marke an jedem Schritt, der es erreicht, und hier."),
			"workflow_editor.decision_rule_note":      text("Diese Auswahlmöglichkeiten stammen aus der Entscheidungsregel dieses Schritts. Regeln lassen sich hier noch nicht bearbeiten."),
			"workflow_editor.library_count":           {Plural: map[string]string{"one": "{count} Schritt", "other": "{count} Schritte"}},
			"workflow_editor.all_results_end":         text("Jedes Ergebnis dieses Schritts beendet den Workflow"),
			"workflow_editor.binding_from":            text("aus {step}"),
			"workflow_editor.problems_title":          text("Noch offen"),
			"workflow_editor.selected_step":           text("{step} wird bearbeitet"),
			"workflow_editor.rail_skip":               text("Durchgezogene Linie: überspringt Schritte"),
			"workflow_editor.rail_loop":               text("Gestrichelte Linie: führt zurück"),
			"workflow_editor.continues":               text("{route} führt unten weiter zu {target}"),
			"workflow_editor.arrives_from":            text("Kommt von {step} ({route})"),
			"workflow_editor.ways_out":                {Plural: map[string]string{"one": "{count} Ausgang", "other": "{count} Ausgänge"}},
			"workflow_editor.ends_here":               text("Von hier geht es nicht weiter"),
			"workflow_editor.problem_exceptions":      {Plural: map[string]string{"one": "{step}: {count} Ergebnis für den Fehlerfall führt nirgendwohin.", "other": "{step}: {count} Ergebnisse für den Fehlerfall führen nirgendwohin."}},
			"workflow_editor.jump_many":               text("{route} führen zu {target}"),
			"workflow_editor.jump_back_many":          text("{route} führen zurück zu {target}"),
			"workflow_editor.list_join":               text(" und "),
			"workflow_editor.exits_hint_selected":     text("Hervorgehoben: wo {step} enden kann."),
			"workflow_editor.more_exits":              text("+{count} weitere"),
			"workflow_editor.nothing_follows":         text("Auf diesen Schritt folgt noch nichts"),
			"workflow_editor.exit_route_count":        {Plural: map[string]string{"one": "{count} Weg", "other": "{count} Wege"}},
			"workflow_editor.exits_hint":              text("Hier kann dieser Workflow enden."),
			"workflow_editor.history":                 text("Verlauf"),
			"workflow_editor.saved_all":               text("Alle Änderungen gespeichert"),
			"workflow_editor.exceptions_summary":      {Plural: map[string]string{"one": "{count} Ergebnis", "other": "{count} Ergebnisse"}},
			"workflow_editor.decision_needs_rule":     text("Diese Entscheidung hat noch keine Auswahlmöglichkeiten. Sie stammen aus einer Entscheidungsregel, und Regeln lassen sich im Editor noch nicht verfassen."),
			"workflow_palette.domain.rewards":         text("Vergütung"),
			"workflow_editor.bulk_label":              {Plural: map[string]string{"one": "{count} offenes Ergebnis senden an", "other": "Alle {count} offenen Ergebnisse senden an"}},
			"workflow_editor.bulk_choose":             text("Ausgang wählen"),
			"workflow_editor.bulk_needs_exit":         text("Fügen Sie einen Ende-Schritt hinzu und leiten Sie diese Ergebnisse dann gesammelt dorthin."),
			"workflow_editor.back_to_path":            text("Zurück zum Ablauf"),
			"workflow_palette.domain.control_flow":    text("Ablauf"),
			"workflow_palette.domain.people":          text("Personal"),
			"workflow_palette.domain.intelligence":    text("Einblicke"),
			"workflow_palette.domain.operations":      text("Betrieb"),
			"workflow_palette.domain.registry":        text("Referenz"),
			"workflow_viewer.outcome.succeeded":       text("Erledigt"),
			"workflow_viewer.outcome.ambiguous":       text("Unklares Ergebnis"),
			"workflow_viewer.outcome.unknown":         text("Jedes andere Ergebnis"),
			"workflow_viewer.outcome.pass":            text("Stimmt überein"),
			"workflow_viewer.outcome.fail":            text("Stimmt nicht überein"),
			"workflow_viewer.outcome.partial":         text("Stimmt teilweise überein"),
			"workflow_viewer.outcome.fired":           text("Zeitpunkt erreicht"),
			"workflow_viewer.outcome.late":            text("Zu spät"),
			"workflow_viewer.outcome.compensated":     text("Rückgängig gemacht"),
			"workflow_viewer.outcome.repair_required": text("Reparatur nötig"),
			"workflow_viewer.outcome.consistent":      text("Konsistent"),
			"workflow_viewer.outcome.degraded":        text("Teilweise konsistent"),
			"workflow_viewer.outcome.blocked":         text("Blockiert"),
			"workflow_viewer.outcome.valid":           text("Weiterhin gültig"),
			"workflow_viewer.outcome.complete":        text("Abgeschlossen"),
			"workflow_viewer.outcome.repair_plan":     text("Reparatur nötig"),

			"workflow_editor.parameter.display_name":           text("Name"),
			"workflow_editor.parameter.retry_max_attempts":     text("Maximale Versuche"),
			"workflow_editor.parameter.signal_event_type":      text("Ereignistyp"),
			"workflow_editor.parameter.signal_timeout_seconds": text("Warten beenden nach (Sekunden)"),
			"workflow_editor.parameter.wait_wake_kind":         text("Fortsetzen bei"),
			"workflow_editor.parameter.wait_zone":              text("Zeitzone"),
			"workflow_editor.parameter.wait_calendar":          text("Geschäftskalender"),

			"workflow_palette.cannot_add":       text("Eine Vorlage kann nur einen leeren Workflow beginnen."),
			"workflow_palette.step.approval":    text("Jemanden um Genehmigung bitten, bevor es weitergeht."),
			"workflow_palette.step.decision":    text("Den nächsten Schritt anhand der bisherigen Daten wählen."),
			"workflow_palette.step.end":         text("Den Workflow mit einem benannten Ergebnis beenden."),
			"workflow_palette.step.join":        text("Auf den Abschluss paralleler Zweige warten."),
			"workflow_palette.step.observe":     text("Prüfen, ob ein anderes System das erwartete Ergebnis zeigt."),
			"workflow_palette.step.parallel":    text("Mehrere Zweige gleichzeitig ausführen."),
			"workflow_palette.step.signal":      text("Auf ein Ereignis aus einem anderen System warten."),
			"workflow_palette.step.subworkflow": text("Einen anderen veröffentlichten Workflow ausführen."),
			"workflow_palette.step.task":        text("Einer Person eine Aufgabe geben."),
			"workflow_palette.step.transform":   text("Werte für einen späteren Schritt umformen."),
			"workflow_palette.step.wait":        text("Bis zu einem Datum oder Zeitpunkt pausieren."),

			"workflow_viewer.effect.pure":                           text("Keine Nebenwirkungen"),
			"workflow_viewer.effect.read_only":                      text("Liest Daten"),
			"workflow_viewer.effect.internal_mutation":              text("Ändert HR-Daten"),
			"workflow_viewer.effect.external_mutation":              text("Ändert ein anderes System"),
			"workflow_viewer.effect.irreversible_external_mutation": text("Ändert ein anderes System dauerhaft"),
			"workflow_viewer.reversal.no_effect":                    text("Nichts rückgängig zu machen"),
			"workflow_viewer.reversal.compensation_required":        text("Wird durch einen Ausgleichsschritt rückgängig gemacht"),
			"workflow_viewer.reversal.compensate_or_correct":        text("Wird rückgängig gemacht oder nachträglich korrigiert"),
			"workflow_viewer.reversal.forward_correction":           text("Kann nur nachträglich korrigiert werden"),
			"workflow_viewer.reversal.unresolved":                   text("Rücknahme nicht festgelegt"),
			"workflow_viewer.lock.start":                            text("Start"),
			"workflow_viewer.lock.governance":                       text("Genehmigung"),
			"workflow_viewer.lock.revalidation":                     text("erneute Prüfung"),
			"workflow_viewer.lock.reconciliation":                   text("Abgleich"),
			"workflow_viewer.lock.closure":                          text("Abschluss"),
			"workflow_viewer.overlay.add":                           text("Hinzugefügt"),
			"workflow_viewer.overlay.omit":                          text("Ausgelassen"),
			"workflow_viewer.overlay.replace":                       text("Ersetzt"),
			"workflow_viewer.source.workflow_input":                 text("Aus der Anfrage, die diesen Workflow startet"),
			"workflow_viewer.source.context":                        text("Aus dem Kontext der Ausführung"),
			"workflow_viewer.source.constant":                       text("Ein fester Wert"),
			"workflow_viewer.source.node_output":                    text("Aus einem früheren Schritt"),
		}
	case "ar":
		return map[string]localize.Message{
			"workflow_editor.back":                    text("مسارات العمل"),
			"workflow_editor.name_label":              text("اسم مسار العمل"),
			"workflow_editor.version":                 text("مسودة {version}"),
			"workflow_editor.path_label":              text("خطوات مسار العمل"),
			"workflow_editor.inspector_label":         text("إعدادات الخطوة"),
			"workflow_editor.pick_step":               text("اختر خطوة لعرض إعداداتها."),
			"workflow_editor.empty_detail":            text("اختر خطوة من هنا، أو أضف أي خطوة من المكتبة."),
			"workflow_editor.ready":                   text("لم يتبقَّ شيء لإكماله"),
			"workflow_editor.problem_count":           {Plural: map[string]string{"zero": "لا يوجد ما يجب إكماله", "one": "أمر واحد يجب إكماله", "two": "أمران يجب إكمالهما", "few": "{count} أمور يجب إكمالها", "many": "{count} أمرًا يجب إكماله", "other": "{count} أمر يجب إكماله"}},
			"workflow_editor.problem_loose":           text("الخطوة {step} غير متصلة بالمسار."),
			"workflow_editor.problem_open":            text("{step}: حدِّد إلى أين تؤدي النتيجة {route}."),
			"workflow_editor.problem_unbound":         text("{step}: اختر قيمة للحقل {input}."),
			"workflow_editor.problem_no_exit":         text("أضف خطوة إنهاء ليتمكن مسار العمل من الاكتمال."),
			"workflow_editor.loose_title":             text("غير متصلة بعد"),
			"workflow_editor.loose_detail":            text("لا شيء يؤدي إلى هذه الخطوات بعد. اختر إحداها، ثم استخدم «اربط هذه الخطوة» لتحديد النتيجة التي يجب أن تؤدي إلى هنا."),
			"workflow_editor.exits_title":             text("المخارج"),
			"workflow_editor.exit_routes":             {Plural: map[string]string{"zero": "لا ينتهي هنا أي مسار", "one": "ينتهي هنا مسار واحد", "two": "ينتهي هنا مساران", "few": "تنتهي هنا {count} مسارات", "many": "ينتهي هنا {count} مسارًا", "other": "ينتهي هنا {count} مسار"}},
			"workflow_editor.route_to":                text("{route} تؤدي إلى {target}"),
			"workflow_editor.jump":                    text("{route} تؤدي إلى {target}"),
			"workflow_editor.jump_back":               text("{route} تعود إلى {target}"),
			"workflow_editor.open_count":              {Plural: map[string]string{"zero": "كل النتائج متصلة", "one": "نتيجة واحدة غير متصلة", "two": "نتيجتان غير متصلتين", "few": "{count} نتائج غير متصلة", "many": "{count} نتيجة غير متصلة", "other": "{count} نتيجة غير متصلة"}},
			"workflow_editor.todo_count":              {Plural: map[string]string{"zero": "لا شيء متبقٍّ", "one": "أمر واحد متبقٍّ", "two": "أمران متبقيان", "few": "{count} أمور متبقية", "many": "{count} أمرًا متبقيًا", "other": "{count} أمر متبقٍّ"}},
			"workflow_editor.required":                text("ضابط إلزامي"),
			"workflow_editor.locked_detail":           text("ضابط إلزامي ({kind}). يمكن تغيير إعداداته، لكن لا يمكن حذفه أو استبداله."),
			"workflow_editor.settings":                text("الإعدادات"),
			"workflow_editor.outcomes":                text("عند انتهاء هذه الخطوة"),
			"workflow_editor.uses":                    text("تستخدم"),
			"workflow_editor.uses_help":               text("القيم التي تأخذها هذه الخطوة من خطوات سابقة."),
			"workflow_editor.target_steps":            text("الخطوات"),
			"workflow_editor.target_exits":            text("المخارج"),
			"workflow_editor.also_goes_to":            text("تؤدي أيضًا إلى {targets}."),
			"workflow_editor.binding_option":          text("{field} · {step}"),
			"workflow_editor.remove_step":             text("حذف الخطوة"),
			"workflow_editor.change":                  text("{kind}: {subject} {field}"),
			"workflow_editor.saved":                   text("تم الحفظ"),
			"workflow_editor.error_conflict":          text("تغيّرت هذه المسودة من مكان آخر. تم تحميل أحدث نسخة، فأعد إجراء التغيير."),
			"workflow_editor.error_refused":           text("هذا التغيير غير مسموح به هنا."),
			"workflow_editor.error_denied":            text("ليست لديك صلاحية تغيير هذه المسودة."),
			"workflow_editor.error_gone":              text("لم تعد هذه المسودة متاحة."),
			"workflow_editor.error_offline":           text("تعذّر الوصول إلى الخادم. تحقق من اتصالك وحاول مرة أخرى."),
			"workflow_editor.empty_title":             text("ابدأ بخطوة أولى"),
			"workflow_editor.history_position":        text("التغيير {position} من {length}"),
			"workflow_editor.exceptions":              text("إذا حدث خطأ"),
			"workflow_editor.not_set":                 text("غير محدد"),
			"workflow_editor.step_name_label":         text("اسم الخطوة"),
			"workflow_editor.connect_from":            text("اربط هذه الخطوة"),
			"workflow_editor.connect_from_help":       text("اختر النتيجة السابقة التي يجب أن تؤدي إلى هنا."),
			"workflow_editor.connect_from_choose":     text("اختر نتيجة"),
			"workflow_editor.connect_from_option":     text("{step}: {route}"),
			"workflow_editor.parity_template_exact":   text("تطابق القالب المعتمد"),
			"workflow_editor.parity_template_changed": text("تختلف عن القالب المعتمد"),
			"workflow_editor.parity_exact":            text("تطابق الإصدار المنشور"),
			"workflow_editor.parity_changed":          text("تختلف عن الإصدار المنشور"),
			"workflow_editor.library_title":           text("إضافة خطوة"),
			"workflow_editor.edit_step":               text("تعديل {step}"),
			"workflow_editor.choose_replacement":      text("اختر بديلاً"),
			"workflow_editor.exceptions_unset":        {Plural: map[string]string{"zero": "لا شيء غير محدد", "one": "نتيجة واحدة غير محددة", "two": "نتيجتان غير محددتين", "few": "{count} نتائج غير محددة", "many": "{count} نتيجة غير محددة", "other": "{count} نتيجة غير محددة"}},
			"workflow_editor.decision_basis":          text("يختار بين {choices} اعتماداً على {inputs}."),
			"workflow_editor.decision_basis_plain":    text("يختار بين {choices}."),
			"workflow_editor.library_show_all":        {Plural: map[string]string{"zero": "لا خطوات", "one": "عرض الخطوة", "two": "عرض الخطوتين", "few": "عرض كل الخطوات ({count})", "many": "عرض كل الخطوات ({count})", "other": "عرض كل الخطوات ({count})"}},
			"workflow_editor.library_show_fewer":      {Plural: map[string]string{"zero": "عرض أقل", "one": "عرض أقل", "two": "عرض أقل", "few": "عرض أقل", "many": "عرض أقل", "other": "عرض أقل"}},
			"workflow_editor.open_others":             text("النتائج الأخرى لا تؤدي إلى شيء بعد"),
			"workflow_editor.open_some":               text("بعض النتائج لا تؤدي إلى شيء بعد"),
			"workflow_editor.open_none_lead":          text("لا تؤدي أي نتيجة إلى شيء بعد"),
			"workflow_editor.exits_hint_end":          text("النهاية ليست صفاً. تظهر كعلامة على كل خطوة تصل إليها، وهنا."),
			"workflow_editor.decision_rule_note":      text("تأتي هذه الخيارات من قاعدة القرار في هذه الخطوة. لا يمكن تعديل القواعد هنا حتى الآن."),
			"workflow_editor.library_count":           {Plural: map[string]string{"zero": "لا خطوات", "one": "خطوة واحدة", "two": "خطوتان", "few": "{count} خطوات", "many": "{count} خطوة", "other": "{count} خطوة"}},
			"workflow_editor.all_results_end":         text("كل نتيجة لهذه الخطوة تنهي مسار العمل"),
			"workflow_editor.binding_from":            text("من {step}"),
			"workflow_editor.problems_title":          text("ما تبقّى لإكماله"),
			"workflow_editor.selected_step":           text("جارٍ تعديل {step}"),
			"workflow_editor.rail_skip":               text("خط متصل: يتخطى خطوات"),
			"workflow_editor.rail_loop":               text("خط متقطع: يعود إلى الخلف"),
			"workflow_editor.continues":               text("{route} تتابع في الأسفل إلى {target}"),
			"workflow_editor.arrives_from":            text("تصل من {step} ({route})"),
			"workflow_editor.ways_out":                {Plural: map[string]string{"zero": "بلا مخارج", "one": "مخرج واحد", "two": "مخرجان", "few": "{count} مخارج", "many": "{count} مخرجًا", "other": "{count} مخرج"}},
			"workflow_editor.ends_here":               text("لا شيء يتابع من هنا"),
			"workflow_editor.problem_exceptions":      {Plural: map[string]string{"zero": "{step}: كل نتائج الأخطاء متصلة.", "one": "{step}: نتيجة واحدة لحالات الخطأ لا تؤدي إلى شيء.", "two": "{step}: نتيجتان لحالات الخطأ لا تؤديان إلى شيء.", "few": "{step}: {count} نتائج لحالات الخطأ لا تؤدي إلى شيء.", "many": "{step}: {count} نتيجة لحالات الخطأ لا تؤدي إلى شيء.", "other": "{step}: {count} نتيجة لحالات الخطأ لا تؤدي إلى شيء."}},
			"workflow_editor.jump_many":               text("{route} تؤديان إلى {target}"),
			"workflow_editor.jump_back_many":          text("{route} تعودان إلى {target}"),
			"workflow_editor.list_join":               text(" و"),
			"workflow_editor.exits_hint_selected":     text("المميَّز: حيث يمكن أن تنتهي {step}."),
			"workflow_editor.more_exits":              text("+{count} أخرى"),
			"workflow_editor.nothing_follows":         text("لا شيء يلي هذه الخطوة بعد"),
			"workflow_editor.exit_route_count":        {Plural: map[string]string{"zero": "لا مسارات", "one": "مسار واحد", "two": "مساران", "few": "{count} مسارات", "many": "{count} مسارًا", "other": "{count} مسار"}},
			"workflow_editor.exits_hint":              text("حيث يمكن أن ينتهي مسار العمل هذا."),
			"workflow_editor.history":                 text("السجل"),
			"workflow_editor.saved_all":               text("تم حفظ كل التغييرات"),
			"workflow_editor.exceptions_summary":      {Plural: map[string]string{"zero": "لا نتائج", "one": "نتيجة واحدة", "two": "نتيجتان", "few": "{count} نتائج", "many": "{count} نتيجة", "other": "{count} نتيجة"}},
			"workflow_editor.decision_needs_rule":     text("لا توجد خيارات لهذا القرار بعد. تأتي الخيارات من قاعدة قرار، ولا يمكن كتابة القواعد في المحرر حتى الآن."),
			"workflow_palette.domain.rewards":         text("الأجور"),
			"workflow_editor.bulk_label":              {Plural: map[string]string{"zero": "لا توجد نتائج غير محددة", "one": "أرسل النتيجة غير المحددة إلى", "two": "أرسل النتيجتين غير المحددتين إلى", "few": "أرسل النتائج غير المحددة ({count}) إلى", "many": "أرسل النتائج غير المحددة ({count}) إلى", "other": "أرسل النتائج غير المحددة ({count}) إلى"}},
			"workflow_editor.bulk_choose":             text("اختر مخرجًا"),
			"workflow_editor.bulk_needs_exit":         text("أضف خطوة إنهاء، ثم أرسل هذه النتائج إليها دفعة واحدة."),
			"workflow_editor.back_to_path":            text("العودة إلى المسار"),
			"workflow_palette.domain.control_flow":    text("التدفق"),
			"workflow_palette.domain.people":          text("الأشخاص"),
			"workflow_palette.domain.intelligence":    text("الرؤى"),
			"workflow_palette.domain.operations":      text("العمليات"),
			"workflow_palette.domain.registry":        text("المراجع"),
			"workflow_viewer.outcome.succeeded":       text("تم"),
			"workflow_viewer.outcome.ambiguous":       text("نتيجة غير واضحة"),
			"workflow_viewer.outcome.unknown":         text("أي نتيجة أخرى"),
			"workflow_viewer.outcome.pass":            text("مطابق"),
			"workflow_viewer.outcome.fail":            text("غير مطابق"),
			"workflow_viewer.outcome.partial":         text("مطابق جزئيًا"),
			"workflow_viewer.outcome.fired":           text("حان الوقت"),
			"workflow_viewer.outcome.late":            text("متأخر جدًا"),
			"workflow_viewer.outcome.compensated":     text("تم التراجع"),
			"workflow_viewer.outcome.repair_required": text("يلزم إصلاح"),
			"workflow_viewer.outcome.consistent":      text("متسق"),
			"workflow_viewer.outcome.degraded":        text("متسق جزئيًا"),
			"workflow_viewer.outcome.blocked":         text("محظور"),
			"workflow_viewer.outcome.valid":           text("ما زال صالحًا"),
			"workflow_viewer.outcome.complete":        text("مكتمل"),
			"workflow_viewer.outcome.repair_plan":     text("يلزم إصلاح"),

			"workflow_editor.parameter.display_name":           text("الاسم"),
			"workflow_editor.parameter.retry_max_attempts":     text("الحد الأقصى للمحاولات"),
			"workflow_editor.parameter.signal_event_type":      text("نوع الحدث"),
			"workflow_editor.parameter.signal_timeout_seconds": text("إيقاف الانتظار بعد (بالثواني)"),
			"workflow_editor.parameter.wait_wake_kind":         text("الاستئناف عند"),
			"workflow_editor.parameter.wait_zone":              text("المنطقة الزمنية"),
			"workflow_editor.parameter.wait_calendar":          text("تقويم العمل"),

			"workflow_palette.cannot_add":       text("لا يمكن للقالب أن يبدأ إلا مسار عمل فارغًا."),
			"workflow_palette.step.approval":    text("اطلب موافقة شخص قبل متابعة العمل."),
			"workflow_palette.step.decision":    text("اختر الخطوة التالية بناءً على البيانات المتوفرة."),
			"workflow_palette.step.end":         text("أنهِ مسار العمل بنتيجة مسمّاة."),
			"workflow_palette.step.join":        text("انتظر انتهاء الفروع المتوازية."),
			"workflow_palette.step.observe":     text("تحقق من أن نظامًا آخر يُظهر النتيجة المتوقعة."),
			"workflow_palette.step.parallel":    text("شغِّل عدة فروع في الوقت نفسه."),
			"workflow_palette.step.signal":      text("انتظر حدثًا من نظام آخر."),
			"workflow_palette.step.subworkflow": text("شغِّل مسار عمل منشورًا آخر."),
			"workflow_palette.step.task":        text("كلِّف شخصًا بمهمة."),
			"workflow_palette.step.transform":   text("أعد تشكيل القيم لخطوة لاحقة."),
			"workflow_palette.step.wait":        text("توقف مؤقتًا حتى تاريخ أو وقت محدد."),

			"workflow_viewer.effect.pure":                           text("بلا آثار جانبية"),
			"workflow_viewer.effect.read_only":                      text("تقرأ البيانات"),
			"workflow_viewer.effect.internal_mutation":              text("تغيّر بيانات الموارد البشرية"),
			"workflow_viewer.effect.external_mutation":              text("تغيّر نظامًا آخر"),
			"workflow_viewer.effect.irreversible_external_mutation": text("تغيّر نظامًا آخر بشكل دائم"),
			"workflow_viewer.reversal.no_effect":                    text("لا شيء للتراجع عنه"),
			"workflow_viewer.reversal.compensation_required":        text("يُتراجع عنها بخطوة تعويضية"),
			"workflow_viewer.reversal.compensate_or_correct":        text("يُتراجع عنها أو تُصحَّح لاحقًا"),
			"workflow_viewer.reversal.forward_correction":           text("لا يمكن إلا تصحيحها لاحقًا"),
			"workflow_viewer.reversal.unresolved":                   text("طريقة التراجع غير محددة"),
			"workflow_viewer.lock.start":                            text("البداية"),
			"workflow_viewer.lock.governance":                       text("الموافقة"),
			"workflow_viewer.lock.revalidation":                     text("إعادة التحقق"),
			"workflow_viewer.lock.reconciliation":                   text("المطابقة"),
			"workflow_viewer.lock.closure":                          text("الإغلاق"),
			"workflow_viewer.overlay.add":                           text("أُضيفت"),
			"workflow_viewer.overlay.omit":                          text("استُبعدت"),
			"workflow_viewer.overlay.replace":                       text("استُبدلت"),
			"workflow_viewer.source.workflow_input":                 text("من الطلب الذي يبدأ مسار العمل"),
			"workflow_viewer.source.context":                        text("من سياق التنفيذ"),
			"workflow_viewer.source.constant":                       text("قيمة ثابتة"),
			"workflow_viewer.source.node_output":                    text("من خطوة سابقة"),
		}
	default:
		return nil
	}
}
