package productui

// The workflow draft editor's copy, one table per locale, in the format
// parseCopyTable reads (copytable.go): `key = text`, or `key#category = text`
// for each plural category of a plural message. They are data rather than a
// map literal because a literal costs about 575 bytes of compiled code per
// entry in the browser bundle, six times the text it carries.
// TestWorkflowEditorCopyDigests pins the content of all three tables.

const workflowEditorEnglishCopy = `
workflow_editor.all_results_end = Every result of this step ends the workflow
workflow_editor.also_goes_to = Also goes to {targets}.
workflow_editor.arrives_from = Arrives from {step} ({route})
workflow_editor.back = Workflows
workflow_editor.back_to_path = Back to the path
workflow_editor.binding_from = from {step}
workflow_editor.binding_option = {field} · {step}
workflow_editor.bulk_choose = Choose an exit
workflow_editor.bulk_label#one = Send {count} unset result to
workflow_editor.bulk_label#other = Send all {count} unset results to
workflow_editor.bulk_needs_exit = Add an End step, then send these results to it in one go.
workflow_editor.change = {kind}: {subject} {field}
workflow_editor.choose_replacement = Choose a replacement
workflow_editor.connect_from = Connect this step
workflow_editor.connect_from_choose = Choose a result
workflow_editor.connect_from_help = Choose the earlier result that should lead here.
workflow_editor.connect_from_option = {step}: {route}
workflow_editor.continues = {route} continues below to {target}
workflow_editor.decision_basis = Chooses between {choices} using {inputs}.
workflow_editor.decision_basis_plain = Chooses between {choices}.
workflow_editor.decision_needs_rule = This decision has no choices yet. Choices come from a decision rule, and rules can't be written in the editor yet.
workflow_editor.decision_rule_note = These choices come from the decision rule on this step. Rules can't be edited here yet.
workflow_editor.edit_step = Edit {step}
workflow_editor.empty_detail = Pick one here, or add any step from the library.
workflow_editor.empty_title = Start with a first step
workflow_editor.ends_here = Nothing continues from here
workflow_editor.error_conflict = This draft changed somewhere else. The latest version is loaded, so make the change again.
workflow_editor.error_denied = You don't have access to change this draft.
workflow_editor.error_gone = This draft is no longer available.
workflow_editor.error_offline = Couldn't reach the server. Check your connection and try again.
workflow_editor.error_refused = That change isn't allowed here.
workflow_editor.exceptions = If something goes wrong
workflow_editor.exceptions_summary#one = {count} result
workflow_editor.exceptions_summary#other = {count} results
workflow_editor.exceptions_unset#one = {count} not set
workflow_editor.exceptions_unset#other = {count} not set
workflow_editor.exit_route_count#one = {count} route
workflow_editor.exit_route_count#other = {count} routes
workflow_editor.exit_routes#one = {count} route ends here
workflow_editor.exit_routes#other = {count} routes end here
workflow_editor.exits_hint = Where this workflow can finish.
workflow_editor.exits_hint_end = Choose an End result when this workflow should finish.
workflow_editor.exits_hint_selected = Highlighted: where {step} can finish.
workflow_editor.exits_title = Exits
workflow_editor.history = History
workflow_editor.history_position = Change {position} of {length}
workflow_editor.inspector_label = Step settings
workflow_editor.jump = {route} goes to {target}
workflow_editor.jump_back = {route} goes back to {target}
workflow_editor.jump_back_many = {route} go back to {target}
workflow_editor.jump_many = {route} go to {target}
workflow_editor.library_count#one = {count} step
workflow_editor.library_count#other = {count} steps
workflow_editor.library_show_all#one = Show {count} step
workflow_editor.library_show_all#other = Show all {count} steps
workflow_editor.library_show_fewer#one = Show fewer
workflow_editor.library_show_fewer#other = Show fewer
workflow_editor.library_title = Add a step
workflow_editor.list_join = " and "
workflow_editor.locked_detail = Required control ({kind}). You can change its settings, but you can't remove or replace it.
workflow_editor.loose_detail = Nothing leads to these steps yet. Pick one, then choose the earlier result that should lead to it under “Connect this step”.
workflow_editor.loose_title = Not connected yet
workflow_editor.more_exits = +{count} more
workflow_editor.name_label = Workflow name
workflow_editor.not_set = Not set
workflow_editor.nothing_follows = Nothing follows this step yet
workflow_editor.open_count#one = {count} result isn't connected
workflow_editor.open_count#other = {count} results aren't connected
workflow_editor.open_none_lead = No result leads anywhere yet
workflow_editor.open_others = Other results lead nowhere yet
workflow_editor.open_some = Some results lead nowhere yet
workflow_editor.outcomes = When this step ends
workflow_editor.parameter.display_name = Name
workflow_editor.parameter.retry_max_attempts = Maximum attempts
workflow_editor.parameter.signal_event_type = Event type
workflow_editor.parameter.signal_timeout_seconds = Stop waiting after (seconds)
workflow_editor.parameter.task_assignee = Assignee (role or relationship)
workflow_editor.parameter.task_due_period_days = Due period (days)
workflow_editor.parameter.task_instructions = Instructions
workflow_editor.parameter.wait_calendar = Business calendar
workflow_editor.parameter.wait_wake_kind = Wake on
workflow_editor.parameter.wait_zone = Time zone
workflow_editor.parity_changed = Changed from the released version
workflow_editor.parity_exact = Matches the released version
workflow_editor.parity_template_changed = Changed from the approved template
workflow_editor.parity_template_exact = Matches the approved template
workflow_editor.path_label = Workflow path
workflow_editor.pick_step = Choose a step to see its settings.
workflow_editor.problem_count#one = {count} thing to finish
workflow_editor.problem_count#other = {count} things to finish
workflow_editor.problem_exceptions#one = {step}: {count} result for when something goes wrong leads nowhere.
workflow_editor.problem_exceptions#other = {step}: {count} results for when something goes wrong lead nowhere.
workflow_editor.problem_loose = {step} isn't connected to the path.
workflow_editor.problem_no_exit = Add an End step so the workflow can finish.
workflow_editor.problem_open = {step}: choose where {route} goes.
workflow_editor.problem_task_assignee = {step} needs an assignee before it can be tested.
workflow_editor.problem_unbound = {step}: choose a value for {input}.
workflow_editor.problems_title = Still to finish
workflow_editor.rail_loop = Dashed line: loops back
workflow_editor.rail_skip = Solid line: skips ahead
workflow_editor.ready = Nothing left to finish
workflow_editor.remove_step = Remove step
workflow_editor.required = Required control
workflow_editor.route_to = {route} goes to {target}
workflow_editor.saved = Saved
workflow_editor.saved_all = All changes saved
workflow_editor.selected_step = Editing {step}
workflow_editor.settings = Settings
workflow_editor.step_name_label = Step name
workflow_editor.target_exits = Exits
workflow_editor.target_steps = Steps
workflow_editor.task_help = Say who owns this work, what they should do, and when it is due.
workflow_editor.todo_count#one = {count} to finish
workflow_editor.todo_count#other = {count} to finish
workflow_editor.uses = Uses
workflow_editor.uses_help = Values this step takes from earlier steps.
workflow_editor.version = Draft {version}
workflow_editor.ways_out#one = {count} way out
workflow_editor.ways_out#other = {count} ways out
workflow_palette.cannot_add = A template can only start an empty workflow.
workflow_palette.domain.control_flow = Flow
workflow_palette.domain.intelligence = Insight
workflow_palette.domain.operations = Operations
workflow_palette.domain.people = People
workflow_palette.domain.registry = Reference
workflow_palette.domain.rewards = Pay
workflow_palette.step.approval = Ask someone to approve before work continues.
workflow_palette.step.decision = Choose the next step from what is known so far.
workflow_palette.step.end = Finish the workflow with a named outcome.
workflow_palette.step.join = Wait for parallel branches to finish.
workflow_palette.step.observe = Check that another system shows the expected result.
workflow_palette.step.parallel = Run several branches at the same time.
workflow_palette.step.signal = Wait for an event from another system.
workflow_palette.step.subworkflow = Run another published workflow.
workflow_palette.step.task = Give a person something to do.
workflow_palette.step.transform = Reshape values for a later step.
workflow_palette.step.wait = Pause until a date or time.
workflow_release.action_activate = Publish and activate
workflow_release.action_approval = Submit for approval
workflow_release.action_save = Save draft
workflow_release.action_test = Run test
workflow_release.activation = Activation
workflow_release.approval = Approval
workflow_release.description = Test the finished draft, get approval, then activate the version that new work will use.
workflow_release.next = Next: {action}
workflow_release.state_blocked = Blocked
workflow_release.state_not_started = Not started
workflow_release.state_ready = Ready
workflow_release.state_waiting = Waiting
workflow_release.test = Test
workflow_release.title = From draft to live
workflow_viewer.effect.external_mutation = Changes another system
workflow_viewer.effect.internal_mutation = Changes HR data
workflow_viewer.effect.irreversible_external_mutation = Changes another system permanently
workflow_viewer.effect.pure = No side effects
workflow_viewer.effect.read_only = Reads data
workflow_viewer.lock.closure = closing
workflow_viewer.lock.governance = approval
workflow_viewer.lock.reconciliation = reconciliation
workflow_viewer.lock.revalidation = revalidation
workflow_viewer.lock.start = start
workflow_viewer.outcome.ambiguous = Unclear result
workflow_viewer.outcome.blocked = Blocked
workflow_viewer.outcome.compensated = Undone
workflow_viewer.outcome.complete = Complete
workflow_viewer.outcome.consistent = Consistent
workflow_viewer.outcome.degraded = Partly consistent
workflow_viewer.outcome.fail = Doesn't match
workflow_viewer.outcome.fired = Time reached
workflow_viewer.outcome.late = Too late
workflow_viewer.outcome.partial = Partly matches
workflow_viewer.outcome.pass = Matches
workflow_viewer.outcome.repair_plan = Needs repair
workflow_viewer.outcome.repair_required = Needs repair
workflow_viewer.outcome.succeeded = Done
workflow_viewer.outcome.unknown = Any other result
workflow_viewer.outcome.valid = Still valid
workflow_viewer.overlay.add = Added
workflow_viewer.overlay.omit = Left out
workflow_viewer.overlay.replace = Replaced
workflow_viewer.reversal.compensate_or_correct = Undone or corrected afterwards
workflow_viewer.reversal.compensation_required = Undone by a compensating step
workflow_viewer.reversal.forward_correction = Can only be corrected afterwards
workflow_viewer.reversal.no_effect = Nothing to undo
workflow_viewer.reversal.unresolved = Reversal not defined
workflow_viewer.source.constant = A fixed value
workflow_viewer.source.context = From the run's context
workflow_viewer.source.node_output = From an earlier step
workflow_viewer.source.workflow_input = From the request that starts this workflow
`

const workflowEditorGermanCopy = `
workflow_editor.all_results_end = Jedes Ergebnis dieses Schritts beendet den Workflow
workflow_editor.also_goes_to = Führt außerdem zu {targets}.
workflow_editor.arrives_from = Kommt von {step} ({route})
workflow_editor.back = Workflows
workflow_editor.back_to_path = Zurück zum Ablauf
workflow_editor.binding_from = aus {step}
workflow_editor.binding_option = {field} · {step}
workflow_editor.bulk_choose = Ausgang wählen
workflow_editor.bulk_label#one = {count} offenes Ergebnis senden an
workflow_editor.bulk_label#other = Alle {count} offenen Ergebnisse senden an
workflow_editor.bulk_needs_exit = Fügen Sie einen Ende-Schritt hinzu und leiten Sie diese Ergebnisse dann gesammelt dorthin.
workflow_editor.change = {kind}: {subject} {field}
workflow_editor.choose_replacement = Ersatz wählen
workflow_editor.connect_from = Diesen Schritt verbinden
workflow_editor.connect_from_choose = Ergebnis wählen
workflow_editor.connect_from_help = Wählen Sie das frühere Ergebnis, das hierher führen soll.
workflow_editor.connect_from_option = {step}: {route}
workflow_editor.continues = {route} führt unten weiter zu {target}
workflow_editor.decision_basis = Wählt zwischen {choices} anhand von {inputs}.
workflow_editor.decision_basis_plain = Wählt zwischen {choices}.
workflow_editor.decision_needs_rule = Diese Entscheidung hat noch keine Auswahlmöglichkeiten. Sie stammen aus einer Entscheidungsregel, und Regeln lassen sich im Editor noch nicht verfassen.
workflow_editor.decision_rule_note = Diese Auswahlmöglichkeiten stammen aus der Entscheidungsregel dieses Schritts. Regeln lassen sich hier noch nicht bearbeiten.
workflow_editor.edit_step = {step} bearbeiten
workflow_editor.empty_detail = Wählen Sie hier einen aus oder fügen Sie einen beliebigen Schritt aus der Bibliothek hinzu.
workflow_editor.empty_title = Beginnen Sie mit einem ersten Schritt
workflow_editor.ends_here = Von hier geht es nicht weiter
workflow_editor.error_conflict = Dieser Entwurf wurde an anderer Stelle geändert. Die aktuelle Fassung ist geladen; nehmen Sie die Änderung bitte erneut vor.
workflow_editor.error_denied = Sie haben keine Berechtigung, diesen Entwurf zu ändern.
workflow_editor.error_gone = Dieser Entwurf ist nicht mehr verfügbar.
workflow_editor.error_offline = Der Server ist nicht erreichbar. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.
workflow_editor.error_refused = Diese Änderung ist hier nicht zulässig.
workflow_editor.exceptions = Wenn etwas schiefgeht
workflow_editor.exceptions_summary#one = {count} Ergebnis
workflow_editor.exceptions_summary#other = {count} Ergebnisse
workflow_editor.exceptions_unset#one = {count} nicht festgelegt
workflow_editor.exceptions_unset#other = {count} nicht festgelegt
workflow_editor.exit_route_count#one = {count} Weg
workflow_editor.exit_route_count#other = {count} Wege
workflow_editor.exit_routes#one = {count} Weg endet hier
workflow_editor.exit_routes#other = {count} Wege enden hier
workflow_editor.exits_hint = Hier kann dieser Workflow enden.
workflow_editor.exits_hint_end = Wählen Sie ein Ende-Ergebnis, wenn dieser Workflow abgeschlossen werden soll.
workflow_editor.exits_hint_selected = Hervorgehoben: wo {step} enden kann.
workflow_editor.exits_title = Ausgänge
workflow_editor.history = Verlauf
workflow_editor.history_position = Änderung {position} von {length}
workflow_editor.inspector_label = Einstellungen des Schritts
workflow_editor.jump = {route} führt zu {target}
workflow_editor.jump_back = {route} führt zurück zu {target}
workflow_editor.jump_back_many = {route} führen zurück zu {target}
workflow_editor.jump_many = {route} führen zu {target}
workflow_editor.library_count#one = {count} Schritt
workflow_editor.library_count#other = {count} Schritte
workflow_editor.library_show_all#one = {count} Schritt anzeigen
workflow_editor.library_show_all#other = Alle {count} Schritte anzeigen
workflow_editor.library_show_fewer#one = Weniger anzeigen
workflow_editor.library_show_fewer#other = Weniger anzeigen
workflow_editor.library_title = Schritt hinzufügen
workflow_editor.list_join = " und "
workflow_editor.locked_detail = Pflichtkontrolle ({kind}). Sie können die Einstellungen ändern, aber den Schritt nicht entfernen oder ersetzen.
workflow_editor.loose_detail = Noch führt nichts zu diesen Schritten. Wählen Sie einen aus und legen Sie mit „Diesen Schritt verbinden“ fest, welches Ergebnis hierher führen soll.
workflow_editor.loose_title = Noch nicht verbunden
workflow_editor.more_exits = +{count} weitere
workflow_editor.name_label = Name des Workflows
workflow_editor.not_set = Nicht festgelegt
workflow_editor.nothing_follows = Auf diesen Schritt folgt noch nichts
workflow_editor.open_count#one = {count} Ergebnis ist nicht verbunden
workflow_editor.open_count#other = {count} Ergebnisse sind nicht verbunden
workflow_editor.open_none_lead = Noch führt kein Ergebnis irgendwohin
workflow_editor.open_others = Andere Ergebnisse führen noch nirgendwohin
workflow_editor.open_some = Einige Ergebnisse führen noch nirgendwohin
workflow_editor.outcomes = Wenn dieser Schritt endet
workflow_editor.parameter.display_name = Name
workflow_editor.parameter.retry_max_attempts = Maximale Versuche
workflow_editor.parameter.signal_event_type = Ereignistyp
workflow_editor.parameter.signal_timeout_seconds = Warten beenden nach (Sekunden)
workflow_editor.parameter.task_assignee = Zuständig (Rolle oder Beziehung)
workflow_editor.parameter.task_due_period_days = Frist (Tage)
workflow_editor.parameter.task_instructions = Anweisungen
workflow_editor.parameter.wait_calendar = Geschäftskalender
workflow_editor.parameter.wait_wake_kind = Fortsetzen bei
workflow_editor.parameter.wait_zone = Zeitzone
workflow_editor.parity_changed = Weicht von der Freigabe ab
workflow_editor.parity_exact = Entspricht der Freigabe
workflow_editor.parity_template_changed = Weicht von der Vorlage ab
workflow_editor.parity_template_exact = Entspricht der Vorlage
workflow_editor.path_label = Ablauf des Workflows
workflow_editor.pick_step = Wählen Sie einen Schritt, um seine Einstellungen zu sehen.
workflow_editor.problem_count#one = {count} offener Punkt
workflow_editor.problem_count#other = {count} offene Punkte
workflow_editor.problem_exceptions#one = {step}: {count} Ergebnis für den Fehlerfall führt nirgendwohin.
workflow_editor.problem_exceptions#other = {step}: {count} Ergebnisse für den Fehlerfall führen nirgendwohin.
workflow_editor.problem_loose = {step} ist nicht mit dem Ablauf verbunden.
workflow_editor.problem_no_exit = Fügen Sie einen Ende-Schritt hinzu, damit der Workflow abschließen kann.
workflow_editor.problem_open = {step}: Legen Sie fest, wohin {route} führt.
workflow_editor.problem_task_assignee = {step} braucht eine zuständige Person oder Rolle, bevor der Test möglich ist.
workflow_editor.problem_unbound = {step}: Wählen Sie einen Wert für {input}.
workflow_editor.problems_title = Noch offen
workflow_editor.rail_loop = Gestrichelte Linie: führt zurück
workflow_editor.rail_skip = Durchgezogene Linie: überspringt Schritte
workflow_editor.ready = Nichts mehr offen
workflow_editor.remove_step = Schritt entfernen
workflow_editor.required = Pflichtkontrolle
workflow_editor.route_to = {route} führt zu {target}
workflow_editor.saved = Gespeichert
workflow_editor.saved_all = Alle Änderungen gespeichert
workflow_editor.selected_step = {step} wird bearbeitet
workflow_editor.settings = Einstellungen
workflow_editor.step_name_label = Name des Schritts
workflow_editor.target_exits = Ausgänge
workflow_editor.target_steps = Schritte
workflow_editor.task_help = Legen Sie fest, wer die Aufgabe übernimmt, was zu tun ist und bis wann.
workflow_editor.todo_count#one = {count} offen
workflow_editor.todo_count#other = {count} offen
workflow_editor.uses = Verwendet
workflow_editor.uses_help = Werte, die dieser Schritt aus früheren Schritten übernimmt.
workflow_editor.version = Entwurf {version}
workflow_editor.ways_out#one = {count} Ausgang
workflow_editor.ways_out#other = {count} Ausgänge
workflow_palette.cannot_add = Eine Vorlage kann nur einen leeren Workflow beginnen.
workflow_palette.domain.control_flow = Ablauf
workflow_palette.domain.intelligence = Einblicke
workflow_palette.domain.operations = Betrieb
workflow_palette.domain.people = Personal
workflow_palette.domain.registry = Referenz
workflow_palette.domain.rewards = Vergütung
workflow_palette.step.approval = Jemanden um Genehmigung bitten, bevor es weitergeht.
workflow_palette.step.decision = Den nächsten Schritt anhand der bisherigen Daten wählen.
workflow_palette.step.end = Den Workflow mit einem benannten Ergebnis beenden.
workflow_palette.step.join = Auf den Abschluss paralleler Zweige warten.
workflow_palette.step.observe = Prüfen, ob ein anderes System das erwartete Ergebnis zeigt.
workflow_palette.step.parallel = Mehrere Zweige gleichzeitig ausführen.
workflow_palette.step.signal = Auf ein Ereignis aus einem anderen System warten.
workflow_palette.step.subworkflow = Einen anderen veröffentlichten Workflow ausführen.
workflow_palette.step.task = Einer Person eine Aufgabe geben.
workflow_palette.step.transform = Werte für einen späteren Schritt umformen.
workflow_palette.step.wait = Bis zu einem Datum oder Zeitpunkt pausieren.
workflow_release.action_activate = Veröffentlichen und aktivieren
workflow_release.action_approval = Genehmigung einreichen
workflow_release.action_save = Entwurf speichern
workflow_release.action_test = Test ausführen
workflow_release.activation = Aktivierung
workflow_release.approval = Genehmigung
workflow_release.description = Testen Sie den fertigen Entwurf, holen Sie die Genehmigung ein und aktivieren Sie dann die Version für neue Vorgänge.
workflow_release.next = Als Nächstes: {action}
workflow_release.state_blocked = Blockiert
workflow_release.state_not_started = Nicht begonnen
workflow_release.state_ready = Bereit
workflow_release.state_waiting = Wartet
workflow_release.test = Test
workflow_release.title = Vom Entwurf zur Veröffentlichung
workflow_viewer.effect.external_mutation = Ändert ein anderes System
workflow_viewer.effect.internal_mutation = Ändert HR-Daten
workflow_viewer.effect.irreversible_external_mutation = Ändert ein anderes System dauerhaft
workflow_viewer.effect.pure = Keine Nebenwirkungen
workflow_viewer.effect.read_only = Liest Daten
workflow_viewer.lock.closure = Abschluss
workflow_viewer.lock.governance = Genehmigung
workflow_viewer.lock.reconciliation = Abgleich
workflow_viewer.lock.revalidation = erneute Prüfung
workflow_viewer.lock.start = Start
workflow_viewer.outcome.ambiguous = Unklares Ergebnis
workflow_viewer.outcome.blocked = Blockiert
workflow_viewer.outcome.compensated = Rückgängig gemacht
workflow_viewer.outcome.complete = Abgeschlossen
workflow_viewer.outcome.consistent = Konsistent
workflow_viewer.outcome.degraded = Teilweise konsistent
workflow_viewer.outcome.fail = Stimmt nicht überein
workflow_viewer.outcome.fired = Zeitpunkt erreicht
workflow_viewer.outcome.late = Zu spät
workflow_viewer.outcome.partial = Stimmt teilweise überein
workflow_viewer.outcome.pass = Stimmt überein
workflow_viewer.outcome.repair_plan = Reparatur nötig
workflow_viewer.outcome.repair_required = Reparatur nötig
workflow_viewer.outcome.succeeded = Erledigt
workflow_viewer.outcome.unknown = Jedes andere Ergebnis
workflow_viewer.outcome.valid = Weiterhin gültig
workflow_viewer.overlay.add = Hinzugefügt
workflow_viewer.overlay.omit = Ausgelassen
workflow_viewer.overlay.replace = Ersetzt
workflow_viewer.reversal.compensate_or_correct = Wird rückgängig gemacht oder nachträglich korrigiert
workflow_viewer.reversal.compensation_required = Wird durch einen Ausgleichsschritt rückgängig gemacht
workflow_viewer.reversal.forward_correction = Kann nur nachträglich korrigiert werden
workflow_viewer.reversal.no_effect = Nichts rückgängig zu machen
workflow_viewer.reversal.unresolved = Rücknahme nicht festgelegt
workflow_viewer.source.constant = Ein fester Wert
workflow_viewer.source.context = Aus dem Kontext der Ausführung
workflow_viewer.source.node_output = Aus einem früheren Schritt
workflow_viewer.source.workflow_input = Aus der Anfrage, die diesen Workflow startet
`

const workflowEditorArabicCopy = `
workflow_editor.all_results_end = كل نتيجة لهذه الخطوة تنهي مسار العمل
workflow_editor.also_goes_to = تؤدي أيضًا إلى {targets}.
workflow_editor.arrives_from = تصل من {step} ({route})
workflow_editor.back = مسارات العمل
workflow_editor.back_to_path = العودة إلى المسار
workflow_editor.binding_from = من {step}
workflow_editor.binding_option = {field} · {step}
workflow_editor.bulk_choose = اختر مخرجًا
workflow_editor.bulk_label#few = أرسل النتائج غير المحددة ({count}) إلى
workflow_editor.bulk_label#many = أرسل النتائج غير المحددة ({count}) إلى
workflow_editor.bulk_label#one = أرسل النتيجة غير المحددة إلى
workflow_editor.bulk_label#other = أرسل النتائج غير المحددة ({count}) إلى
workflow_editor.bulk_label#two = أرسل النتيجتين غير المحددتين إلى
workflow_editor.bulk_label#zero = لا توجد نتائج غير محددة
workflow_editor.bulk_needs_exit = أضف خطوة إنهاء، ثم أرسل هذه النتائج إليها دفعة واحدة.
workflow_editor.change = {kind}: {subject} {field}
workflow_editor.choose_replacement = اختر بديلاً
workflow_editor.connect_from = اربط هذه الخطوة
workflow_editor.connect_from_choose = اختر نتيجة
workflow_editor.connect_from_help = اختر النتيجة السابقة التي يجب أن تؤدي إلى هنا.
workflow_editor.connect_from_option = {step}: {route}
workflow_editor.continues = {route} تتابع في الأسفل إلى {target}
workflow_editor.decision_basis = يختار بين {choices} اعتماداً على {inputs}.
workflow_editor.decision_basis_plain = يختار بين {choices}.
workflow_editor.decision_needs_rule = لا توجد خيارات لهذا القرار بعد. تأتي الخيارات من قاعدة قرار، ولا يمكن كتابة القواعد في المحرر حتى الآن.
workflow_editor.decision_rule_note = تأتي هذه الخيارات من قاعدة القرار في هذه الخطوة. لا يمكن تعديل القواعد هنا حتى الآن.
workflow_editor.edit_step = تعديل {step}
workflow_editor.empty_detail = اختر خطوة من هنا، أو أضف أي خطوة من المكتبة.
workflow_editor.empty_title = ابدأ بخطوة أولى
workflow_editor.ends_here = لا شيء يتابع من هنا
workflow_editor.error_conflict = تغيّرت هذه المسودة من مكان آخر. تم تحميل أحدث نسخة، فأعد إجراء التغيير.
workflow_editor.error_denied = ليست لديك صلاحية تغيير هذه المسودة.
workflow_editor.error_gone = لم تعد هذه المسودة متاحة.
workflow_editor.error_offline = تعذّر الوصول إلى الخادم. تحقق من اتصالك وحاول مرة أخرى.
workflow_editor.error_refused = هذا التغيير غير مسموح به هنا.
workflow_editor.exceptions = إذا حدث خطأ
workflow_editor.exceptions_summary#few = {count} نتائج
workflow_editor.exceptions_summary#many = {count} نتيجة
workflow_editor.exceptions_summary#one = نتيجة واحدة
workflow_editor.exceptions_summary#other = {count} نتيجة
workflow_editor.exceptions_summary#two = نتيجتان
workflow_editor.exceptions_summary#zero = لا نتائج
workflow_editor.exceptions_unset#few = {count} نتائج غير محددة
workflow_editor.exceptions_unset#many = {count} نتيجة غير محددة
workflow_editor.exceptions_unset#one = نتيجة واحدة غير محددة
workflow_editor.exceptions_unset#other = {count} نتيجة غير محددة
workflow_editor.exceptions_unset#two = نتيجتان غير محددتين
workflow_editor.exceptions_unset#zero = لا شيء غير محدد
workflow_editor.exit_route_count#few = {count} مسارات
workflow_editor.exit_route_count#many = {count} مسارًا
workflow_editor.exit_route_count#one = مسار واحد
workflow_editor.exit_route_count#other = {count} مسار
workflow_editor.exit_route_count#two = مساران
workflow_editor.exit_route_count#zero = لا مسارات
workflow_editor.exit_routes#few = تنتهي هنا {count} مسارات
workflow_editor.exit_routes#many = ينتهي هنا {count} مسارًا
workflow_editor.exit_routes#one = ينتهي هنا مسار واحد
workflow_editor.exit_routes#other = ينتهي هنا {count} مسار
workflow_editor.exit_routes#two = ينتهي هنا مساران
workflow_editor.exit_routes#zero = لا ينتهي هنا أي مسار
workflow_editor.exits_hint = حيث يمكن أن ينتهي مسار العمل هذا.
workflow_editor.exits_hint_end = اختر نتيجة إنهاء عندما يجب أن ينتهي مسار العمل هذا.
workflow_editor.exits_hint_selected = المميَّز: حيث يمكن أن تنتهي {step}.
workflow_editor.exits_title = المخارج
workflow_editor.history = السجل
workflow_editor.history_position = التغيير {position} من {length}
workflow_editor.inspector_label = إعدادات الخطوة
workflow_editor.jump = {route} تؤدي إلى {target}
workflow_editor.jump_back = {route} تعود إلى {target}
workflow_editor.jump_back_many = {route} تعودان إلى {target}
workflow_editor.jump_many = {route} تؤديان إلى {target}
workflow_editor.library_count#few = {count} خطوات
workflow_editor.library_count#many = {count} خطوة
workflow_editor.library_count#one = خطوة واحدة
workflow_editor.library_count#other = {count} خطوة
workflow_editor.library_count#two = خطوتان
workflow_editor.library_count#zero = لا خطوات
workflow_editor.library_show_all#few = عرض كل الخطوات ({count})
workflow_editor.library_show_all#many = عرض كل الخطوات ({count})
workflow_editor.library_show_all#one = عرض الخطوة
workflow_editor.library_show_all#other = عرض كل الخطوات ({count})
workflow_editor.library_show_all#two = عرض الخطوتين
workflow_editor.library_show_all#zero = لا خطوات
workflow_editor.library_show_fewer#few = عرض أقل
workflow_editor.library_show_fewer#many = عرض أقل
workflow_editor.library_show_fewer#one = عرض أقل
workflow_editor.library_show_fewer#other = عرض أقل
workflow_editor.library_show_fewer#two = عرض أقل
workflow_editor.library_show_fewer#zero = عرض أقل
workflow_editor.library_title = إضافة خطوة
workflow_editor.list_join = " و"
workflow_editor.locked_detail = ضابط إلزامي ({kind}). يمكنك تغيير إعداداته، لكن لا يمكنك حذفه أو استبداله.
workflow_editor.loose_detail = لا شيء يؤدي إلى هذه الخطوات بعد. اختر إحداها، ثم استخدم «اربط هذه الخطوة» لتحديد النتيجة التي يجب أن تؤدي إلى هنا.
workflow_editor.loose_title = غير متصلة بعد
workflow_editor.more_exits = +{count} أخرى
workflow_editor.name_label = اسم مسار العمل
workflow_editor.not_set = غير محدد
workflow_editor.nothing_follows = لا شيء يلي هذه الخطوة بعد
workflow_editor.open_count#few = {count} نتائج غير متصلة
workflow_editor.open_count#many = {count} نتيجة غير متصلة
workflow_editor.open_count#one = نتيجة واحدة غير متصلة
workflow_editor.open_count#other = {count} نتيجة غير متصلة
workflow_editor.open_count#two = نتيجتان غير متصلتين
workflow_editor.open_count#zero = كل النتائج متصلة
workflow_editor.open_none_lead = لا تؤدي أي نتيجة إلى شيء بعد
workflow_editor.open_others = النتائج الأخرى لا تؤدي إلى شيء بعد
workflow_editor.open_some = بعض النتائج لا تؤدي إلى شيء بعد
workflow_editor.outcomes = عند انتهاء هذه الخطوة
workflow_editor.parameter.display_name = الاسم
workflow_editor.parameter.retry_max_attempts = الحد الأقصى للمحاولات
workflow_editor.parameter.signal_event_type = نوع الحدث
workflow_editor.parameter.signal_timeout_seconds = إيقاف الانتظار بعد (بالثواني)
workflow_editor.parameter.task_assignee = المسؤول (دور أو علاقة)
workflow_editor.parameter.task_due_period_days = مدة الاستحقاق (أيام)
workflow_editor.parameter.task_instructions = التعليمات
workflow_editor.parameter.wait_calendar = تقويم العمل
workflow_editor.parameter.wait_wake_kind = الاستئناف عند
workflow_editor.parameter.wait_zone = المنطقة الزمنية
workflow_editor.parity_changed = تختلف عن الإصدار المنشور
workflow_editor.parity_exact = تطابق الإصدار المنشور
workflow_editor.parity_template_changed = تختلف عن القالب المعتمد
workflow_editor.parity_template_exact = تطابق القالب المعتمد
workflow_editor.path_label = خطوات مسار العمل
workflow_editor.pick_step = اختر خطوة لعرض إعداداتها.
workflow_editor.problem_count#few = {count} أمور يجب إكمالها
workflow_editor.problem_count#many = {count} أمرًا يجب إكماله
workflow_editor.problem_count#one = أمر واحد يجب إكماله
workflow_editor.problem_count#other = {count} أمر يجب إكماله
workflow_editor.problem_count#two = أمران يجب إكمالهما
workflow_editor.problem_count#zero = لا يوجد ما يجب إكماله
workflow_editor.problem_exceptions#few = {step}: {count} نتائج لحالات الخطأ لا تؤدي إلى شيء.
workflow_editor.problem_exceptions#many = {step}: {count} نتيجة لحالات الخطأ لا تؤدي إلى شيء.
workflow_editor.problem_exceptions#one = {step}: نتيجة واحدة لحالات الخطأ لا تؤدي إلى شيء.
workflow_editor.problem_exceptions#other = {step}: {count} نتيجة لحالات الخطأ لا تؤدي إلى شيء.
workflow_editor.problem_exceptions#two = {step}: نتيجتان لحالات الخطأ لا تؤديان إلى شيء.
workflow_editor.problem_exceptions#zero = {step}: كل نتائج الأخطاء متصلة.
workflow_editor.problem_loose = الخطوة {step} غير متصلة بالمسار.
workflow_editor.problem_no_exit = أضف خطوة إنهاء ليتمكن مسار العمل من الاكتمال.
workflow_editor.problem_open = {step}: حدِّد إلى أين تؤدي النتيجة {route}.
workflow_editor.problem_task_assignee = تحتاج {step} إلى منفذ قبل إجراء الاختبار.
workflow_editor.problem_unbound = {step}: اختر قيمة للحقل {input}.
workflow_editor.problems_title = ما تبقّى لإكماله
workflow_editor.rail_loop = خط متقطع: يعود إلى الخلف
workflow_editor.rail_skip = خط متصل: يتخطى خطوات
workflow_editor.ready = لم يتبقَّ شيء لإكماله
workflow_editor.remove_step = حذف الخطوة
workflow_editor.required = ضابط إلزامي
workflow_editor.route_to = {route} تؤدي إلى {target}
workflow_editor.saved = تم الحفظ
workflow_editor.saved_all = تم حفظ كل التغييرات
workflow_editor.selected_step = جارٍ تعديل {step}
workflow_editor.settings = الإعدادات
workflow_editor.step_name_label = اسم الخطوة
workflow_editor.target_exits = المخارج
workflow_editor.target_steps = الخطوات
workflow_editor.task_help = حدد من يتولى العمل، وما المطلوب، وموعد إنجازه.
workflow_editor.todo_count#few = {count} أمور متبقية
workflow_editor.todo_count#many = {count} أمرًا متبقيًا
workflow_editor.todo_count#one = أمر واحد متبقٍّ
workflow_editor.todo_count#other = {count} أمر متبقٍّ
workflow_editor.todo_count#two = أمران متبقيان
workflow_editor.todo_count#zero = لا شيء متبقٍّ
workflow_editor.uses = تستخدم
workflow_editor.uses_help = القيم التي تأخذها هذه الخطوة من خطوات سابقة.
workflow_editor.version = مسودة {version}
workflow_editor.ways_out#few = {count} مخارج
workflow_editor.ways_out#many = {count} مخرجًا
workflow_editor.ways_out#one = مخرج واحد
workflow_editor.ways_out#other = {count} مخرج
workflow_editor.ways_out#two = مخرجان
workflow_editor.ways_out#zero = بلا مخارج
workflow_palette.cannot_add = لا يمكن للقالب أن يبدأ إلا مسار عمل فارغًا.
workflow_palette.domain.control_flow = التدفق
workflow_palette.domain.intelligence = الرؤى
workflow_palette.domain.operations = العمليات
workflow_palette.domain.people = الأشخاص
workflow_palette.domain.registry = المراجع
workflow_palette.domain.rewards = الأجور
workflow_palette.step.approval = اطلب موافقة شخص قبل متابعة العمل.
workflow_palette.step.decision = اختر الخطوة التالية بناءً على البيانات المتوفرة.
workflow_palette.step.end = أنهِ مسار العمل بنتيجة مسمّاة.
workflow_palette.step.join = انتظر انتهاء الفروع المتوازية.
workflow_palette.step.observe = تحقق من أن نظامًا آخر يُظهر النتيجة المتوقعة.
workflow_palette.step.parallel = شغِّل عدة فروع في الوقت نفسه.
workflow_palette.step.signal = انتظر حدثًا من نظام آخر.
workflow_palette.step.subworkflow = شغِّل مسار عمل منشورًا آخر.
workflow_palette.step.task = كلِّف شخصًا بمهمة.
workflow_palette.step.transform = أعد تشكيل القيم لخطوة لاحقة.
workflow_palette.step.wait = توقف مؤقتًا حتى تاريخ أو وقت محدد.
workflow_release.action_activate = نشر وتفعيل
workflow_release.action_approval = إرسال للموافقة
workflow_release.action_save = حفظ المسودة
workflow_release.action_test = تشغيل الاختبار
workflow_release.activation = تفعيل
workflow_release.approval = موافقة
workflow_release.description = اختبر المسودة المكتملة، واحصل على الموافقة، ثم فعّل الإصدار الذي سيستخدمه العمل الجديد.
workflow_release.next = التالي: {action}
workflow_release.state_blocked = محظور
workflow_release.state_not_started = لم يبدأ
workflow_release.state_ready = جاهز
workflow_release.state_waiting = في الانتظار
workflow_release.test = اختبار
workflow_release.title = من المسودة إلى التشغيل
workflow_viewer.effect.external_mutation = تغيّر نظامًا آخر
workflow_viewer.effect.internal_mutation = تغيّر بيانات الموارد البشرية
workflow_viewer.effect.irreversible_external_mutation = تغيّر نظامًا آخر بشكل دائم
workflow_viewer.effect.pure = بلا آثار جانبية
workflow_viewer.effect.read_only = تقرأ البيانات
workflow_viewer.lock.closure = الإغلاق
workflow_viewer.lock.governance = الموافقة
workflow_viewer.lock.reconciliation = المطابقة
workflow_viewer.lock.revalidation = إعادة التحقق
workflow_viewer.lock.start = البداية
workflow_viewer.outcome.ambiguous = نتيجة غير واضحة
workflow_viewer.outcome.blocked = محظور
workflow_viewer.outcome.compensated = تم التراجع
workflow_viewer.outcome.complete = مكتمل
workflow_viewer.outcome.consistent = متسق
workflow_viewer.outcome.degraded = متسق جزئيًا
workflow_viewer.outcome.fail = غير مطابق
workflow_viewer.outcome.fired = حان الوقت
workflow_viewer.outcome.late = متأخر جدًا
workflow_viewer.outcome.partial = مطابق جزئيًا
workflow_viewer.outcome.pass = مطابق
workflow_viewer.outcome.repair_plan = يلزم إصلاح
workflow_viewer.outcome.repair_required = يلزم إصلاح
workflow_viewer.outcome.succeeded = تم
workflow_viewer.outcome.unknown = أي نتيجة أخرى
workflow_viewer.outcome.valid = ما زال صالحًا
workflow_viewer.overlay.add = أُضيفت
workflow_viewer.overlay.omit = استُبعدت
workflow_viewer.overlay.replace = استُبدلت
workflow_viewer.reversal.compensate_or_correct = يُتراجع عنها أو تُصحَّح لاحقًا
workflow_viewer.reversal.compensation_required = يُتراجع عنها بخطوة تعويضية
workflow_viewer.reversal.forward_correction = لا يمكن إلا تصحيحها لاحقًا
workflow_viewer.reversal.no_effect = لا شيء للتراجع عنه
workflow_viewer.reversal.unresolved = طريقة التراجع غير محددة
workflow_viewer.source.constant = قيمة ثابتة
workflow_viewer.source.context = من سياق التنفيذ
workflow_viewer.source.node_output = من خطوة سابقة
workflow_viewer.source.workflow_input = من الطلب الذي يبدأ مسار العمل
`
