package productui

// workflowEditorStylesheet styles the draft editor: the bar, the step library,
// the path and the step inspector. It is concatenated into the server-rendered
// sheet whose hash the content security policy pins, so nothing here may be
// written at run time, and it uses product tokens only so every brand, theme
// and contrast setting reaches it.
//
// The surface has one border weight and two surfaces. A selected step, an
// unfinished route and an exit's tone are the only things allowed colour,
// because they are the only things an author is looking for.
func workflowEditorStylesheet() string {
	return `.workflow-designer-page.editing{display:grid;gap:var(--hcm-space-2)}
.network-stage:has(.workflow-designer-page.editing)>.page-head{position:absolute;inline-size:1px;block-size:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.workflow-designer-page .status-chip{display:inline-flex;align-items:center;gap:.25rem;padding:.0625rem .5rem;border:1px solid var(--control-border,var(--line));border-radius:999px;color:var(--muted);font-size:var(--hcm-font-size-small);font-weight:600;white-space:nowrap}.workflow-designer-page .status-chip[data-tone=positive]{color:var(--success);border-color:var(--success)}.workflow-designer-page .status-chip[data-tone=warning]{color:var(--warning);border-color:var(--warning)}.workflow-designer-page .status-chip[data-tone=danger]{color:var(--danger);border-color:var(--danger)}.workflow-designer-page .status-chip[data-tone=info]{color:var(--info);border-color:var(--info)}
.workflow-editor{display:grid;gap:var(--hcm-space-2);min-inline-size:0}
.workflow-editor-bar{display:flex;flex-wrap:wrap;align-items:center;gap:var(--hcm-space-2) var(--hcm-space-3);padding-block-end:var(--hcm-space-2);border-block-end:1px solid var(--line)}
.workflow-editor-back{display:inline-flex;align-items:center;gap:.25rem;color:var(--muted);text-decoration:none;font-size:var(--hcm-font-size-small);padding:.375rem .5rem;margin-inline-start:-.5rem;border-radius:var(--hcm-radius-control)}
.workflow-editor-back:hover,.workflow-editor-back:focus-visible{color:var(--ink);background:var(--soft)}
.workflow-editor-back-icon{inline-size:1rem;block-size:1rem}[dir=rtl] .workflow-editor-back-icon{transform:scaleX(-1)}
.workflow-editor-identity{display:flex;flex-wrap:wrap;align-items:center;gap:var(--hcm-space-1) var(--hcm-space-2);flex:1 1 18rem;min-inline-size:0}
.workflow-editor-name-field,.workflow-inspector-name-field{display:flex;align-items:center;gap:.25rem;min-inline-size:0}.workflow-editor-name-field{flex:0 1 auto}.workflow-editor-name-icon{inline-size:.875rem;block-size:.875rem;flex:none;color:var(--muted)}
h2.workflow-editor-name{margin:0;font-size:1.25rem;line-height:1.3}
input.workflow-editor-name{inline-size:100%;min-block-size:2.5rem;padding:.25rem .5rem;margin-inline-start:-.5rem;border:1px solid transparent;border-radius:var(--hcm-radius-control);background:transparent;color:var(--ink);font:inherit;font-size:1.25rem;font-weight:650;text-overflow:ellipsis}
input.workflow-editor-name:hover{border-color:var(--control-border,var(--line))}
input.workflow-editor-name:focus-visible{border-color:var(--accent);background:var(--surface)}
.workflow-editor-parity{display:inline-flex;align-items:center;gap:.375rem;padding:.125rem .5rem;border:1px solid var(--control-border,var(--line));border-radius:999px;color:var(--muted);font-size:var(--hcm-font-size-small);white-space:nowrap}.workflow-editor-parity::before{content:"";inline-size:.375rem;block-size:.375rem;border-radius:50%;background:var(--success)}.workflow-editor-parity[data-parity=changed]::before{background:var(--warning)}
.workflow-editor-version{color:var(--muted);font-size:var(--hcm-font-size-small);font-variant-numeric:tabular-nums;white-space:nowrap}
.workflow-editor-tools{display:flex;flex-wrap:wrap;align-items:center;gap:var(--hcm-space-1);margin-inline-start:auto}
.workflow-editor-history{display:flex;gap:.125rem}.workflow-editor-history .icon-button{inline-size:2.25rem;block-size:2.25rem;padding:.5rem}.workflow-editor-history svg{inline-size:1.125rem;block-size:1.125rem}
[dir=rtl] .workflow-editor-history svg{transform:scaleX(-1)}
.workflow-editor-popover{position:relative}.workflow-editor-popover>summary{list-style:none;cursor:pointer;white-space:nowrap}.workflow-editor-popover>summary::-webkit-details-marker{display:none}
.workflow-editor-popover>summary[data-tone=warning]{color:var(--warning);border-color:var(--warning)}
.workflow-editor-popover-body{position:absolute;inset-block-start:calc(100% + .375rem);inset-inline-end:0;z-index:5;inline-size:min(24rem,calc(100vw - 2rem));max-block-size:min(24rem,70dvh);overflow:auto;display:grid;gap:var(--hcm-space-1);padding:var(--hcm-space-2);border:1px solid var(--control-border,var(--line));border-radius:var(--hcm-radius-surface);background:var(--surface)}
.workflow-editor-change-list,.workflow-editor-problem-list{list-style:none;margin:0;padding:0;display:grid;gap:.125rem}
.workflow-editor-change{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:baseline;gap:var(--hcm-space-1);padding-block:.25rem}
.workflow-editor-problem{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:start;gap:.375rem;inline-size:100%;padding:.5rem;border:0;border-radius:var(--hcm-radius-control);background:transparent;color:var(--ink);font:inherit;text-align:start;cursor:pointer}
.workflow-editor-problem:hover,.workflow-editor-problem:focus-visible{background:var(--soft)}.workflow-editor-problem span{text-decoration:underline dotted;text-underline-offset:.2em}.workflow-editor-problem-icon{inline-size:.875rem;block-size:.875rem;margin-block-start:.1875rem;color:var(--muted)}[dir=rtl] .workflow-editor-problem-icon{transform:scaleX(-1)}
.workflow-designer-status{margin:0;color:var(--muted);font-size:var(--hcm-font-size-small)}.workflow-designer-status:empty{display:none}.workflow-editor-tools .workflow-designer-status{max-inline-size:26rem;text-align:end;margin-inline-end:var(--hcm-space-1)}
.workflow-editor-panes{display:grid;grid-template-columns:14rem minmax(0,1fr) 20rem;gap:var(--hcm-space-3);align-items:start}
.workflow-palette,.workflow-editor-inspector{position:sticky;inset-block-start:var(--hcm-space-2);max-block-size:calc(100dvh - var(--hcm-space-4));overflow:auto;overscroll-behavior:contain;min-inline-size:0}
.workflow-palette{display:grid;gap:var(--hcm-space-2);align-content:start;padding-inline:.125rem var(--hcm-space-1)}
.workflow-palette-more{display:none}.workflow-path-no-exit{display:flex;align-items:center;gap:.375rem;margin:var(--hcm-space-2) 0 0;color:var(--warning);font-size:var(--hcm-font-size-small)}.workflow-inspector-notify-routing{color:var(--muted)}.workflow-palette h3{display:flex;align-items:baseline;gap:.5rem;margin:0;font-size:1rem}.workflow-palette-count{color:var(--muted);font-size:var(--hcm-font-size-small);font-weight:400}.workflow-palette h4{margin:0;color:var(--muted);font-size:var(--hcm-font-size-small);font-weight:600}
.workflow-palette input[type=search]{inline-size:100%;min-block-size:2.25rem}
.workflow-palette-groups{display:grid;gap:var(--hcm-space-3)}.workflow-palette-group{display:grid;gap:.25rem}
.workflow-palette-list{list-style:none;margin:0;padding:0;display:grid}
.workflow-palette-item{min-inline-size:0}.workflow-palette-row{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:.5rem;inline-size:100%;padding-block:.375rem;padding-inline:.5rem;border:1px solid transparent;border-radius:var(--hcm-radius-control);background:transparent;color:var(--ink);font:inherit;text-align:start;cursor:pointer}.workflow-palette-row:hover:not(:disabled){background:var(--soft)}.workflow-palette-row:focus-visible{outline:2px solid var(--hcm-color-focus,var(--accent));outline-offset:1px}.workflow-palette-row:disabled{opacity:.55;cursor:not-allowed}.workflow-palette-plus{inline-size:1rem;block-size:1rem;color:var(--muted);flex:none}.workflow-palette-row:hover:not(:disabled) .workflow-palette-plus{color:var(--accent)}
.workflow-palette-copy{display:grid;gap:.0625rem;min-inline-size:0}.workflow-palette-copy>*{min-inline-size:0;overflow-wrap:break-word}.workflow-palette-copy strong{font-weight:600}
.workflow-palette-copy .muted{font-size:var(--hcm-font-size-small);line-height:1.35}
.workflow-palette-flags{display:flex;flex-wrap:wrap;gap:.25rem}.workflow-palette-flags:empty{display:none}
.workflow-palette-flag{font-size:var(--hcm-font-size-small);color:var(--muted)}.workflow-palette-flag[data-tone=warning]{color:var(--warning)}
.workflow-palette-flag+.workflow-palette-flag::before{content:"/";margin-inline-end:.25rem;color:var(--muted)}
.workflow-editor .icon-button{background:transparent;border:1px solid transparent;color:var(--muted);box-shadow:none}.workflow-editor .icon-button:hover:not(:disabled),.workflow-editor .icon-button:focus-visible{background:var(--surface);border-color:var(--control-border,var(--line));color:var(--ink)}.workflow-editor .icon-button:disabled{opacity:.55;color:var(--muted)}

.workflow-palette-empty{margin:0}
.workflow-path{display:grid;grid-template-columns:minmax(0,1fr) 11.5rem;gap:var(--hcm-space-3);align-items:start;padding:var(--hcm-space-3);border:1px solid var(--line);border-radius:var(--hcm-radius-surface);background:var(--canvas);min-inline-size:0}
.workflow-path-empty{grid-template-columns:1fr;min-block-size:22rem;place-content:center}.workflow-path-empty-copy{display:grid;gap:var(--hcm-space-1);max-inline-size:26rem}.workflow-path-empty-copy h3,.workflow-path-empty-copy p{margin:0}.workflow-path-starters{display:grid;gap:var(--hcm-space-1);margin-block-start:var(--hcm-space-2)}.workflow-path-starter{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:var(--hcm-space-2);inline-size:100%;padding:.625rem .75rem;text-align:start;block-size:auto}.workflow-path-starter .button-icon{inline-size:1.125rem;block-size:1.125rem}.workflow-path-starter span{display:grid;gap:.0625rem}.workflow-path-starter small{font-weight:400;font-size:var(--hcm-font-size-small)}
.workflow-path-main{display:grid;gap:var(--hcm-space-4);min-inline-size:0;max-inline-size:32rem;inline-size:100%;justify-self:center}
.workflow-path-steps{list-style:none;margin:0;padding:0}
.workflow-path-row{display:grid;grid-template-columns:auto minmax(0,1fr)}
.workflow-path-rail{position:relative;inline-size:0}.workflow-path-rail svg{position:absolute;inset:0;inline-size:100%;block-size:100%;overflow:visible}
[data-lanes="1"] .workflow-path-rail{inline-size:12px}[data-lanes="2"] .workflow-path-rail{inline-size:24px}[data-lanes="3"] .workflow-path-rail{inline-size:36px}[data-lanes="4"] .workflow-path-rail{inline-size:48px}[data-lanes="5"] .workflow-path-rail{inline-size:60px}[data-lanes="6"] .workflow-path-rail,[data-lanes="7"] .workflow-path-rail,[data-lanes="8"] .workflow-path-rail,[data-lanes="9"] .workflow-path-rail{inline-size:72px}
[dir=rtl] .workflow-path-rail svg{transform:scaleX(-1)}
.workflow-rail-line{fill:none;stroke:var(--muted);stroke-width:1.75}.workflow-rail-line.back{stroke-dasharray:4 3}.workflow-rail-line.active{stroke:var(--accent);stroke-width:2;opacity:1}
.workflow-path-rail.arrives::after{content:"";position:absolute;inset-block-start:calc(50% - 4px);inset-inline-end:-1px;border-block:4px solid transparent;border-inline-start:6px solid var(--muted)}
.workflow-path-step{display:grid;grid-template-columns:1.5rem minmax(0,1fr) auto;align-items:start;gap:var(--hcm-space-2);inline-size:100%;min-block-size:3.25rem;padding:.5rem .75rem;border:1px solid var(--control-border,var(--line));border-radius:var(--hcm-radius-control);background:var(--surface);color:var(--ink);font:inherit;text-align:start;cursor:pointer;transition:border-color var(--hcm-motion-fast) var(--hcm-motion-easing),background-color var(--hcm-motion-fast) var(--hcm-motion-easing)}
.workflow-path-step[data-step-type=decision]{border-radius:1.625rem;padding-inline:1rem}
.workflow-path-step:hover{border-color:color-mix(in oklab,var(--accent) 55%,var(--line))}
.workflow-path-step:focus-visible,.workflow-path-exit:focus-visible,.workflow-editor-problem:focus-visible{outline:2px solid var(--hcm-color-focus,var(--accent));outline-offset:2px}
.workflow-path-step.selected{border-color:var(--accent);box-shadow:inset 3px 0 0 var(--accent),inset 0 0 0 1px var(--accent);background:var(--soft)}[dir=rtl] .workflow-path-step.selected{box-shadow:inset -3px 0 0 var(--accent),inset 0 0 0 1px var(--accent)}
.workflow-path-number{padding-block-start:.125rem;color:var(--muted);font-size:var(--hcm-font-size-small);font-variant-numeric:tabular-nums;text-align:center}.workflow-path-step.loose{border-style:dashed}
.workflow-path-copy{display:grid;gap:.0625rem;min-inline-size:0}.workflow-path-copy strong{font-weight:600;overflow-wrap:break-word;hyphens:auto}
.workflow-path-meta{display:flex;flex-wrap:wrap;align-items:center;gap:.125rem .5rem;color:var(--muted);font-size:var(--hcm-font-size-small)}
.workflow-path-flag{display:inline-flex;align-items:center;gap:.25rem}.workflow-path-todo{display:inline-flex;align-items:center;gap:.25rem;color:var(--warning);font-size:var(--hcm-font-size-small);white-space:nowrap}.workflow-path-todo-icon{inline-size:.875rem;block-size:.875rem}.workflow-path-lock{inline-size:.8125rem;block-size:.8125rem}
.workflow-path-marks{display:flex;flex-wrap:wrap;gap:.25rem;margin-block-start:.25rem}.workflow-path-exit-chip{display:inline-flex;align-items:center;gap:.3125rem;padding:.0625rem .4375rem;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:.75rem;line-height:1.4;white-space:nowrap}.workflow-path-exit-chip.more{border-style:dashed}
.workflow-path-mark{--mark:var(--muted);box-sizing:border-box;display:inline-block;inline-size:.625rem;block-size:.625rem;border-radius:50%;border:2px solid var(--mark);background:var(--mark);flex:none}
.workflow-path-mark[data-tone=danger]{--mark:var(--danger)}.workflow-path-mark[data-tone=warning]{--mark:var(--warning)}.workflow-path-mark[data-tone=positive]{--mark:var(--success)}.workflow-path-mark[data-tone=info]{--mark:var(--info)}
.workflow-path-mark[data-shape="1"]{background:transparent}.workflow-path-mark[data-shape="2"]{border-radius:1px}.workflow-path-mark[data-shape="3"]{border-radius:1px;background:transparent}
.workflow-path-step.static,.workflow-path-exit.static{cursor:default}.workflow-path-step.static:hover{border-color:var(--control-border,var(--line))}.workflow-path-exit.static:hover{background:transparent;border-color:transparent}.workflow-path-step.current{border-color:var(--accent);box-shadow:inset 0 0 0 1px var(--accent)}
.workflow-path-state{color:var(--ink)}.workflow-path-state[data-tone=positive]{color:var(--success)}.workflow-path-state[data-tone=danger]{color:var(--danger)}.workflow-path-state[data-tone=warning]{color:var(--warning)}.workflow-path-state[data-tone=info]{color:var(--info)}
.workflow-path-after{display:grid;min-inline-size:0}.workflow-path-before{min-inline-size:0}.workflow-path-arrivals{padding-block:0 .25rem}.workflow-editor li,.workflow-path li{font-size:inherit}.workflow-editor [dir=auto],.workflow-path [dir=auto]{text-align:match-parent}
.workflow-path-jumps{list-style:none;margin:0;padding:.25rem 0 0;padding-inline-start:2.75rem;display:grid;gap:.0625rem;color:var(--muted);font-size:.75rem}.workflow-path-jumps li{display:flex;align-items:center;gap:.25rem}.workflow-path-jump{display:inline-flex;align-items:center;gap:.25rem;padding:.125rem .25rem;margin-inline-start:-.25rem;border:0;border-radius:var(--hcm-radius-control);background:transparent;color:var(--muted);font:inherit;text-align:start;cursor:pointer;text-decoration:underline dotted;text-underline-offset:.2em}.workflow-path-jump:hover,.workflow-path-jump:focus-visible{color:var(--ink);background:var(--soft)}.workflow-path-jump.primary{color:var(--ink);font-size:var(--hcm-font-size-small);text-decoration:none}li.workflow-path-jump.static{color:var(--muted);text-decoration:none;cursor:default}li.workflow-path-jump.static.primary{color:var(--ink)}.workflow-path-jump-icon{inline-size:.75rem;block-size:.75rem;flex:none}
.workflow-path-link{position:relative;min-block-size:1.5rem;margin-inline-start:1.4375rem;padding-inline-start:.875rem;border-inline-start:2px solid var(--control-border,var(--line));display:flex;align-items:center;color:var(--ink);font-size:var(--hcm-font-size-small)}
.workflow-path-link.broken{border-inline-start:2px dotted var(--control-border,var(--line));color:var(--muted);min-block-size:1.5rem;font-size:.75rem}.workflow-path-link{flex-wrap:wrap;gap:0 .75rem}.workflow-path-link.unfinished{border-inline-start:2px dashed var(--warning);min-block-size:1.75rem}.workflow-path-link-open{display:inline-flex;align-items:center;gap:.25rem;color:var(--warning);font-size:.75rem}
.workflow-path-loose{display:grid;gap:var(--hcm-space-1);padding-block-start:var(--hcm-space-3);border-block-start:1px dashed var(--control-border,var(--line))}
.workflow-path-loose h3,.workflow-path-exits h3{margin:0;font-size:var(--hcm-font-size-small);font-weight:600;color:var(--muted)}.workflow-path-exits-heading p{margin:0;font-size:var(--hcm-font-size-small)}.workflow-path-exits h3,.workflow-path-loose h3{overflow-wrap:normal;word-break:normal;flex:none}.workflow-path-loose p{margin:0 0 var(--hcm-space-1);font-size:var(--hcm-font-size-small)}
.workflow-path-loose .workflow-path-row+.workflow-path-row{margin-block-start:var(--hcm-space-1)}
.workflow-path-exits{position:sticky;inset-block-start:var(--hcm-space-2);display:grid;gap:var(--hcm-space-1)}
.workflow-path-rail-key{list-style:none;margin:var(--hcm-space-1) 0 0;padding:var(--hcm-space-1) 0 0;border-block-start:1px solid var(--line);display:grid;gap:.125rem;color:var(--muted);font-size:.75rem}.workflow-path-rail-key li{display:flex;align-items:center;gap:.5rem}.workflow-path-rail-sample{inline-size:1.25rem;border-block-start:2px solid var(--muted);flex:none}.workflow-path-rail-sample.back{border-block-start-style:dashed}
.workflow-path-exit-list{list-style:none;margin:0;padding:0;display:grid;gap:.25rem}
.workflow-path-exit{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:0 .5rem;inline-size:100%;padding:.4375rem .625rem;border:1px solid transparent;border-radius:var(--hcm-radius-control);background:transparent;color:var(--ink);font:inherit;text-align:start;cursor:pointer}
.workflow-path-exit strong{font-weight:600;font-size:var(--hcm-font-size-small);overflow-wrap:normal}.workflow-path-exit-count{grid-column:2;color:var(--muted);font-size:.75rem;font-variant-numeric:tabular-nums}
.workflow-path-exit:hover,.workflow-path-exit:focus-visible{background:var(--surface);border-color:var(--control-border,var(--line))}
.workflow-path-exit.linked{box-shadow:inset 2px 0 0 var(--accent)}[dir=rtl] .workflow-path-exit.linked{box-shadow:inset -2px 0 0 var(--accent)}.workflow-path-exit.dimmed strong{color:var(--muted);font-weight:500}
.workflow-path-exit.selected{background:var(--soft);border-color:var(--accent);box-shadow:inset 0 0 0 1px var(--accent)}
.workflow-inspector{display:grid;gap:var(--hcm-space-3);align-content:start;min-inline-size:0}
.workflow-inspector-head{display:grid;gap:.125rem}input.workflow-inspector-name{inline-size:100%;min-block-size:2.5rem;padding:.25rem .5rem;margin-inline-start:-.5rem;border:1px solid transparent;border-radius:var(--hcm-radius-control);background:transparent;color:var(--ink);font:inherit;font-size:1.125rem;font-weight:650;text-overflow:ellipsis}input.workflow-inspector-name,input.workflow-editor-name{field-sizing:content;inline-size:auto;min-inline-size:6rem;max-inline-size:100%}input.workflow-inspector-name:hover{border-color:var(--control-border,var(--line))}input.workflow-inspector-name:focus-visible{border-color:var(--accent);background:var(--surface)}.workflow-inspector-head h3{margin:0;font-size:1.125rem;overflow-wrap:anywhere}
.workflow-inspector-kind{margin:0;color:var(--muted);font-size:var(--hcm-font-size-small)}
.workflow-inspector-note{display:flex;align-items:flex-start;gap:.5rem;margin:0;color:var(--muted);font-size:var(--hcm-font-size-small)}.workflow-inspector-note-icon{inline-size:1rem;block-size:1rem;flex:none;margin-block-start:.125rem}
.workflow-inspector-section{display:grid;gap:var(--hcm-space-2);padding-block-start:var(--hcm-space-3);border-block-start:1px solid var(--line)}
.workflow-inspector-section h4{margin:0;font-size:var(--hcm-font-size-small);font-weight:600;color:var(--muted)}
.workflow-inspector-notify h4{display:flex;align-items:center;gap:.375rem}.workflow-inspector-notify-icon{inline-size:.875rem;block-size:.875rem;flex:none}
.workflow-inspector-notify-list{display:grid;gap:.375rem;margin:0;padding-inline-start:1.125rem;font-size:var(--hcm-font-size-small);line-height:1.45}
.workflow-inspector-help{margin:0;font-size:var(--hcm-font-size-small)}.workflow-inspector-exceptions>summary{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:.375rem;cursor:pointer;list-style:none;padding:.375rem .5rem;margin-inline:-.5rem;border-radius:var(--hcm-radius-control)}.workflow-inspector-exceptions>summary::-webkit-details-marker{display:none}.workflow-inspector-exceptions>summary:hover{background:var(--soft)}.workflow-inspector-chevron{inline-size:.875rem;block-size:.875rem;color:var(--muted);transform:rotate(-90deg)}[dir=rtl] .workflow-inspector-chevron{transform:rotate(90deg)}.workflow-inspector-exceptions[open] .workflow-inspector-chevron{transform:none}.workflow-inspector-exceptions>summary .muted{font-size:var(--hcm-font-size-small)}.workflow-inspector-exceptions[open]>summary{margin-block-end:var(--hcm-space-1)}
.workflow-inspector-fields{display:grid;gap:var(--hcm-space-2)}
.workflow-inspector .labeled-control,.workflow-inspector-route{display:grid;gap:.25rem;min-inline-size:0}
.workflow-inspector :where(input:not([type=checkbox]),select){inline-size:100%;min-inline-size:0;min-block-size:2.5rem}
.workflow-inspector-route label{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:.25rem}.workflow-inspector-route.open select{border-color:var(--warning)}.workflow-inspector-unset{display:inline-flex;align-items:center;gap:.25rem;color:var(--warning);font-size:var(--hcm-font-size-small)}.workflow-inspector-unset-icon{inline-size:.875rem;block-size:.875rem}.workflow-inspector-connect{padding:var(--hcm-space-2);border:1px solid var(--warning);border-radius:var(--hcm-radius-control)}
.workflow-inspector-fixed{margin:0;color:var(--muted)}.workflow-inspector-exceptions>.workflow-inspector-help{margin-block-end:var(--hcm-space-2)}.workflow-inspector-bulk{display:grid;gap:.25rem;margin-block-end:var(--hcm-space-2);padding:var(--hcm-space-2);border-radius:var(--hcm-radius-control);background:var(--soft)}.workflow-inspector-bulk label{font-size:var(--hcm-font-size-small);color:var(--muted)}
.workflow-inspector-remove{padding-block-start:var(--hcm-space-3);border-block-start:1px solid var(--line)}
.workflow-inspector .workflow-inspector-remove-button{display:inline-flex;align-items:center;gap:.375rem;padding-inline:.5rem;border:1px solid transparent;background:transparent;box-shadow:none;color:var(--danger)}.workflow-inspector .workflow-inspector-remove-button:hover,.workflow-inspector .workflow-inspector-remove-button:focus-visible{border-color:var(--danger);background:transparent}.workflow-inspector-remove-button .button-icon{inline-size:1rem;block-size:1rem}
.workflow-overlay-actions{display:flex;flex-wrap:wrap;gap:var(--hcm-space-1)}.workflow-overlay-history>summary{cursor:pointer;color:var(--muted);font-size:var(--hcm-font-size-small)}.workflow-overlay-history ol{display:grid;gap:var(--hcm-space-1);padding-inline-start:1.25rem;margin-block:var(--hcm-space-1) 0}.workflow-overlay-history li{display:grid;gap:.125rem}
.workflow-editor-hop{position:absolute;inline-size:1px;block-size:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;align-items:center;gap:.375rem;padding:.5rem .75rem;border-radius:var(--hcm-radius-control);color:var(--ink);font-size:var(--hcm-font-size-small);font-weight:600;text-decoration:none}.workflow-editor-hop:focus-visible{position:static;display:inline-flex;inline-size:auto;block-size:auto;overflow:visible;clip-path:none;outline:2px solid var(--hcm-color-focus,var(--accent));outline-offset:2px}.workflow-editor-hop svg{inline-size:1rem;block-size:1rem;flex:none}.workflow-editor-hop-settings{position:sticky;inset-block-end:0;z-index:4;justify-content:center;margin-inline:calc(var(--hcm-space-2) * -1);padding-block:.75rem;border-radius:0;border-block-start:1px solid var(--line);background:var(--canvas)}.workflow-editor-hop-settings span{min-inline-size:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.workflow-designer-page[aria-busy=true]{cursor:progress}.workflow-designer-page[aria-busy=true] .workflow-editor-panes{opacity:.72}.workflow-palette input::placeholder{color:var(--muted)}.workflow-inspector-basis{margin:0;font-size:var(--hcm-font-size-small);line-height:1.45}.workflow-inspector-exceptions summary .workflow-inspector-unset{margin-inline-start:auto}.workflow-designer-page[aria-busy=true] :where(.workflow-editor-panes,.workflow-editor-tools,.workflow-designer-actions,.workflow-version-create){pointer-events:none}
@media (max-width:1560px){.workflow-path{grid-template-columns:1fr}.workflow-path-exits{order:-1;inset-block-start:0;z-index:3;margin:calc(var(--hcm-space-3) * -1) calc(var(--hcm-space-3) * -1) 0;padding:var(--hcm-space-2) var(--hcm-space-3);border-block-end:1px solid var(--line);background:var(--canvas);border-start-start-radius:var(--hcm-radius-surface);border-start-end-radius:var(--hcm-radius-surface)}.workflow-path-exits-heading{display:flex;align-items:baseline;gap:var(--hcm-space-2)}.workflow-path-exit-list{display:flex;flex-wrap:wrap}.workflow-path-rail-key{display:flex;flex-wrap:wrap;gap:.125rem var(--hcm-space-3);margin:0;padding:0;border:0}.workflow-path-exit-count{grid-column:auto}.workflow-path-exit{inline-size:auto;grid-template-columns:auto auto auto;gap:.375rem;padding:.125rem .5rem;border-color:var(--control-border,var(--line));background:var(--surface)}}
@media (max-width:1400px){.workflow-editor-panes{grid-template-columns:minmax(0,1fr) 19rem}.workflow-palette{grid-column:1/-1;position:static;order:-1;max-block-size:11rem;overflow:hidden;padding:var(--hcm-space-2) var(--hcm-space-2) 0;background:var(--canvas);border:1px solid var(--line);border-radius:var(--hcm-radius-surface);grid-template-columns:auto minmax(10rem,16rem);align-items:center}.workflow-palette-groups{grid-column:1/-1;display:grid;gap:var(--hcm-space-2)}.workflow-palette-list{grid-template-columns:repeat(auto-fill,minmax(13rem,1fr));gap:.125rem var(--hcm-space-2)}.workflow-palette-groups::after{content:"";position:sticky;inset-block-end:0;display:block;block-size:.5rem;margin-block-start:0;pointer-events:none;background:linear-gradient(to bottom,transparent,color-mix(in srgb,var(--canvas) 70%,transparent))}}
@media (max-width:1400px){.workflow-palette{grid-template-columns:auto minmax(0,1fr) minmax(10rem,16rem)}.workflow-palette.expanded{max-block-size:min(60vh,34rem);overflow:auto}.workflow-palette-more{display:inline-flex;grid-row:1;grid-column:2;justify-self:end}.workflow-palette-search{grid-row:1;grid-column:3}.workflow-palette.expanded .workflow-palette-groups::after{display:none}}
@media (max-width:560px){.workflow-palette{grid-template-columns:minmax(0,1fr) auto;max-block-size:13.5rem}.workflow-palette h3{grid-column:1/-1}.workflow-palette-search{grid-row:2;grid-column:1}.workflow-palette-more{grid-row:2;grid-column:2;justify-self:end;align-self:center}.workflow-palette-groups{grid-column:1/-1}.workflow-palette h3{flex-wrap:wrap}}
@media (max-width:820px){.workflow-editor-panes{grid-template-columns:1fr}.workflow-editor-inspector{position:static;max-block-size:none;padding-block-start:var(--hcm-space-3);border-block-start:1px solid var(--line);scroll-margin-block-start:var(--hcm-space-2)}.workflow-editor-hop{position:static;display:inline-flex;inline-size:auto;block-size:auto;overflow:visible;clip-path:none}.workflow-editor-hop-settings{position:sticky;display:flex}.workflow-path-main{padding-block-end:var(--hcm-space-2)}.workflow-path{padding:var(--hcm-space-2)}.workflow-editor-tools{margin-inline-start:0}.workflow-editor-popover-body{inset-inline:0 auto}}
@media (max-width:420px){.workflow-path{padding:var(--hcm-space-1);border-inline:0;border-radius:0;margin-inline:calc(var(--hcm-space-1) * -1)}.workflow-path-step{padding-inline:.5rem;gap:var(--hcm-space-1)}.workflow-path-jumps{padding-inline-start:2rem}[data-lanes] .workflow-path-rail{max-inline-size:36px}}
@supports not (field-sizing:content){input.workflow-editor-name,input.workflow-inspector-name{inline-size:100%}}
@media (prefers-reduced-motion:reduce){.workflow-path-step{transition:none}}`
}
