package application

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strconv"
	"time"

	chatcore "github.com/monstercameron/human-capital-management-suite/internal/collaboration/chat"
	"github.com/monstercameron/human-capital-management-suite/internal/collaboration/chatadmission"
	"github.com/monstercameron/human-capital-management-suite/internal/collaboration/chatstream"
	"github.com/monstercameron/human-capital-management-suite/internal/data/chatstore"
	"github.com/monstercameron/human-capital-management-suite/internal/trust"
)

var ErrChatStreamingDisabled = errors.New("application: chat streaming disabled")

// ChatStreamRuntime is the composition-owned bridge for live chat. The
// cursor key is supplied by ServeConfig and never generated by this runtime.
// A missing key leaves Watch disabled, so a deployment cannot accidentally
// expose unsigned or process-local resumable cursors.
type ChatStreamRuntime struct {
	stream    *chatstream.Stream
	bridge    chatstream.Bridge
	admission *chatadmission.Admission
	clock     func() time.Time
}

type ChatStreamRuntimeConfig struct {
	CursorKey       string
	Reader          chatstream.Reader
	Authorizer      chatstream.Authorizer
	PollInterval    time.Duration
	RecheckInterval time.Duration
	PageLimit       int
	QueueSize       int
	ReplayLimit     int
	CursorTTL       time.Duration
	Budgets         chatadmission.Config
	Clock           func() time.Time
}

func NewChatStreamRuntime(c ChatStreamRuntimeConfig) (*ChatStreamRuntime, error) {
	if c.CursorKey == "" {
		return nil, ErrChatStreamingDisabled
	}
	if c.Clock == nil {
		c.Clock = time.Now
	}
	stream, err := chatstream.New(chatstream.Config{Key: []byte(c.CursorKey), Reader: c.Reader, Authorizer: c.Authorizer, QueueSize: c.QueueSize, ReplayLimit: c.ReplayLimit, CursorTTL: c.CursorTTL, Clock: c.Clock, RecheckInterval: c.RecheckInterval})
	if err != nil {
		return nil, err
	}
	admission, err := chatadmission.New(c.Budgets)
	if err != nil {
		return nil, err
	}
	return &ChatStreamRuntime{stream: stream, admission: admission, clock: c.Clock, bridge: chatstream.Bridge{Stream: stream, Reader: c.Reader, PollInterval: c.PollInterval, PageLimit: c.PageLimit}}, nil
}

func (r *ChatStreamRuntime) Watch(ctx context.Context, req chatstream.WatchRequest) (*chatstream.Subscription, *chatadmission.Lease, error) {
	if r == nil || r.stream == nil || r.admission == nil {
		return nil, nil, ErrChatStreamingDisabled
	}
	lease, err := r.admission.Acquire(ctx, chatadmission.Request{TenantID: req.TenantID, ConversationID: req.ConversationID, Lane: chatadmission.LaneWatch})
	if err != nil {
		return nil, nil, err
	}
	sub, err := r.bridge.Watch(ctx, req)
	if err != nil {
		_ = lease.Release()
		return nil, nil, err
	}
	go func() {
		<-sub.Done()
		_ = lease.Release()
	}()
	return sub, lease, nil
}

// AcquireSend reserves the chat lane before a durable SendPost transaction.
func (r *ChatStreamRuntime) AcquireSend(ctx context.Context, tenantID, conversationID string) (*chatadmission.Lease, error) {
	return r.acquire(ctx, tenantID, conversationID, chatadmission.LaneSend)
}

// AcquireRead reserves the cheaper read lane for a bounded cursor page or a
// metadata lookup. It is shed before a send but after derived work.
func (r *ChatStreamRuntime) AcquireRead(ctx context.Context, tenantID, conversationID string) (*chatadmission.Lease, error) {
	return r.acquire(ctx, tenantID, conversationID, chatadmission.LaneRead)
}

// AcquireDerived reserves the ephemeral/derived lane: reference suggestions,
// integration event pulls and similar work the spec sheds first.
func (r *ChatStreamRuntime) AcquireDerived(ctx context.Context, tenantID, conversationID string) (*chatadmission.Lease, error) {
	return r.acquire(ctx, tenantID, conversationID, chatadmission.LaneDerived)
}

func (r *ChatStreamRuntime) acquire(ctx context.Context, tenantID, conversationID string, lane chatadmission.Lane) (*chatadmission.Lease, error) {
	if r == nil || r.admission == nil {
		return nil, ErrChatStreamingDisabled
	}
	lease, err := r.admission.Acquire(ctx, chatadmission.Request{TenantID: tenantID, ConversationID: conversationID, Lane: lane})
	if err != nil {
		return nil, chatOverload(err)
	}
	return lease, nil
}

// chatOverload maps a shed or saturated lane onto the chat contract's retryable
// unavailable result, so a caller sees "retry" rather than a denial. The
// admission sentinel stays in the chain for operators and tests.
func chatOverload(err error) error {
	if errors.Is(err, chatadmission.ErrOverloaded) {
		return fmt.Errorf("%w: %w", chatcore.ErrUnavailable, err)
	}
	return err
}

// chatStreamError names a failed subscribe in the chat contract's vocabulary.
//
// Every one of these used to leave here as a bare wrapped chatstream sentinel,
// which the transport could not classify: the request log recorded one
// UNAVAILABLE transport.unclassified_failure for a bad cursor, a revoked
// membership and a saturated watch lane alike, so the whole class of watch
// failures was invisible. The original stays in the chain, so a test and an
// operator can still see which condition it was.
func chatStreamError(err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, chatstream.ErrInvalidCursor), errors.Is(err, chatstream.ErrExpiredCursor):
		return fmt.Errorf("chat stream cursor: %w: %w", chatcore.ErrInvalidArgument, err)
	case errors.Is(err, chatstream.ErrUnauthorized), errors.Is(err, chatstream.ErrRevoked):
		return fmt.Errorf("chat stream authority: %w: %w", chatcore.ErrPermissionDenied, err)
	case errors.Is(err, chatadmission.ErrOverloaded), errors.Is(err, chatstream.ErrBackpressure), errors.Is(err, chatstream.ErrClosed):
		return fmt.Errorf("chat stream capacity: %w: %w", chatcore.ErrUnavailable, err)
	case errors.Is(err, chatstream.ErrInvalidConfig):
		return fmt.Errorf("chat stream configuration: %w: %w", ErrChatStreamingDisabled, err)
	}
	return fmt.Errorf("chat stream watch: %w", err)
}

// Revoke closes the live subscriptions one principal holds on a conversation.
// Membership removal calls it so revocation does not wait for the periodic
// re-authorization.
func (r *ChatStreamRuntime) Revoke(hostTenantID, homeTenantID, subjectID, conversationID string, membershipEpoch uint64) {
	if r != nil && r.stream != nil {
		r.stream.Revoke(hostTenantID, homeTenantID, subjectID, conversationID, membershipEpoch)
	}
}

// RevokeTenant closes every live subscription a consumer tenant holds on a host
// conversation. Cross-company grant revocation calls it.
func (r *ChatStreamRuntime) RevokeTenant(hostTenantID, homeTenantID, conversationID string) {
	if r != nil && r.stream != nil {
		r.stream.RevokeTenant(hostTenantID, homeTenantID, conversationID)
	}
}

type chatServiceReader struct {
	service    chatcore.ConversationService
	membership chatMembershipResolver
	events     chatDurableEventReader
}

// chatDurableEventReader exposes the store's global outbox watermark. The
// watermark must advance over records hidden by history policy, otherwise a
// watcher repeatedly scans the same invisible prefix forever.
type chatDurableEventReader interface {
	ReadConversationEvents(context.Context, chatcore.WatchConversationRequest, uint64, int) (chatstore.EventPage, error)
}
type chatPublicSequenceMapper interface {
	ResolvePublicSequence(context.Context, string, string, uint64) (uint64, error)
}
type chatMembershipResolver interface {
	GetMembership(context.Context, string, string, string, string) (chatcore.Membership, error)
}

type chatMachineWatchResolver interface {
	MachineWatchEpoch(context.Context, string, string, chatcore.Principal) (uint64, error)
}

// Read returns one bounded page of durable conversation events. The durable
// event source is mandatory: a live WatchConversation fallback here would
// re-enter the stream this reader feeds.
func (r chatServiceReader) Read(ctx context.Context, q chatstream.ReadRequest) (chatstream.Page, error) {
	if r.service == nil || r.events == nil {
		return chatstream.Page{}, ErrChatStreamingDisabled
	}
	homeTenant := q.HomeTenantID
	if homeTenant == "" {
		homeTenant = q.TenantID
	}
	principal := chatcore.Principal{TenantID: homeTenant, SubjectID: q.SubjectID}
	limit := q.Limit
	if limit <= 0 {
		return chatstream.Page{Complete: true}, nil
	}
	page, err := r.events.ReadConversationEvents(ctx, chatcore.WatchConversationRequest{Principal: principal, TenantID: q.TenantID, ConversationID: q.ConversationID}, q.AfterSequence, limit)
	if err != nil {
		return chatstream.Page{}, err
	}
	out := make([]chatstream.Event, 0, len(page.Events))
	// The membership epoch is a property of the reader's principal and
	// conversation, not of an individual event, so it is resolved once per page.
	epoch := uint64(0)
	if len(page.Events) > 0 || len(page.EphemeralPosts) > 0 {
		epoch, err = chatMembershipEpoch(ctx, r.service, r.membership, q.TenantID, q.ConversationID, principal)
		if err != nil {
			return chatstream.Page{}, err
		}
	}
	for _, event := range page.Events {
		payload, marshalErr := json.Marshal(event.Event)
		if marshalErr != nil {
			return chatstream.Page{}, marshalErr
		}
		sequence := event.Event.Sequence
		if parsed, parseErr := strconv.ParseUint(event.ResumeCursor, 10, 64); parseErr == nil && parsed > 0 {
			sequence = parsed
		}
		out = append(out, chatstream.Event{TenantID: q.TenantID, ConversationID: q.ConversationID, Sequence: sequence, MembershipEpoch: epoch, Payload: payload})
	}
	for _, post := range page.EphemeralPosts {
		payload, marshalErr := json.Marshal(post)
		if marshalErr != nil {
			return chatstream.Page{}, marshalErr
		}
		out = append(out, chatstream.Event{
			TenantID: q.TenantID, ConversationID: q.ConversationID, Sequence: post.Sequence,
			MembershipEpoch: epoch, RecipientHomeTenantID: post.RecipientHomeTenantID, RecipientSubjectID: post.RecipientSubjectID,
			Ephemeral: true, ExpiresAt: post.ExpiresAt, Payload: payload,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Sequence < out[j].Sequence })
	return chatstream.Page{Events: out, NextSequence: page.NextOffset, Complete: page.Complete}, nil
}

type chatServiceStreamAuthorizer struct {
	service    chatcore.ConversationService
	membership chatMembershipResolver
}

func (a chatServiceStreamAuthorizer) Authorize(ctx context.Context, access chatstream.Access) error {
	if a.service == nil {
		return ErrChatStreamingDisabled
	}
	home := access.HomeTenantID
	if home == "" {
		home = access.TenantID
	}
	principal := chatcore.Principal{TenantID: home, SubjectID: access.SubjectID}
	if _, err := a.service.GetConversation(ctx, chatcore.GetConversationRequest{Principal: principal, TenantID: access.TenantID, ConversationID: access.ConversationID}); err != nil {
		return err
	}
	epoch, err := chatMembershipEpoch(ctx, a.service, a.membership, access.TenantID, access.ConversationID, principal)
	if err != nil || epoch != access.MembershipEpoch {
		return chatcore.ErrPermissionDenied
	}
	routeEpoch, err := chatRouteEpoch(ctx, a.service, access.TenantID, access.ConversationID)
	if err != nil || routeEpoch != access.RouteEpoch {
		return chatcore.ErrPermissionDenied
	}
	return nil
}

func chatMembershipEpoch(ctx context.Context, service chatcore.ConversationService, resolver chatMembershipResolver, tenantID, conversationID string, principal chatcore.Principal) (uint64, error) {
	if verified, ok := trust.FromContext(ctx); ok && verified != nil && (verified.SubjectKind() == trust.SubjectKindAgent || verified.SubjectKind() == trust.SubjectKindIntegration) {
		if verified.Tenant().String() != principal.TenantID || verified.Subject() != principal.SubjectID || principal.TenantID != tenantID {
			return 0, chatcore.ErrPermissionDenied
		}
		machines, ok := resolver.(chatMachineWatchResolver)
		if !ok {
			return 0, chatcore.ErrPermissionDenied
		}
		return machines.MachineWatchEpoch(ctx, tenantID, conversationID, principal)
	}
	if resolver != nil {
		member, err := resolver.GetMembership(ctx, tenantID, conversationID, principal.TenantID, principal.SubjectID)
		if err != nil || member.LeftAt != nil {
			return 0, chatcore.ErrPermissionDenied
		}
		return member.Revision, nil
	}
	cursor := ""
	for pageNo := 0; pageNo < 100; pageNo++ {
		page, err := service.ListMemberships(ctx, chatcore.ListMembershipsRequest{Principal: principal, TenantID: tenantID, ConversationID: conversationID, Page: chatcore.Page{Cursor: cursor, PageSize: 100}})
		if err != nil {
			return 0, err
		}
		for _, member := range page.Memberships {
			if member.HomeTenantID == principal.TenantID && member.SubjectID == principal.SubjectID && member.LeftAt == nil {
				return member.Revision, nil
			}
		}
		if page.NextCursor == "" || page.NextCursor == cursor {
			break
		}
		cursor = page.NextCursor
	}
	return 0, chatcore.ErrPermissionDenied
}

// streamingChatService is the outermost chat decorator. It owns chat admission
// (every lane, not only sends) and the event-driven half of revocation: it holds
// the stream runtime and the authority cache, so a membership removal closes the
// affected subscriptions and drops the cached facts before returning.
type streamingChatService struct {
	chatcore.ConversationService
	runtime           *ChatStreamRuntime
	membership        chatMembershipResolver
	authority         *chatAuthorityCache
	personaDM         chatcore.PersonaDMResolver
	personaInvocation *PersonaInvocationServeWiring
	// projector is Chat's reader projection, installed with the document hub's
	// access check (bindAgentSourceAccess). Without it the stream is unprojected.
	projector agentWatchProjector
	// masker applies the workspace's language filters to a live event. It runs
	// only when no projector is bound: the projector (the core service) masks
	// as part of its own projection (CHATMOD-002).
	masker chatWatchMasker
}

// chatWatchMasker is the reader's masked view of one live watch event.
type chatWatchMasker interface {
	MaskWatchEvent(context.Context, chatcore.Principal, string, string, chatcore.WatchEvent) chatcore.WatchEvent
}

// agentWatchProjector is the one method of the Chat service the live watch needs.
type agentWatchProjector interface {
	ProjectWatchEvent(context.Context, chatcore.Principal, string, string, chatcore.WatchEvent) chatcore.WatchEvent
}

// bindPersonaInvocation installs the post-commit mention handoff while leaving
// this decorator as the served ConversationService. The handoff writes through
// the already routed and audited inner service, so this layer owns send admission
// exactly once and every other optional chat port remains promoted unchanged.
func (s *streamingChatService) bindPersonaInvocation(wiring *PersonaInvocationServeWiring) error {
	if s == nil || s.ConversationService == nil || wiring == nil || wiring.Chat == nil {
		return errPersonaInvocationServeWiring
	}
	s.personaInvocation = wiring
	return nil
}

func (s *streamingChatService) sendPost(ctx context.Context, request chatcore.SendPostRequest) (chatcore.Post, error) {
	if s == nil || s.ConversationService == nil {
		return chatcore.Post{}, chatcore.ErrUnavailable
	}
	if s.personaInvocation != nil {
		return s.personaInvocation.SendPost(ctx, request)
	}
	return s.ConversationService.SendPost(ctx, request)
}

// lease reserves one chat lane for a request. A composition without a stream
// runtime has no admission to take, and the call proceeds unmetered exactly as
// it did before.
func (s *streamingChatService) lease(ctx context.Context, lane chatadmission.Lane, tenantID, conversationID string) (*chatadmission.Lease, error) {
	if s.runtime == nil || tenantID == "" || conversationID == "" {
		return nil, nil
	}
	return s.runtime.acquire(ctx, tenantID, conversationID, lane)
}

func releaseChatLease(lease *chatadmission.Lease) {
	if lease != nil {
		_ = lease.Release()
	}
}

// GetConversation, ListPosts and ListMemberships take the cheaper read lane so a
// reconnect storm or a large-channel backfill cannot starve workflow through the
// shared process.
func (s *streamingChatService) GetConversation(ctx context.Context, r chatcore.GetConversationRequest) (chatcore.Conversation, error) {
	lease, err := s.lease(ctx, chatadmission.LaneRead, r.TenantID, r.ConversationID)
	if err != nil {
		return chatcore.Conversation{}, err
	}
	defer releaseChatLease(lease)
	return s.ConversationService.GetConversation(ctx, r)
}

func (s *streamingChatService) ListPosts(ctx context.Context, r chatcore.ListPostsRequest) (chatcore.ListPostsResponse, error) {
	lease, err := s.lease(ctx, chatadmission.LaneRead, r.TenantID, r.ConversationID)
	if err != nil {
		return chatcore.ListPostsResponse{}, err
	}
	defer releaseChatLease(lease)
	return s.ConversationService.ListPosts(ctx, r)
}

func (s *streamingChatService) ListMemberships(ctx context.Context, r chatcore.ListMembershipsRequest) (chatcore.ListMembershipsResponse, error) {
	lease, err := s.lease(ctx, chatadmission.LaneRead, r.TenantID, r.ConversationID)
	if err != nil {
		return chatcore.ListMembershipsResponse{}, err
	}
	defer releaseChatLease(lease)
	return s.ConversationService.ListMemberships(ctx, r)
}

// RemoveMembership is a revocation path: the removed principal's live
// subscriptions are closed and its cached authority dropped before the call
// returns, instead of waiting for the stream's safety-net recheck.
func (s *streamingChatService) RemoveMembership(ctx context.Context, r chatcore.RemoveMembershipRequest) (chatcore.Membership, error) {
	m, err := s.ConversationService.RemoveMembership(ctx, r)
	if err != nil {
		return m, err
	}
	home := m.HomeTenantID
	if home == "" {
		home = m.TenantID
	}
	s.authority.InvalidatePrincipal(home, m.SubjectID)
	s.runtime.Revoke(m.TenantID, home, m.SubjectID, m.ConversationID, m.Revision)
	return m, nil
}

func (s *streamingChatService) SendPost(ctx context.Context, req chatcore.SendPostRequest) (chatcore.Post, error) {
	if s.runtime == nil {
		return s.sendPost(ctx, req)
	}
	lease, err := s.runtime.AcquireSend(ctx, req.TenantID, req.ConversationID)
	if err != nil {
		return chatcore.Post{}, err
	}
	defer lease.Release()
	return s.sendPost(ctx, req)
}

// CommitPersonaReply preserves the optional server-owned write through the
// streaming decorator and reserves the same bounded send capacity as a post.
// Routed and audit semantics remain with the inner decorated service.
func (s *streamingChatService) CommitPersonaReply(ctx context.Context, req chatcore.PersonaReplyCommitRequest) (chatcore.Post, error) {
	lease, err := s.lease(ctx, chatadmission.LaneSend, req.TenantID, req.ConversationID)
	if err != nil {
		return chatcore.Post{}, err
	}
	defer releaseChatLease(lease)
	committer, ok := s.ConversationService.(chatcore.PersonaReplyCommitter)
	if !ok {
		return chatcore.Post{}, chatcore.ErrUnavailable
	}
	return committer.CommitPersonaReply(ctx, req)
}
func (s *streamingChatService) SendEphemeralPost(ctx context.Context, req chatcore.SendEphemeralPostRequest) (chatcore.EphemeralPost, error) {
	if s.personaDM == nil {
		return chatcore.EphemeralPost{}, chatcore.ErrUnavailable
	}
	if req.Principal.TenantID != req.TenantID || req.TenantID == "" || req.Principal.SubjectID == "" || req.ConversationID == "" {
		return chatcore.EphemeralPost{}, chatcore.ErrPermissionDenied
	}
	dmConversation, err := s.personaDM.ResolvePersonaDM(ctx, req.Principal, req.TenantID)
	if err != nil {
		return chatcore.EphemeralPost{}, err
	}
	if dmConversation == "" {
		return chatcore.EphemeralPost{}, chatcore.ErrPermissionDenied
	}
	// A request routing hint is never allowed to choose which conversation
	// admission protects. Resolve the canonical persona DM from server-owned
	// identity, then reserve both writes in a stable order to avoid deadlocks.
	req.DurableCopyConversationID = dmConversation
	conversationIDs := []string{req.ConversationID, dmConversation}
	if conversationIDs[0] > conversationIDs[1] {
		conversationIDs[0], conversationIDs[1] = conversationIDs[1], conversationIDs[0]
	}
	leases := make([]*chatadmission.Lease, 0, 2)
	for i, conversationID := range conversationIDs {
		if i > 0 && conversationID == conversationIDs[i-1] {
			continue
		}
		lease, leaseErr := s.lease(ctx, chatadmission.LaneSend, req.TenantID, conversationID)
		if leaseErr != nil {
			for j := len(leases) - 1; j >= 0; j-- {
				releaseChatLease(leases[j])
			}
			return chatcore.EphemeralPost{}, leaseErr
		}
		leases = append(leases, lease)
	}
	defer func() {
		for i := len(leases) - 1; i >= 0; i-- {
			releaseChatLease(leases[i])
		}
	}()
	ephemeral, ok := s.ConversationService.(chatcore.EphemeralService)
	if !ok {
		return chatcore.EphemeralPost{}, chatcore.ErrUnavailable
	}
	return ephemeral.SendEphemeralPost(ctx, req)
}

func (s *streamingChatService) referenceService() (chatcore.ReferenceService, error) {
	v, ok := s.ConversationService.(chatcore.ReferenceService)
	if !ok {
		return nil, chatcore.ErrUnavailable
	}
	return v, nil
}

// SuggestReferences is derived work: it is shed before reads and sends.
func (s *streamingChatService) SuggestReferences(ctx context.Context, r chatcore.SuggestReferencesRequest) ([]chatcore.ReferenceCandidate, error) {
	v, err := s.referenceService()
	if err != nil {
		return nil, err
	}
	lease, err := s.lease(ctx, chatadmission.LaneDerived, r.TenantID, r.ConversationID)
	if err != nil {
		return nil, err
	}
	defer releaseChatLease(lease)
	return v.SuggestReferences(ctx, r)
}

func (s *streamingChatService) SendPostWithReferences(ctx context.Context, r chatcore.SendPostWithReferencesRequest) (chatcore.Post, error) {
	// SendPost owns stream admission and publication; the core service receives
	// the validated reference list through the ordinary durable send port.
	r.SendPostRequest.References = append([]chatcore.Reference(nil), r.References...)
	return s.SendPost(ctx, r.SendPostRequest)
}

func (s *streamingChatService) CreateShareLink(ctx context.Context, p chatcore.Principal, tenant, conversation, post string) (chatcore.ConversationLink, error) {
	v, err := s.referenceService()
	if err != nil {
		return chatcore.ConversationLink{}, err
	}
	return v.CreateShareLink(ctx, p, tenant, conversation, post)
}

func (s *streamingChatService) ResolveShareLink(ctx context.Context, p chatcore.Principal, token string) (chatcore.Conversation, *chatcore.Post, error) {
	v, err := s.referenceService()
	if err != nil {
		return chatcore.Conversation{}, nil, err
	}
	return v.ResolveShareLink(ctx, p, token)
}

func (s *streamingChatService) ReadAuthorizedReference(ctx context.Context, p chatcore.Principal, tenant, conversation, post string) (chatcore.Conversation, *chatcore.Post, error) {
	reader, ok := s.ConversationService.(chatcore.AuthorizedReferenceReader)
	if !ok {
		return chatcore.Conversation{}, nil, chatcore.ErrUnavailable
	}
	return reader.ReadAuthorizedReference(ctx, p, tenant, conversation, post)
}

func (s *streamingChatService) ForwardPost(ctx context.Context, r chatcore.ForwardPostRequest) (chatcore.Post, error) {
	v, err := s.referenceService()
	if err != nil {
		return chatcore.Post{}, err
	}
	if s.runtime == nil {
		return v.ForwardPost(ctx, r)
	}
	lease, err := s.runtime.AcquireSend(ctx, r.DestinationTenantID, r.DestinationConversationID)
	if err != nil {
		return chatcore.Post{}, err
	}
	defer lease.Release()
	return v.ForwardPost(ctx, r)
}

// WatchConversationWithErrors is the reporting form of the watch: it hands back
// the terminal cause alongside the event stream so a transport can tell a failed
// subscription from a completed one.
func (s *streamingChatService) WatchConversationWithErrors(ctx context.Context, req chatcore.WatchConversationRequest) (<-chan chatcore.WatchEvent, <-chan error, error) {
	// after_sequence used to be refused outright here, which made the field
	// permanently unusable and turned every resubscribe that carried it into an
	// unclassified internal failure. Both starting positions are now honoured;
	// naming both at once is still a bad request, because a client that
	// disagrees with itself about where it left off has to be told so.
	if req.AfterSequence != 0 && req.ResumeCursor != "" {
		return nil, nil, chatcore.ErrInvalidArgument
	}
	if verified, ok := trust.FromContext(ctx); ok && verified != nil && (verified.SubjectKind() == trust.SubjectKindAgent || verified.SubjectKind() == trust.SubjectKindIntegration) && req.AfterSequence != 0 {
		// The public event sequence is per conversation; the stream's durable
		// offset is an outbox ID. Machines resume only with a signed cursor so
		// a caller cannot accidentally replay by treating those as equivalent.
		return nil, nil, chatcore.ErrInvalidArgument
	}
	if s.runtime == nil {
		return nil, nil, ErrChatStreamingDisabled
	}
	// The routed service verifies the invocation, current installation scope,
	// conversation policy and route before a machine receives a stream epoch.
	if _, err := s.ConversationService.GetConversation(ctx, chatcore.GetConversationRequest{Principal: req.Principal, TenantID: req.TenantID, ConversationID: req.ConversationID}); err != nil {
		return nil, nil, err
	}
	epoch, err := chatMembershipEpoch(ctx, s.ConversationService, s.membership, req.TenantID, req.ConversationID, req.Principal)
	if err != nil {
		return nil, nil, err
	}
	routeEpoch, err := chatRouteEpoch(ctx, s.ConversationService, req.TenantID, req.ConversationID)
	if err != nil {
		return nil, nil, chatStreamError(err)
	}
	if req.AfterSequence != 0 {
		mapper, ok := s.membership.(chatPublicSequenceMapper)
		if !ok || mapper == nil {
			return nil, nil, chatcore.ErrUnavailable
		}
		offset, mapErr := mapper.ResolvePublicSequence(ctx, req.TenantID, req.ConversationID, req.AfterSequence)
		if mapErr != nil {
			return nil, nil, mapErr
		}
		req.AfterSequence = offset
	}
	sub, _, err := s.runtime.Watch(ctx, chatstream.WatchRequest{TenantID: req.TenantID, HomeTenantID: req.Principal.TenantID, SubjectID: req.Principal.SubjectID, ConversationID: req.ConversationID, MembershipEpoch: epoch, RouteEpoch: routeEpoch, Cursor: req.ResumeCursor, AfterSequence: req.AfterSequence})
	if err != nil {
		return nil, nil, chatStreamError(err)
	}
	out := make(chan chatcore.WatchEvent, 32)
	// fail carries the one terminal cause. Discarding it is what made every
	// stream failure look like a healthy end of stream: a failed durable read
	// closed the subscription, this goroutine returned, the channel closed and
	// the transport answered EOF with no error at all — so a browser saw a clean
	// end 10 ms after opening and retried until it gave up.
	fail := make(chan error, 1)
	go func() {
		defer close(out)
		defer close(fail)
		defer sub.Close()
		for {
			event, nextErr := sub.Next(ctx)
			if nextErr != nil {
				if ctx.Err() == nil && !errors.Is(nextErr, context.Canceled) && !errors.Is(nextErr, chatstream.ErrClosed) {
					fail <- chatStreamError(nextErr)
				}
				return
			}
			projected, projectErr := projectChatStreamEvent(ctx, req, event, s.runtime.clock())
			if projectErr != nil {
				if errors.Is(projectErr, chatcore.ErrEphemeralExpired) {
					// Subscription.Next has already advanced its signed cursor over
					// this offset. An expired recipient envelope is a skipped record,
					// not a terminal failure for the shared conversation watch.
					continue
				}
				fail <- chatStreamError(projectErr)
				return
			}
			if s.projector != nil {
				// The stream carries the stored body. The reader's own view of an
				// agent answer's sources is decided here, the same as on a read.
				projected = s.projector.ProjectWatchEvent(ctx, req.Principal, req.TenantID, req.ConversationID, projected)
			} else if s.masker != nil {
				projected = s.masker.MaskWatchEvent(ctx, req.Principal, req.TenantID, req.ConversationID, projected)
			}
			projected.ResumeCursor = sub.Cursor()
			select {
			case out <- projected:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, fail, nil
}

func projectChatStreamEvent(ctx context.Context, request chatcore.WatchConversationRequest, event chatstream.Event, now time.Time) (chatcore.WatchEvent, error) {
	if !event.Ephemeral {
		var conversationEvent chatcore.ConversationEvent
		if err := json.Unmarshal(event.Payload, &conversationEvent); err != nil {
			return chatcore.WatchEvent{}, fmt.Errorf("chat stream payload: %w: %w", chatcore.ErrUnavailable, err)
		}
		return chatcore.WatchEvent{Event: conversationEvent}, nil
	}
	if event.TenantID != request.TenantID || event.ConversationID != request.ConversationID ||
		event.RecipientHomeTenantID != request.Principal.TenantID || event.RecipientSubjectID != request.Principal.SubjectID ||
		request.Principal.TenantID == "" || request.Principal.SubjectID == "" {
		return chatcore.WatchEvent{}, chatcore.ErrPermissionDenied
	}
	if verified, ok := trust.FromContext(ctx); ok {
		if verified.SubjectKind() != trust.SubjectKindHuman || verified.Tenant().String() != request.Principal.TenantID || verified.Subject() != request.Principal.SubjectID {
			return chatcore.WatchEvent{}, chatcore.ErrPermissionDenied
		}
	}
	if event.ExpiresAt.IsZero() {
		return chatcore.WatchEvent{}, fmt.Errorf("chat ephemeral envelope expiry: %w", chatcore.ErrUnavailable)
	}
	if !now.Before(event.ExpiresAt) {
		return chatcore.WatchEvent{}, chatcore.ErrEphemeralExpired
	}
	var post chatcore.EphemeralPost
	if err := json.Unmarshal(event.Payload, &post); err != nil {
		return chatcore.WatchEvent{}, fmt.Errorf("chat ephemeral payload: %w: %w", chatcore.ErrUnavailable, err)
	}
	if post.ExpiresAt.IsZero() {
		return chatcore.WatchEvent{}, fmt.Errorf("chat ephemeral payload expiry: %w", chatcore.ErrUnavailable)
	}
	if !now.Before(post.ExpiresAt) {
		return chatcore.WatchEvent{}, chatcore.ErrEphemeralExpired
	}
	if post.TenantID != request.TenantID || post.ConversationID != request.ConversationID ||
		post.RecipientHomeTenantID != request.Principal.TenantID || post.RecipientSubjectID != request.Principal.SubjectID ||
		post.Sequence == 0 || post.Sequence != event.Sequence || post.ID == "" || post.ThreadID == "" ||
		!post.OnlyVisibleToYou || post.Body == "" || post.CreatedAt.IsZero() || post.ThreadLink == "" ||
		!post.ExpiresAt.After(post.CreatedAt) || post.ExpiresAt.After(post.CreatedAt.Add(chatcore.EphemeralLifetime)) ||
		!post.ExpiresAt.Equal(event.ExpiresAt) || !now.Before(post.ExpiresAt) {
		return chatcore.WatchEvent{}, chatcore.ErrPermissionDenied
	}
	delivery := &chatcore.EphemeralDelivery{
		ID: post.ID, ThreadID: post.ThreadID, Body: post.Body, OnlyVisibleToYou: true,
		CreatedAt: post.CreatedAt, ExpiresAt: post.ExpiresAt, ThreadLink: post.ThreadLink,
	}
	return chatcore.WatchEvent{EphemeralDelivery: delivery}, nil
}

// WatchConversation keeps the canonical single-channel contract for callers that
// do not distinguish a failure from an end of stream.
func (s *streamingChatService) WatchConversation(ctx context.Context, req chatcore.WatchConversationRequest) (<-chan chatcore.WatchEvent, error) {
	events, _, err := s.WatchConversationWithErrors(ctx, req)
	return events, err
}

// defaultChatAdmissionConfig is the composition default. ChatComposition.Admission
// overrides any field a deployment sets; the rest keep these bounds.
func defaultChatAdmissionConfig() chatadmission.Config {
	return chatadmission.Config{TenantConcurrent: 128, ConversationConcurrent: 32, SendConcurrent: 64, WatchConcurrent: 256, ReadConcurrent: 128, DerivedConcurrent: 32, WatchTenantConcurrent: 256, WatchConversationConcurrent: 256}
}

// mergeChatAdmissionConfig applies the deployment's overrides field by field, so
// setting one bound does not silently zero the others.
func mergeChatAdmissionConfig(base, override chatadmission.Config) chatadmission.Config {
	if override.TenantConcurrent > 0 {
		base.TenantConcurrent = override.TenantConcurrent
	}
	if override.ConversationConcurrent > 0 {
		base.ConversationConcurrent = override.ConversationConcurrent
	}
	if override.SendConcurrent > 0 {
		base.SendConcurrent = override.SendConcurrent
	}
	if override.WatchConcurrent > 0 {
		base.WatchConcurrent = override.WatchConcurrent
	}
	if override.ReadConcurrent > 0 {
		base.ReadConcurrent = override.ReadConcurrent
	}
	if override.DerivedConcurrent > 0 {
		base.DerivedConcurrent = override.DerivedConcurrent
	}
	if override.WatchTenantConcurrent > 0 {
		base.WatchTenantConcurrent = override.WatchTenantConcurrent
	}
	if override.WatchConversationConcurrent > 0 {
		base.WatchConversationConcurrent = override.WatchConversationConcurrent
	}
	if override.ReadShedFraction > 0 {
		base.ReadShedFraction = override.ReadShedFraction
	}
	if override.DerivedShedFraction > 0 {
		base.DerivedShedFraction = override.DerivedShedFraction
	}
	return base
}
