package main

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
)

// TestTodo_TOOL_012_Golden pins the TOOL-012 matrix and its two fixture
// halves. The primary test exercises the detector; this test makes sure a
// future edit cannot silently remove either the deliberate race (RED) or the
// synchronized control (GREEN).
func TestTodo_TOOL_012_Golden(t *testing.T) {
	root := repoRoot(t)
	data, err := os.ReadFile(filepath.Join(root, "definitions", "planning", "todo-registry.json"))
	if err != nil {
		t.Fatalf("read TODO registry: %v", err)
	}
	var entries []struct {
		ID         string            `json:"id"`
		TestMatrix map[string]string `json:"test_matrix"`
		Red        string            `json:"red"`
		Green      string            `json:"green"`
	}
	if err := json.Unmarshal(data, &entries); err != nil {
		t.Fatalf("parse TODO registry: %v", err)
	}
	var entry *struct {
		ID         string            `json:"id"`
		TestMatrix map[string]string `json:"test_matrix"`
		Red        string            `json:"red"`
		Green      string            `json:"green"`
	}
	for i := range entries {
		if entries[i].ID == "TOOL-012" {
			entry = &entries[i]
			break
		}
	}
	if entry == nil {
		t.Fatal("TOOL-012 is missing from the TODO registry")
	}
	want := map[string]string{
		"PRIMARY":     "TestTodo_TOOL_012",
		"GOLDEN":      "TestTodo_TOOL_012_Golden",
		"INTEGRATION": "TestTodo_TOOL_012_Integration",
		"RACE":        "TestTodo_TOOL_012_Race",
	}
	for kind, name := range want {
		if entry.TestMatrix[kind] != name {
			t.Errorf("matrix[%q] = %q, want %q", kind, entry.TestMatrix[kind], name)
		}
	}
	if !strings.Contains(entry.Red, "shared-state race") || !strings.Contains(entry.Green, "-race") {
		t.Fatalf("registry red/green contract lost: red=%q green=%q", entry.Red, entry.Green)
	}

	fixture, err := os.ReadFile(filepath.Join(root, "tools", "quality", "testdata", "racefixture", "racefixture.go"))
	if err != nil {
		t.Fatalf("read race fixture: %v", err)
	}
	text := string(fixture)
	if !strings.Contains(text, "RacyCounter") || !strings.Contains(text, "SynchronizedCounter") || !strings.Contains(text, "sync.Mutex") {
		t.Fatal("race fixture no longer contains both racy and synchronized implementations")
	}
}

// TestTodo_TOOL_012_Integration pins the CI integration point. The local
// windows/arm64 toolchain cannot execute -race; Linux CI is the authoritative
// environment for the root-module race sweep.
//
// The sweep used to be a literal `go test -race -count=1 ./...` and this test
// pinned that exact string. It is now driven by tools/policy/racepolicy's own
// -list output, because racing all 776 packages (101 of them PostgreSQL-backed
// and carrying no race-class signal) could not finish inside the job's wall
// clock. That is a stronger arrangement, not a looser one, so this test now
// pins all four of its load-bearing parts rather than one substring:
//
//  1. the job still runs on Linux, the only platform here with a detector;
//  2. the raced package set is generated by racepolicy, so it cannot drift
//     from the set the policy audits;
//  3. `go test -race` is actually invoked over that generated set; and
//  4. the packages outside that set are still built and run, detector off, by
//     covergate's full sweep -- so narrowing the race set never turns into
//     skipping a package.
//
// The separate racepolicy step that fails the build when a concurrent package
// has no raceable test file is pinned by its own assertion below: without it,
// (2) would be a set that quietly shrinks to nothing.
func TestTodo_TOOL_012_Integration(t *testing.T) {
	root := repoRoot(t)
	workflow, err := os.ReadFile(filepath.Join(root, ".github", "workflows", "tests.yml"))
	if err != nil {
		t.Fatalf("read CI workflow: %v", err)
	}
	text := string(workflow)
	if !strings.Contains(text, "runs-on: ubuntu-latest") {
		t.Fatal("TOOL-012 race job is not pinned to a Linux runner")
	}
	if !strings.Contains(text, "racepolicy -root . -list") {
		t.Fatal("go-core CI job does not generate the race package set from tools/policy/racepolicy")
	}
	if !strings.Contains(text, "go test -race -count=1") {
		t.Fatal("go-core CI job does not run the race detector at all")
	}
	if strings.Count(text, "racepolicy/cmd/racepolicy") < 2 {
		t.Fatal("go-core CI job lists the concurrent packages but no longer verifies the race-coverage policy over them")
	}
	if !strings.Contains(text, "covergate -root . -all") {
		t.Fatal("go-core CI job no longer sweeps every package with the detector off, so packages outside the race set would go unrun")
	}
}

// TestTodo_TOOL_012_Race runs the detector RED/GREEN proof under its own
// concurrent load. Eight goroutines hammer one atomic counter behind a
// WaitGroup (so this test itself exercises shared state and asserts the
// exact total, proving no lost update), then the synchronized fixture must
// pass clean under `go test -race`. Like the primary test it probes the
// active toolchain and skips explicitly when that platform does not support
// -race (for example windows/arm64); it therefore never reports unsupported
// local execution as race coverage.
func TestTodo_TOOL_012_Race(t *testing.T) {
	root := repoRoot(t)
	fixturePattern := "./tools/quality/testdata/racefixture/"

	probe := exec.Command("go", "test", "-race", "-run", "^$", fixturePattern)
	probe.Dir = root
	probeOut, _ := probe.CombinedOutput()
	if raceUnsupported(probeOut) {
		t.Skipf("race detector not supported on %s/%s; TOOL-012 must be verified on race-capable CI (e.g. linux/amd64). go test output:\n%s", runtime.GOOS, runtime.GOARCH, probeOut)
	}

	const workers = 8
	const perWorker = 1000
	var total atomic.Int64
	var wg sync.WaitGroup
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := 0; i < perWorker; i++ {
				total.Add(1)
			}
		}()
	}
	wg.Wait()
	if got, want := total.Load(), int64(workers*perWorker); got != want {
		t.Fatalf("concurrent increments = %d, want %d (lost update under test's own load)", got, want)
	}

	cmd := exec.Command("go", "test", "-race", "-run", "^TestSynchronizedIncrement$", "-count=1", fixturePattern)
	cmd.Dir = root
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("expected the synchronized fixture to pass under -race, got:\n%s", out)
	}
}
