package legal_test

// LEGAL-ST-AL-001: Alabama's promotion/base-pay obligation parameters carried
// in a reviewed RulePack. The pack is generated by
// internal/governance/legal/extract from alabama.md and published through the
// section 7.1 pipeline at the status it honestly earns; the three section 8.1
// artifacts live under testdata/legal/us-al/.

import (
	"testing"

	legal "github.com/monstercameron/human-capital-management-suite/internal/governance/legal"
)

// The Vendor Legal Reviewer's hand-written findings: one non-blocking
// observation on the E-Verify obligation's VERIFY confidence marker, retained
// because the contract's section 7.3 permits VERIFY at VENDOR_BASELINE. The
// harness adds the blocking/concern findings the pack's own gaps generate.
var legalStAlFindings = []legal.ReviewFinding{
	{
		ObligationID: "us-al-e-verify",
		Severity:     legal.FindingSeverityInfo,
		Note:         "E-Verify mandate carries a VERIFY confidence marker; re-check employer-size scope at the next corpus refresh",
	},
}

func TestTodo_LEGAL_ST_AL_001(t *testing.T) {
	legalStAssertPack(t, "AL", []legalStExpectation{
		// WAGE_FLOOR is federal-only for Alabama (matrix cell `F`): no state
		// minimum-wage or overtime statute, so the pack carries only the
		// federal FLSA baseline (29 U.S.C. § 206) with no state amount.
		{Kind: legal.ObligationTypeWageFloor, Requires: []string{"29 U.S.C.", "no Alabama statute"}},
		// Clarke-Figures Equal Pay Act: sex/race pay-equity review with
		// documentation required and the 3-year retention it mandates.
		{Kind: legal.ObligationTypePayEquityReview, Requires: []string{"25-1-30", `"documentation_required":true`}},
		// 3-year wage-record minimum tied to Ala. Code § 25-1-30.
		{Kind: legal.ObligationTypeRetention, Requires: []string{"25-1-30", `"duration_years":3`}},
		// Presumptive reasonableness: ≤2 years employees / ≤1 year business
		// sale / ≤18 months non-solicit (Ala. Code § 8-1-190 et seq., § 8-1-191).
		{Kind: legal.ObligationTypeNonCompete, Requires: []string{"8-1-190", "2 years or less", "18 months or less"}},
		// Beason-Hammon Act: E-Verify mandatory for all employers.
		{Kind: legal.ObligationTypeEVerify, Requires: []string{"31-13-15"}},
		// Workers'-compensation retaliation, "solely because" standard.
		{Kind: legal.ObligationTypeAntiRetaliation, Requires: []string{"25-5-11.1", "solely because"}},
		// 45-day biometric-plus-name breach notification (Ala. Code § 8-38-5).
		{Kind: legal.ObligationTypeBreachNotification, Requires: []string{"8-38-5", `"subject_deadline_days":45`}},
	})
}

func TestTodo_LEGAL_ST_AL_001_Golden(t *testing.T) {
	p, release, registry, _ := legalStPack(t, "AL", legalStAlFindings)
	legalStGoldens(t, "AL", p, release, registry)
}

func TestTodo_LEGAL_ST_AL_001_Conformance(t *testing.T) {
	// § 8-38-5's 45-day window is stated without a calendar/business basis,
	// so the breach obligation's day_basis is honestly unstated and the pack
	// publishes at the contract's deliberately-unresolved status rather than
	// fabricating a qualifier the statute does not use.
	legalStConformance(t, "AL", legalStAlFindings, legal.ReviewStatusRequiresCustomerCounselConfiguration)
}
